### ISSUE TITLE
AgoraAiEchoCancellationExtension

### ISSUE THREAD

**Issue by Mo0Khaled** [AgoraIO-Extensions/Agora-Flutter-SDK#1005]
I am getting an exception when run on IOS,

with the following

Library not loaded: @rpath/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension
  Referenced from: <DBBA86A3-FF99-3399-A085-95F62399EFAF> /Users/mo/Library/Developer/CoreSimulator/Devices/177CE850-A62C-457B-898C-8C1310B92324/data/Containers/Bundle/Application/E9FB4427-C6BB-4464-86C1-794D0A984C2D/Runner.app/Runner
  Reason: tried: '/Users/mo/Library/Developer/Xcode/DerivedData/Runner-dzfyyularxycplbquojyupjdhjgb/Build/Products/Debug-iphonesimulator/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/usr/lib/swift/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/usr/lib/swift/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file, not in dyld cache), '/Users/mo/Library/Developer/CoreSimulator/Devices/177CE850-A62C-457B-898C-8C1310B92324/data/Containers/Bundle/Application/E9FB4427-C6BB-4464-86C1-794D0A984C2D/Runner.app/Frameworks/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/Users/mo/Library/Developer/CoreSimulator/Devices/177CE850-A62C-457B-898C-8C1310B92324/data/Containers/Bundle/Application/E9FB4427-C6BB-4464-86C1-794D0A984C2D/Runner.app/Frameworks/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/Users/mo/Library/Developer/CoreSimulator/Devices/177CE850-A62C-457B-898C-8C1310B92324/data/Containers/Bundle/Application/E9FB4427-C6BB-4464-86C1-794D0A984C2D/Runner.app/Frameworks/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/usr/lib/swift/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/usr/lib/swift/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file, not in dyld cache), '/Users/mo/Library/Developer/CoreSimulator/Devices/177CE850-A62C-457B-898C-8C1310B92324/data/Containers/Bundle/Application/E9FB4427-C6BB-4464-86C1-794D0A984C2D/Runner.app/Frameworks/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/Users/mo/Library/Developer/CoreSimulator/Devices/177CE850-A62C-457B-898C-8C1310B92324/data/Containers/Bundle/Application/E9FB4427-C6BB-4464-86C1-794D0A984C2D/Runner.app/Frameworks/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/Users/mo/Library/Developer/CoreSimulator/Devices/177CE850-A62C-457B-898C-8C1310B92324/data/Containers/Bundle/Application/E9FB4427-C6BB-4464-86C1-794D0A984C2D/Runner.app/Frameworks/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/AgoraAiEchoCancellationExtension.framework/AgoraAiEchoCancellationExtension' (no such file)

Can Any One Help?

**Comment by littleGnAl** [comment]
Can you fill in more info by following the issue template, thanks a lot.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Mo0Khaled** [comment]
I solved,

I removed the Podfile and re installed again with 0 dependancies to remove the current agora SDKs,

Then install all the dependance,

For your information it's suddenly happen I was working on the simulator then tried to run it on my iPhone 13,

then it crashed with the provided exception above,

for more information please tell me I'll be glad to help

I'll close it for now.
