### ISSUE TITLE
包体积过大

### ISSUE THREAD

**Issue by ZCHUANGJie** [AgoraIO-Extensions/Agora-Flutter-SDK#1007]
新项目一引入该插件6.1.0 打包android apk时 包体积直接增大100到200m，这是不是有点问题了，需要我做什么处理，不然一个app无故增加怎么多，难以处理，希望给出一个有效的解决方法
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/50944417/231325158-749b491c-4c9a-4bdf-a986-024ea3b83a9d.png">
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/50944417/231325280-9e6c855c-afed-42e3-8f0f-88228b2e0177.png">

**Comment by littleGnAl** [comment]
You can use `packagingOptions.exclude` to filter the unused `.so` files

https://stackoverflow.com/questions/37382057/android-apk-how-to-exclude-a-so-file-from-a-3rd-party-dependency-using-gradle
e.g.,
```gradle
packagingOptions {
    exclude 'lib/armeabi-v7a/libagora_ai_denoise_extension.so'
    exclude 'lib/armeabi-v7a/libagora_spatial_audio_extension.so'
    exclude 'lib/armeabi-v7a/libagora_full_audio_format_extension.so'
    ...
 
    exclude 'lib/arm64-v8a/libagora_ai_denoise_extension.so'
    exclude 'lib/arm64-v8a/libagora_spatial_audio_extension.so'
    exclude 'lib/arm64-v8a/libagora_full_audio_format_extension.so'
    ...
}
```
You can find the all `.so` list here:
https://docs.agora.io/cn/video-call-4.x/reduce_size_ng?platform=Android#参考信息

**Comment by ZCHUANGJie** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/50944417/231416708-cfff08db-7e46-4cde-ac1a-ceac806e3202.png">
<img width="968" alt="image" src="https://user-images.githubusercontent.com/50944417/231417008-d1986ec1-d0a0-47d3-bd4b-3a82d68326c9.png">
包体积虽然减少了一些，但是还是不理想，包体积还是太大了，还有什么优化方式吗

**Comment by littleGnAl** [comment]
Is it a release build? I think you can follow this doc to measure the APP size more accurately.
https://docs.flutter.dev/perf/app-size

**Comment by ZCHUANGJie** [comment]
是发布版本的，
<img width="938" alt="image" src="https://user-images.githubusercontent.com/50944417/231423923-714ef3b8-c0bc-4631-8a0a-48f56188e268.png">
<img width="721" alt="image" src="https://user-images.githubusercontent.com/50944417/231424082-4aeea748-5048-4fcd-a256-96aaaee816d7.png">
<img width="740" alt="image" src="https://user-images.githubusercontent.com/50944417/231424191-49c8d60a-78a9-4385-99be-c566aa2c82fc.png">
这是flutter  分析的包体积，

**Comment by littleGnAl** [comment]
Please check this section
<img width="829" alt="image" src="https://user-images.githubusercontent.com/8847263/231433703-9e2c75b9-b3fd-4d30-8e67-b477489284b3.png">

https://docs.flutter.dev/perf/app-size#breaking-down-the-size

**Comment by ZCHUANGJie** [comment]
意思是也没有好的解决方案了是吗，这只是在各平台的应用商店有用，我们App内部有做内更新，这样这个方法就没办法适用了吧，包还是会过大

**Comment by ZCHUANGJie** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/50944417/231917385-e2e64121-7b92-42a0-891c-0caf1a07ad04.png">
你这个是flutter 哪个版本，agora-rtc哪个版本打包的，怎么差别这么大

**Comment by ZCHUANGJie** [comment]
我想问一下你们有没有这个现象：
就是我新建一空项目，里面没有其他内容，就是引用agora_rtc_engine插件，然后打包出来libagora-rtc-sdk.so文件不会很大，可以接受，但是在一个我现有的项目里引用该插件（业务代码里面有用其开发出内容【就是不是单纯引用插件而不使用】），打包出来的libagora-rtc-sdk.so文件就会变大很多，不知道你们有没有这个现象，

**Comment by littleGnAl** [comment]
> 你这个是flutter 哪个版本，agora-rtc哪个版本打包的，怎么差别这么大

It's the API example based on the `main` branch, which should be the same as the `agora_rtc_engine: 6.1.0`, the native SDK version: `4.1.0`.

**Comment by littleGnAl** [comment]
> 我想问一下你们有没有这个现象：
就是我新建一空项目，里面没有其他内容，就是引用agora_rtc_engine插件，然后打包出来libagora-rtc-sdk.so文件不会很大，可以接受，但是在一个我现有的项目里引用该插件（业务代码里面有用其开发出内容【就是不是单纯引用插件而不使用】），打包出来的libagora-rtc-sdk.so文件就会变大很多，不知道你们有没有这个现象，

Our API example actually has codes but not an empty project, for your case, I think you may need to adjust your release build config in your gradle file, please check this doc for reference.

https://developer.android.com/build/shrink-code
