### ISSUE TITLE
onAgoraVideoViewCreated 回调没有，Incorrect NSStringEncoding value 0x8000100 detected 一直输出

### ISSUE THREAD

**Issue by xlg** [AgoraIO-Extensions/Agora-Flutter-SDK#1012]
您好，这边试着接入了6.0.0 和6.1.0版本，发现与SDK里的代码有些不一样
AgoraVideoView(
      controller: VideoViewController(
        rtcEngine: _engine,
        canvas: const VideoCanvas(uid: 0),
        useFlutterTexture: _isUseFlutterTexture,
        useAndroidSurfaceView: _isUseAndroidSurfaceView,
      ),
      onAgoraVideoViewCreated: (viewId) {
        _engine.startPreview();
      },
    )
1、首先6.0.0 和6.1.0版本里面，没有onAgoraVideoViewCreated回调方法。
2、通过收到添加按钮调用startPreview(),预览失败，一直在输出log，Incorrect NSStringEncoding value 0x8000100 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future.
3、跪求正确的接入方式，非常感谢。

**Comment by littleGnAl** [comment]
The `onAgoraVideoViewCreated ` is added in the `main` branch but not published yet, if you use `6.0.0/6.1.0`, please check the specific tag for reference
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/v6.0.0
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/v6.1.0
