### ISSUE TITLE
Switching from Voice call to Video call

### ISSUE THREAD

**Issue by sovannarithsok** [AgoraIO-Extensions/Agora-Flutter-SDK#1020]
Hi, I have implemented voice call using Agora flutter SDK.
`agora_rtc_engine: ^6.1.0
`

First I start with a voice call between 2 users known as Host and Remoter.
Host start a voice call and remoter successfully joinned channel, we can hear each other.

Then Host enable video  `agoraEngine.enableVideo()`  (Both front and Rear camera work fine).
Remoter listening event `onUserEnableVideo`  to update UI.

The problem is Remoter cannot see Host video, always display black screen.
So please guide me what's the issue that cause this? Does anyone met this scenario before?

Note: I tested with 2 android devices.

**Comment by littleGnAl** [comment]
I think it's better to raise a ticket to Agora support for further investigation.
