### ISSUE TITLE
System incoming phone call causes agora ongoing call's mic output to stop working

### ISSUE THREAD

**Issue by HuzPainter** [AgoraIO-Extensions/Agora-Flutter-SDK#1065]
When in an ongoing agora audioScenarioGameStreaming call, whenever for example, I get a system phone call (regular phone call), the mic shows that its outputting (Can see event for volume in: onAudioVolumeIndication event handler) for only myself, not for others in the call. Others cannot hear me.

1. Setup audio call with AudioScenarioType.audioScenarioGameStreaming
2. Receive system phone call on Android/Ios

Agora version: 6.1.1

**Comment by littleGnAl** [comment]
Do you mean this issue only happens in `audioScenarioGameStreaming ` set?

**Comment by HuzPainter** [comment]
No, I haven't tried extensively with others but it definitely doesn't work with audioScenarioGameStreaming. But Im pretty sure it happens with other sets too. Also, audioProfile is set to: audioProfileMusicHighQuality. Unsure if thats related but forgot to mention earlier.

**Comment by littleGnAl** [comment]
I think it's better to raise a ticket to agora support for further investigation.

**Comment by HuzPainter** [comment]
Okay will do, thanks.
