### ISSUE TITLE
Execution failed for task ':iris_method_channel:buildCMakeDebug[arm64-v8a]'

### ISSUE THREAD

**Issue by MuhammadIbrahim001** [AgoraIO-Extensions/Agora-Flutter-SDK#1086]
**Unable to run flutter app due to following exception.**

- Basically this error is occurring due to  agora_rtc_engine: ^6.1.1 .  
- which uses iris_method_channel
- If I remove this package code works perfectly. 

> What i have tried before posting this exception.

- flutter clean 
- flutter pub get
- flutter pub cache repair
- removed build folder
- removed android folder and recreated.
- updated flutter 
- Tried other versions as well 6.0.0, and 6.1.0

> Flutter Doctor (flutter doctor -v)

[✓] Flutter (Channel stable, 3.10.0, on Linux Mint 20.3 5.15.0-72-generic, locale en_US.UTF-8)
    • Flutter version 3.10.0 on channel stable at /home/muhammad/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (8 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/muhammad/Android/Sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /home/muhammad/Desktop/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /home/muhammad/Desktop/android-studio
    • Flutter plugin version 71.1.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at /home/muhammad/Downloads/idea-IU-222.4345.14
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)         • linux         • linux-x64      • Linux Mint 20.3 5.15.0-72-generic
    • Chrome (web)            • chrome        • web-javascript • Chromium 113.0.5672.63 for Linux Mint

[✓] Network resources
    • All expected network resources are available.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':iris_method_channel:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/muhammad/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0-rc.5/android/.cxx/Debug/2i83q535/arm64-v8a'
  [1/2] Building CXX object CMakeFiles/iris_method_channel.dir/iris_event.cc.o
  FAILED: CMakeFiles/iris_method_channel.dir/iris_event.cc.o 
  /home/muhammad/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/muhammad/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/muhammad/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DDART_SHARED_LIB -Diris_method_channel_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/iris_method_channel.dir/iris_event.cc.o -MF CMakeFiles/iris_method_channel.dir/iris_event.cc.o.d -o CMakeFiles/iris_method_channel.dir/iris_event.cc.o -c /home/muhammad/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0-rc.5/src/iris_event.cc
  In file included from /home/muhammad/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0-rc.5/src/iris_event.cc:6:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/muhammad/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0-rc.5/src/iris_event.cc:90:17: error: use of undeclared identifier 'memcpy'; did you mean 'wmemcpy'?
                  memcpy(abuffer, obuffer, abufferLength);
                  ^~~~~~
                  wmemcpy
  /snap/flutter/current/usr/include/wchar.h:262:17: note: 'wmemcpy' declared here
  extern wchar_t *wmemcpy (wchar_t *__restrict __s1,
                  ^
  /home/muhammad/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0-rc.5/src/iris_event.cc:90:24: error: cannot initialize a parameter of type 'wchar_t *' with an lvalue of type 'uint8_t *' (aka 'unsigned char *')
                  memcpy(abuffer, obuffer, abufferLength);
                         ^~~~~~~
  /snap/flutter/current/usr/include/wchar.h:262:46: note: passing argument to parameter '__s1' here
  extern wchar_t *wmemcpy (wchar_t *__restrict __s1,
                                               ^
  3 errors generated.
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      /home/muhammad/Android/Sdk/cmake/3.18.1/bin/ninja \
        -C \
        /home/muhammad/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0-rc.5/android/.cxx/Debug/2i83q535/arm64-v8a \
        iris_method_channel
    from /home/muhammad/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0-rc.5/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 18s
Exception: Gradle task assembleDebug failed with exit code 1

```

**Comment by littleGnAl** [comment]
It is most likely that there's an issue with your C++ environment, is it possible to share your `build.gradle` config?

**Comment by MuhammadIbrahim001** [comment]
> It is most likely that there's an issue with your C++ environment, is it possible to share your `build.gradle` config?
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
// START: FlutterFire Configuration
apply plugin: 'com.google.gms.google-services'
// END: FlutterFire Configuration
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.gameshow"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 19
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

**Comment by littleGnAl** [comment]
Can you try remove the line `ndkVersion flutter.ndkVersion`?

**Comment by MohamedELGar7y** [comment]
same issue

**Comment by MuhammadIbrahim001** [comment]
> ndkVersion flutter.ndkVersion
still the same issue

**Comment by sharma-dushyant** [comment]
Launching lib/main.dart on GM1901 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':iris_method_channel:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/dushyant/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/62q2o1us/arm64-v8a'
  [1/4] Building C object CMakeFiles/iris_method_channel.dir/dart-sdk/include/dart_api_dl.c.o
  [2/4] Building CXX object CMakeFiles/iris_method_channel.dir/iris_life_cycle_observer.cc.o
  [3/4] Building CXX object CMakeFiles/iris_method_channel.dir/iris_event.cc.o
  FAILED: CMakeFiles/iris_method_channel.dir/iris_event.cc.o
  /home/dushyant/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/dushyant/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/dushyant/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DDART_SHARED_LIB -Diris_method_channel_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/iris_method_channel.dir/iris_event.cc.o -MF CMakeFiles/iris_method_channel.dir/iris_event.cc.o.d -o CMakeFiles/iris_method_channel.dir/iris_event.cc.o -c /home/dushyant/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/src/iris_event.cc
  In file included from /home/dushyant/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/src/iris_event.cc:6:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/dushyant/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/src/iris_event.cc:90:17: error: use of undeclared identifier 'memcpy'; did you mean 'wmemcpy'?
                  memcpy(abuffer, obuffer, abufferLength);
                  ^~~~~~
                  wmemcpy
  /snap/flutter/current/usr/include/wchar.h:262:17: note: 'wmemcpy' declared here
  extern wchar_t *wmemcpy (wchar_t *__restrict __s1,
                  ^
  /home/dushyant/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/src/iris_event.cc:90:24: error: cannot initialize a parameter of type 'wchar_t *' with an lvalue of type 'uint8_t *' (aka 'unsigned char *')
                  memcpy(abuffer, obuffer, abufferLength);
                         ^~~~~~~
  /snap/flutter/current/usr/include/wchar.h:262:46: note: passing argument to parameter '__s1' here
  extern wchar_t *wmemcpy (wchar_t *__restrict __s1,
                                               ^
  3 errors generated.
  ninja: build stopped: subcommand failed.
  C++ build system [build] failed while executing:
      /home/dushyant/Android/Sdk/cmake/3.18.1/bin/ninja \
        -C \
        /home/dushyant/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/62q2o1us/arm64-v8a \
        iris_method_channel
    from /home/dushyant/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 10s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by littleGnAl** [comment]
I think a reproducible demo is helpful.

**Comment by littleGnAl** [comment]
Maybe a solution
https://github.com/flutter/flutter/issues/106102
https://stackoverflow.com/questions/70149507/flutter-build-failed-for-android-bitmapexternalnativebuilddebug

**Comment by MuhammadIbrahim001** [comment]
Reinstalling flutter installed via snap. and Installing it again manually solved my problem.
Thank you for support.

**Comment by MuhammadIbrahim001** [comment]
Reinstalling flutter installed through snap and installing it again through manually solved my problem.
Thank you for support.
