### ISSUE TITLE
when layoutType is floating, i got this error in agora uikit

### ISSUE THREAD

**Issue by kyawthet-wam** [AgoraIO-Extensions/Agora-Flutter-SDK#1101]
Exception caught by widgets library ═══════════════════════════════════
Remote uid can not be null or 0
'package:agora_rtc_engine/src/render/video_view_controller.dart':
video_view_controller.dart:1
Failed assertion: line 74 pos 16: 'canvas.uid != null && canvas.uid != 0'

**Comment by AsriKizi** [comment]
how u solve this issue?
