### ISSUE TITLE
Check if a user is waiting for others to join channel.

### ISSUE THREAD

**Issue by ahndwon** [AgoraIO-Extensions/Agora-Flutter-SDK#1125]
**Is your feature request related to a problem? Please describe.**
I am creating a 1-on-1 voice call feature on my app.
I need to check if the other user is waiting for the user to join before joining a channel.

I tried the Agora restful APIs (Get user status, get user list), but both only works when minimum of two have joined.
I want them to work when only one user have joined channel.

It seems Agora creates a channel when 2 users have joined.
Is there an existing api for this?
If not, please create this feature!

**Describe the solution you'd like**
Need to check if the other user is waiting for the user to join before joining a channel.
Need an API thats checks for a user waiting for channel creation.

Or make channel creation possible when one user has called joinChannel method.

**Describe alternatives you've considered**

**Additional context**

**Comment by littleGnAl** [comment]
I think if the `onUserJoined` callback has not been received, it should be waiting.

**Comment by amityamsi** [comment]
Channel will be created when a first user start the call and you only get the status of other user after joining the channel and there is no feature to check if an user is waiting or not
