### ISSUE TITLE
Screen Recording

### ISSUE THREAD

**Issue by adigujjar** [AgoraIO-Extensions/Agora-Flutter-SDK#1147]
There should be a screen recording feature i don't think it's already there.
So both user can share screen as well.

**Comment by littleGnAl** [comment]
I'm not very sure if you saying the screen-sharing feature, you can check our example for reference.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/screen_sharing/screen_sharing.dart
