### ISSUE TITLE
From version 6.2.0 we can't build web

### ISSUE THREAD

**Issue by maravilhosinga** [AgoraIO-Extensions/Agora-Flutter-SDK#1192]
**Describe the bug**
From version 6.2.0 (including 6.2.1), building web is imposible. It's giving so many errors and exiting the build proccess

**To Reproduce**
1. run $flutter build web

**Expected behavior**
We expect to build web release

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Ventura 13.5

**Additional context**

`./../../../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.1/lib/src/impl/native_iris_api_engine_binding_delegate.dart:3:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi' as ffi;
       ^
../../../../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.1/lib/src/impl/native_iris_api_engine_bindings.dart:6:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi' as ffi;
       ^
../../../../../.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/lib/src/iris_method_channel.dart:2:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi' as ffi;
       ^
../../../../../.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/lib/src/iris_event.dart:1:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi' as ffi;
       ^
../../../../../.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/lib/src/native_bindings_delegate.dart:2:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi' as ffi;
       ^
../../../../../.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/lib/src/bindings/native_iris_api_common_bindings.dart:3:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi' as ffi;
       ^
../../../../../.pub-cache/hosted/pub.dev/ffi-2.0.2/lib/src/allocation.dart:5:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi';
       ^
../../../../../.pub-cache/hosted/pub.dev/ffi-2.0.2/lib/src/arena.dart:8:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi';
       ^
../../../../../.pub-cache/hosted/pub.dev/ffi-2.0.2/lib/src/utf8.dart:6:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi';
       ^
../../../../../.pub-cache/hosted/pub.dev/ffi-2.0.2/lib/src/utf16.dart:5:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi';
       ^
../../../../../.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/lib/src/bindings/native_iris_event_bindings.dart:6:8:
Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi' as ffi;
       ^
../../../../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.1/lib/src/impl/native_iris_api_engine_binding_delegate.dart:16:1:
Error: Type 'ffi.DynamicLibrary' not found.
ffi.DynamicLibrary _loadLib() {
^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.1/lib/src/impl/native_iris_api_engine_binding_delegate.dart:40:24:
Error: Type 'ffi.Void' not found.
      List<ffi.Pointer<ffi.Void>> args) {
                       ^^^^^^^^
`

**Comment by littleGnAl** [comment]
For web support issues, see https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/844

**Comment by maravilhosinga** [comment]
With the version version 6.0.0 I was where able to build web, even without using agora in web version, the problem with the current version is that it's impossible to build web app, even if you will not use agora for web. In my case we are using agora only in mobile (iOS and Android)

**Comment by littleGnAl** [comment]
Flutter web is not supported on 6.x, I'm not sure how you can build it with 6.0.0.

**Comment by maravilhosinga** [comment]
@littleGnAl Instead only writing, why don't you just test.
