### ISSUE TITLE
when i add latest version of  agora_rtc_engine: ^6.2.1 i getting error 

### ISSUE THREAD

**Issue by darshan1226** [AgoraIO-Extensions/Agora-Flutter-SDK#1195]
when i add latest version of  agora_rtc_engine: ^6.2.1 i getting error :
  [1/2] Building CXX object CMakeFiles/iris_method_channel.dir/iris_event.cc.o
  FAILED: CMakeFiles/iris_method_channel.dir/iris_event.cc.o 
  /home/stack/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/stack/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/stack/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DDART_SHARED_LIB -Diris_method_channel_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/iris_method_channel.dir/iris_event.cc.o -MF CMakeFiles/iris_method_channel.dir/iris_event.cc.o.d -o CMakeFiles/iris_method_channel.dir/iris_event.cc.o -c /home/stack/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/src/iris_event.cc
  In file included from /home/stack/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/src/iris_event.cc:6:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/stack/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/src/iris_event.cc:90:17: error: use of undeclared identifier 'memcpy'; did you mean 'wmemcpy'?
                  memcpy(abuffer, obuffer, abufferLength);
                  ^~~~~~
                  wmemcpy
  /snap/flutter/current/usr/include/wchar.h:262:17: note: 'wmemcpy' declared here
  extern wchar_t *wmemcpy (wchar_t *__restrict __s1,
                  ^
  /home/stack/.pub-cache/hosted/pub.dev/iris_method_channel-1.1.0/src/iris_event.cc:90:24: error: cannot initialize a parameter of type 'wchar_t *' with an lvalue of type 'uint8_t *' (aka 'unsigned char *')
                  memcpy(abuffer, obuffer, abufferLength);
                         ^~~~~~~

**Comment by littleGnAl** [comment]
Relative https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1086

**Comment by ChiragYogi** [comment]
the Relative issue is closed with answer that say  reinstalling flutter wiil solve the issue but i have tried that still getting same error. Please let me know if found any fix.
Thanks
