### ISSUE TITLE
Add EXTERNAL to the CameraDirection enum

### ISSUE THREAD

**Issue by neilhosey** [AgoraIO-Extensions/Agora-Flutter-SDK#1211]
**Is your feature request related to a problem? Please describe.**
We use Agora.io with our flutter app on Android AOSP boxes, we have 2 cameras, one back camera which is used for something else, and an EXTERNAL camera which is the one we want to use for video calls:
![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/3287921/08805b1d-9164-44f4-baaa-bdc92e1b4f16)

When i try to call this to pick the EXTERNAL camera:

      await _engine.setCameraCapturerConfiguration(CameraCapturerConfiguration( cameraDirection: CameraDirection.EXTERNAL));

there is no CameraDirection.EXTERNAL enum value, i can only set FRONT or BACK camera.  Tt doesn't allow to pre-select the one I want. 

**Describe the solution you'd like**
Add EXTERNAL as a value to this enum:

https://api-ref.agora.io/en/video-sdk/flutter/6.x/API/enum_cameradirection.html

**Describe alternatives you've considered**
I cannot extend the ENUM or subclass because of dart so i really dont have other options.

**Additional context**

**Comment by littleGnAl** [comment]
It's not supported by the agora native sdk.
