### ISSUE TITLE
Samsung speaker volume causing significant disruptions to the users.

### ISSUE THREAD

**Issue by OmarHamed553** [AgoraIO-Extensions/Agora-Flutter-SDK#1216]
Describe the bug
The bug that is being reported is related to the use of Agora's Flutter SDK (version 6.2.0) on Samsung devices. When users receive a video call, the volume fluctuates, often decreasing to the point where the user is unable to hear anything. Interestingly, the issue sometimes resolves itself if the user turns off their Bluetooth, regardless of whether they are connected to a Bluetooth device or not.

To Reproduce

Receive a video call on a Samsung device using the app.
Observe that the volume fluctuates dramatically during the call.
Disable Bluetooth on the device.
Note that sometimes the issue resolves itself upon doing so.
Expected behavior
The expected behavior is for the audio volume to remain consistent throughout the duration of a video call. Turning Bluetooth on or off should not have any impact on the audio performance during a video call.

Screenshots

https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/74277257/10308eff-2731-4275-aba4-89e2d1d61ab0

Desktop (please complete the following information):
Not applicable, as the issue pertains to Samsung smartphone devices.

Smartphone (please complete the following information):

Device: Samsung Devices (more specific model information needed)
OS: (This would require more specific OS version information. As the error pertains to multiple Samsung devices, a range may be applicable here.)
Browser: Not applicable (as this is an issue with the app, not a browser-based application)
Agora Flutter SDK Version: 6.2.0
Additional context
This issue is causing significant disruption for our users, leading to multiple complaints. The peculiar behavior where turning off Bluetooth sometimes resolves the issue suggests there may be an underlying conflict between the audio management in the Agora Flutter SDK and Samsung's Bluetooth/audio management systems. Further investigation is needed.

**Comment by littleGnAl** [comment]
@OmarHamed553
I think it's better to raise a ticket to Agora support for further investigation.

**Comment by OmarHamed553** [comment]
@littleGnAl How to raise a ticket to Agora support ?

**Comment by littleGnAl** [comment]
Please try https://agora-ticket.agora.io/

**Comment by utkudenis** [comment]
I have same problem, please inform us

**Comment by OmarHamed553** [comment]
I just noticed that it happens only if the Bluetooth is on and it's paired to a device (watch, etc..) once you unpair the device and leave the Bluetooth ON there's no issue this is frustrating for users and should be fixed!

**Comment by OmarHamed553** [comment]
I opened a ticket and their suggestion was to change the audio scenario to`AudioScenarioType.audioScenarioGameStreaming` which doesn't make sense and also the issue wasn't resolved

**Comment by littleGnAl** [comment]
I think you can keep asking the agora support for this issue, they're more professional to investigate it.
