### ISSUE TITLE
pod install bug

### ISSUE THREAD

**Issue by osama450** [AgoraIO-Extensions/Agora-Flutter-SDK#1223]
osamamohamed@Osamas-MacBook-Pro ios % pod install      
Analyzing dependencies
firebase_core: Using Firebase SDK version '10.10.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.10.0' defined in 'firebase_core'
[!] CDN: trunk Repo update failed - 107 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.5.2/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.6.2/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.6.2-fix.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.7.0.3/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.7.1-beta.1/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.7.1-beta.2/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.7.1-beta.5/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.7.2.2-test.1/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.7.2.2-test.2/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.7.2.70-build.1/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.7.2.70-test.1/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/3.8.201/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-alpha.1/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.10/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.11/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.12/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.13/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.2/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.3/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.4/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.5/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.6/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.7/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.8/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-beta.9/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-rc.1/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-rc.2/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-rc.3/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0-test.3/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0.130/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0.130-build.3/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0.130-rc.2/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0.132-build.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0.133-build.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0.133.2-build.2/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0.229-rc.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0.5-beta.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0.5-beta.2/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.0.5-beta.3/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.1-test.1/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.1.205-rc.2/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.1.215/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.1.217/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.1.218/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.1.5-rc.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.0.1.7-rc.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.0-build.3/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.0-build.4/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.0-dev.3/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.0-rc.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.0-rc.2/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.0-test.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.0-test.2/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.0-test.3/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.1-dev.1/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.1-rc.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.1.1-rc.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.1.2012-dev.1/AgoraIrisRTC_iOS.podspec.json Response: SSL connect error
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/1/7/a/AgoraIrisRTC_iOS/4.1.1.2013-dev.1/AgoraIrisRTC_iOS.podspec.json Response: Timeout was reached

**Comment by Ayman-Barghout** [comment]
@osama450
If you reside in Egypt, this is most likely a side effect of website blocking imposed by our ISP, this is not related to Agora but any `pod install` fails for me unless I use VPN, so using a VPN should resolve this issue hopefully!

**Comment by littleGnAl** [comment]
It is most like a network issue, as @Ayman-Barghout suggested, using a VPN may resolve it.
