### ISSUE TITLE
W/agora.io(24391): [STRATEGY RUNNER] strategy chain not found! timer_type type:1

### ISSUE THREAD

**Issue by jerrypaulsam** [AgoraIO-Extensions/Agora-Flutter-SDK#1225]
After an audio call, I am getting this response in console. This runs for an infinite amount of time, until I reinstall the app (debug). and no further incoming calls are possible. The device just vibrates for a moment and this response keeps getting printed on the console.
 

D/CCodecBufferChannel(24391): [c2.android.aac.decoder#966] DEBUG: elapsed: mInputMetEos 6, hasPendingOutputsInClient 0, n=1 [in=0 pipeline=0 out=2]
D/PipelineWatcher(24391): [0xb400007d2b532680] elapsed: mFramesInPipeline 2, n 6
D/CCodecBufferChannel(24391): [c2.android.aac.decoder#197] DEBUG: elapsed: mInputMetEos 6, hasPendingOutputsInClient 0, n=1 [in=0 pipeline=0 out=2]
D/PipelineWatcher(24391): [0xb400007c3d7ed680] elapsed: mFramesInPipeline 2, n 6
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []
W/agora.io(24391): [STRATEGY RUNNER] strategy chain not found! timer_type type:1
D/JSON    (24391): []
D/JSON    (24391): []
D/JSON    (24391): []

**Comment by laxkarparas1** [comment]
same issue ,but in my case when i end a video call this issue is coming 
any solution

**Comment by jerrypaulsam** [comment]
after I call `_engine.release()`, it seems to have disappeared.

**Comment by littleGnAl** [comment]
Call `RtcEngine.release` is necessary to avoid unknown issues. If calling `RtcEngine.release` does not work for you, I think it's better to raise a new ticket to the agora support.

**Comment by melshenawyarabapps** [comment]
In RtcEngineEventHandler
you can put this code 
onError: (ErrorCodeType err, String msg) {
            debugPrint(
                'Error rtc engin =============================> Code = ${err.name} MSG = $msg');
          },
          then you will know the reason
          I think this message because rtc token is not true

**Comment by jerrypaulsam** [comment]
@laxkarparas1 on dispose add `_await engine.release()` and see if the error still appear.

**Comment by LeeeYudE** [comment]
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1225

**Comment by diaaAlterh** [comment]
`await engine.initialize(const RtcEngineContext(
      appId: kAgoraAppId,
      channelProfile: ChannelProfileType.channelProfileLiveBroadcasting,
      logConfig: LogConfig(level: LogLevel.logLevelError)
    ));`
    
 just change the logLevel to  LogLevel.logLevelError in the log config when initializing the RTC engine

**Comment by jerrypaulsam** [comment]
I am getting the same error again which is creating lots of issues. It's literally consuming a lot of memory and no further calls can be received on the device as the incoming call notifications are suppressed as this keeps on printing. The same happens with both dev and release builds.

**Comment by littleGnAl** [comment]
@jerrypaulsam 
I think it's better to raise a new ticket to the agora support for further investigation of this issue.
