### ISSUE TITLE
Execution failed for task ':iris_method_channel:configureCMakeDebug[arm64-v8a]'.

### ISSUE THREAD

**Issue by yazanalkamsheh** [AgoraIO-Extensions/Agora-Flutter-SDK#1226]
**Describe the bug**
after install package and run code I have problem in cmake but I installed microsoft c++ redistributable and install ndk from sdk tools  and install cmake also but i don't know what is problem

**this is problem in console** 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':iris_method_channel:configureCMakeDebug[arm64-v8a]'.
> [CXX1405] error when building with cmake using C:\Users\ASUS\AppData\Local\Pub\Cache\hosted\pub.dev\iris_method_channel-1.1.0\src\CMakeLists.txt: -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - failed
  -- Check for working CXX compiler: C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
  -- Check for working CXX compiler: C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - broken
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/2z5851z3/arm64-v8a/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/2z5851z3/arm64-v8a/CMakeFiles/CMakeError.log".

  C++ build system [configure] failed while executing:
      @echo off
      "C:\\Users\\ASUS\\AppData\\Local\\Android\\sdk\\cmake\\3.18.1\\bin\\cmake.exe" ^
        "-HC:\\Users\\ASUS\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\iris_method_channel-1.1.0\\src" ^
        "-DCMAKE_SYSTEM_NAME=Android" ^
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
        "-DCMAKE_SYSTEM_VERSION=16" ^
        "-DANDROID_PLATFORM=android-16" ^
        "-DANDROID_ABI=arm64-v8a" ^
        "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^
        "-DANDROID_NDK=C:\\Users\\ASUS\\AppData\\Local\\Android\\sdk\\ndk\\23.1.7779620" ^
        "-DCMAKE_ANDROID_NDK=C:\\Users\\ASUS\\AppData\\Local\\Android\\sdk\\ndk\\23.1.7779620" ^
        "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\ASUS\\AppData\\Local\\Android\\sdk\\ndk\\23.1.7779620\\build\\cmake\\android.toolchain.cmake" ^
        "-DCMAKE_MAKE_PROGRAM=C:\\Users\\ASUS\\AppData\\Local\\Android\\sdk\\cmake\\3.18.1\\bin\\ninja.exe" ^
        "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\ASUS\\StudioProjects\\streaming\\build\\iris_method_channel\\intermediates\\cxx\\Debug\\2z5851z3\\obj\\arm64-v8a" ^
        "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=C:\\Users\\ASUS\\StudioProjects\\streaming\\build\\iris_method_channel\\intermediates\\cxx\\Debug\\2z5851z3\\obj\\arm64-v8a" ^
        "-DCMAKE_BUILD_TYPE=Debug" ^
        "-BC:\\Users\\ASUS\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\iris_method_channel-1.1.0\\android\\.cxx\\Debug\\2z5851z3\\arm64-v8a" ^
        -GNinja
    from C:\Users\ASUS\AppData\Local\Pub\Cache\hosted\pub.dev\iris_method_channel-1.1.0\android
  CMake Warning at C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
    C:/Users/ASUS/AppData/Local/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
    CMakeLists.txt:10 (project)

  CMake Warning at C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
    C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/2z5851z3/arm64-v8a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
    C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/2z5851z3/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

  CMake Warning at C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
    C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/2z5851z3/arm64-v8a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
    C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/2z5851z3/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

  CMake Warning at C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
    An old version of CMake is being used that cannot automatically detect
    compiler attributes.  Compiler identification is being bypassed.  Some
    values may be wrong or missing.  Update to CMake 3.19 or newer to use
    CMake's built-in compiler identification.
  Call Stack (most recent call first):
    C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
    C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/2z5851z3/arm64-v8a/CMakeFiles/3.18.1-g262b901-dirty/CMakeSystem.cmake:6 (include)
    C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/2z5851z3/arm64-v8a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

  CMake Error at C:/Users/ASUS/AppData/Local/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeTestCXXCompiler.cmake:59 (message):
    The C++ compiler

      "C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.dev/iris_method_channel-1.1.0/android/.cxx/Debug/2z5851z3/arm64-v8a/CMakeFiles/CMakeTmp

      Run Build Command(s):C:\Users\ASUS\AppData\Local\Android\sdk\cmake\3.18.1\bin\ninja.exe cmTC_2ecaf && ninja: fatal: CreateProcess: %1 is not a valid Win32 application.

    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:10 (project)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by littleGnAl** [comment]
> from C:\Users\ASUS\AppData\Local\Pub\Cache\hosted\pub.dev\iris_method_channel-1.1.0\android
CMake Warning at C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
An old version of CMake is being used that cannot automatically detect
compiler attributes. Compiler identification is being bypassed. Some
values may be wrong or missing. Update to CMake 3.19 or newer to use
CMake's built-in compiler identification.
Call Stack (most recent call first):
C:/Users/ASUS/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
C:/Users/ASUS/AppData/Local/Android/Sdk/cmake/3.18.1/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)
CMakeLists.txt:10 (project)

Based on the console log output, maybe you can try to upgrade to cmake 3.19 to see if it works or not.

**Comment by littleGnAl** [comment]
There's a relative issue, I'm not sure if it is helpful or not 
https://github.com/android/ndk/issues/1363

And which version of gradle do you use, here the version the API example used.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/10038b87a8297d23addbec6124f69e7e7032f297/example/android/build.gradle#L10

**Comment by hrxiang** [comment]
注释插件 iris_method_channel-1.2.0 下的build.grade里的代码
```
// 注释以下代码
externalNativeBuild {
    cmake {
        path "src/main/cpp/CMakeLists.txt"
    }
}
```

**Comment by littleGnAl** [comment]
@yazanalkamsheh 
Can you try to download the `Microsoft Visual C++ 2015 Redistributable` to see if works or not
https://stackoverflow.com/a/76192198

**Comment by devsideal** [comment]
I'm Also getting same issue:

AILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':iris_method_channel:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process /home/ideal228/Android/Sdk/cmake/3.18.1/bin/ninja with arguments {-C /home/ideal228/.pub-cache/hosted/pub.dev/iris_method_channel-1.2.1/android/.cxx/Debug/352r421n/arm64-v8a iris_method_channel}
  ninja: Entering directory `/home/ideal228/.pub-cache/hosted/pub.dev/iris_method_channel-1.2.1/android/.cxx/Debug/352r421n/arm64-v8a'
  [1/2] Building CXX object CMakeFiles/iris_method_channel.dir/iris_event.cc.o
  [2/2] Linking CXX shared library /home/ideal228/AndroidStudioProjects/Agora-Flutter-SDK/example/build/iris_method_channel/intermediates/cxx/Debug/352r421n/obj/arm64-v8a/libiris_method_channel.so
  FAILED: /home/ideal228/AndroidStudioProjects/Agora-Flutter-SDK/example/build/iris_method_channel/intermediates/cxx/Debug/352r421n/obj/arm64-v8a/libiris_method_channel.so 
  : && /home/ideal228/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/ideal228/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/ideal228/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libiris_method_channel.so -o /home/ideal228/AndroidStudioProjects/Agora-Flutter-SDK/example/build/iris_method_channel/intermediates/cxx/Debug/352r421n/obj/arm64-v8a/libiris_method_channel.so CMakeFiles/iris_method_channel.dir/iris_event.cc.o CMakeFiles/iris_method_channel.dir/iris_life_cycle_observer.cc.o CMakeFiles/iris_method_channel.dir/dart-sdk/include/dart_api_dl.c.o  -latomic -lm && :
  CMakeFiles/iris_method_channel.dir/iris_event.cc.o: In function `DartMessageHandler':
  /home/ideal228/.pub-cache/hosted/pub.dev/iris_method_channel-1.2.1/src/iris_event.cc:32: undefined reference to `irisevent::ILifeCycleObserver::ILifeCycleObserver(std::__ndk1::function<void ()>)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
```

**Comment by littleGnAl** [comment]
Hello @devsideal , I make a potential fix, can you try adding `dependency_overrides` below to see if it works?
```
dependency_overrides:
  iris_method_channel:
    git: https://github.com/AgoraIO-Extensions/iris_method_channel_flutter.git
    ref: littlegnal/android-linux-build
```

**Comment by devsideal** [comment]
@littleGnAl , Yes, Its working by adding given dependency_overrides, Thanks.

**Comment by littleGnAl** [comment]
@devsideal Thanks for your try. I will publish the fix of the `iris_method_channel` to the pub.dev, and update the `agora_rtc_engine`, you need to dependent the latest `main` branch of the `agora_rtc_engine` later.

**Comment by littleGnAl** [comment]
@devsideal 
The fix has been merged into the `main` branch, please remove the `dependency_overrides ` and dependent the `main` branch instead.

**Comment by elihaialgoaitech** [comment]
Hi I got similar error.
I used main branch:
```
  agora_rtc_engine:
    git:
      url: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK.git
      ref: main
```

I tried `flutter clean`
I tried reinstall flutter
I tried delete pub cache directories
In another machine it works fine. I don't understand what the diffrence

This is the error:
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using /home/elihai/.pub-cache/git/Agora-Flutter-SDK-f9a81c697812d6e18692c9589e0d47abd8b1cb60/android/src/main/cpp/CMakeLists.txt: -- android-16 is not supported for arm64-v8a. Using minimum supported LP64 version 21.
  -- Android: Targeting API '21' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
  -- Android: Selected unified Clang toolchain
  -- The C compiler identification is Clang 12.0.8
  -- The CXX compiler identification is Clang 12.0.8
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - failed
  -- Check for working C compiler: /home/elihai/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
  -- Check for working C compiler: /home/elihai/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - broken
  -- Configuring incomplete, errors occurred!
  See also "/home/elihai/.pub-cache/git/Agora-Flutter-SDK-f9a81c697812d6e18692c9589e0d47abd8b1cb60/android/.cxx/Debug/e275s6j2/arm64-v8a/CMakeFiles/CMakeOutput.log".
  See also "/home/elihai/.pub-cache/git/Agora-Flutter-SDK-f9a81c697812d6e18692c9589e0d47abd8b1cb60/android/.cxx/Debug/e275s6j2/arm64-v8a/CMakeFiles/CMakeError.log".

  C++ build system [configure] failed while executing:
      /home/elihai/Android/Sdk/cmake/3.22.1/bin/cmake \
        -H/home/elihai/.pub-cache/git/Agora-Flutter-SDK-f9a81c697812d6e18692c9589e0d47abd8b1cb60/android/src/main/cpp \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=16 \
        -DANDROID_PLATFORM=android-16 \
        -DANDROID_ABI=arm64-v8a \
        -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
        -DANDROID_NDK=/home/elihai/Android/Sdk/ndk/23.1.7779620 \
        -DCMAKE_ANDROID_NDK=/home/elihai/Android/Sdk/ndk/23.1.7779620 \
        -DCMAKE_TOOLCHAIN_FILE=/home/elihai/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/home/elihai/Android/Sdk/cmake/3.22.1/bin/ninja \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/elihai/FlutterProjects/meeplus_app/build/agora_rtc_engine/intermediates/cxx/Debug/e275s6j2/obj/arm64-v8a \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/elihai/FlutterProjects/meeplus_app/build/agora_rtc_engine/intermediates/cxx/Debug/e275s6j2/obj/arm64-v8a \
        -DCMAKE_BUILD_TYPE=Debug \
        -B/home/elihai/.pub-cache/git/Agora-Flutter-SDK-f9a81c697812d6e18692c9589e0d47abd8b1cb60/android/.cxx/Debug/e275s6j2/arm64-v8a \
        -GNinja
    from /home/elihai/.pub-cache/git/Agora-Flutter-SDK-f9a81c697812d6e18692c9589e0d47abd8b1cb60/android
  CMake Error at /home/elihai/Android/Sdk/cmake/3.22.1/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
    The C compiler

      "/home/elihai/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: /home/elihai/.pub-cache/git/Agora-Flutter-SDK-f9a81c697812d6e18692c9589e0d47abd8b1cb60/android/.cxx/Debug/e275s6j2/arm64-v8a/CMakeFiles/CMakeTmp

      Run Build Command(s):/home/elihai/Android/Sdk/cmake/3.22.1/bin/ninja cmTC_c8c06 && [1/2] Building C object CMakeFiles/cmTC_c8c06.dir/testCCompiler.c.o
      [2/2] Linking C executable cmTC_c8c06
      FAILED: cmTC_c8c06 
      : && /home/elihai/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android21 --sysroot=/home/elihai/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions  -O2 -g -DNDEBUG -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined  -Wl,--gc-sections -B/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/9 -B/snap/flutter/current/usr/lib/x86_64-linux-gnu -B/snap/flutter/current/lib/x86_64-linux-gnu -B/snap/flutter/current/usr/lib/ -L/snap/flutter/current/usr/lib/gcc/x86_64-linux-gnu/9 -L/snap/flutter/current/usr/lib/x86_64-linux-gnu -L/snap/flutter/current/lib/x86_64-linux-gnu -L/snap/flutter/current/usr/lib/ -lblkid -lgcrypt -llzma -llz4 -lgpg-error -luuid -lpthread -ldl -lepoxy -lfontconfig CMakeFiles/cmTC_c8c06.dir/testCCompiler.c.o -o cmTC_c8c06  -latomic -lm && :
      ld: error: --fix-cortex-a53-843419 is only supported on AArch64 targets
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ninja: build stopped: subcommand failed.





    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:10 (project)
```

**Comment by abdalla3yash** [comment]
try to install iris_method_channel from here
https://pub.dev/packages/iris_method_channel

**Comment by elihaialgoaitech** [comment]
> try to install iris_method_channel from here https://pub.dev/packages/iris_method_channel

not helping

**Comment by abdalla3yash** [comment]
> > try to install iris_method_channel from here https://pub.dev/packages/iris_method_channel
> 
> not helping

so try 
```dart

flutter run --release 
cd android
./gradlew clean

**Comment by abdalla3yash** [comment]
> > > try to install iris_method_channel from here https://pub.dev/packages/iris_method_channel
> > 
> > 
> > not helping
> 
> so try
> 
> ```dart
> flutter run --release 
> cd android
> ./gradlew clean
> ```

or try ta add this in android/build.gradle


```dart
android {
  externalNativeBuild {
            cmake {
                cppFlags ""
                abiFilters 'arm64-v8a'
                arguments "-DANDROID_TOOLCHAIN=clang"
            }
     }
}
```

**Comment by elihaialgoaitech** [comment]
Still doesn't work
But I foud  a workaroud:
1.Open the `android` directory with android studio.
2. run.

**Comment by elihaialgoaitech** [comment]
The problem sloved after restart my system 🤦🏽‍♂️
