### ISSUE TITLE
Doc Improvements for MediaRecorder

### ISSUE THREAD

**Issue by tushar0518** [AgoraIO-Extensions/Agora-Flutter-SDK#1242]
**Is your feature request related to a problem? Please describe.**
I'm trying to integrate MediaRecorder Feature in our app so I checked the MediaRecorder example from the git hub repo, I get the start and stop functions but somehow I'm not able to connect the 2 devices,
My ChannelID, token(temp), and App ID are proper and take the local UId as 0.
So I don't know what going wrong in the code or if Am I missing something there.

**Describe the solution you'd like**
So, can any of you provide a workable example of the MediaRecorder?

**Describe alternatives you've considered**
I searched the internet but did not find anything or even a proper example.

**Additional context**
I'm using the same code as the MediaRecorder GitHub repo -> [Link](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/media_recorder/media_recorder.dart)

**Comment by littleGnAl** [comment]
Which version do you use? There's a bugfix of the `MediaRecorder `, which is released in 6.2.2
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/1194

**Comment by tp-coderbabu** [comment]
@littleGnAl I'm using 6.2.1, yeah I just show that the new version is released. will check with the new version and let you know soon.
Thanks for the update.
