### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by abdulkash** [AgoraIO-Extensions/Agora-Flutter-SDK#1248]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':iris_method_channel:generateDebugRFile'.
> Could not resolve all files for configuration ':iris_method_channel:debugCompileClasspath'.
   > Could not find io.flutter:flutter_embedding_debug:1.0.0-655974aed33b608d1075cffae0fcaf06772d90d8.
     Required by:
         project :iris_method_channel

**Comment by littleGnAl** [comment]
Based on the log, it most like the `io.flutter:flutter_embedding_debug:1.0.0-655974aed33b608d1075cffae0fcaf06772d90d8` is missing.

**Comment by abdulkash** [comment]
I noticed it happens when I'm using flutter pre release version

**Comment by littleGnAl** [comment]
I'm sorry that the `agora_rtc_engine` only tested with the stable version of Flutter sdk, and can not gurentee it works fine with the non-stable version.

**Comment by abdulkash** [comment]
Oh ok I haved switched back to stable version
