### ISSUE TITLE
The basic example of Agora Voice call can't connect

### ISSUE THREAD

**Issue by akiligedeon** [AgoraIO-Extensions/Agora-Flutter-SDK#1265]
Agora simply doesn't work. `I have been fighting with voice call for a month now. All instructions were done successfully token was successfully generated but the engine will not connect and won't return any useful information

**Comment by littleGnAl** [comment]
Hello @akiligedeon, can you try running our API example to see if works or not?
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/example
