### ISSUE TITLE
Screen record issue when remote user connect

### ISSUE THREAD

**Issue by adnanatif** [AgoraIO-Extensions/Agora-Flutter-SDK#1274]
I try to record the screen when two users connect on a call in the app. But it does not work.
But screen recording feature works when no remote user connect.
I am using flutter_screen_recording plugin for record screen.
When I save a video it saves with zero bytes.
It works well on Android but on ios it does not.
Any help would be appreciated thanks.
Do you guys thinks somehow it connect with remote user connection?
Any help would be appreciated.

**Comment by littleGnAl** [comment]
The `agora_rtc_engine` has the screen sharing feature, please check the get started guide
https://docs.agora.io/en/video-calling/develop/product-workflow?platform=flutter
or API example
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/screen_sharing/screen_sharing.dart
