### ISSUE TITLE
Is agora_rtc_engine: ^5.3.1 has switch camera feature?

### ISSUE THREAD

**Issue by SittiphanSittisak** [AgoraIO-Extensions/Agora-Flutter-SDK#1288]
It is not a bug.
I want to switch the camera from the front to the back camera on the mobile browser.
The UI of this package doesn't show on the mobile browser but the function to share camera view is still working, but I don't want the front camera view.
How to do this?

I tried to use
```
                  ElevatedButton(
                    onPressed: () async {
                      try {
                        await _engine.switchCamera();
                        if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('switch camera success'), duration: Duration(seconds: 3)));
                      } catch (e) {
                        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.toString()), duration: const Duration(seconds: 3)));
                      }
                    },
                    child: const Text('switch camera'),
                  )
```
The snack bar showed 'switch camera success' but the camera still did not change.

**Comment by littleGnAl** [comment]
I think it's not supported on mobile browser in 5.x

**Comment by SittiphanSittisak** [comment]
Rrr, I need to use just one page that shows video calls on the mobile browser.
Can you suggest a framework that has an Agora package with support for mobile web?

**Comment by littleGnAl** [comment]
We only recommend using the web features on the desktop at this time.

**Comment by littleGnAl** [comment]
On the latest code of the main branch, you can enumerate the devices and set the back camera yourself. Maybe you can try this example https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/device_manager/device_manager.dart
