### ISSUE TITLE
infinite rejoin when setting up a UDP proxy on iOS devices from agora_rtc_engine 6.2.2

### ISSUE THREAD

**Issue by OtterBub** [AgoraIO-Extensions/Agora-Flutter-SDK#1298]
**Describe the bug**
infinite rejoin when setting up a UDP proxy on agora_rtc_engine 6.2.2.
- This occurs lag video/audio stream

**To Reproduce**
1. Initialize Engine
2. Set the proxy server to udp
3. Join the channel
4. See infinite loop on RtcEngineEventHandler onConnectionStateChanged.

**Expected behavior**
Just run only one rejoin the action

**Screenshots**
![Flutter Log](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/11672324/d024f407-8f3d-4d67-ab44-02c9ec73d323)

**Smartphone :**
 - Device: iPad Pro 12.9
 - OS: iOS 16.6
 - Version iOS 16.6 
 - agora_rtc_engine: 6.2.2

**Additional context**
There is no this issue on agora_rtc_engine: 6.1.1+1
There is no issue on Android devices

**Comment by littleGnAl** [comment]
I think it's better to raise a new ticket to Agora Support for further investigation of this issue.
