### ISSUE TITLE
Screen sharing

### ISSUE THREAD

**Issue by Allamprabhu1058** [AgoraIO-Extensions/Agora-Flutter-SDK#1301]
**Describe the bug**
Without enabling the video we are unable to share the screen. How it is possible?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by littleGnAl** [comment]
All video-relative features need to enable the video first.

**Comment by littleGnAl** [comment]
Yes, screen sharing is the video-related feature, you should enable the video first.

**Comment by Allamprabhu1058** [comment]
Hi, I am using agora flutter sdk version : ^5.3.1, one to one user screen sharing working fine, If there are more then 2 members in the call and shared the screen by one person, it will stop after certain time( in 1 or 2 min screen share will stop sharing disply white screen). Tested in flutter web build.

**Comment by littleGnAl** [comment]
Can you try the latest code in `main` branch to see if it works or not?
