### ISSUE TITLE
Error (Xcode): There is no XCFramework found

### ISSUE THREAD

**Issue by sven-xie** [AgoraIO-Extensions/Agora-Flutter-SDK#1330]
agora_rtc_engine: ^6.2.2 版本

已试过
flutter clean
cd ios
删除Podfile文件夹和podfile.lock
pod install
结果 依旧报错

日志：

Automatically signing iOS for device deployment using specified development team in Xcode project: GA5Y9FST86
Running pod install...                                             13.9s
Running Xcode build...                                                  
Xcode build done.                                           13.3s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): There is no XCFramework found at '/Users/sven/mtworkspace/yunphone/yunphone_controller/ios/Pods/AgoraRtcEngine_iOS/AgoraDav1d.xcframework'.

Error (Xcode): There is no XCFramework found at
'/Users/sven/mtworkspace/yunphone/yunphone_controller/ios/Pods/AgoraRtcEngine_iOS/AgoraSuperResolutionExtension.xcframework'.

podsfile:

# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'ShareScreen' do
    use_frameworks!
    use_modular_headers!
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # Temporary exclude simulator arm64 to allow run app on simulator
    # https://developer.apple.com/forums/thread/656509
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386"
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
         ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1'
      ]
    end
  end
end

**Comment by littleGnAl** [comment]
Maybe you can try deleting the `ios/Pods` directory too.

**Comment by sven-xie** [comment]
try 
flutter clean
cd ios
delete ios/Pods directory and ios/podfile.lock file
pod install

but result is error alive

**Comment by littleGnAl** [comment]
Can you try running our example to see if the error exists?
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/example
