### ISSUE TITLE
Converting VideoFrame to JPEG in Agora Flutter SDK

### ISSUE THREAD

**Issue by azazadev** [AgoraIO-Extensions/Agora-Flutter-SDK#1335]
I'm working on a project where I need to apply a TFLite model for each frame of the local user's video during a video call using the Agora Flutter SDK.

I came across the VideoFrameObserver in the documentation, which seems to be a promising tool for this task. Here's the code snippet I found:
```

VideoFrameObserver videoFrameObserver = VideoFrameObserver(
    onCaptureVideoFrame: (VideoSourceType sourceType, VideoFrame videoFrame) async {
      // How to convert videoFrame to JPEG?
    },
    onRenderVideoFrame: (String channelId, int remoteUid, VideoFrame videoFrame) {});
```

I've been trying to figure out how to convert the videoFrame to a JPEG image, but I haven't been successful so far. I've also checked this [issue](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1221#issuecomment-1643466857) , but the solution provided there didn't work for me.

So, my question is: Has anyone successfully converted the videoFrame to a JPEG image in the Agora Flutter SDK? If you have any insights, tips, or code samples to share, it would be greatly appreciated!

**Comment by littleGnAl** [comment]
Which version of the `agora_rtc_engine` you are using, and which system you are testing on?

**Comment by azazadev** [comment]
> Which version of the `agora_rtc_engine` you are using, and which system you are testing on?

agora_rtc_engine: ^6.2.2 
Device : Iphone 11 pro

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.1 22C65 darwin-arm64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
[✓] VS Code (version 1.82.1)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!

**Comment by azazadev** [comment]
Thanks @littleGnAl for you answer, please do not spend more time on this I will close as solution is provided by **brendan-duncan** the owner of image package 

```
onCaptureVideoFrame: (VideoSourceType sourceType, VideoFrame videoFrame) async {
  final directory = await getTemporaryDirectory();
  final filePath = '${directory.path}/frame.jpeg';
  int height = videoFrame.height!;
  int width = videoFrame.width!;
  final img = Image(width: width, height: height);
  final yData = videoFrame.yBuffer!;
  final uData = videoFrame.uBuffer!;
  final vData = videoFrame.vBuffer!;
  final yStride = videoFrame.yStride!;
  final uStride = videoFrame.uStride!;
  final vStride = videoFrame.vStride!;
          
  for (int y = 0; y < height; y++) {
    var y2 = y ~/ 2;
    for (int x = 0; x < width; x++) {
        var x2 = x ~/ 2;
        var yIndex = y * yStride + x;
        var uIndex = y2 * uStride + x2;
        var vIndex = y2 * vStride + x2;

        int yValue = yData[yIndex].toInt();
        int uValue = uData[uIndex].toInt();
        int vValue = vData[vIndex].toInt();

        // YUV to RGB conversion
        int r = (yValue + 1.13983 * (vValue - 128)).toInt();
        int g = (yValue - 0.39465 * (uValue - 128) - 0.58060 * (vValue - 128)).toInt();
        int b = (yValue + 2.03211 * (uValue - 128)).toInt();

        // Clamp the values to the range [0, 255]
        r = r.clamp(0, 255);
        g = g.clamp(0, 255);
        b = b.clamp(0, 255);
        
        img.setPixelRgb(x, y, r, g, b);
    }
  }
          
  File(filePath).writeAsBytesSync(img_lib.encodeJpg(img));
  await OpenFile.open(filePath);
}
```
