### ISSUE TITLE
Do we need both camera and mic to be enabled during screen sharing ?

### ISSUE THREAD

**Issue by souravdivii** [AgoraIO-Extensions/Agora-Flutter-SDK#1350]
**Describe the bug**
In my application I tried muting the mic and sharing the screen but eventually noticed that  the mic toggling stops responding for the remote users after screen sharing is stopped.

**To Reproduce**
1. Disable mic before sharing the screen.
2. Toggle it during screen sharing & then stop the screen sharing.
3. The mic stops responding unless the user joins the call again.
4. It happens for both iOS and Android.

**Expected behaviour**
I would like to know if the mic needs to be enabled always during screen sharing ?

**Comment by littleGnAl** [comment]
I think it's better to raise a new ticket to Agora support for further investigation, thanks.

**Comment by souravdivii** [comment]
Closing the issue as this is not relevant anymore. Thank you.

**Comment by souravdivii** [comment]
Please close this issue as it is not relevant anymore.

**Comment by souravdivii** [comment]
Closing this issue as it is not relevant anymore.
