### ISSUE TITLE
Audience count

### ISSUE THREAD

**Issue by nisha-rana16** [AgoraIO-Extensions/Agora-Flutter-SDK#1367]
How do I get the audience count which are active to show on app to everyone? Is there any callback for that?

**Comment by littleGnAl** [comment]
I think you can count it in the `onUserJoined` callback.

**Comment by nisha-rana16** [comment]
It only gives callback for the users joined as a broadcaster, not for the users who joined as the Audience. Actually, we need to get the callback for audience count. Is there any way to get the audience count at audience side as well?

**Comment by littleGnAl** [comment]
I think you should maintain this state(audience count) in your server, or use the Agora RTM SDK to achieve it, there's no built-in callback for this in the RTC SDK.
