### ISSUE TITLE
Disable microphone permission 

### ISSUE THREAD

**Issue by azazadev** [AgoraIO-Extensions/Agora-Flutter-SDK#1368]
I have a use case when I want to have only camera permission, but by default camera and microphone are requested, my question : 

How we can completely remove microphone permission request ?.

I have try to override   enabledPermission in AgoraClient ( enabledPermission: [Permission.camera] ) --> not working
I have also remove askForUserCameraAndMicPermission from SessionController but also not working ?

any idea ?

**Comment by littleGnAl** [comment]
May I ask what `AgoraClient ` ref from?
