### ISSUE TITLE
Unable to release ios build

### ISSUE THREAD

**Issue by woueziou** [AgoraIO-Extensions/Agora-Flutter-SDK#1375]
**Describe the bug**
I built an app that works fine on debug. The release build is ok also. but when the process failed when I try to post the app to appstoreconnect
**To Reproduce**
1. Make archive
2. upload with Transporter or any CI/CD platform

**Expected behavior**
I expect the build be uploaded 
**Screenshots**
<img width="634" alt="Screenshot 2023-10-13 at 22 46 40" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/38907637/768a86c8-5ff0-44f7-9224-df9f25253783">

**Desktop (please complete the following information):**
 - OS:  any IOS

**Comment by ahndwon** [comment]
Happening to me also. Can't release. Fix needed ASAP

**Comment by littleGnAl** [comment]
Hello @woueziou @ahndwon, can you share the `flutter doctor -v` and which version of Xcode you are using?

**Comment by woueziou** [comment]
Hi all.  I use Xcode 15.0 and my flutter doctor -v output below

[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-TG)
    • Flutter version 3.13.6 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (3 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Applications/android
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Applications/android
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 20.0.2+9-78)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • Wzx (mobile)    • 00008110-00110DCA3A0A801E • ios          • iOS 17.0.3 21A360
    • macOS (desktop) • macos                     • darwin-arm64 • macOS 14.0 23A344 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by littleGnAl** [comment]
I'm updating my system and Xcode, hope I can try to reproduce this issue TMR.

**Comment by woueziou** [comment]
Please this bug prevents me from submitting. I would like to have alternative or a work around. please !!

**Comment by woueziou** [comment]
> I'm updating my system and Xcode, hope I can try to reproduce this issue TMR.

**Comment by littleGnAl** [comment]
@woueziou Which version of `agora_rtc_engine` you are using?

**Comment by littleGnAl** [comment]
I found that this problem appeared in 6.2.3. We will release a hotfix version ASAP. For a workaround, you can downgrade to  6.2.2 first.

**Comment by woueziou** [comment]
> I found that this problem appeared in 6.2.3. We will release a hotfix version ASAP. For a workaround, you can downgrade to 6.2.2 first.

I already downgraded but same result

**Comment by woueziou** [comment]
> @woueziou Which version of `agora_rtc_engine` you are using?

the last one. but It started with 6.2.2

**Comment by littleGnAl** [comment]
It's weird, I have confirmed that the `CFBundleShortVersionString` in 6.2.2 should be corrected.
<img width="731" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/8847263/c4bbc3fc-c334-4cd3-b372-b00098e3041f">

Can you try clean it and retry?

**Comment by woueziou** [comment]
> It's weird, I have confirmed that the `CFBundleShortVersionString` in 6.2.2 should be corrected. <img alt="image" width="731" src="https://user-images.githubusercontent.com/8847263/275764975-c4bbc3fc-c334-4cd3-b372-b00098e3041f.png">
> 
> Can you try clean it and retry?

Ok let me check again.

**Comment by woueziou** [comment]
Hello,
This is the agroa package in my pubspec
<img width="616" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/38907637/165e5196-315f-4544-aa7f-ae0c73801300">

I made :
- flutter clean
- pod deintegrate
- flutter pub get
- pod install
This is the output to the pod install :

Analyzing dependencies
firebase_core: Using Firebase SDK version '10.15.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.15.0' defined in 'firebase_core'
Downloading dependencies
Installing AgoraIrisRTC_iOS (4.2.3-build.3) <--- Agora 
Installing AgoraRtcEngine_iOS (4.2.3) <--- Agora
Installing CryptoSwift (1.8.0)
Installing FMDB (2.7.5)
Installing Firebase (10.15.0)
Installing FirebaseCore (10.15.0)
Installing FirebaseCoreInternal (10.16.0)
Installing FirebaseInstallations (10.16.0)
Installing FirebaseMessaging (10.15.0)
Installing Flutter (1.0.0)
Installing GoogleDataTransport (9.2.5)
Installing GoogleUtilities (7.11.5)
Installing MapboxCommon (23.5.0)
Installing MapboxCoreMaps (10.13.1)
Installing MapboxMaps (10.13.1)
Installing MapboxMobileEvents (1.0.10)
Installing PromisesObjC (2.3.1)
Installing Sentry (8.11.0)
Installing SentryPrivate (8.11.0)
Installing Turf (2.7.0)
Installing agora_rtc_engine (6.2.3) <----- Agora Engine
Installing app_links (0.0.1)
Installing camera_avfoundation (0.0.1)
Installing device_info_plus (0.0.1)
Installing firebase_core (2.17.0)
Installing firebase_messaging (14.6.9)
Installing flutter_callkit_incoming (0.0.1)
Installing flutter_local_notifications (0.0.1)
Installing flutter_native_splash (0.0.1)
Installing flutter_ringtone_player (0.0.1)
Installing geocoding_ios (1.0.5)
Installing geolocator_apple (1.2.0)
Installing image_picker_ios (0.0.1)
Installing iris_method_channel (0.0.1)
Installing mapbox_maps_flutter (0.4.5)
Installing nanopb (2.30909.0)
Installing package_info_plus (0.4.5)
Installing path_provider_foundation (0.0.1)
Installing permission_handler_apple (9.1.1)
Installing sentry_flutter (0.0.1)
Installing share_plus (0.0.1)
Installing shared_preferences_foundation (0.0.1)
Installing sign_in_with_apple (0.0.1)
Installing sqflite (0.0.3)
Installing url_launcher_ios (0.0.1)
Installing vibration (1.7.5)
Installing video_player_avfoundation (0.0.1)
Installing webview_flutter_wkwebview (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 28 dependencies from the Podfile and 48 total pods installed.
I made an archive. 
I try to validate it. and this happened
![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/38907637/efb63369-fbc7-4dd3-a8f0-160c0dd0308d)

**Comment by littleGnAl** [comment]
I think you should remove the `^` to force specify the version: `agora_rtc_engine: 6.2.2`

**Comment by woueziou** [comment]
Yup. You're right! I let you know when validate again

**Comment by woueziou** [comment]
@littleGnAl  is ok. the build passed the validation process. Thanks
