### ISSUE TITLE
RtcEngine from Native and Agora Extensions

### ISSUE THREAD

**Issue by nizwar** [AgoraIO-Extensions/Agora-Flutter-SDK#1378]
I wondering how to get RtcEngine from native side
![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/33113137/8f4f93b4-ef28-4284-9a1a-896f3a8c41f4)

I've seen this #615, but the example seems doesn't work anymore with latest Agora

My goals is trying to use Banuba extensions on Flutter, and i can't find any docs anywhere between Agora or Banuba to implement it, and i can see native implementation that maybe do the hack for flutter side

**Comment by littleGnAl** [comment]
It's not supported after 6.x.

**Comment by nizwar** [comment]
Is there any solutions regarding that?

**Comment by littleGnAl** [comment]
As I know, the Banuba SDK implemented the Agora marketplace plugin, but I'm not sure if it can be integrated into Flutter or not.
