### ISSUE TITLE
App Freeze by AgoraRtcWrapper once hot restart

### ISSUE THREAD

**Issue by nizwar** [AgoraIO-Extensions/Agora-Flutter-SDK#1382]
**Describe the bug**
App freeze once hot restart the application

![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/33113137/0344f7ee-d7df-4ed2-b0f5-9607b98e2eef)

**To Reproduce**
It's hard to produce, sometime it happened once i randomly hot restart the app
 
![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/33113137/6a904377-51cc-498b-a30c-3f24ce052d7b)

I put agora initialization inside MainScreen, which i can say that was the root of the project
![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/33113137/ae496473-9363-4645-a3c5-559736913cd7)

I put it on root to avoid multiple IrisMethodChannel, it doesn't removed even i _engin.release() the agora
![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/33113137/134e4af2-dbc4-4d91-beee-be79559e0467)

**Platform**
Happened a lot on iOS (Device)

**Comment by littleGnAl** [comment]
Which version of `agora_rtc_engine` you are using?
