### ISSUE TITLE
Video and Audio not visible on Audience device but on other broadcaster's device it visible. 

### ISSUE THREAD

**Issue by Saket7042** [AgoraIO-Extensions/Agora-Flutter-SDK#1404]
Hi, I've integrated Agora Flutter RTC package for Live streaming feature.

On the audience device as Audio and video of broadcasters are not showing but at the same time If I check any other broadcaster on different device then I can hear the audio and video is visible too. Please help as in documentation it's unclear how we can subscribe to other's audio/video on Audience device.

agora_rtc_engine: ^6.2.2
Android version 12
Device Samsung M32 5G

**Comment by littleGnAl** [comment]
Do you mean you set `ClientRoleType.clientRoleAudience`, and then you want to receive the streams of other audiences?

**Comment by Saket7042** [comment]
yes I've set this ClientRoleType.clientRoleAudience for Audience but video and audio streams are not getting received, for broadcasters who are also in the same room at the same time they are able to hear and view other broadcaster's streams.

**Comment by littleGnAl** [comment]
This should be expected behavior, the user with `ClientRoleType.clientRoleAudience` can only receive the user with `ClientRoleType.clientRoleBroadcaster` but not other users with `ClientRoleType.clientRoleAudience` in the same channel

**Comment by littleGnAl** [comment]
I suppose you didn't set the `ChannelMediaOptions.autoSubscribeVideo` when you joinChannel as an audience.
But can you share the agora-iris.log so I can investigate it in more detail?

**Comment by Saket7042** [comment]
@littleGnAl that was the missing code I know this has something with subscribe so i was using rtcEngine.setSubscribeVideoAllowlist and any other code that I found related to this but there is no effect. It's working now please mention this in documentation as I couldn't able to find this piece of code anywhere in docs . Thanks 🙌

**Comment by littleGnAl** [comment]
If you can share the log, maybe I can investigate it in more detail.
