### ISSUE TITLE
iOS - Unable to submit build to testflight

### ISSUE THREAD

**Issue by gau187** [AgoraIO-Extensions/Agora-Flutter-SDK#1408]
I am unable to upload the build to testflight. I always shows this error.

This bundle is invalid. The value for key CFBundleShortVersionString '4.1.1.7' in the Info.plist file at 'Payload/Runner.app/Frameworks/AgoraRtWrapper.framework' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/
information_property_list/cfbundleshortversionstring (ID: aae15020-b363-4bcc-b6b1-5debf6c2e989)

I am using latest version from pub.dev, but still facing the same issue

**Comment by littleGnAl** [comment]
Please update `agora_rtc_engine: 6.2.4`.
