### ISSUE TITLE
Tests failing cus of error: type 'MockRtcEngine' is not a subtype of type 'RtcEngineImpl' in type cast

### ISSUE THREAD

**Issue by lewooz** [AgoraIO-Extensions/Agora-Flutter-SDK#1420]
Before v6.2.3 I could easily mock RtcEngine class and run tests but after updating to the most recent version my tests are no longer working.  This is the error I am getting:

![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/50250583/cb40372c-7f1f-4f24-96af-221116b5ff1b)

I am using mocktail package to mock RtcEngine and stub it's methods. When I downgrade to 6.2.2 everything works fine.

Any help would be greatly appreciated.

**Comment by littleGnAl** [comment]
The `createAgoraRtcEngine` returns the `RtcEngineImpl` underlying
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/64dbdada39638d763c1ef0dd07646eb95ecbd7bf/lib/src/agora_rtc_engine_ext.dart#L44

How does your test case look like, maybe it's not a good way to mock the `RtcEngine` interface if your test case is combined with the `AgoraVideoView`.

**Comment by lewooz** [comment]
I am getting the error when each widget test is finished which means I am getting the error only when the AgoraVideoView is getting disposed. This is how I am mocking the RtcEngine: 
![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/50250583/48b767a0-4b05-430c-97d6-f60c0a728d0e)

As I said I am not having issues with 6.2.2. A change made in 6.2.3 is the cause of the issue. My hunch is that the problem might be happening because extension methods can not be stubbed.

**Comment by littleGnAl** [comment]
If the rendering is not a matter of your test, I think you'd better mock `VideoViewController` and pass it to your `AgoraVideoView` implementation.
