### ISSUE TITLE
README from web section unclear

### ISSUE THREAD

**Issue by tadaspetra** [AgoraIO-Extensions/Agora-Flutter-SDK#1427]
The [README for the web section](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK#web-alpha) is not very clear.

The following sentence brings some questions:
```
We recommend downloading the iris_web artifact and including it as a local script in your <your-project>/web/index.html file, as this will allow for fine-grained control over how you host it.
```

What does "recommend" mean? Does Flutter Web work if we include this?
The phrase "fine-grained control over how you host it" is vague. Host what? What kind of control does it give?

**Comment by littleGnAl** [comment]
Sorry for the confusion, I updated the README to make it clearer now
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK?tab=readme-ov-file#web-alpha

**Comment by tadaspetra** [comment]
Appreciate it. That is more clear 👍
