### ISSUE TITLE
iOS按照一二步骤完成后，屏幕共享不成功，手机端 提示（null）屏幕直播；推流不成功；

### ISSUE THREAD

**Issue by sven-xie** [AgoraIO-Extensions/Agora-Flutter-SDK#1431]
第一步骤：pod增加；
targets_to_weaklink=['Pods-Runner', "agora_rtc_engine"]
    frameworks_to_weaklink=["AgoraAiEchoCancellationExtension", "AgoraAiNoiseSuppressionExtension", "AgoraAudioBeautyExtension", "AgoraClearVisionExtension", "AgoraContentInspectExtension", "AgoraDrmLoaderExtension", "AgoraVideoQualityAnalyzerExtension", "AgoraVideoSegmentationExtension"]
 
    next unless targets_to_weaklink.include?(target.name)
    target.build_configurations.each do |config|
      base_config_reference = config.base_configuration_reference
      unless base_config_reference. nil?
        xcconfig_path = base_config_reference.real_path
        xcconfig = File.read(xcconfig_path)
        frameworks_to_weaklink.each do |framework|
          xcconfig = xcconfig.gsub(/-framework "#{framework}"/, "-weak_framework \"#{framework}\"")
        end
        File.open(xcconfig_path, "w") { |file| file << xcconfig }
      end
    end

第二步骤：
<img width="869" alt="企业微信20231110-171230@2x" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/13388790/642fd57f-de26-4ad8-9260-d3ab8eaee00f">

APP 可以运行起来，但到了共享屏幕的时候；推流不成功；手机顶部显示的是 （null）屏幕直播；

该怎么解决这个问题呢？

**Comment by littleGnAl** [comment]
Which version of `agora_rtc_engine` you are using? Does it work if you do not add this change?

**Comment by sven-xie** [comment]
agora_rtc_engine: 6.1.0

it can work when id do not add this change

**Comment by littleGnAl** [comment]
Can you try the latest version to see if it works or not?
