### ISSUE TITLE
Call _engine.deviceManager.enumerateVideoDevices() on macOS or Windows error

### ISSUE THREAD

**Issue by liusir008** [AgoraIO-Extensions/Agora-Flutter-SDK#1435]
Describe the bug
Call _engine.deviceManager.enumerateVideoDevices() on macOS or Windows error:

type 'int' is not a subtype of type 'Iterable<dynamic>'
flutter: #0      VideoDeviceManagerImpl.enumerateVideoDevices                   agora_rtc_engine_impl.dart:1223

**Comment by littleGnAl** [comment]
Which version of `agora_rtc_engine` you are using? Can you share the full error log?

**Comment by liusir008** [comment]
Flutter (Channel stable, 3.13.9, on Microsoft Windows [版本 10.0.19045.3636], locale zh-CN)
Windows Version (Installed version of Windows is version 10 22H2 内部版本19045.3636)
agora_rtc_engine: ^6.2.4

<img width="1373" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/7404392/bdd3f1b1-8034-42cf-ac98-801ebc39129b">

**Comment by littleGnAl** [comment]
Can you share the log, log path: `C:\Users\<username>\AppData\Local\Agora\agora-iris.log`

**Comment by liusir008** [comment]
Maybe no useful logs
<img width="1238" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/7404392/08960d40-cc16-4af0-88fa-d7d53361c72b">

After I download the sdk source code, use local dependencies. Then debug the app. Found result is 0.

```
final rm = callApiResult.data;
final result = rm['result'];
```

<img width="644" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/7404392/89d28fd9-833d-4bbf-b5aa-b8649b3631cf">

**Comment by littleGnAl** [comment]
Based on your error log, I know which line caused the error, but I need to check why this happened. But it's weird, it should have logs file, it's there any file named `xx_iris.log`?

**Comment by littleGnAl** [comment]
Can you try our example to see if it works or not?

**Comment by liusir008** [comment]
After I added the code
```
await _engine.initialize(const RtcEngineContext(
    appId: 'xxxx',
));
```
There was no exception.
But Call ` _engine.deviceManager.enumerateVideoDevices()` return empty list.

**Comment by liusir008** [comment]
Based on the example, the problem was solved. Thanks.
