### ISSUE TITLE
iPhone connection to the video call failure 

### ISSUE THREAD

**Issue by DaryaZhukovich** [AgoraIO-Extensions/Agora-Flutter-SDK#1437]
We have troubles with connection to video via iPhone. We have integrated Broadcast Streaming sdk. Everything works good on Android, but iPhone doesn't connect to video at all. All permission on the phone were given. 

Everything works great on Android, but on IOS it works on a simulator, with any build from xcode via a wire, but as soon as the build is archived and uploaded on diawi/testflight/app store, it stops working ("_agoraEngine.initialize" method doesn't work)

It probably falls at the initialization stage of the video engine, so it does not even have time to write any logs

The "setupVideoSDKEngine" method is called then the method goes into an infinite await and does not return a value as well as does not perform anything after

Maybe someone has faced the same issue?

import 'package:agora_rtc_engine/agora_rtc_engine.dart';
import 'package:flutter/cupertino.dart';
import 'package:sound_guess/data/http/api_service.dart';
import 'package:sound_guess/data/utils/data_consts.dart';
import 'package:sound_guess/data/utils/enums/request_type.dart';
import 'package:sound_guess/domain/repository/agora_repository.dart';

import '../../domain/utils/enums/agora_token_type.dart';

class AgoraRepositoryImpl extends AgoraRepository {
  final ApiService _apiService;

  final RtcEngine _agoraEngine = createAgoraRtcEngine();

  AgoraRepositoryImpl(
    this._apiService,
  );

  @override
  RtcEngine get agoraEngine => _agoraEngine;

  @override
  Future<String> fetchToken({
    required AgoraTokenType tokenType,
    required String channelName,
    required int tokenRole,
    required int uid,
    int tokenExpireTime = 18000,
  }) async {
    // Prepare the Url
    String url =
        '${DataConsts.serverUrl}/${tokenType.getString}/$channelName/${tokenRole.toString()}/uid/${uid.toString()}';
    // Setup expire time
    final query = {
      'expiry': tokenExpireTime.toString(),
    };
    //Send the request
    final response = await _apiService.request(
      url: url,
      type: RequestType.get,
      queryParameters: query,
    );
    if (response.statusCode == 200) {
      Map<String, dynamic> json = response.data;
      String newToken = json['rtcToken'];
      debugPrint('Token Received');
      // Use the token to join a channel or renew an expiring token
      return newToken;
    } else {
      // If the server did not return an OK response, then throw an exception.
      throw Exception(
          'Failed to fetch a token. Make sure that your server URL is valid');
    }
  }

  @override
  Future<void> setupVideoSDKEngine({
    Function(int localUid)? onJoinChannelSuccess,
    Function(int remoteUid)? onUserJoined,
    Function(int remoteUid)? onUserOffline,
    Function()? onLeaveChannel,
    Function(int remoteUid, bool enabled)? onUserEnableLocalVideo,
    Function(int remoteUid, bool enabled)? onUserEnableVideo,
  }) async {
    await _agoraEngine.initialize(
      const RtcEngineContext(
        appId: DataConsts.appId,
        channelProfile: ChannelProfileType.channelProfileLiveBroadcasting,
        logConfig: LogConfig()
      ),
    );
    await _agoraEngine.enableVideo();
    _agoraEngine.registerEventHandler(

**Comment by littleGnAl** [comment]
I assume it's the symbols issue, maybe you can try setting this
https://docs.flutter.dev/platform-integration/ios/c-interop#stripping-ios-symbols

**Comment by DaryaZhukovich** [comment]
Thank you so much! It worked
