### ISSUE TITLE
onFacePositionChanged don't trigger when enableFaceDetection is true

### ISSUE THREAD

**Issue by iriya-kom** [AgoraIO-Extensions/Agora-Flutter-SDK#1445]
I tried to test face detection in already working video broadcast in app using enableFaceDetection method and onFacePositionChanged callback. enableFaceDetection(true) works without any exceptions, but callback don't send any data. Am I doing something wrong?

I'm using following code:

  Future<void> setupVideoSDKEngine({
    Function(int localUid)? onJoinChannelSuccess,
    Function(int remoteUid)? onUserJoined,
    Function(int remoteUid)? onUserOffline,
    Function()? onLeaveChannel,
    Function(int remoteUid, bool enabled)? onUserEnableLocalVideo,
    Function(int remoteUid, bool enabled)? onUserEnableVideo,
  }) async {
    await _agoraEngine.initialize(
      const RtcEngineContext(
        appId: DataConsts.appId,
        channelProfile: ChannelProfileType.channelProfileLiveBroadcasting,
      ),
    );
    await _agoraEngine.enableVideo();

    try {
      await _agoraEngine.enableFaceDetection(true);
    } catch (e) {
      debugPrint('$e');
    }

    _agoraEngine.registerEventHandler(
      RtcEngineEventHandler(
        onJoinChannelSuccess: (RtcConnection connection, int elapsed) {
          debugPrint(
              "Local user uid:${connection.localUid} joined the channel");
          if (onJoinChannelSuccess != null) {
            onJoinChannelSuccess(connection.localUid ?? 0);
          }
        },
        onUserJoined: (RtcConnection connection, int remoteUid, int elapsed) {
          debugPrint("Remote user uid:$remoteUid joined the channel");
          if (onUserJoined != null) onUserJoined(remoteUid);
        },
        onUserOffline: (RtcConnection connection, int remoteUid,
            UserOfflineReasonType reason) {
          debugPrint("Remote user uid:$remoteUid left the channel");
          if (onUserOffline != null) onUserOffline(remoteUid);
        },
        onLeaveChannel: (connection, stats) {
          if (onLeaveChannel != null) onLeaveChannel();
        },
        onUserEnableLocalVideo:
            (RtcConnection connection, int uid, bool enabled) {
          //debugPrint('onUserEnableLocalVideo $uid : $enabled');
          if (onUserEnableLocalVideo != null) {
            onUserEnableLocalVideo(uid, enabled);
          }
        },
        onUserEnableVideo: (RtcConnection connection, int uid, bool enabled) {
          //debugPrint('onUserEnableVideo $uid : $enabled');
          if (onUserEnableVideo != null) {
            onUserEnableVideo(uid, enabled);
          }
        },
        onFacePositionChanged: (
          int width,
          int height,
          List<Rectangle> vecRectangle,
          List<int> vecDistance,
          int numFaces,
        ) {
          debugPrint('/////////////////////');
          debugPrint('$vecRectangle');
          debugPrint('$vecDistance');
          debugPrint('/////////////////////');
        },
      ),
    );
  }

  Future<void> joinVideoCall({
    required String channelName,
    required int tokenRole,
    required uid,
  }) async {
    // Set channel options including the client role and channel profile
    final options = ChannelMediaOptions(
      clientRoleType: tokenRole == 1
          ? ClientRoleType.clientRoleBroadcaster
          : ClientRoleType.clientRoleAudience,
      channelProfile: ChannelProfileType.channelProfileLiveBroadcasting,
      audienceLatencyLevel: tokenRole != 1
          ? AudienceLatencyLevelType.audienceLatencyLevelLowLatency
          : null,
    );

    final token = await fetchToken(
      tokenType: AgoraTokenType.rtc,
      channelName: channelName,
      tokenRole: tokenRole,
      uid: uid,
    );

    if (tokenRole == 1) {
      await _agoraEngine.startPreview();
    }

    await _agoraEngine.leaveChannel();
    await _agoraEngine.joinChannel(
      token: token,
      channelId: channelName,
      options: options,
      uid: uid,
    );
  }

They are called one after another with await in async function.

Smartphones:
 - Galaxy S10e
 - Redmi Note 10 Pro
 - Galaxy M12.

**Additional context**
I tested similar functions in sample app and it worked, but I wasn't able to find any differenses in code.

**Comment by littleGnAl** [comment]
Which version of `agora_rtc_engine` you're using?

**Comment by iriya-kom** [comment]
> Which version of `agora_rtc_engine` you're using?

6.2.4

**Comment by littleGnAl** [comment]
Can you try to move `enableFaceDetection ` after the `startPreview`?
