### ISSUE TITLE
Flutter Web control functions returning NotImplemented

### ISSUE THREAD

**Issue by Adrianzctpa** [AgoraIO-Extensions/Agora-Flutter-SDK#1454]
**Describe the bug**
On Flutter Web, the control functions return NotImplementedError
I.E  muteLocalAudioStream(),  muteLocalVideoStream() and SwitchCamera()

**To Reproduce**
1. Start a call
2. Try to execute any of the said actions

**Expected behavior**
Action executed would be able to run.

**Desktop (please complete the following information):**
 - Pop!_OS
 - Chrome, Firefox
 - 22.04

**Smartphone (please complete the following information):**
 - Samsung Galaxy A22
 - Android
 - Chrome, Firefox
 - 11

**Comment by littleGnAl** [comment]
muteLocalAudioStream(), muteLocalVideoStream() are not implemented at this time, which will be implemented in the future.

The `agora_rtc_engine` web is built on top of the agora rtc web sdk, but the agora rtc web sdk does not support the  switchCamera by default. But I think you can do a similar thing by using the device manager.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/example/lib/examples/advanced/device_manager
