### ISSUE TITLE
Audio cuts off when the phone gets locked

### ISSUE THREAD

**Issue by nithin-ascent** [AgoraIO-Extensions/Agora-Flutter-SDK#1461]
Audio disconnects when phone gets locked (iOS)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install app on 2 devices and join the same channel from both devices with channel profile or live broadcasting
2. publishmicrophone should be 'true' on one device and 'false' on other device. (One is a speaker and the other is a listener)
3. the listener can hear whatever the speaker talks. Once the phone gets locked for listener, the audio from speaker gets stopped. 

**Expected behavior**
The listener should continue hearing the speaker even if the phone gets locked. 

**Smartphone :**
 - Device: All iPhones
 - OS: All iOS versions

**Comment by littleGnAl** [comment]
Can you try to enable the Audio Background Mode?
https://developer.apple.com/documentation/watchkit/storyboard_support/playing_background_audio
