### ISSUE TITLE
FLUTTER WEB : onRtcStats is not fired

### ISSUE THREAD

**Issue by antoijo** [AgoraIO-Extensions/Agora-Flutter-SDK#1471]
On Flutter web, onRtcStats is not fired, with the same code on android the onRtcStats works fine.

Maybe there is another way to get the duration of the connection for the web platform ?

**Comment by littleGnAl** [comment]
It's not supported on the web at this time.

**Comment by antoijo** [comment]
ok thanks, is there a documentation somewhere that list all the functionnalities not supported (or supported) on web ? I think I have the same issue with disabling local video on web
