### ISSUE TITLE
agora rtc: when joinChannel and passing a uid it return random aid

### ISSUE THREAD

**Issue by Mo0Khaled** [AgoraIO-Extensions/Agora-Flutter-SDK#1476]
i am trying to add uid to the joinChannel but it returns random id

what is written on the docs is:

> [uid] The user ID. This parameter is used to identify the user in the channel for real-time audio and video interaction. You need to set and manage user IDs yourself, and ensure that each user ID in the same channel is unique. This parameter is a 32-bit unsigned integer. The value range is 1 to 2 32 -1. If the user ID is not assigned (or set to 0), the SDK assigns a random user ID and returns it in the onJoinChannelSuccess callback. Your application must record and maintain the returned user ID, because the SDK does not do so.

so i passed the id but not return back as expected any idea?

```
await agoraEngine.joinChannel(
        token: currentSessionCredential.rtcToken,
        channelId: channelName!,
        options: options,
        uid: myUserId,
      );
```

**Comment by littleGnAl** [comment]
I think you can get the `myUserId ` when `onJoinChannelSuccess` is received.

**Comment by Mo0Khaled** [comment]
nope it returns a random id instead of the actual id i passed to the function!

**Comment by littleGnAl** [comment]
Can you share more logs, and what uid you get from the `onJoinChannelSuccess ` callback.

**Comment by Mo0Khaled** [comment]
it returns the id but it's random one !

**Comment by littleGnAl** [comment]
Can you share the logs that run into this issue?
