### ISSUE TITLE
Only Agora Voice SDK is needed

### ISSUE THREAD

**Issue by saraeng** [AgoraIO-Extensions/Agora-Flutter-SDK#148]
My app only requires the Agora Voice SDK, no need for Video. I'm using this Flutter plugin and it's great except that it drastically increases the size of the apk file. 

How can I reduce the size of the apk?
Is there going to be a plugin for Agora Voice SDK only? Is there any other solution to this issue?

**Comment by yoreland** [comment]
Currently SDK contains all video and audio components. The configurable component feature is in the roadmap.
