### ISSUE TITLE
muteLocalAudioStream() returns throws: AgoraRtcException(-4, null)

### ISSUE THREAD

**Issue by omarshaban0** [AgoraIO-Extensions/Agora-Flutter-SDK#1481]
**Describe the bug**
When muteLocalAudioStream(true) is called, AgoraRtcException 4 is thrown

**To Reproduce**
1. Create basic flutter app
2. Create file for agora functionality (code below)
3. Create basic flutter view and initialize on startup, and make a button that calls "toggleMic()"

**Expected behavior**
the local audio should be muted, the listener on the other end of the call not be able to hear them. Also, the exception should not be thrown.

**My code**
```dart
import 'package:agora_rtc_engine/agora_rtc_engine_web.dart';
import 'package:agora_rtc_engine/agora_rtc_engine.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'dart:developer';

class AgoraService {
  final String agoraAppId;
  final int uid;
  AgoraService({required this.agoraAppId, required this.uid}) {
    _initEngine();
  }

  RtcEngine? _engine;
  List<int> remoteUids = [];
  bool muted = false;

  void _initEngine() async {
    _engine = await createAgoraRtcEngine();

    if (_engine == null) {
      log("engine not initialized");
    }
    await _engine!.initialize(RtcEngineContext(
        appId: "" //hardcode appId
        ));

    await _engine!.enableAudio();
    await _engine!.enableLocalAudio(true);
    await joinChannel(""); //hardcode channel id
  }

  Future<void> joinChannel(String channelId) async {
    if (_engine == null) {
      _initEngine();
    }
    ChannelMediaOptions mediaOptions = await const ChannelMediaOptions(
        clientRoleType: ClientRoleType.clientRoleBroadcaster,
        channelProfile: ChannelProfileType.channelProfileLiveBroadcasting);
    await _engine!.joinChannel(
        token: "", channelId: channelId, uid: uid, options: mediaOptions);
  }
  void toggleMic() async {
    try {
      await _engine!.muteLocalAudioStream(true);
    } catch (e) {
      log("Error during toggle Mic: $e");
    }
  }
}
```
**Additional context**
I am trying to create the basic Agora functionality of calling, muting, and joining a channel. I am running into issues when it comes to muting, and the encryption solution provided by https://api-ref.agora.io/en/voice-sdk/flutter/6.x/API/enum_errorcodetype.html doesn't work.

**Comment by littleGnAl** [comment]
Which platform you are testing on?

**Comment by omarshaban0** [comment]
If I understand you correctly, I am running it as a web app on Chrome on my Windows PC.

**Comment by littleGnAl** [comment]
Only a subset of APIs are implemented on `agora_rtc_engine` web at this time.

Relative:
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1471
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1454
