### ISSUE TITLE
onActiveSpeaker is not called for local user (uid 0)

### ISSUE THREAD

**Issue by shashikantdurge** [AgoraIO-Extensions/Agora-Flutter-SDK#150]
As mentioned in the docs https://docs.agora.io/en/Voice/API%20Reference/cpp/classagora_1_1rtc_1_1_i_rtc_engine_event_handler.html#ae643c9dbf94360a23a8b3a56c93f90bc

The onActiveSpeaker has to be called with uid 0 if local user is actively speaking.

It is called if remote users are active but not for the local user.

**Comment by plutoless** [comment]
could you pls put a log print in the callback and share the logs for certain amount of time?

**Comment by shashikantdurge** [comment]
![Screenshot 2020-07-08 at 9 39 21 PM](https://user-images.githubusercontent.com/20161204/86943084-9a210600-c163-11ea-9c0d-0294d8fda5a8.png)

No callback when current user is actively speaking

**Comment by LichKing-2234** [comment]
will be fixed in native SDK version 3.2.0

**Comment by shashikantdurge** [comment]
Just a note: This issue still exists on 3.1.3v

**Comment by shashikantdurge** [comment]
Looks like there's change in the docs. It does not mention about the local speaker

**Comment by shashikantdurge** [comment]
As per the docs This issue can be closed.


[onAudioVolumeIndication](https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_i_rtc_engine_event_handler.html#a4d37f2b4d569fa787bb8c0e3ae8cd424)
Reports which users are speaking and the speakers' volume, and whether the local user is speaking.


[onActiveSpeaker](https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_i_rtc_engine_event_handler.html#a895e965178d808f9d33b387ab3e50300)
After a successful call of enableAudioVolumeIndication, the SDK continuously determines which remote user has the loudest volume. The remote user determined to be the loudest and most continuous speaker is considered the most active user.

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
