### ISSUE TITLE
voice call voice issue

### ISSUE THREAD

**Issue by karan-encanto** [AgoraIO-Extensions/Agora-Flutter-SDK#1550]
Hello ,I have implemented Agora Voice Call functionality in my app when I am calling one user to another Call is Placed Successfully but not able to get the audio/voice from both the users
[log] [onError] err: ErrorCodeType.errAdmStartPlayout, msg:
[log] [onError] err: ErrorCodeType.errAdmStartPlayout, msg:
[log] [onError] err: ErrorCodeType.errAdmInitRecording, msg:
[log] [onError] err: ErrorCodeType.errAdmInitRecording, msg:
[log] [onError] err: ErrorCodeType.errAdmStartRecording, msg:
[log] [onError] err: ErrorCodeType.errAdmStartRecording, msg:

**Comment by littleGnAl** [comment]
Have you requested the audio permission?

**Comment by karan-encanto** [comment]
> Have you requested the audio permission?
yes

  <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

**Comment by mjjoshi** [comment]
can you please share me any solution as voice is not coming

**Comment by littleGnAl** [comment]
I'm so sorry that we are on holiday until 02/17, it's better to raise a new ticket to Agora Support if you face an urgent issue.

**Comment by karan-encanto** [comment]
i think its not a agora issue, in my case flutter call kit dependency bug
