### ISSUE TITLE
Voice not coming while calling from video with latest version 

### ISSUE THREAD

**Issue by mjjoshi** [AgoraIO-Extensions/Agora-Flutter-SDK#1553]
I want to inquire about the issue of the voice not being audible during video calls. I've referenced several codes, but there's still no sound during the video calls. Could you please assist me in resolving this issue? When I initially developed this feature, the sound was functioning correctly. However, suddenly, during video calls, there is no sound.

**Comment by littleGnAl** [comment]
I'm so sorry that we are on holiday until 02/17, it's better to raise a new ticket to Agora Support if you face an urgent issue.

**Comment by mjjoshi** [comment]
Okay thanks for update but now got solution & resolve issue.

**Comment by bhattishb92** [comment]
> Okay thanks for update but now got solution & resolve issue.

Hi, can you share me your solution. As I also face the same issue. my code is working perfectly when I implement but suddenly can't hear voice in android, on ios working fine.

**Comment by littleGnAl** [comment]
Thanks for your update @mjjoshi .
@bhattishb92  If you still face issues, it's better to raise a new issue for your case, it may or may not be the same as this issue.
