### ISSUE TITLE
RtcEngine enableVideo  function causes IllegalStateException(sending message to a Handler on a dead thread) on Android

### ISSUE THREAD

**Issue by Ilgz** [AgoraIO-Extensions/Agora-Flutter-SDK#1554]
**My logs**
W/MessageQueue( 4240): java.lang.IllegalStateException: Handler (android.os.Handler) {e6d39c5} sending message to a Handler on a dead thread
W/MessageQueue( 4240): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:563)
W/MessageQueue( 4240): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue( 4240): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue( 4240): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue( 4240): 	at android.os.Handler.post(Handler.java:427)
W/MessageQueue( 4240): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraHandlerExecutor.execute(CameraDeviceImpl.java:2252)
W/MessageQueue( 4240): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
W/MessageQueue( 4240): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:588)
W/MessageQueue( 4240): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:879)
W/MessageQueue( 4240): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
W/MessageQueue( 4240): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
W/MessageQueue( 4240): 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
W/MessageQueue( 4240): 	at java.lang.Thread.run(Thread.java:923)

**To Reproduce**
1. Copy code ` await engine.initialize(
        RtcEngineContext(
          appId: appIdAgora,
          audioScenario: AudioScenarioType.audioScenarioChatroom,
        ),
      );
      await engine.enableVideo();
      await engine.joinChannel(
        token: token,
        channelId: channel!,
        uid: 0,
        options: const ChannelMediaOptions(
          clientRoleType: ClientRoleType.clientRoleBroadcaster,
          channelProfile: ChannelProfileType.channelProfileCommunication,
        ),
      ); `
3. Run
4. See an exception in logs

**My device**
Xiaomi redmi note 8. Android version: 11

**Comment by littleGnAl** [comment]
I'm so sorry that we are on holiday until 02/17, it's better to raise a new ticket to Agora Support if you face an urgent issue.

**Comment by Ilgz** [comment]
Ok, i'll wait for you

**Comment by littleGnAl** [comment]
May I ask if is there a crash or other issues for your case, it is most likely the log is not related to our SDK.
