### ISSUE TITLE
Android Embedding Issue

### ISSUE THREAD

**Issue by kostricanitechnology** [AgoraIO-Extensions/Agora-Flutter-SDK#1563]
Hello,

I am getting an issue with Agora plugin, when I try to build I get this error `Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
The plugin `agora_rtc_engine` requires your app to be migrated to the Android embedding v2. Follow the steps on the migration doc above and re-run this command.`

I already have the app migrated to Android embedding v2

**Comment by littleGnAl** [comment]
Related https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1545
