### ISSUE TITLE
Update README Android Permission part for Android 14 

### ISSUE THREAD

**Issue by utkudenis** [AgoraIO-Extensions/Agora-Flutter-SDK#1575]
Hi Agora,

Play Store directly control Foreground permission for android 14. 
If target SDK android 14 , package readme cannot help us. 

Can you update it ?

**Comment by utkudenis** [comment]
Especially for Media Projection.

**Comment by utkudenis** [comment]
we tried your suggestion on the PR https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1458
but it is not solved

**Comment by albaschez** [comment]
We are having problems with the PlayStore with the following permissions:

- FOREGROUND_SERVICE_CAMERA

- FOREGROUND_SERVICE_MEDIA_PLAYBACK

- FOREGROUND_SERVICE_MICROPHONE

How can we solve the issue if we are not currently using this foreground services?

**Comment by littleGnAl** [comment]
I think you should first check where the permission comes from by viewing the `<your-project>/build/app/outputs/logs/manifest-merger-release-report.txt`

Here's the report of our example:
```
uses-permission#android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION
ADDED from [io.agora.rtc:full-screen-sharing:4.2.6] /Users/xxx/.gradle/caches/transforms-3/e7cd6c6a6609aed2b4d7925f5922d8f2/transformed/jetified-full-screen-sharing-4.2.6/AndroidManifest.xml:8:5-94
	android:name
		ADDED from [io.agora.rtc:full-screen-sharing:4.2.6] /Users/xxx/.gradle/caches/transforms-3/e7cd6c6a6609aed2b4d7925f5922d8f2/transformed/jetified-full-screen-sharing-4.2.6/AndroidManifest.xml:8:22-91
```

<img width="870" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/8847263/08004a5f-c3f7-4547-9ae0-5df2486fe74d">

After applying the https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1458#issuecomment-1844835294, the permission in the manifest is gone.

<img width="798" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/8847263/f04c1e87-4d21-4651-9d8a-151d4806b481">

**Comment by albaschez** [comment]
Thank you for the answer @littleGnAl . I have added the following in the build.gradle
`
configurations.all {
    exclude group:"io.agora.rtc", module:"audio-beauty"
    exclude group:"io.agora.rtc", module:"full-content-inspect"
    exclude group:"io.agora.rtc", module:"screen-capture"
    exclude group:"io.agora.rtc", module:"full-screen-sharing"
    exclude group:"io.agora.rtc", module:"full-virtual-background"
    exclude group:"io.agora.rtc", module:"spatial-audio"
    exclude group:"io.agora.rtc", module:"pvc"
    exclude group:"io.agora.rtc", module:"full-super-resolution"
    exclude group:"io.agora.rtc", module:"drm-loader"
    exclude group:"io.agora.rtc", module:"drm"
    exclude group:"io.agora.rtc", module:"aiaec"
    exclude group:"io.agora.rtc", module:"full-roi-enc"
    exclude group:"io.agora.rtc", module:"full-vqa"
    exclude group:"io.agora.rtc", module:"full-face-detection"
}
`

Because of that now I don't have any of the FOREGROUND_SERVICE_XXX permissions that were appearing before. However, when I try to upload the app to playStore I still get the same issues about not-declared foreground services: (Health is okay, I have added that manually)

![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/75412214/bf6e8d4d-24e0-426e-9aea-10a78be0601c)

**Comment by littleGnAl** [comment]
@albaschez 
I think you can easily check where those permissions come from by viewing the `<your-project>/build/app/outputs/logs/manifest-merger-release-report.txt`

**Comment by albaschez** [comment]
@littleGnAl 
They do not appear in the manifest-merger-release-report. I add as an example HEALTH, which is the one that should be appearing, but CAMERA for example does not bring any result, nor do MEDIA_PLAYBACK or MICROPHONE.

![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/75412214/718b6453-82d9-4684-adbf-be61b081808b)
![image](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/75412214/c0abc4a6-3daa-4ed4-ad8f-46c28e1ce229)

**Comment by littleGnAl** [comment]
Ok, I correct the path `<your-project>/build/app/outputs/logs/manifest-merger-<build-type>-report.txt`.
So in your case, you haven't built the release apk yet, so you can check it from your `manifest-merger-staging-debug-report.txt`.

**Comment by littleGnAl** [comment]
Can you check the manifest file in your final APK in Android Studio to see if these permissions exist or not? I'm not very sure how the PlayStore analyzes the permission, if you found that these permissions do not exist in the manifest file, I think you'd better raise an issue to the PlayStore to see how to work next step.

**Comment by littleGnAl** [comment]
@albaschez I think it's better to raise an issue to the Play Store for your issue.

**Comment by albaschez** [comment]
@littleGnAl Thank you for your time. I'll raise them an issue and I'll update here when they answer back
