### ISSUE TITLE
BUILD FAILED, when I update Video SDK from 2.15.0 to 3.0.0

### ISSUE THREAD

**Issue by anirbanhazra** [AgoraIO-Extensions/Agora-Flutter-SDK#1586]
When I am migrating to new version of Agora Video SDK, I am unable to compile my app. It's showing build failed, with
/C:/Users/Intersoft/AppData/Local/Pub/Cache/hosted/pub.dev/agora_uikit-1.0.4/lib/controllers/rtm_client_event_handler.dart:76:7: Error: A value of type 'Null Function(LocalInvitation)' can't be assigned to a variable of type 'dynamic Function(LocalInvitation, String)?'.
 - 'LocalInvitation' is from 'package:agora_rtm/src/utils.dart' ('/C:/Users/Intersoft/AppData/Local/Pub/Cache/hosted/pub.dev/agora_rtm-1.5.9/lib/src/utils.dart').
      (AgoraRtmLocalInvitation invitation) {
      ^
/C:/Users/Intersoft/AppData/Local/Pub/Cache/hosted/pub.dev/agora_uikit-1.0.4/lib/controllers/rtm_client_event_handler.dart:81:7: Error: A value of type 'void Function(LocalInvitation)' can't be assigned to a variable of type 'void Function(LocalInvitation, String)?'.
 - 'LocalInvitation' is from 'package:agora_rtm/src/utils.dart' ('/C:/Users/Intersoft/AppData/Local/Pub/Cache/hosted/pub.dev/agora_rtm-1.5.9/lib/src/utils.dart').
      (AgoraRtmLocalInvitation invitation) {
      ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1350

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 49s
Exception: Gradle task assembleDebug failed with exit code 1

Gradle | Search for Help with Gradle Build Tool
https://help.gradle.org
/C:/Users/Intersoft/AppData/Local/Pub/Cache/hosted/pub.dev/agora_uikit-1.0.4/lib/controllers/rtm_client_event_handler.dart:76:7: Error: A value of type 'Null Function(LocalInvitation)' can't be assigned to a variable of type 'dynamic Function(LocalInvitation, String)?'.
 - 'LocalInvitation' is from 'package:agora_rtm/src/utils.dart' ('/C:/Users/Intersoft/AppData/Local/Pub/Cache/hosted/pub.dev/agora_rtm-1.5.9/lib/src/utils.dart').
      (AgoraRtmLocalInvitation invitation) {
      ^
/C:/Users/Username/AppData/Local/Pub/Cache/hosted/pub.dev/agora_uikit-1.0.4/lib/controllers/rtm_client_event_handler.dart:81:7: Error: A value of type 'void Function(LocalInvitation)' can't be assigned to a variable of type 'void Function(LocalInvitation, String)?'.
 - 'LocalInvitation' is from 'package:agora_rtm/src/utils.dart' ('/C:/Users/Username/AppData/Local/Pub/Cache/hosted/pub.dev/agora_rtm-1.5.9/lib/src/utils.dart').
      (AgoraRtmLocalInvitation invitation) {
      ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1350

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by littleGnAl** [comment]
I think you should raise an issue to the agora_uikit repo.
