### ISSUE TITLE
[Flutter][Android] Local snapshot taken using takeSnapshot API is cached

### ISSUE THREAD

**Issue by locandpad** [AgoraIO-Extensions/Agora-Flutter-SDK#1590]
**Describe the bug**
When taking snapshot continuously, the newly taken image is cached and the API returns the same image as previous one.

**To Reproduce**
1. Use the `TakeSnapshot` example from this repo.
2. Join a channel.
3. Take snapshot of `picture A` --> API returns correctly.
4. Continue to take snapshot of `picture B` --> API returns successfully (errorCode = 0) but result is the same as previous call (`picture A`).
5. Call take snapshot again of `picture C` --> API returns the result of `picture B`.

**Expected behavior**
API should return the correct image and should not cache the result

**Comment by khanhandpad** [comment]
same as me, please help us have a look on this

**Comment by littleGnAl** [comment]
Which platform you are facing this issue, I tested on macOS, and it seems to work fine.

**Comment by locandpad** [comment]
@littleGnAl I tested on Android device.

**Comment by littleGnAl** [comment]
Okay, I will test it later.

**Comment by littleGnAl** [comment]
It is most likely a bug on 6.2.6, I tested it on 6.3.0, and it works fine, please try our example on the main branch.

**Comment by locandpad** [comment]
@littleGnAl Thank you for your support, it is working correctly now.
