### ISSUE TITLE
Problem with agora rtc engine plugin version 6.2.6

### ISSUE THREAD

**Issue by Tawanny** [AgoraIO-Extensions/Agora-Flutter-SDK#1592]
I installed the agora rtc engine 6.2.6

after setting up everything I restarted my app and then this error happened. I tried flutter clean, flutter pub cache clean but nothing is changing. I even deleted .pub_cache manually hoping it will repair itself but it's not helping. 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/tawanny/.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.6/android/.cxx/Debug/421y6a58/arm64-v8a'
  [1/2] Building CXX object CMakeFiles/iris_rendering_android.dir/iris_rtc_rendering_android.cc.o
  FAILED: CMakeFiles/iris_rendering_android.dir/iris_rtc_rendering_android.cc.o 
  /home/tawanny/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --sysroot=/home/tawanny/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Diris_rendering_android_EXPORTS -I/home/tawanny/.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.6/android/src/main/cpp/third_party/include/iris -I/home/tawanny/.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.6/android/src/main/cpp/third_party/include/agora_rtc -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/iris_rendering_android.dir/iris_rtc_rendering_android.cc.o -MF CMakeFiles/iris_rendering_android.dir/iris_rtc_rendering_android.cc.o.d -o CMakeFiles/iris_rendering_android.dir/iris_rtc_rendering_android.cc.o -c /home/tawanny/.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.6/android/src/main/cpp/iris_rtc_rendering_android.cc
  In file included from /home/tawanny/.pub-cache/hosted/pub.dev/agora_rtc_engine-6.2.6/android/src/main/cpp/iris_rtc_rendering_android.cc:13:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.

Desktop
I am using Ubuntu 22.04 lts
Chrome browser

 - Device: Samsung A30
 
**Additional context**
I am testing on a real device not an emulator

**Comment by littleGnAl** [comment]
See if it works for you or not https://github.com/rive-app/rive-flutter/issues/323#issuecomment-1638880701
