### ISSUE TITLE
Android App not running because of error: "Could not determine the dependencies of task ':compileReleaseAidl'."

### ISSUE THREAD

**Issue by Chimba123** [AgoraIO-Extensions/Agora-Flutter-SDK#160]
I have been developing my App for some time now and have mostly been testing it on an iOS device and iOS emulator and the agora_rtc package has given me no issues up untill now when I tried to run my app on a real android device. 

Flutter is throwing the error below related to the package as:
"
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/apple/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-1.0.13/android/local.properties'.
"

I don't understand what could be the issue?

**Comment by LichKing-2234** [comment]
the solution is as you comment.

**Comment by SaoGoKu** [comment]
> the solution is as you comment.

Btw there is no local.properties in agora_rtc_engine-1.0.13/android/ . i only found gradles.properties

**Comment by LichKing-2234** [comment]
@SaoGoKu what file path you have opened in the android studio?

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
