### ISSUE TITLE
VideoCanvas background color is not respected

### ISSUE THREAD

**Issue by CodingAleCR** [AgoraIO-Extensions/Agora-Flutter-SDK#1603]
**Describe the bug**
When setting `backgroundColor` on `VideoCanvas`, and also playing a media with `MediaPlayerController`, background color is not respected and it always display black bars instead of respecting video canvas configuration.

**To Reproduce**
1. Open the media controller example.
2. Set the media controller config to the following:
```dart
_mediaPlayerController = MediaPlayerController(
  rtcEngine: AgoraClient.instance.engine,
  useAndroidSurfaceView: true,
  canvas: VideoCanvas(
    uid: 0,
    sourceType: VideoSourceType.videoSourceMediaPlayer,
    backgroundColor: Colors.white.value,
    renderMode: RenderModeType.renderModeFit,
  ),
);
```

**Expected behavior**

`VideoCanvas.backgroundColor` should be respected.

**Screenshots**

![Simulator Screenshot - iPhone 15 Pro Max - 2024-03-03 at 12 27 04](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/12262852/cb1c7089-d129-4606-ba63-87464301d8ea)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser: chrome

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser -
 - Version -

**Additional context**
SDK version: `agora_rtc_engine: ^6.3.0`

**Comment by littleGnAl** [comment]
It does not support the `MediaPlayerController`.

**Comment by CodingAleCR** [comment]
It does feel like it should be respected. Is there a way to configure this anywhere else then?

**Comment by littleGnAl** [comment]
There's no way to configure it at this time, the media player does not support this feature on the native side.

**Comment by CodingAleCR** [comment]
Do you know by any chance what other properties of `VideoCanvas` does it support? I was trying to do something with `VideoCanvas.cropArea` but it also doesn't respect it. So I'm curious to know what are the only properties that can be used with `MediaPlayerController`.

**Comment by littleGnAl** [comment]
All the properties in `VideoCanvas` are not supported for the media player feature.
