### ISSUE TITLE
Issue while running agora flutter sdk in web browser ('createIrisApiEngine')

### ISSUE THREAD

**Issue by vickyone0** [AgoraIO-Extensions/Agora-Flutter-SDK#1606]
**Describe the bug**
I am trying to build a video call feature for a web app using the Agora Flutter SDK. When I try to run it in a web browser, it shows 'TypeError: Cannot read properties of undefined (reading 'createIrisApiEngine').' All the UI elements are loaded properly, but the Agora engine does not work as I expect.

**To Reproduce**
1. create a flutter project
2. add the agora_rtc_engine: ^6.3.0
  permission_handler: ^11.0.1 dependency in the project
3. create a code for run a simple video call using agora and add app Id and channel name to the code .
4. try to run it in web browser

**Expected behavior**
Expected that agora engine will work 
**Screenshots**
![Screenshot 2024-03-05 162339](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/101127083/34c919be-e379-4106-99ca-8d12ff4855ba)
![Screenshot 2024-03-05 162432](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/101127083/04399e12-7774-48b7-a923-c9373d6a675d)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome
 - Version : 122.0.6261.95 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
video call is an important feature of my web app. so please reply as soon as possible

**Comment by littleGnAl** [comment]
Have you set up the project
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK?tab=readme-ov-file#web-alpha
