### ISSUE TITLE
Privacy manifest file for iOS is missing

### ISSUE THREAD

**Issue by oremlawi** [AgoraIO-Extensions/Agora-Flutter-SDK#1674]
To ensure a smooth app update and avoid App Store rejection, kindly consider adding a privacy manifest to your library. This helps developers reflect data collection practices in our own manifests.

[Apple documentation.](https://developer.apple.com/support/third-party-SDK-requirements/)

**Comment by littleGnAl** [comment]
This will be done from the native side, will update here when it is supported.

**Comment by littleGnAl** [comment]
After confirmation, it will be added to the native SDK framework in the next release.

**Comment by ChrisMICDUP** [comment]
When is next release due?

**Comment by littleGnAl** [comment]
@ChrisMICDUP Maybe mid-May.

**Comment by littleGnAl** [comment]
This has been supported in the latest version (>= 6.3.2).
