### ISSUE TITLE
Republishing Video also causes audio to be unpublished and republished

### ISSUE THREAD

**Issue by dannnnthemannnn** [AgoraIO-Extensions/Agora-Flutter-SDK#1726]
### Version of the agora_rtc_engine

6.3.0

### Platforms affected

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [X] Web

### Steps to reproduce

My understanding is the only way to unpublish video (and turn off hte camera is to do the following)
`engine.enableLocalVideo(false);`

But to renable it you have to do:
```
await engine.enableLocalVideo(true);
await engine.updateChannelMediaOptions(ChannelMediaOptions(
  publishCameraTrack: true,
));
```

However, when I do this it also turns off and on the audio. 

I believe the code that toggles both of them is here:
https://github.com/AgoraIO-Extensions/iris_web/blob/dc46c16fbbe2871a19cdc56453f12f5ff9f03093/packages/rtc/src/helper/ImplHelper.ts#L359

### Expected results

It only toggles on the video and does not effect the audio. 

### Actual results

Both audio and video are unpublished and then republished. 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.1.1 23B81 darwin-arm64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.84.2)
[✓] VS Code (version 1.86.0-insider)
[✓] Connected device (2 available)
[✓] Network resources


```

</details>

**Comment by littleGnAl** [comment]
I think you can try `muteLocalVideoStream` to unpublish or re-publish the video stream.
