### ISSUE TITLE
Execution failed for task ':agora_rtc_engine:buildCMakeDebug[arm64-v8a] 

### ISSUE THREAD

**Issue by developer-zerobug** [AgoraIO-Extensions/Agora-Flutter-SDK#1736]
Issue Description:

I encountered an error while trying to run my application on both my phone for testing and the emulator. The error occurred during the build process, specifically when executing the buildCMakeDebug task for the agora_rtc_engine module.

Error Message:

```
* What went wrong:
Execution failed for task ':agora_rtc_engine:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/azar/.pub-cache/hosted/pub.dev/agora_rtc_engine-6.3.0/android/.cxx/Debug/5u6q5t3i/arm64-v8a'
  [1/2] Building CXX object CMakeFiles/iris_rendering_android.dir/iris_rtc_rendering_android.cc.o
  FAILED: CMakeFiles/iris_rendering_android.dir/iris_rtc_rendering_android.cc.o 

```

Steps to Reproduce:

1. Run the application on an Android device or emulator.
2. Observe the error during the build process.
3. Expected Behavior:
4. The application should build successfully without any errors.

Additional Information:

1. Operating System: Ubuntu
2. Gradle Version: 1.9.23
3. Agora RTC Engine Version: 6.3.0

![Screenshot from 2024-05-01 17-07-05](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/151624719/5d8661f2-4c02-47d7-84d1-0af92f929f56)

**Comment by littleGnAl** [comment]
Related https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1086, https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1592
