### ISSUE TITLE
How can I send a video call notification to a remote user or receiver using Agora in my Flutter app? Or should I use Firebase messaging for it? 

### ISSUE THREAD

**Issue by 21prnv** [AgoraIO-Extensions/Agora-Flutter-SDK#1751]
**Is your feature request related to a problem? Please describe.**
how I can send video call notification I'm using supabase for database and authentication in my flutter app.

**Comment by littleGnAl** [comment]
Yes, you should have a way to send the message or notification to do this logic, firebase or our RTM SDK or other third-party SDK that can send the real-time message should be fine.
