### ISSUE TITLE
agora screen not render or rerender when use tranform widget

### ISSUE THREAD

**Issue by conan1150** [AgoraIO-Extensions/Agora-Flutter-SDK#1760]
### Version of the agora_rtc_engine

6.2.2

### Platforms affected

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] Web

### Steps to reproduce

1. use mirror camera on android

### Expected results

1. mirror video

### Actual results

1. blank screen or freez video

### Code sample

<details open><summary>Code sample</summary>

```dart
    this._agoraWidget = Transform(
        alignment: Alignment.center,
        transform: Matrix4.rotationY(!this.mirrorMode ? math.pi : 0),
        child: this._agoraLocalView);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by littleGnAl** [comment]
Hello @conan1150, I tried it on the latest version, and it works fine, can you try updating the `agora_rtc_engine: ^6.3.1` to see if it works for you or not?
