### ISSUE TITLE
FOREGROUND_SERVICE_MEDIA_PROJECTION is in the app but Screen sharing is not enabled

### ISSUE THREAD

**Issue by iririya** [AgoraIO-Extensions/Agora-Flutter-SDK#1785]
I'm using SDK just for video calls between multiple users, screen sharing is not used
But still I'm getting issues from Google Play for using android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION
I found that it used in full screen sharing manifest.
How do I disable it, I can’t even upload the app to the store, I can’t describe how it is used (because it is not)?
Agora ver. 6.3.1
Flutter ver. 3.22.1

**Comment by littleGnAl** [comment]
Related https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1666
