### ISSUE TITLE
Use pushVideoFrame special card

### ISSUE THREAD

**Issue by Nuyoahhjh** [AgoraIO-Extensions/Agora-Flutter-SDK#1869]
### Version of the agora_rtc_engine

6.3.2

### Platforms affected

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] Web

### Steps to reproduce

1, onCaptureVideoFrame to obtain the original data,
2. Push yuv through pushVideoFrame
code:`
_videoFrameObserver = VideoFrameObserver(
      onCaptureVideoFrame: (sourceType, videoFrame) {
        // print(
        //     'Captured video frame from $sourceType size: ${videoFrame.width}x${videoFrame.height} y: ${videoFrame.yBuffer?.length} u:${videoFrame.uBuffer?.length} v:${videoFrame.vBuffer?.length}');
        if (!isJoined) {
          return;
        }
        if (videoFrame.yBuffer != null &&
            videoFrame.uBuffer != null &&
            videoFrame.vBuffer != null &&
            videoFrame.width != null &&
            videoFrame.height != null) {
          // 创建一个新缓冲区来存储拼接后的数据
          final int totalLength = videoFrame.yBuffer!.length +
              videoFrame.uBuffer!.length +
              videoFrame.vBuffer!.length;
          final Uint8List yuvBuffer = Uint8List(totalLength);

          // 拼接缓冲区数据
          yuvBuffer.setRange(
              0, videoFrame.yBuffer!.length, videoFrame.yBuffer!);
          yuvBuffer.setRange(
              videoFrame.yBuffer!.length,
              videoFrame.yBuffer!.length + videoFrame.uBuffer!.length,
              videoFrame.uBuffer!);
          yuvBuffer.setRange(
              videoFrame.yBuffer!.length + videoFrame.uBuffer!.length,
              totalLength,
              videoFrame.vBuffer!);
          
          _engine.getMediaEngine().pushVideoFrame(
                frame: ExternalVideoFrame(
                  type: VideoBufferType.videoBufferArray,
                  format: VideoPixelFormat.videoPixelNv12,
                  buffer: yuvBuffer,
                  stride: videoFrame.width!,
                  height: videoFrame.height!,
                  timestamp: videoFrame.renderTimeMs,
                ),
              );
        }
      },
    );
`

### Expected results

Local preview screen change card
High CPU usage

### Actual results

Local preview screen change card
High CPU usage

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by Nuyoahhjh** [comment]
I need a usb compatible camera here

**Comment by Nuyoahhjh** [comment]
@littleGnAl

**Comment by littleGnAl** [comment]
I think if you can get the raw data from the `onCaptureVideoFrame `, it can be previewed with `AgoraVideoView` or published using the `joinChannel` function.

**Comment by Nuyoahhjh** [comment]
I think pushVideoFrame is pushing data to the remote end

**Comment by littleGnAl** [comment]
You can use `joinChannel ` to publish it to remote users.
