### ISSUE TITLE
agora flutter web screen sharing a power point window getting frozen when full screen

### ISSUE THREAD

**Issue by danilo1998271** [AgoraIO-Extensions/Agora-Flutter-SDK#1881]
### Version of the agora_rtc_engine

5.3.1

### Platforms affected

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [X] Web

### Steps to reproduce

we have a screen sharing functionality in flutter web but when sharing a powerpoint window and hit full screen, the video is freezing

### Expected results

screensharing powerpoint is not freezing when shared using fullscreen

### Actual results

screensharing powerpoint freezing when fullscreen

### Code sample

  _startScreenShare() async {
    await getRtcToken2("screenshare");

    helper = await _engine.getScreenShareHelper(
        appGroup: kIsWeb || Platform.isWindows ? null : "io.agora");
    helper.setEventHandler(
      RtcEngineEventHandler(
        userJoined: (uid, elapsed) async {
          var exist = rtcHelperMembers.where((e) => e.uid == uid);
          if (exist.isEmpty) {
            if (kDebugMode) {
              print("RTC Helper: Remote user joined $uid");
            }
          }
        },
        userInfoUpdated: (uid, userInfo) {
          if (kDebugMode) {
            print("RTC Helper: UserInfo Updated for ${userInfo.userAccount}");
          }
        },
        userOffline: (uid, reason) {
          rtcHelperMembers.removeWhere((e) => e.uid == uid);
          if (kDebugMode) {
            print("RTC Helper: Remote user Left $uid");
          }
        },
        joinChannelSuccess: (String channel, String uid, int elapsed) {
          rtcMembers.refresh();
          rtcHelperMembers.refresh();
        },
        leaveChannel: (stats) {
          rtcHelperMembers.clear();
          if (mounted) {
            isScreenShared.value = false;
          }
        },
        localVideoStateChanged: (LocalVideoStreamState localVideoState,
            LocalVideoStreamError error) {
          if (kDebugMode) {
            print(
                'RTC Helper: ScreenSharing localVideoStateChanged $localVideoState $error');
          }
          if (localVideoState == LocalVideoStreamState.Failed) {
            _stopScreenShare();
          }
        },
        warning: (warningCode) {
          if (kDebugMode) {
            print('RTC Helper: warning $warningCode');
          }
        },
        error: (errorCode) {
          if (kDebugMode) {
            print('RTC Helper: error $errorCode');
          }
        },
      ),
    );
    await helper.enableVideo();
    await helper.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await helper.muteLocalAudioStream(!isScreenShareMuted.value);
    await helper.setClientRole(ClientRole.Broadcaster);
    var windowId = 0;
    if (!kIsWeb && (Platform.isWindows || Platform.isMacOS)) {
      final windows = _engine.enumerateWindows();
      if (windows.isNotEmpty) {
        windowId = windows[0].id;
      }
    }
    await helper.startScreenCaptureByWindowId(windowId);

    await helper.registerLocalUserAccount(config.appId, "screenshare");
    await helper.joinChannelWithUserAccount(
        rtcToken, rtcChannelName, "screenshare");

    isScreenShared.value = true;
  }

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by littleGnAl** [comment]
The version `5.x` is no longer maintained, please upgrade to the latest version of `6.x`.
