### ISSUE TITLE
RenderModeType.renderModeFit only works for local screenshare video but not remote screenshare video

### ISSUE THREAD

**Issue by amit3xpo** [AgoraIO-Extensions/Agora-Flutter-SDK#1894]
### Version of the agora_rtc_engine

6.3.2

### Platforms affected

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [X] Web

### Steps to reproduce

1. Join channel and share screen
2. Join same channel from another instance
3. Notice the screenshare video render as local and remote user

### Expected results

Screenshare video for remote with renderModeFit should have the video as a contained fit.

### Actual results

Screenshare video for remote with renderModeFit has video as cover (zoomed to fill). This happens only when loading remote video. However, local video render works as expected which is contained.

### Code sample

<details open><summary></summary>

```dart
AgoraVideoView(
     controller: VideoViewController.remote(
                         rtcEngine: _engine,
                         canvas: const VideoCanvas(
                         uid: e,
                         renderMode: RenderModeType.renderModeFit,
                         sourceType: VideoSourceType.videoSourceScreen,
                       ),
                       connection: RtcConnection(channelId: rtcChannelName),
                   ),
              )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

### Video render for screenshare from local user
<img width="679" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/81599122/deef6cb5-00b2-4ebe-a604-03a7e272361a">

### Video render for screenshare from remote user (used renderModeFit)
<img width="823" alt="image" src="https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/assets/81599122/7b028202-74c9-4a1f-bdce-33baf3999f88">

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by littleGnAl** [comment]
Related https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1765, the render mode is not supported on the web at this time.
