### ISSUE TITLE
[web] leaveChannelEx not supported in this platform

### ISSUE THREAD

**Issue by amit3xpo** [AgoraIO-Extensions/Agora-Flutter-SDK#1895]
### Version of the agora_rtc_engine

6.3.2

### Platforms affected

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [X] Web

### Steps to reproduce

1. Join using joinChannelEx with uid 0
2. Join again for screensharing user only with joinChannelEx with uid 1001
3. Leave channel only for screensharing user with leaveChannelEx with connection data using uid 1001

### Expected results

Joins that happened using joinChannelEx should be able to be left separately

### Actual results

[02:51:44:644][Iris warning]:RtcEngineEx_leaveChannelEx_b03ee9a not supported in this platform!
[02:51:44:644][Iris log]:[callIrisApiAsync][result] RtcEngineEx_leaveChannelEx_b03ee9a ret -4
AgoraRtcException(-4, null)

### Code sample

<details open><summary>Code sample</summary>

```dart
await _engine
        .leaveChannelEx(
      connection: RtcConnection(
        channelId: rtcChannelName,
        localUid: config.screenSharingUid,
      ),
    )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by amit3xpo** [comment]
I need to achieve the following workflow:

### A. Tried using RtcEngineEx
1. Join user first with joinChannelEx with uid 0 - this is for normal audio and primary camera
2. When screensharing, join again with joinChannelEx with uid 1001 - this for screensharing only
3. When stopped screensharing, I need to disconnect only uid 1001 but still keep uid 0 user connected

So, how can I make leaveChannelEx work to acheive this?

### B. Tried using RtcEngine
1. Create two RtcEngine instances **engineA** and **engineB**
2. Join **engineA** first with joinChannel with uid 0 - this is for normal audio and primary camera
3. When screensharing, join **engineB** with joinChannel with uid 1001 - this for screensharing only
4. When stopped screensharing, I need to disconnect only uid 1001 but still keep uid 0 user connected
5. But when i invoke leaveChannel() for **engineB**, it also affects **engineA**

So, is it normal behaviour? Anyway I can make this work?

Thanks!

**Comment by danilo1998271** [comment]
@littleGnAl can you help us with this one?

**Comment by littleGnAl** [comment]
> So, how can I make leaveChannelEx work to acheive this?

The error code `-4` means this API is not supported, the `leaveChannelEx ` is not supported on the web at this time, we will implement it in the future.

> B. Tried using RtcEngine

The `RtcEngine` is a singleton, and the `leaveChannel ` leaves channel for all the uid, this should be the expected behavior, you can only use the `leaveChannelEx` to achieve your requirement.

**Comment by amit3xpo** [comment]
Thanks for the response @littleGnAl . So there is no way to handle stopping of screen share (ex uid: 1001) without kicking the original user (ex uid: 1000) out? When can we expect leaveChannelEx to be available for flutter web?

**Comment by littleGnAl** [comment]
> So there is no way to handle stopping of screen share (ex uid: 1001) without kicking the original user (ex uid: 1000) out? 

Yes in a short time.

> When can we expect leaveChannelEx to be available for flutter web?

We will implement it when we have resources, but it's so sorry there's no timeline guarantee for it.

**Comment by danilo1998271** [comment]
@littleGnAl any news on this the cutoff of the sunset plan is 14th September 2024. in that case all of our services will not work since upgrading to latest version cannot fix this problem?

**Comment by littleGnAl** [comment]
It should be supported now, please try the latest version https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK?tab=readme-ov-file#web-alpha

**Comment by danilo1998271** [comment]
@littleGnAl is AgoraVideoView now stable on the web?

**Comment by danilo1998271** [comment]
@littleGnAl 
` SingleChildScrollView(
                                        scrollDirection: Axis.horizontal,
                                        child: Row(
                                          children: List.of(
                                            rtcMembers.map(
                                              (e) {
                                                if (e == 0) {
                                                  return const SizedBox(
                                                    height: 200,
                                                    width: 200,
                                                    child: Text("Local"),
                                                  );
                                                }
                                                return Container(
                                                  width: 200,
                                                  height: 200,
                                                  decoration: BoxDecoration(
                                                      border: Border.all(
                                                          color: Colors.blue),
                                                      color: Colors.red),
                                                  child: AspectRatio(
                                                    aspectRatio: 16 / 9,
                                                    child: AgoraVideoView(
                                                      controller:
                                                          VideoViewController
                                                              .remote(
                                                        rtcEngine: _engine,
                                                        canvas: VideoCanvas(
                                                          uid: e,
                                                          renderMode:
                                                              RenderModeType
                                                                  .renderModeFit,
                                                          sourceType:
                                                              VideoSourceType
                                                                  .videoSourceScreen,
                                                        ),
                                                        connection:
                                                            RtcConnection(
                                                          channelId:
                                                              rtcChannelName,
                                                        ),
                                                      ),
                                                    ),
                                                  ),
                                                );
                                              },
                                            ),
                                          ),
                                        ),
                                      ),`
why AgoraVideoView not working when using agoraRtcEngineEx but works on agoraRtcEngine? Is it still not working in web just like you said in the other issue? VideoViewController.remote also accepts agoraRtcEngine as parameters and not agoraRtcEngineEx is that the reason why its not working?

**Comment by littleGnAl** [comment]
@danilo1998271 
I think you also need to set the `localUid` for the `RtcConnection`.

**Comment by danilo1998271** [comment]
<img width="493" alt="Screenshot 2024-09-18 at 1 04 28 PM" src="https://github.com/user-attachments/assets/42d832fe-edac-44c4-83be-bde8ae4477fa">
<img width="248" alt="Screenshot 2024-09-18 at 1 05 03 PM" src="https://github.com/user-attachments/assets/a3fc8fd5-1e7b-446d-87a1-95eb918aafe2">
@littleGnAl can you clarify i still got this error even if i updated to the latest version and followed the instructions given in here https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK?tab=readme-ov-file#web-alpha

**Comment by danilo1998271** [comment]
<img width="565" alt="Screenshot 2024-09-19 at 12 11 47 PM" src="https://github.com/user-attachments/assets/3408ba54-c59b-4a2c-b10a-06d8909c1657">
<img width="1127" alt="Screenshot 2024-09-19 at 12 11 57 PM" src="https://github.com/user-attachments/assets/53caf3e5-52eb-400a-9ed0-754d43500917">
@littleGnAl i already updated to iris_web to 0.8.0 can i ask why it still has this errors?

**Comment by littleGnAl** [comment]
@danilo1998271 
Please file a new issue to keep track of these APIs that are not supported, we will implement them when we have resources
