### ISSUE TITLE
Incorrect Face Detection Coordinates on Android

### ISSUE THREAD

**Issue by azazadev** [AgoraIO-Extensions/Agora-Flutter-SDK#1907]
### Version of the agora_rtc_engine

6.3.2

### Platforms affected

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] Web

### Steps to reproduce

Run the provided code on both iOS and Android devices.
Observe the logged face position and image dimensions.
Notice the incorrect face rectangle positioning on Android compared to iOS.

### Expected results

The face detection rectangle should be correctly positioned around the face on both iOS and Android.
The width and height values should be consistent and accurate on both platforms.

### Actual results

On iOS, the face detection rectangle is correctly positioned around the face.
On Android, the face detection rectangle is incorrectly positioned, and the width and height values are inconsistent (e.g., width > height).

### Code sample

```
import 'dart:developer';

import 'package:agora_rtc_engine/agora_rtc_engine.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: VideoCallScreen(),
    );
  }
}

class VideoCallScreen extends StatefulWidget {
  const VideoCallScreen({super.key});

  @override
  VideoCallScreenState createState() => VideoCallScreenState();
}

class VideoCallScreenState extends State<VideoCallScreen> {
  late final RtcEngine _engine;
  Rectangle? _faceRectangle;
  @override
  void initState() {
    super.initState();
    initAgora();
  }

  void initAgora() async {
    _engine = createAgoraRtcEngine();
    await _engine.initialize(const RtcEngineContext(
      appId: '<YOUR_APP_ID>',
      channelProfile: ChannelProfileType.channelProfileCloudGaming,
    ));
    _engine.registerEventHandler(
      RtcEngineEventHandler(
        onFacePositionChanged: (int imageWidth, int imageHeight, List<Rectangle> vecRectangle, List<int> vecDistance, int numFaces) {
          if (mounted) {
            setState(() {
              if (numFaces > 0) {
                int faceX = vecRectangle[0].x!;
                int faceY = vecRectangle[0].y!;
                int faceWidth = vecRectangle[0].width!;
                int faceHeight = vecRectangle[0].height!;
                log('Face position: $faceX, $faceY, $faceWidth, $faceHeight');
                log('Face image width: $imageWidth, height: $imageHeight');
                _faceRectangle = vecRectangle[0];
              }
            });
          }
        },
      ),
    );
    await _engine.enableVideo();
    await _engine.enableFaceDetection(true);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.transparent,
        child: Stack(
          children: [
            AgoraVideoView(
              controller: VideoViewController(
                rtcEngine: _engine,
                canvas: const VideoCanvas(uid: 0),
              ),
              onAgoraVideoViewCreated: (viewId) {
                _engine.startPreview();
              },
            ),
            if (_faceRectangle != null)
              Positioned(
                  left: _faceRectangle!.x!.toDouble(),
                  top: _faceRectangle!.y!.toDouble(),
                  width: _faceRectangle!.width!.toDouble(),
                  height: _faceRectangle!.height!.toDouble(),
                  child: Container(
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.red, width: 4),
                    ),
                  ))
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _engine.release();
  }
}

```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

IOS logs

```
Face position: 163, 329, 129, 130
Face image width: 540, height: 960
```

Android logs
```

Face position: 375, 614, 550, 550
Face image width: 960, height: 540
```

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] Android Studio (version 4.0)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (7 available)
[✓] Network resources

• No issues found!

**Comment by littleGnAl** [comment]
As I know, the face detection feature works on high-end devices on Android, what device you're testing?

**Comment by littleGnAl** [comment]
I'm so sorry that I may not have time to follow up on this issue, I think you'd better raise a ticket to Agora Support for an on-time response at this time.
