### ISSUE TITLE
Support for Multiple Simultaneous Video Streams with external camera

### ISSUE THREAD

**Issue by kunjaarogyatech** [AgoraIO-Extensions/Agora-Flutter-SDK#1931]
## Description:
We are building an app that requires streaming video from two cameras simultaneously: one built-in camera and one USB external camera. We need support in the Agora Flutter SDK to stream both cameras together. App will be running on **Android, Linux and Windows** platforms.

## Current Capability:
We can detect both cameras using the following code:

```
_videoDeviceManager = _engine.getVideoDeviceManager();
_videoDeviceInfos = await _videoDeviceManager.enumerateVideoDevices();

for (var device in _videoDeviceInfos) {
  log('device: ${device.deviceId}-${device.deviceName}');
}
```

## Feature Request:
Provide the ability to add multiple camera video streams, including both built-in and external cameras, to the same session.

## Proposed Solution:
Methods to create and manage multiple local video tracks for different cameras.
API to publish and render multiple video streams simultaneously.

**_I am open to use existing solution if available._**

**Comment by littleGnAl** [comment]
I think this example may meet your requirements.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/send_multi_camera_stream/send_multi_camera_stream.dart
