### ISSUE TITLE
Caused by kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by zQ4** [AgoraIO-Extensions/Agora-Flutter-SDK#1948]
### Version of the agora_rtc_engine

6.3.1

### Platforms affected

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] Web

### Steps to reproduce

  agora_rtc_engine: ^6.0.0
  flutter pub get
  

### Expected results

无报错

### Actual results

lateinit property methodChannel has not been initialized

io.agora.agora_rtc_engine.AgoraRtcEnginePlugin.onDetachedFromEngine (AgoraRtcEnginePlugin.kt:39)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove (FlutterEngineConnectionRegistry.java:270)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove (FlutterEngineConnectionRegistry.java:280)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll (FlutterEngineConnectionRegistry.java:288)
io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy (FlutterEngineConnectionRegistry.java:121)
io.flutter.embedding.engine.FlutterEngine.destroy (FlutterEngine.java:427)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:704)
io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java:715)
android.app.Activity.performDestroy (Activity.java:8876)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Flutter version 3.3.4

**Comment by littleGnAl** [comment]
Can you provide the correct version of `agora_rtc_engine `? In the 6. x, there is no Kotlin code anymore.

**Comment by zQ4** [comment]
> Can you provide the correct version of `agora_rtc_engine `? In the 6. x, there is no Kotlin code anymore.

![Uploading image.png…]()

**Comment by zQ4** [comment]
> Can you provide the correct version of `agora_rtc_engine `? In the 6. x, there is no Kotlin code anymore.

6.3.1

**Comment by littleGnAl** [comment]
There's no `AgoraRtcEnginePlugin.kt` anymore.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/android/src/main/java/io/agora/agora_rtc_ng

I believe there's a cache of your code. Can you check your `pubspec.lock` file to confirm the final `agora_rtc_engine` version? And maybe you can run the `flutter clean` first and then build your APP again to see if this error persists.

**Comment by zQ4** [comment]
> There's no `AgoraRtcEnginePlugin.kt` anymore. https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/android/src/main/java/io/agora/agora_rtc_ng
> 
> I believe there's a cache of your code. Can you check your `pubspec.lock` file to confirm the final `agora_rtc_engine` version? And maybe you can run the `flutter clean` first and then build your APP again to see if this error persists.

ok thanks
We switched from a local plugin to a remote plugin, but the local plugin did not delete the initialization-related business code
