### ISSUE TITLE
SurfaceView Not working

### ISSUE THREAD

**Issue by adham-ashraf77** [AgoraIO-Extensions/Agora-Flutter-SDK#2046]
![image](https://github.com/user-attachments/assets/344c62cf-0f75-490e-a6ea-0e397f79784b)

can anyone help me with the new package?

**Comment by littleGnAl** [comment]
There're no these classes in the latest version, please check our examples for reference 
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/basic/join_channel_video/join_channel_video.dart
