### ISSUE TITLE
Occasionally, the uid obtained by app is negative, and the uid obtained by web and app is inconsistent

### ISSUE THREAD

**Issue by yueyuehu** [AgoraIO-Extensions/Agora-Flutter-SDK#223]
Occasionally, the uid obtained by app is negative, and the uid obtained by web and app is inconsistent

**Comment by LichKing-2234** [comment]
because java doesn't support UInt, you can refer to this doc and get more info from `optionalUid `

https://docs.agora.io/en/live-streaming/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a8b308c9102c08cb8dafb4672af1a3b4c

**Comment by LichKing-2234** [comment]
I will try to make a wrapper to cross javascript and java.

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
