### ISSUE TITLE
Support for MediaPlayer Kit

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO-Extensions/Agora-Flutter-SDK#242]
Can you please consider including MediaPlayer Kit and RtcChannelPublishHelper in the plug-in?

**Comment by zhangtao1104** [comment]
Sorry, we don't support MediaPlayerKit in Flutter yet, we plan to do this, but it maybe in the future, it is not in our roadmap yet.

**Comment by jovermars** [comment]
Any plans for putting this on the roadmap? That would be very appreciated!

**Comment by nizwar** [comment]
Any update about this feature?

**Comment by LichKing-2234** [comment]
The latest version has supported it.
