### ISSUE TITLE
[Question] When is it safe to call isCameraZoomSupported?

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO-Extensions/Agora-Flutter-SDK#261]
I am calling isCameraZoomSupported after RTC engine is initialised and I have called enabledVideo(). More often than not it returns false and only sometimes true. If I introduce a delay of 3 seconds, I consistently get the correct response.

When is it safe to call isCameraZoomSupported and other camera feature functions?

Similarly, when switchCamera() is called, if isCameraZoomSupported() is called after without a delay, again the same issue arises.

**Comment by plutoless** [comment]
so you will get different results on the same device?

**Comment by rgb1380** [comment]
> so you will get different results on the same device?

Correct.

**Comment by plutoless** [comment]
could you pls help collect the sdk logs for me? cheers

**Comment by rgb1380** [comment]
So what I have done is to call isCameraZoomSupported() immediately after enableVideo. Here is what I see in the log:
INFO    (14:52:29:324 |    0)  21400; API call to enable video
INFO    (14:52:29:324 |    0)  21400; [rp] ["che.video.camera.zoom_supported"]
INFO    (14:52:29:324 |    0)  21400; [rp] res: {} 

then after two seconds delay a second call which returns this:
INFO    (14:52:31:331 |    2)  19920; [API][rtc_engine_impl.cpp:985][getParameters]
INFO    (14:52:31:331 |    0)  21400; [rp] ["che.video.camera.zoom_supported"]
INFO    (14:52:31:332 |    1)  21400; [rp] res: {"che.video.camera.zoom_supported":true} 

The flutter wrapper, however, is returning false in the first instance whilst the SDK is returning nothing. Here is what I have logged in the flutter app:
I/flutter (19920): [2021-03-02 14:52:29.309230] zoom supported: false
I/flutter (19920): [2021-03-02 14:52:31.330621] zoom supported: true

The expected behaviour is for the asynchronous method not to return a value until the SDK is ready. 

I have attached the SDK log just in case. 
[ItRExC4X134P4CaIK9iA_20210302-035258.log](https://github.com/AgoraIO/Agora-Flutter-SDK/files/6066107/ItRExC4X134P4CaIK9iA_20210302-035258.log)

**Comment by plutoless** [comment]
@rgb1380 just talked to our engineer. it's suggested to use this api after you see video local preview.

**Comment by rgb1380** [comment]
Same issue. Calling immediately after startPreview() has the same effect. Also note that this same issue is present after switchCamera().
Even the 3 second delay that I have introduced is not reliable. At least once, the information was not ready after 3 seconds.

I think the issue needs to be passed on to the RTC SDK team.

In the meantime, and as a workaround, I suggest that in the Flutter SDK you should return null when the SDK has returned nothing. What the Flutter wrapper is doing now is returning 'false' which is misleading. At least with a null value we would know that the SDK was not ready and can poll until we get a definitive response.

**Comment by rgb1380** [comment]
Cannot see any more info that is of help in #267

**Comment by LichKing-2234** [comment]
> Same issue. Calling immediately after startPreview() has the same effect. Also note that this same issue is present after switchCamera().
> Even the 3 second delay that I have introduced is not reliable. At least once, the information was not ready after 3 seconds.
> 
> I think the issue needs to be passed on to the RTC SDK team.
> 
> In the meantime, and as a workaround, I suggest that in the Flutter SDK you should return null when the SDK has returned nothing. What the Flutter wrapper is doing now is returning 'false' which is misleading. At least with a null value we would know that the SDK was not ready and can poll until we get a definitive response.

The SDK returns false, so I return false on the Flutter layer.

**Comment by rgb1380** [comment]
The SDK log shows that it is returning an empty json: {}

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a9c8ac52b0435fb09ac19fc60c8d075f4
https://docs.agora.io/en/Video/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/isCameraZoomSupported

**Comment by rgb1380** [comment]
I can see what the document says. The SDK log shows that it is returning empty not false or true. If it is indeed returning false, then it needs to be reported to SDK to fix. The device has the camera feature and the SDK. Is prematurely saying that it does not.

**Comment by LichKing-2234** [comment]
I will report to our native SDK team.

**Comment by LichKing-2234** [comment]
1、set the capture dimensions more than 720p
2、call this API after the `firstLocalVideoFrame` or `localVideoStateChanged`(LocalVideoStreamState.Capturing) event received.

**Comment by rgb1380** [comment]
Thanks. I will try this but why do I need to capture more than 720p?

**Comment by LichKing-2234** [comment]
too small dimensions not support zoom.

**Comment by rgb1380** [comment]
That has not been my experience. Zoom is supported on 360p which is what I use by default. The issue is that isCameraZoomSupported() returns false after enableVideo() but after a few seconds if you query the API it will return true. The problem I have is to do with timing of the API call.

**Comment by LichKing-2234** [comment]
maybe not support with some camera, I get this from our native SDK team.

whatever, `isCameraZoomSupported` should be called after `firstLocalVideoFrame` or `localVideoStateChanged`(LocalVideoStreamState.Capturing) event received.
