### ISSUE TITLE
Cannot disable logging on Android

### ISSUE THREAD

**Issue by mehmetartun** [AgoraIO-Extensions/Agora-Flutter-SDK#276]
We have been unable to stop excessive logging by Agora on the Android device running flutter. In IOS we don't experience any problems of this nature.

Implementation to disable logs:
We are disabling the logs with the following code;
`
import 'package:agora_rtc_engine/rtc_engine.dart' as RTC_Engine;

RTC_Engine.LogConfig logConfig = RTC_Engine.LogConfig();
    logConfig.level = RTC_Engine.LogLevel.None;
RtcEngineConfig config = RtcEngineConfig(APP_ID, logConfig: logConfig);
engine = await RTC_Engine.RtcEngine.createWithConfig(config);`

LOGS
I/agora_vrp(12050): stuck_watch: sd:271, id:0
I/agora_vrp(12050): Frames out=31. out Fps=15, Total out=91, stream=0, out interv=0, 0, 0, 0, 31, out render time interv=0, 0, 0, 0, 31
E/agora_vrp(12050): Frames replaced by swap=0, stream=0
I/agora_vrp(12050): stuck_watch: fps=15, id=0
I/agora_vrp(12050): stuck_watch: total=31, 0~15=0%, 15~30=0%, 30~40=0%, 40~60=3%, 60~80=96%, 80~110=0%, 110~150=0%, 150~200=0%, 200+=0%, id=0
I/agora_vrp(12050): stuck_watch: interval_distribution=128849018880, sd:361, id:0, avg draw cost:1
I/agora_vrp(12050): Frames rendered=31. Render Fps=15, Total rendered=91, stream=0, draw cost=31, 0, 0, 0, 0, 0, render inter=0, 0, 0, 1, 30, 0, 0, 0, 0
W/GENP.0  (12050): type=1400 audit(0.0:26508): avc: denied { search } for name="thermal" dev="sysfs" ino=31034 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
W/GENP.0  (12050): type=1400 audit(0.0:26510): avc: denied { search } for name="thermal" dev="sysfs" ino=31035 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
E/libc    (12050): Access denied finding property "net.dns1"
E/libc    (12050): Access denied finding property "net.dns2"
E/libc    (12050): Access denied finding property "net.dns3"
E/libc    (12050): Access denied finding property "net.dns4"
W/GENP.0  (12050): type=1400 audit(0.0:26511): avc: denied { search } for name="thermal" dev="sysfs" ino=31035 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
W/GENP.0  (12050): type=1400 audit(0.0:26512): avc: denied { search } for name="thermal" dev="sysfs" ino=31034 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
I/agora_vrp(12050): stuck_watch: fps=15, id=0
I/agora_vrp(12050): stuck_watch: total=30, 0~15=0%, 15~30=0%, 30~40=0%, 40~60=3%, 60~80=93%, 80~110=3%, 110~150=0%, 150~200=0%, 200+=0%, id=0
I/agora_vrp(12050): stuck_watch: interval_distribution=128050003968, sd:525, id:0, avg draw cost:1
I/agora_vrp(12050): Frames rendered=30. Render Fps=15, Total rendered=121, stream=0, draw cost=30, 0, 0, 0, 0, 0, render inter=0, 0, 0, 1, 28, 1, 0, 0, 0
I/agora_vrp(12050): stuck_watch: sd:487, id:0
I/agora_vrp(12050): Frames out=31. out Fps=15, Total out=122, stream=0, out interv=0, 0, 0, 2, 29, out render time interv=0, 0, 0, 1, 30
E/agora_vrp(12050): Frames replaced by swap=0, stream=0
W/GENP.0  (12050): type=1400 audit(0.0:26514): avc: denied { search } for name="thermal" dev="sysfs" ino=31034 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
E/libc    (12050): Access denied finding property "net.dns1"
E/libc    (12050): Access denied finding property "net.dns2"
E/libc    (12050): Access denied finding property "net.dns3"
E/libc    (12050): Access denied finding property "net.dns4"
I/agora_vrp(12050): stuck_watch: fps=15, id=0
I/agora_vrp(12050): stuck_watch: total=31, 0~15=0%, 15~30=0%, 30~40=0%, 40~60=0%, 60~80=100%, 80~110=0%, 110~150=0%, 150~200=0%, 200+=0%, id=0
I/agora_vrp(12050): stuck_watch: interval_distribution=26843545600, sd:177, id:0, avg draw cost:1
I/agora_vrp(12050): Frames rendered=31. Render Fps=15, Total rendered=152, stream=0, draw cost=31, 0, 0, 0, 0, 0, render inter=0, 0, 0, 0, 31, 0, 0, 0, 0
I/agora_vrp(12050): stuck_watch: sd:171, id:0
I/agora_vrp(12050): Frames out=31. out Fps=15, Total out=153, stream=0, out interv=0, 0, 0, 0, 31, out render time interv=0, 0, 0, 0, 31
E/agora_vrp(12050): Frames replaced by swap=0, stream=0
W/GENP.0  (12050): type=1400 audit(0.0:26520): avc: denied { search } for name="thermal" dev="sysfs" ino=31034 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
E/agora_vrp(12050): replaced by swap before render. gap=66 ms. all replaced by swap=1, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=66 ms. all replaced by swap=2, stream=0
I/agora_vrp(12050): stuck_watch: sd:240, id:0
I/agora_vrp(12050): Frames out=30. out Fps=15, Total out=183, stream=0, out interv=0, 0, 0, 0, 30, out render time interv=0, 0, 0, 0, 30
E/agora_vrp(12050): replaced by swap before render. gap=71 ms. all replaced by swap=3, stream=0
E/agora_vrp(12050): Frames replaced by swap=3, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=64 ms. all replaced by swap=1, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=73 ms. all replaced by swap=2, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=62 ms. all replaced by swap=3, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=66 ms. all replaced by swap=4, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=67 ms. all replaced by swap=5, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=65 ms. all replaced by swap=6, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=65 ms. all replaced by swap=7, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=69 ms. all replaced by swap=8, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=67 ms. all replaced by swap=9, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=67 ms. all replaced by swap=10, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=66 ms. all replaced by swap=11, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=64 ms. all replaced by swap=12, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=66 ms. all replaced by swap=13, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=75 ms. all replaced by swap=14, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=62 ms. all replaced by swap=15, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=64 ms. all replaced by swap=16, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=71 ms. all replaced by swap=17, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=62 ms. all replaced by swap=18, stream=0
W/GENP.0  (12050): type=1400 audit(0.0:26526): avc: denied { search } for name="thermal" dev="sysfs" ino=31034 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
E/agora_vrp(12050): replaced by swap before render. gap=65 ms. all replaced by swap=19, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=70 ms. all replaced by swap=20, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=67 ms. all replaced by swap=21, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=63 ms. all replaced by swap=22, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=68 ms. all replaced by swap=23, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=66 ms. all replaced by swap=24, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=66 ms. all replaced by swap=25, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=69 ms. all replaced by swap=26, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=67 ms. all replaced by swap=27, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=64 ms. all replaced by swap=28, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=73 ms. all replaced by swap=29, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=60 ms. all replaced by swap=30, stream=0
I/agora_vrp(12050): stuck_watch: sd:307, id:0
I/agora_vrp(12050): Frames out=31. out Fps=15, Total out=214, stream=0, out interv=0, 0, 0, 0, 31, out render time interv=0, 0, 0, 0, 31
E/agora_vrp(12050): replaced by swap before render. gap=65 ms. all replaced by swap=31, stream=0
E/agora_vrp(12050): Frames replaced by swap=31, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=70 ms. all replaced by swap=1, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=64 ms. all replaced by swap=2, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=66 ms. all replaced by swap=3, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=72 ms. all replaced by swap=4, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=63 ms. all replaced by swap=5, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=63 ms. all replaced by swap=6, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=73 ms. all replaced by swap=7, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=63 ms. all replaced by swap=8, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=64 ms. all replaced by swap=9, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=70 ms. all replaced by swap=10, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=67 ms. all replaced by swap=11, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=63 ms. all replaced by swap=12, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=70 ms. all replaced by swap=13, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=65 ms. all replaced by swap=14, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=64 ms. all replaced by swap=15, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=72 ms. all replaced by swap=16, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=63 ms. all replaced by swap=17, stream=0
W/GENP.0  (12050): type=1400 audit(0.0:26532): avc: denied { search } for name="thermal" dev="sysfs" ino=31034 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
E/agora_vrp(12050): replaced by swap before render. gap=66 ms. all replaced by swap=18, stream=0
W/GENP.0  (12050): type=1400 audit(0.0:26534): avc: denied { search } for name="thermal" dev="sysfs" ino=31035 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
E/libc    (12050): Access denied finding property "net.dns1"
E/libc    (12050): Access denied finding property "net.dns2"
E/libc    (12050): Access denied finding property "net.dns3"
E/libc    (12050): Access denied finding property "net.dns4"
E/agora_vrp(12050): replaced by swap before render. gap=69 ms. all replaced by swap=19, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=65 ms. all replaced by swap=20, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=64 ms. all replaced by swap=21, stream=0
E/agora_vrp(12050): replaced by swap before render. gap=66 ms. all replaced by swap=22, stream=0
D/*WEBRTCN*(12050): VideoRenderAndroid dtor
I/AGORA_SDK(12050): Surface changed to width 1080 height 1658
W/GENP.0  (12050): type=1400 audit(0.0:26538): avc: denied { search } for name="thermal" dev="sysfs" ino=31034 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
I/agora_vrp(12050): stuck_watch: sd:279, id:0
I/agora_vrp(12050): Frames out=32. out Fps=15, Total out=32, stream=0, out interv=0, 0, 0, 1, 30, out render time interv=0, 0, 0, 1, 30
E/agora_vrp(12050): Frames replaced by swap=0, stream=0
I/agora_vrp(12050): stuck_watch: fps=15, id=0
I/agora_vrp(12050): stuck_watch: total=31, 0~15=0%, 15~30=0%, 30~40=0%, 40~60=3%, 60~80=96%, 80~110=0%, 110~150=0%, 150~200=0%, 200+=0%, id=0
I/agora_vrp(12050): stuck_watch: interval_distribution=128849018880, sd:310, id:0, avg draw cost:1
I/agora_vrp(12050): Frames rendered=32. Render Fps=15, Total rendered=32, stream=0, draw cost=32, 0, 0, 0, 0, 0, render inter=0, 0, 0, 1, 30, 0, 0, 0, 0
W/GENP.0  (12050): type=1400 audit(0.0:26544): avc: denied { search } for name="thermal" dev="sysfs" ino=31034 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
I/agora_vrp(12050): stuck_watch: sd:230, id:0
I/agora_vrp(12050): Frames out=31. out Fps=15, Total out=63, stream=0, out interv=0, 0, 0, 0, 31, out render time interv=0, 0, 0, 0, 31
E/agora_vrp(12050): Frames replaced by swap=0, stream=0
I/agora_vrp(12050): stuck_watch: fps=15, id=0
I/agora_vrp(12050): stuck_watch: total=31, 0~15=0%, 15~30=0%, 30~40=0%, 40~60=0%, 60~80=100%, 80~110=0%, 110~150=0%, 150~200=0%, 200+=0%, id=0
I/agora_vrp(12050): stuck_watch: interval_distribution=26843545600, sd:289, id:0, avg draw cost:1
I/agora_vrp(12050): Frames rendered=31. Render Fps=15, Total rendered=63, stream=0, draw cost=31, 0, 0, 0, 0, 0, render inter=0, 0, 0, 0, 31, 0, 0, 0, 0
W/GENP.0  (12050): type=1400 audit(0.0:26550): avc: denied { search } for name="thermal" dev="sysfs" ino=31034 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
W/GENP.0  (12050): type=1400 audit(0.0:26552): avc: denied { search } for name="thermal" dev="sysfs" ino=31035 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
E/libc    (12050): Access denied finding property "net.dns2"
E/libc    (12050): Access denied finding property "net.dns3"
E/libc    (12050): Access denied finding property "net.dns4"
I/agora_vrp(12050): stuck_watch: sd:226, id:0
I/agora_vrp(12050): Frames out=31. out Fps=15, Total out=94, stream=0, out interv=0, 0, 0, 0, 31, out render time interv=0, 0, 0, 0, 31
E/agora_vrp(12050): Frames replaced by swap=0, stream=0
I/agora_vrp(12050): stuck_watch: fps=15, id=0
I/agora_vrp(12050): stuck_watch: total=31, 0~15=0%, 15~30=0%, 30~40=0%, 40~60=0%, 60~80=100%, 80~110=0%, 110~150=0%, 150~200=0%, 200+=0%, id=0
I/agora_vrp(12050): stuck_watch: interval_distribution=26843545600, sd:305, id:0, avg draw cost:1
I/agora_vrp(12050): Frames rendered=31. Render Fps=15, Total rendered=94, stream=0, draw cost=31, 0, 0, 0, 0, 0, render inter=0, 0, 0, 0, 31, 0, 0, 0, 0
W/GENP.0  (12050): type=1400 audit(0.0:26556): avc: denied { search } for name="thermal" dev="sysfs" ino=31034 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
W/GENP.0  (12050): type=1400 audit(0.0:26558): avc: denied { search } for name="thermal" dev="sysfs" ino=31035 scontext=u:r:untrusted_app_29:s0:c97,c257,c512,c768 tcontext=u:object_r:sysfs_thermal:s0 tclass=dir permissive=0 app=com.vidiolo.app.dev
I/agora_vrp(12050): stuck_watch: sd:141, id:0
I/agora_vrp(12050): Frames out=31. out Fps=15, Total out=125, stream=0, out interv=0, 0, 0, 0, 31, out render time interv=0, 0, 0, 0, 31
E/agora_vrp(12050): Frames replaced by swap=0, stream=0
I/agora_vrp(12050): stuck_watch: fps=15, id=0
I/agora_vrp(12050): stuck_watch: total=31, 0~15=0%, 15~30=0%, 30~40=0%, 40~60=0%, 60~80=100%, 80~110=0%, 110~150=0%, 150~200=0%, 200+=0%, id=0
I/agora_vrp(12050): stuck_watch: interval_distribution=26843545600, sd:254, id:0, avg draw cost:1
I/agora_vrp(12050): Frames rendered=31. Render Fps=15, Total rendered=125, stream=0, draw cost=31, 0, 0, 0, 0, 0, render inter=0, 0, 0, 0, 31, 0, 0, 0, 0
D/*WEBRTCN*(12050): VideoRenderAndroid dtor
E/libc    (12050): Access denied finding property "net.dns1"
E/libc    (12050): Access denied finding property "net.dns2"
E/libc    (12050): Access denied finding property "net.dns3"
E/libc    (12050): Access denied finding property "net.dns4"
W/MessageQueue(12050): Handler (android.media.ImageReader$ListenerHandler) {874e87c} sending message to a Handler on a dead thread
W/MessageQueue(12050): java.lang.IllegalStateException: Handler (android.media.ImageReader$ListenerHandler) {874e87c} sending message to a Handler on a dead thread
W/MessageQueue(12050): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
W/MessageQueue(12050): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue(12050): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue(12050): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue(12050): 	at android.os.Handler.sendEmptyMessageDelayed(Handler.java:662)
W/MessageQueue(12050): 	at android.os.Handler.sendEmptyMessage(Handler.java:647)
W/MessageQueue(12050): 	at android.media.ImageReader.postEventFromNative(ImageReader.java:764)
D/AudioTrack(12050): stop(257): called with 415360 frames delivered
D/*WEBRTCN*(12050): SetRenderAndroidVM
D/agora-jni(12050): android bridge destroy done...
D/BluetoothHeadset(12050): Proxy object disconnected
I/Choreographer(12050): Skipped 49 frames!  The application may be doing too much work on its main thread.
I/BpBinder(12050): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
W/System  (12050): A resource failed to call release.
W/System  (12050): A resource failed to call release.
I/BpBinder(12050): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
W/MessageQueue(12050): Handler (android.os.Handler) {6022167} sending message to a Handler on a dead thread

Flutter Doctor Output
`[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB)
    • Flutter version 2.0.2 at /Users/embonds/Utils/flutter
    • Framework revision 8962f6dc68 (7 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/embonds/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] VS Code (version 1.54.3)
    • VS Code at /Users/embonds/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Pixel 2 (mobile)       • HT7C11A00770                         • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • D52FFF67-90E0-45DB-AB06-2BA77D3BB612 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 89.0.4389.90

**Comment by LichKing-2234** [comment]
the log filter just for the log file now, I will report to our native SDK team.

**Comment by rushi-12320** [comment]
i want to solve this issue

**Comment by LichKing-2234** [comment]
this log might mean your CPU usage is high, pls provide our SDK log.
