### ISSUE TITLE
Cross platform not working

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [AgoraIO-Extensions/Agora-Flutter-SDK#281]
while i create stream from the android it will be visible from the android device but not on the ios device.
same as if i create stream from the ios  device then it is not visible from the android device but visible from ios device.

so mainly its not working on cross platform.
Please help.

however i am receiving all the messages from rtm but rtc seems not working on cross platform or i am missing something.

I have used [this](https://www.agora.io/en/blog/build-a-live-streaming-social-media-app-on-flutter/) as code and implemented it.

**Comment by BhavyKoshti9spl** [comment]
> while i create stream from the android it will be visible from the android device but not on the ios device.
> same as if i create stream from the ios device then it is not visible from the android device but visible from ios device.
> 
> so mainly its not working on cross platform.
> Please help.
> 
> however i am receiving all the messages from rtm but rtc seems not working on cross platform or i am missing something.

**Comment by LichKing-2234** [comment]
maybe you use the same uid, and another one will be kicked out.

**Comment by BhavyKoshti9spl** [comment]
i don't think so, but even if this is the case why its working for android-android and ios-ios ?

**Comment by LichKing-2234** [comment]
which version of SDK you used. maybe you can provide the SDK log, you can refer to the `setLogFile` method.

**Comment by BhavyKoshti9spl** [comment]
we are using plugin version of  
```
agora_rtc_engine: ^1.0.13
agora_rtm: ^0.9.11
```

**Comment by LichKing-2234** [comment]
this version is too old, pls upgrade it.

**Comment by BhavyKoshti9spl** [comment]
now i changed the agora_rtc_engine 3.3.2 now i am able to start stream from android and join in iOS its not working.

i have checked the stream id i am passing its perfect also my android - android working & iOS- iOS not tested yet.

you might encounter something i am missing or what ?

**Comment by LichKing-2234** [comment]
could pls share your code about our SDK?

**Comment by BhavyKoshti9spl** [comment]
**for host :**

```
@override
  void initState() {
    super.initState();
    // initialize agora sdk
    initialize();
    userMap = {widget.channelName: widget.image};
    _createClient();
    WidgetsBinding.instance.addObserver(
      new LifecycleEventHandler(suspendingCallBack: () {
        endStream();
        return;
      }),
    );
  }
```

```
Future<void> initialize() async {
    await _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    await _engine.enableWebSdkInteroperability(true);
    if (widget.streamType == 2) {
      await _engine.disableVideo();
    } else {
      await _engine.enableVideo();
    }
    await _engine.setParameters(
        '''{\"che.video.lowBitRateStreamParameter\":{\"width\":640,\"height\":360,\"frameRate\":15,\"bitRate\":400}}''');
    await _engine.joinChannel(null, widget.channelName, null, 0);
  }
```

```
/// Add agora event handlers
  void _addAgoraEventHandlers() {
    _engine?.setEventHandler(RtcEngineEventHandler(joinChannelSuccess: (
      String channel,
      int uid,
      int elapsed,
    ) async {
      final documentId = widget.channelName;
      channelName = documentId;
      print("UID    :   $uid");
      myUid = uid;
      sendStartCallNotification(uid);
      // The above line create a document in the firestore with username as documentID

      await Wakelock.enable();
      // This is used for Keeping the device awake. Its now enabled
    }, leaveChannel: (stats) {
      setState(() {
        _users.clear();
      });
    }, userJoined: (int uid, int elapsed) {
      setState(() {
        _users.add(uid);
      });
    }, userOffline: (int uid, UserOfflineReason reason) {
      if (uid == guestID) {
        setState(() {
          accepted = false;
        });
      }
      setState(() {
        _users.remove(uid);
      });
    }));
  }
```

  ```
void _createClient() async {
    _client = await AgoraRtmClient.createInstance(Constant.AGORA_APP_ID);
    _client.onMessageReceived = (AgoraRtmMessage message, String peerId) {
      _log(user: peerId, info: message.text, type: 'message');
    };
    _client.onConnectionStateChanged = (int state, int reason) {
      if (state == 5) {
        _client.logout();
        //_log('Logout.');
        setState(() {
          _isLogin = false;
        });
      }
    };
    await _client.login(null, widget.channelName);
    _channel = await _createChannel(widget.channelName);
    await _channel.join();
  }
```

```
Future<AgoraRtmChannel> _createChannel(String name) async {
    channel = await _client.createChannel(name);
    channel.onMemberJoined = (AgoraRtmMember member) async {
      setState(() {
        userList.add(
            new User(username: member.userId, name: member.userId, image: ''));
        if (userList.length > 0) anyPerson = true;
      });
      // }
      var len;
      _channel.getMembers().then((value) {
        len = value.length;
        setState(() {
          userNo = len - 1;
        });
      });

      print("USER JOINTED : " + member.userId.toString());
      _log(info: 'Member joined: ', user: member.userId, type: 'join');
    };
    channel.onMemberLeft = (AgoraRtmMember member) {
      var len;

      print("USER LEFT : " + member.userId.toString());
      setState(() {
        userList.removeWhere((element) => element.username == member.userId);
        if (userList.length == 0) anyPerson = false;
      });

      _channel.getMembers().then((value) {
        len = value.length;
        setState(() {
          userNo = len - 1;
        });
      });
      _log(info: 'Member left: ', user: member.userId, type: 'left');
    };
    channel.onMessageReceived =
        (AgoraRtmMessage message, AgoraRtmMember member) {
      _log(user: member.userId, info: message.text, type: 'message');
    };
    return channel;
  }
```

**for view on host :** 

```
Widget _viewRows() {
    final views = _getRenderViews();

    switch (views.length) {
      case 1:
        return Container(
            child: Column(
          children: <Widget>[_videoView(views[0])],
        ));
      case 2:
        return Container(
            child: Column(
          children: <Widget>[
            _expandedVideoRow([views[0]]),
            _expandedVideoRow([views[1]])
          ],
        ));
    }
    return Container();
  }
```

```
List<Widget> _getRenderViews() {
    final list = [
      RtcLocalView.SurfaceView(),
    ];
    return list;
  }

  /// Video view wrapper
  Widget _videoView(view) {
    return Expanded(child: ClipRRect(child: view));
  }

  /// Video view row wrapper
  Widget _expandedVideoRow(List<Widget> views) {
    final wrappedViews = views.map<Widget>(_videoView).toList();
    return Expanded(
      child: Row(
        children: wrappedViews,
      ),
    );
  }
```

**Comment by BhavyKoshti9spl** [comment]
**for jointed user :**

```
@override
  void initState() {
    super.initState();
    // initialize agora sdk
    initialize();
    userMap = {widget.username: widget.userImage};
    _createClient();
  }
```

```
Future<void> initialize() async {
    await _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    await _engine.enableWebSdkInteroperability(true);
    await _engine.setParameters(
        '''{\"che.video.lowBitRateStreamParameter\":{\"width\":640,\"height\":360,\"frameRate\":15,\"bitRate\":400}}''');
    await _engine.joinChannel(null, widget.channelName, null, 0);
  }
```

```
/// Create agora sdk instance and initialize
  Future<void> _initAgoraRtcEngine() async {
    _engine = await RtcEngine.createWithConfig(
        RtcEngineConfig(Constant.AGORA_APP_ID));
    await _engine.enableVideo();
    await _engine.muteLocalAudioStream(true);
    await _engine.enableLocalAudio(false);
    // await AgoraRtcEngine.enableLocalVideo(!muted);
  }
```

```
/// Add agora event handlers
  void _addAgoraEventHandlers() {
    _engine?.setEventHandler(RtcEngineEventHandler(joinChannelSuccess: (
      String channel,
      int uid,
      int elapsed,
    ) async {
      await Wakelock.enable();
    }, userJoined: (int uid, int elapsed) {
      setState(() {
        _users.add(uid);
      });
    }, userOffline: (int uid, UserOfflineReason reason) {
      if (uid == widget.channelId) {
        setState(() {
          completed = true;
          endStream();
          Future.delayed(const Duration(milliseconds: 1500), () async {
            await Wakelock.disable();
            // Navigator.pop(context);
            GameRoomsModel gameRoomsModel = new GameRoomsModel(0, 4);

            if (widget.isFromNotification) {
              MyApp.navKey.currentState.pushNamedAndRemoveUntil(
                  RouteGenerator.home_screen, (Route<dynamic> route) => false,
                  arguments: gameRoomsModel);
            } else {
              Navigator.pop(context);
            }
          });
        });
      }
      _users.remove(uid);
    }));
  }
```

**for view :**

 ```
Widget _viewRows() {
    final views = _getRenderViews();

    switch (views.length) {
      case 1:
        return (loading == true) && (completed == false)
            ?
            //LoadingPage()
            CircularProgressIndicator()
            : Container(
                child: Column(
                children: <Widget>[_videoView(views[0])],
              ));
      case 2:
        return (loading == true) && (completed == false)
            ?
            //LoadingPage()
            CircularProgressIndicator()
            : Container(
                child: Column(
                children: <Widget>[
                  _expandedVideoRow([views[0]]),
                  _expandedVideoRow([views[1]])
                ],
              ));
    }
    return Container();
  }
```

```
/// Helper function to get list of native views
  List<Widget> _getRenderViews() {
    final List<RtcRemoteView.SurfaceView> list = [];
    //user.add(widget.channelId);
    _users.forEach((int uid) {
      if (uid == widget.channelId) {
        list.add(RtcRemoteView.SurfaceView(
          uid: uid,
        ));
      }
    });
    /*if (accepted == true) {
      list.add(AgoraRenderWidget(0, local: true, preview: true));
    }*/
    if (list.isEmpty) {
      setState(() {
        loading = true;
      });
    } else {
      setState(() {
        loading = false;
      });
    }

    return list;
  }

  /// Video view wrapper
  Widget _videoView(view) {
    return Expanded(child: ClipRRect(child: view));
  }

  /// Video view row wrapper
  Widget _expandedVideoRow(List<Widget> views) {
    final wrappedViews = views.map<Widget>(_videoView).toList();
    return Expanded(
      child: Row(
        children: wrappedViews,
      ),
    );
  }

  /// Video layout wrapper
  Widget _viewRows() {
    final views = _getRenderViews();

    switch (views.length) {
      case 1:
        return (loading == true) && (completed == false)
            ?
            //LoadingPage()
            CircularProgressIndicator()
            : Container(
                child: Column(
                children: <Widget>[_videoView(views[0])],
              ));
      case 2:
        return (loading == true) && (completed == false)
            ?
            //LoadingPage()
            CircularProgressIndicator()
            : Container(
                child: Column(
                children: <Widget>[
                  _expandedVideoRow([views[0]]),
                  _expandedVideoRow([views[1]])
                ],
              ));
    }
    return Container();
  }
```

**Comment by LichKing-2234** [comment]
await _client.login(null, widget.channelName);

why login with the `channelName`? the param need be uid.

**Comment by LichKing-2234** [comment]
pls refer to our example, it must work on different platforms.

**Comment by BhavyKoshti9spl** [comment]
> await _client.login(null, widget.channelName);
> 
> why login with the `channelName`? the param need be uid.

it is uid. and its working for Android - Android

**Comment by BhavyKoshti9spl** [comment]
> pls refer to our example, it must work on different platforms.

i have referred the example and changed my old code to the new latest 3.3.2. there is class changes as well as video view is also changed.

**Comment by LichKing-2234** [comment]
> > pls refer to our example, it must work on different platforms.
> 
> i have referred the example and changed my old code to the new latest 3.3.2. there is class changes as well as video view is also changed.

I mean you can use our example to test on Android - iOS.

**Comment by BhavyKoshti9spl** [comment]
ok will check and back to you!

**Comment by BhavyKoshti9spl** [comment]
i tried with 2 android devices and it seems the example is not working for android-android audio seems playing but video is not working then i started one channel with my app and tried to join that channel from the example and that was working fine.

i am not getting anything what is the issue here?

**Comment by LichKing-2234** [comment]
which of example you used?

**Comment by BhavyKoshti9spl** [comment]
> which of example you used?

https://github.com/AgoraIO/Agora-Flutter-SDK

**Comment by LichKing-2234** [comment]
> i tried with 2 android devices and it seems the example is not working for android-android audio seems playing but video is not working then i started one channel with my app and tried to join that channel from the example and that was working fine.
> 
> i am not getting anything what is the issue here?

pls use the `JoinChannelVideo` example.

**Comment by LichKing-2234** [comment]
maybe you can provide the SDK log file.

**Comment by BhavyKoshti9spl** [comment]
> maybe you can provide the SDK log file.

what do you mean by sdk log file ?
flutter sdk logs or agora logs ?
and for my application or your example ?

also i have used the `JoinChannelVideo` example.

**Comment by LichKing-2234** [comment]
you can refer to `setLogFile` method.

replicate the problem, and pull the log file.

**Comment by BhavyKoshti9spl** [comment]
worked on a first try but then again when i started it its the same as before.

couldn't got the log file

**Comment by LichKing-2234** [comment]
Why couldn't get the log file?

**Comment by BhavyKoshti9spl** [comment]
Sorry for late response but so far i got this and i have some issues getting log files on both devices. i dont know where are they and how to check logs.

ios-ios working

android-android working

ios(host) - Android(spectator) - working

android(host) -ios(spectator) - sometimes not working

**Comment by BhavyKoshti9spl** [comment]
hey if there is a function for clearCache or something like this or reseting the agora account like that would be much helpful we can try that.

**Comment by BhavyKoshti9spl** [comment]
[here](https://www.dropbox.com/s/u1kigov1ymzn331/agorartm.log?dl=0) are the logs on android device in which i hosted the rtc session.

although i couldn't find any log files in ios devices.

**Comment by florianthiel** [comment]
Is this issue going to be fixed? This currently makes Agora unusable in production. Here can you find my sdk logs: #311

**Comment by imrajeshcoder** [comment]
**### host.dart**
```
  /// Helper function to get list of native views
  List<Widget> _getRenderViews() {
    final List<StatefulWidget> list = [];
    list.add(RtcLocalView.SurfaceView());
    if (accepted == true) {
      _users.forEach((int uid) {
        if (uid != 0) {
          guestID = uid;
        }
        list.add(RtcRemoteView.SurfaceView(uid: uid));
      });
    }
    return list;
  }
```

**### join.dart**
  List<Widget> _getRenderViews() {
    final List<StatefulWidget> list = [];
    _users.forEach((int uid) => list.add(RtcRemoteView.SurfaceView(uid: uid)));

    if (accepted == true) {
      list.add(RtcLocalView.SurfaceView());
    }

    if (list.isEmpty) {
      setState(() {
        loading = true;
      });
    } else {
      setState(() {
        loading = false;
      });
    }
    return list;
  }

**Comment by agora-vin** [comment]
Hi Florian,

//Form your iOS log, you enabled encryption

Agora SDK ver 3.4.2 build 76955, built on May 11 2021 13:52:27
INFO    (12:18:47:169 |    0)  69643; Agora SDK git ver:6fb8aef706 and branch:release/3.4.2
WARN    (12:18:47:170 |    1)  69643; CacheManager: check cache file header failed
INFO    (12:18:47:170 |    0)  69643; initialize plugin manager
INFO    (12:18:47:170 |    0)  69643; built-in encryption is enabled
INFO    (12:18:47:176 |    6)  69643; built-in ssl is enabled
INFO    (12:18:47:177 |    1)  69643; use AHPL engine
INFO    (12:18:47:182 |    5)  69643; CacheManager: save cache to storage elapsed 4
 


A couple of thing here, I would like to check on IOS and Android sides.

1.	The AppId of createInstance should be the same among IOS and Android 
RTC -- mRtcEngine = RtcEngine.create(getApplicationContext(), getString(R.string.private_app_id), mHandler);
	        RTM -- mRtmClient = RtmClient.createInstance(mContext, appID, new RtmClientListener() {
	  2.The encryption algorithm should be the same among iOS and Android. 
	  3. Enable encryption before joining channels
 
 
For follow up if needed,  
please attach BOTH iOS and android log. 
Please have time stamp, channel name, uid on IOS and Android.


 
Regards,
..Vin

**Comment by florianthiel** [comment]
I'm using the same code to create the engine on iOS and Android. Is encryption enabled by default? Because I didn't enable it in my code. The code I'm using to create the engine:

```
final token = (await _genAgoraToken.call({ 'trainingId': training.id })).data['token'];
        _engine = await RtcEngine.create('xxx');
        _engine!.setEventHandler(RtcEngineEventHandler(
          joinChannelSuccess: joinChannelSuccess,
          userJoined: userJoined,
          userOffline: userOffline,
          videoSizeChanged: videoSizeChanged,
          localUserRegistered: localUserRegistered,
          networkQuality: networkQuality,
          error: (error) {
            FirebaseCrashlytics.instance.recordFlutterError(FlutterErrorDetails(
              exception: error,
              library: 'agora_rtc_engine'
            ));
            print('=== ERROR ===');
            print(error);
            print('=============');
          },
          warning: (warning) {
            print('=== WARINING ===');
            print(warning);
            print('=============');
          }
        ));

        if (Client.instance.currentUser is Trainer)
          await AgoraRtcRawdata.registerVideoFrameObserver((await _engine!.getNativeHandle())!);

        // Set Video config
        final config = VideoEncoderConfiguration();
        config.dimensions = VideoDimensions(width: 1280, height: 720);
        config.frameRate = VideoFrameRate.Fps24;
        config.bitrate = 1710;
        config.degradationPrefer = DegradationPreference.MaintainBalanced;

        await _engine!.setVideoEncoderConfiguration(config);
        await _engine!.registerLocalUserAccount('xxx', Client.instance.currentUser!.id);
        await _engine!.enableAudio();
        await _engine!.enableVideo();
        await _engine!.joinChannelWithUserAccount(token, training.id, Client.instance.currentUser!.id);
```

The error occurs fairly random. Sometimes it doesn't occur at all. But there are times where this happens on every call. I will post the Android and iOS logs if I catch the error again.

**Comment by agora-vin** [comment]
Hi Florian,

Thx,  both Agora iOS and Android logs would definitely help when the faulty condition happening.

The other question I’m asking is the Agora AppId,  it must be in your App config file. Please compare the values in IOS and Android one to see they’re the same or not.

For example, on Android
<?xml version="1.0" encoding="UTF-8"?>

<resources>
    <string name="app_id" translatable="false">XXXXXXXXXXXXXX</string>>
    <string name="agora_access_token" translatable="false"></string>
</resources>


On iOS,


struct KeyCenter {

    static let AppId: String = "XXXXXXXXXXXXXXXXXXXX"



    // assign token to nil if you have not enabled app certificate

    static var Token: String? = nil

}



Regards,
..Vin

From: Florian Thiel ***@***.***>
Date: Monday, August 23, 2021 at 1:54 AM
To: AgoraIO/Agora-Flutter-SDK ***@***.***>
Cc: Vincent Su ***@***.***>, Comment ***@***.***>
Subject: Re: [AgoraIO/Agora-Flutter-SDK] Cross platform not working (#281)

I'm using the same code to create the engine on iOS and Android. Is encryption enabled by default? Because I didn't enable it in my code. The code I'm using to create the engine:

final token = (await _genAgoraToken.call({ 'trainingId': training.id })).data['token'];

        _engine = await RtcEngine.create('xxx');

        _engine!.setEventHandler(RtcEngineEventHandler(

          joinChannelSuccess: joinChannelSuccess,

          userJoined: userJoined,

          userOffline: userOffline,

          videoSizeChanged: videoSizeChanged,

          localUserRegistered: localUserRegistered,

          networkQuality: networkQuality,

          error: (error) {

            FirebaseCrashlytics.instance.recordFlutterError(FlutterErrorDetails(

              exception: error,

              library: 'agora_rtc_engine'

            ));

            print('=== ERROR ===');

            print(error);

            print('=============');

          },

          warning: (warning) {

            print('=== WARINING ===');

            print(warning);

            print('=============');

          }

        ));



        if (Client.instance.currentUser is Trainer)

          await AgoraRtcRawdata.registerVideoFrameObserver((await _engine!.getNativeHandle())!);



        // Set Video config

        final config = VideoEncoderConfiguration();

        config.dimensions = VideoDimensions(width: 1280, height: 720);

        config.frameRate = VideoFrameRate.Fps24;

        config.bitrate = 1710;

        config.degradationPrefer = DegradationPreference.MaintainBalanced;



        await _engine!.setVideoEncoderConfiguration(config);

        await _engine!.registerLocalUserAccount('xxx', Client.instance.currentUser!.id);

        await _engine!.enableAudio();

        await _engine!.enableVideo();

        await _engine!.joinChannelWithUserAccount(token, training.id, Client.instance.currentUser!.id);

The error occurs fairly random. Sometimes it doesn't occur at all. But there are times where this happens on every call. I will post the Android and iOS logs if I catch the error again.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAgoraIO%2FAgora-Flutter-SDK%2Fissues%2F281%23issuecomment-903570707&data=04%7C01%7Cvincent%40agora.io%7C035b018bb1084e56299608d9661360d6%7C602753743eaa49c283c3cc189d126981%7C0%7C0%7C637653056647657255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XhNJvPKI6g4Ez65RtEutH6%2FzWkDZdQy0IbE0OE3cwB8%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASD33L2VXDLAY3763W5A3QDT6ID5ZANCNFSM4ZUR3AJA&data=04%7C01%7Cvincent%40agora.io%7C035b018bb1084e56299608d9661360d6%7C602753743eaa49c283c3cc189d126981%7C0%7C0%7C637653056647657255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CkTs9wYaHlUokxXKJRLWewsUch9ZkxbfaxaaMJxCmx8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cvincent%40agora.io%7C035b018bb1084e56299608d9661360d6%7C602753743eaa49c283c3cc189d126981%7C0%7C0%7C637653056647667212%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bMkH7itQHhX0PtwcfCehPvbbRQ%2B7wtweffJbUOWLfk8%3D&reserved=0> or Android<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cvincent%40agora.io%7C035b018bb1084e56299608d9661360d6%7C602753743eaa49c283c3cc189d126981%7C0%7C0%7C637653056647667212%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8fTUZGpqvQu90TWrr8FWKGgacg%2BiY5%2FuyeVDIqkkvRk%3D&reserved=0>.

**Comment by florianthiel** [comment]
I don't have different config files for iOS and Android. I have one dart file which stores the AppId. So the AppId is the same on both platforms

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
