### ISSUE TITLE
Volume issue with single speaker

### ISSUE THREAD

**Issue by shashikantdurge** [AgoraIO-Extensions/Agora-Flutter-SDK#288]
**Describe the bug**
Volume is very low when there is only one speaker.
Volume increases when 2nd speaker joins.

Audio scenario: Default
Channel profile: Live Broadcasting

**Expected behavior**
Volume should be constant irrespective of  the number of speakers

**Comment by LichKing-2234** [comment]
How many users in the channel when you test only one speaker?

**Comment by shashikantdurge** [comment]
> How many users in the channel when you test only one speaker?

4-5 users

**Comment by LichKing-2234** [comment]
could pls record a video for this issue and provide the SDK log.

**Comment by shashikantdurge** [comment]
https://user-images.githubusercontent.com/20161204/112989076-28ba3500-9182-11eb-9e21-89e9186e9fd2.mp4

**Comment by RoJoHub** [comment]
I'm sorry I came too late.
Due to lack of human resources, can you provide an example for my verification?

**Comment by shashikantdurge** [comment]
Check the Agora example project
https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/example/lib/examples/basic/join_channel_audio.dart

1. In 1st device join as ClientRole.**Audience**

2. From 2nd device join as ClientRole.**Broadcaster**
(when you speak here, the volume is loud in 1st device)

3. From 3rd device join as ClientRole.**Broadcaster**
(The volume drastically comes down on 1st device)

**Comment by gson2019** [comment]
@RoJoHub Do we have any updates on this issue ?

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
