### ISSUE TITLE
Video Call Ringing and receiver online/offline status tracking

### ISSUE THREAD

**Issue by skabirgithub** [AgoraIO-Extensions/Agora-Flutter-SDK#306]
**Is your feature request related to a problem? Please describe.**
Doctor is waiting in a video channel. He can not know patient is getting the call or not. He is waiting and waiting. How can the doctor know in the patient end it is ringing or not?

**Describe the solution you'd like**
We want a feature where user from a channel will know about the status and specially there will be a Ringing Tone from call initiating and before another one join in the channel.

**Describe alternatives you've considered**
Alternatively the call can be automatically cuts after some moment if only one is in the room. And of course sound starting when in a room is a must.

please share me any solution to our problem.

**Comment by LichKing-2234** [comment]
maybe you can use FCM.

**Comment by skabirgithub** [comment]
> maybe you can use FCM.

Thank you for your reply.
I have already implemented FCM. But how can I make a calling screen like whatsapp or messenger calling? Is there any way to do this?

**Comment by LichKing-2234** [comment]
maybe you should use CallKit(iOS) and ConnectionService(Android)
