### ISSUE TITLE
CrossPlatform video stream not working

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [AgoraIO-Extensions/Agora-Flutter-SDK#311]
**Describe the bug**
Sometimes ios to Android video stream is not working

**To Reproduce**
1. IOS start a stream
2. Android try to join not able to see video but audio and rtm is working fine
3. IOS try to join working fine

**Expected behavior**
IOS-Android streaming should work

**Screenshots**

**Smartphone (please complete the following information):**
 - iphone x, Red mi note 8 pro
 - OS: Iphone , Android
 - Version: agora_rtc_engine: "3.3.2"

**Additional context**
IOS-IOS working fine Android-Android working fine it produces sometimes but when it produces it is happening with all the devices like i am testing with ios and android devices started stream with one ios device and jointed that stream in several devices of android none of them are showing video stream but iphone device jointed showing the stream.

**Comment by plutoless** [comment]
could you pls provide a sdklog for when the issue happens? or at least provide a channel name you used and corresponding timestamp

**Comment by florianthiel** [comment]
Having the exact same issue. It worked perfectly until yesterday. Now video streams between iOS and Android aren't working anymore. Only one of the devices is showing the video streams (local and remote). On the other device local and remote streams are not working. I'm using SDK version 4.0.2. Here the logs from my iPhone 12 Pro Max where the local and remote streams weren't working: [agorasdk.log](https://github.com/AgoraIO/Agora-Flutter-SDK/files/6758220/agorasdk.log)
This seems to be related: #281
