### ISSUE TITLE
Watermark Image Not Appearing in Video

### ISSUE THREAD

**Issue by mukai154** [AgoraIO-Extensions/Agora-Flutter-SDK#314]
**Bug Description**
I'm attempting to add a watermark to a livestream.
It is not appearing and I'm not getting any error or information regarding what's happening. It's not appearing in the local preview and it's not appearing in any of the CDN services I've provided either.

**To Reproduce**
```
    agoraRtcEngine = await RtcEngine.createWithConfig(config).catchError((e) {
      print(e);
    });

    VideoEncoderConfiguration vidConfig = VideoEncoderConfiguration(
      dimensions: VideoDimensions(720, 1280),
      frameRate: VideoFrameRate.Fps30,
      bitrate: 1130,
    );

    await agoraRtcEngine.setVideoEncoderConfiguration(vidConfig);
    await agoraRtcEngine.enableVideo();
    await agoraRtcEngine.enableLocalAudio(true);

    WatermarkOptions watermarkOptions = WatermarkOptions(Rectangle(0, 0, 100, 100), Rectangle(0, 0, 100, 100));
    await agoraRtcEngine.addVideoWatermark("/assets/images/webblen_coin.png", watermarkOptions).catchError((e) {
      print(e);
    });

    await agoraRtcEngine.startPreview();
    await agoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await agoraRtcEngine.setClientRole(ClientRole.Broadcaster);
    agoraRtcEngine.joinChannel(token, channelName, null, user.id.hashCode);
```

**Expected behavior**
I would like a watermark to appear in the video being streamed.
Is there a valid example out there that streams a video and adds a watermark with Flutter?

**Device Information**
 - Device:  Iphone 11
 - OS: IOS 14

**Comment by LichKing-2234** [comment]
is it flutter assets?

**Comment by mukai154** [comment]
> is it flutter assets?

Yes it is

**Comment by LichKing-2234** [comment]
you can refer to the example JoinChannelAudio playEffect, then get the real path about flutter assets

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
