### ISSUE TITLE
Audio only call state  joinChannelSuccess not issued

### ISSUE THREAD

**Issue by calhu** [AgoraIO-Extensions/Agora-Flutter-SDK#317]
This bug report unfortunately will not contain a way to reproduce the problem unfortunately. However hopefylly some clues are going to be available.

Issue when joining a audio only call the eventhandler callback is not being called even though the call is established, audio call is setup and the call in itself works. 
I'm on version 4.0.0. rc3 however I have tried going back to 3.2.0 from where I started and where I don't recall this experience older version have the same issue.

When trying to narrow down in which version the bug is introduced I've found that its most likely not the client side version that is the underlying issue. There can be one phone which works most of the time and phones on the same version don't. Restarting the app doesn't fix the problem once it is occuring. It will be a consistent problem accross restarts of the application once it occurs. The token is generated each time the appl launches and the call itself is established

The way I work around this is by setting up a timer when I initiate the call and peridically check for ConnectionStateType.Connected and progress my UI state.

Issue on IOS and Android. Iphone SE2016 and 2020, Multiple Android devices

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (2 available)

• No issues found!
 
Best regards,
Kalevi

**Comment by LichKing-2234** [comment]
we need more infomation, such as the SDK log.

**Comment by calhu** [comment]
HI,
Here is a log of an unsuccesful run:

Best regards,
Kalevi 

--
I/flutter (25072): BS ago engine state : BSEngineState.READY
I/flutter (25072): BS ago engine enable audio
D/AudioManager(25072): setSpeakerphoneOn false
D/AudioManager(25072): setSpeakerphoneOn true
E/libc    (25072): Access denied finding property "net.dns1"
E/libc    (25072): Access denied finding property "net.dns2"
E/libc    (25072): Access denied finding property "net.dns3"
E/libc    (25072): Access denied finding property "net.dns4"
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/chatty  (25072): uid=10409(one.mimosa.duo) 1.ui identical 8 lines
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS ago engine call channel id DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.JOINING
I/chatty  (25072): uid=10409(one.mimosa.duo) 1.ui identical 8 lines
I/flutter (25072): BS ago callState BSCallState.JOINING
I/flutter (25072): BS foreground MAYBE starting
D/ForegroundServicePlugin(25072): started service, making foreground
D/ForegroundServicePlugin(25072): started foreground notification, entering service loop
D/        (25072): PlayerBase::PlayerBase()
D/        (25072): TrackPlayerBase::TrackPlayerBase()
I/libOpenSLES(25072): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
I/AudioTrack(25072): createTrack_l(1919243124): AUDIO_OUTPUT_FLAG_FAST successful; frameCount 0 -> 384
W/libOpenSLES(25072): Conversion from OpenSL ES positional channel mask 0x4 to Android mask 0 loses channels
I/libOpenSLES(25072): Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x10 based on channel count of 1)
I/AudioRecord(25072): createRecord_l(-428953600): AUDIO_INPUT_FLAG_FAST successful; frameCount 0 -> 4096
I/one.mimosa.duo(25072): Background concurrent copying GC freed 322387(12MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 15MB/30MB, paused 3.022ms total 243.671ms
I/one.mimosa.duo(25072): Background concurrent copying GC freed 515905(17MB) AllocSpace objects, 1(16KB) LOS objects, 49% free, 13MB/26MB, paused 319us total 126.810ms
E/libc    (25072): Access denied finding property "net.dns1"
E/libc    (25072): Access denied finding property "net.dns2"
E/libc    (25072): Access denied finding property "net.dns3"
E/libc    (25072): Access denied finding property "net.dns4"
I/one.mimosa.duo(25072): Background concurrent copying GC freed 298838(12MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 13MB/27MB, paused 257us total 119.346ms
E/libc    (25072): Access denied finding property "net.dns1"
E/libc    (25072): Access denied finding property "net.dns2"
E/libc    (25072): Access denied finding property "net.dns3"
E/libc    (25072): Access denied finding property "net.dns4"
I/one.mimosa.duo(25072): Background concurrent copying GC freed 309416(11MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 16MB/32MB, paused 236us total 141.303ms
E/libc    (25072): Access denied finding property "net.dns1"
E/libc    (25072): Access denied finding property "net.dns2"
E/libc    (25072): Access denied finding property "net.dns3"
E/libc    (25072): Access denied finding property "net.dns4"
I/one.mimosa.duo(25072): Background concurrent copying GC freed 478618(16MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 16MB/32MB, paused 236us total 124.797ms
D/ViewRootImpl@58b0756[MainActivity](25072): ViewPostIme pointer 0
D/ViewRootImpl@58b0756[MainActivity](25072): ViewPostIme pointer 1
I/flutter (25072): bs card update room
I/flutter (25072): BS ago engine call END Instance of 'RtcEngine'
I/flutter (25072): BS ago callState BSCallState.DISCONNECTING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.DISCONNECTING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.DISCONNECTING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.DISCONNECTING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.DISCONNECTING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.DISCONNECTING
I/flutter (25072): BS CSCALL pull state not my channel. this is active: DpcBI39SYqBW8FFPBS4U
I/flutter (25072): BS ago callState BSCallState.DISCONNECTING
I/flutter (25072): BS ago callState BSCallState.DISCONNECTING
I/chatty  (25072): uid=10409(one.mimosa.duo) 1.ui identical 7 lines
I/flutter (25072): BS ago callState BSCallState.DISCONNECTING
I/flutter (25072): bs channel settings  update room hangout : false
I/flutter (25072): BS AC PAUSE for channel: DpcBI39SYqBW8FFPBS4U
D/        (25072): PlayerBase::stop() from IPlayer
D/AudioTrack(25072): stop(64): called with 448128 frames delivered
I/flutter (25072): BS foreground service STOP

**Comment by LichKing-2234** [comment]
I need our SDK log file, you can get more info from `setLogFile` method.

**Comment by calhu** [comment]
Hi LichKing,
I tried two devices without my workaround and I was not able reproduce the issue. Due to the fact that I have a workaround I will not be able to notice necessarily if the problem is occuring. Now that I know how to get the log I will open a new case if and when the need arises. Could you please provide me with a 4.0.0 method of setLogFile (as its deprecated in 3.3.1) and close this case.
Thanks,
Kalevi

**Comment by LichKing-2234** [comment]
you can keep using setLogFile

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
