### ISSUE TITLE
[ios] Screen Share Crashing due to memmory usage over 50MB

### ISSUE THREAD

**Issue by Faisalkc4u** [AgoraIO-Extensions/Agora-Flutter-SDK#338]
**Describe the bug**

Screen share is crashing due to memory exceeded over 50MB

**To Reproduce**
1. Integrate Broadcast extension with flutter 
2. Run screen share
 
**Screenshots**

<img width="1670" alt="Screen Shot 2021-05-31 at 1 17 26 PM" src="https://user-images.githubusercontent.com/12441355/120172624-4d7b6900-c214-11eb-9bf6-3b430ea52494.png">
<img width="624" alt="Screen Shot 2021-05-31 at 1 18 02 PM" src="https://user-images.githubusercontent.com/12441355/120172656-5409e080-c214-11eb-93f7-83f1679b8d09.png">
 

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.4

**Smartphone (please complete the following information):**
 - Device: iPhone 7, iPhone 12 pro
 - OS: iOS
 - Version 14.6

**Comment by LichKing-2234** [comment]
is the screen sharing made by yourself?

**Comment by Faisalkc4u** [comment]
Yes,
I saw the documents in agora https://docs.agora.io/en/Video/custom_video_apple?platform=iOS
I followed and it works.
This is will join to existing meeting, also it will shows the mobile screen.
The only problem is memory issue.

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
