### ISSUE TITLE
Hi there!! Screen share not working in flutter using native code implementation

### ISSUE THREAD

**Issue by coderGirl9796** [AgoraIO-Extensions/Agora-Flutter-SDK#341]
I have implemented the native code for share screen in android according to below example code
https://github.com/AgoraIO/API-Examples/blob/master/Android/APIExample/app/src/main/java/io/agora/api/example/examples/advanced/SwitchCameraScreenShare.java

code executes successfully for screen share but when I start screen sharing it shows reconnecting on other side and screen share not working.

Is there any suggestion or idea about it, that what is the issue?

Thanks in advance.

**Comment by plutoless** [comment]
what do you mean reconnecting? are you seeing sth?

**Comment by coderGirl9796** [comment]
I mean when I start screen share the connection state change to Reconnecting

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
