### ISSUE TITLE
Muting local stream on phone makes the video on web disappear for the muted device

### ISSUE THREAD

**Issue by Xellly** [AgoraIO-Extensions/Agora-Flutter-SDK#348]
**What happens**
Upon starting a call everything works flawlessly. While testing cross platform, the phone video would randomly disappear on the web while it stays running normally on the phone. I realized that the second I pressed mute, it would disappear.
I did not alter the functions or the method that gets called in _engine.muteLocalAudioStream(muted); 
This started happening after a certain point that I don't recall and is now reproducable 100% of the time. I was running agora 2.6.3, now on 4.0.1. Same thing on both and I did not alter the code of either.
Before muting: 
![before](https://user-images.githubusercontent.com/54323091/121367803-46a2d380-c943-11eb-81d4-6df4e46cafc9.jpeg)
![WhatsApp Image 2021-06-09 at 4 50 23 PM](https://user-images.githubusercontent.com/54323091/121367928-5e7a5780-c943-11eb-9c11-7943a4611291.jpeg)

After tapping mute:
![after](https://user-images.githubusercontent.com/54323091/121367789-4571a680-c943-11eb-878b-a0aded511e88.jpeg)
![WhatsApp Image 2021-06-09 at 4 50 23 PM (1)](https://user-images.githubusercontent.com/54323091/121368003-6c2fdd00-c943-11eb-9bee-41e1c6a8097f.jpeg)

**To Reproduce**
1. Start a call between a computer and an android phone normally
2. After confirming everything is working properly, tap the mute mic button on the phone
3. You'll see that the phone video stream disappeared from the computer.
4. No errors in console other than 

**Screenshots**

**Desktop:**
 - OS: Windows 10
 - Chrome

**Smartphone:**

 - Device: Note 9 (Happens on others)
 - OS: Android 10
 - Version 4.0.1

**Comment by LichKing-2234** [comment]
have you try our demo?

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.
