### ISSUE TITLE
Call Not Connected  [Channel joining error] While Call receiving in lock state - Flutter iOS 

### ISSUE THREAD

**Issue by InheritxSolution** [AgoraIO-Extensions/Agora-Flutter-SDK#349]
Hi  @plutoless 

We are facing a strange issue in channel joining failure, due to `RtcEngine` object being null, while in our coding sequence we are calling the configuration method without any miss before joining channel. Still some time we get bellow logs on joining channel.

We are using agora_rtc_engine: ^4.0.0-rc.3
Issue occurs with ios devices. 

we face this issue(of joining channel failure) while user’s device(iOS) is in locked state. Not Always but  randomly. We are using `Pushkit` for call notification and application wakeup from background or kill state (if this make any difference of delay in `RtcEngine` initialisation process) and our project is in flutter, Any insights of possible issue or mistake and solution/suggestions would be helpful.

**Expected behavior**
It should join channel everytime even killed mode and locked screen.

**Smartphone (please complete the following information):**
 - Device: All iPhones
 - OS:  iOS 12,13,14 + 

**Additional context**
Below is the log  we got using `setLogFile`: 

flutter: on che.audio.enable.speakerphone event call with error : ErrorCode.NoError and result :
flutter: on rtc.video.mute_me event call with error : ErrorCode.NoError and result :
flutter: on che.video.local.send event call with error : ErrorCode.NoError and result :
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(5, request is refused, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)

Please help us with this problem. Thanks in Advance.

**Comment by InheritxSolution** [comment]
[agorasdk.log](https://github.com/AgoraIO/Agora-Flutter-SDK/files/6630461/agorasdk.log)

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Voice/release_ios_audio?platform=iOS#v332

**Comment by LichKing-2234** [comment]
seem like it has been fixed on native SDK 3.3.2.

you can try to upgrade to 4.0.2

**Comment by InheritxSolution** [comment]
Hi  @LichKing-2234 

Upgrading to 4.0.2 solved the reported problem, thank you.

But, this new update is causing similar problem but in other steps,

User can join the channel after killing and not locking the device, but killing app and locking device reproduce this issue. here is new log file attached.

INFO    (15:35:28:134 |    0)    771; API call to join channel 'd2d4084b-37a7-4daa-a858-f261e852118b' uid 48, SDK ver 3.4.2 build 76955, device info 'iPhone/iPhone7,1/iOS/12.4.9'
ERROR   (15:35:28:134 |    0)    771; Refused to join channel d2d4084b-37a7-4daa-a858-f261e852118b: curPublishChannel is 1a25b4db-1c3d-43ce-8103-5e1e46195e54
INFO    (15:35:28:134 |    0)  13839; [rp] {"che.audio.profile":{"config":100,"scenario":100}}
WARN    (15:35:28:136 |    2)  13839; audioProfile lambda: Audio Profile should be set prior to joinChannel

Attached log file , too.
Regards.

[agorasdk_1.log](https://github.com/AgoraIO/Agora-Flutter-SDK/files/6645779/agorasdk_1.log)

**Comment by InheritxSolution** [comment]
Hi @LichKing-2234,

Did you get a chance to review the above issue? 
Let us know your thoughts.

**Comment by LichKing-2234** [comment]
@InheritxSolution The log shows you have joined another channel named `1a25b4db-1c3d-43ce-8103-5e1e46195e54`.

**Comment by LichKing-2234** [comment]
you should call `leaveChannel` before join a new channel.

**Comment by InheritxSolution** [comment]
@LichKing-2234,

Thank you for your help,

Calling leaveChannel before joining a new channel solved the issue, we are still testing it with different OS versions, devices, and scenarios. We will let you know in case we found any issues.

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
