### ISSUE TITLE
Screen share in android app using agora sdk in flutter 

### ISSUE THREAD

**Issue by MaheshKeshvala** [AgoraIO-Extensions/Agora-Flutter-SDK#357]
-Hello 
I am not able to share the screen using the agora flutter SDK.
can you please help to implement this part?

**Comment by LichKing-2234** [comment]
not support yet, you can refer to the native API-Example.

**Comment by 1AhmedYasser** [comment]
Agora now supports Screen Sharing for flutter & react native

Flutter: https://docs.agora.io/en/Video/screensharing_flutter?platform=Flutter
React Native: https://docs.agora.io/en/Video/screensharing_react_native?platform=React%20Native

Have Fun

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
