### ISSUE TITLE
4.1.0-alpha2 The prefix "tools" for attribute "tools:ignore" associated with an element type "uses-permission" is not bound.

### ISSUE THREAD

**Issue by sils** [AgoraIO-Extensions/Agora-Flutter-SDK#363]
**Describe the bug**

Build error when upgrading to 4.1.0-alpha2:

```
Execution failed for task ':app:generateReleaseBuildConfig'.            
> Failed to calculate the value of task ':app:generateReleaseBuildConfig' property 'buildConfigPackageName'.
   > Failed to query the value of property 'packageName'.               
      > org.xml.sax.SAXParseException; systemId: file:/home/lasse/Documents/viperdev/runtogether/runtogether/android/app/src/main/AndroidManifest.xml; lineNumber: 15; columnNumber: 122; The prefix "tools" for attribute "tools:ignore" associated with an element type "uses-permission" is not bound.
```

**To Reproduce**

Add alpha2 to existing project
Change the config to the new context object
`flutter clean; flutter build apk --release`

**Expected behavior**
Build should pass.

It did when I removed that line from the android xml FWIW but your docs explicitly tell me to add it. Maybe this is just a docs issue, I don't know that xml file that well but felt you'd like to get this feedback.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Smartphone (please complete the following information):**
 Not relevant since it doesn't build.

**Comment by LichKing-2234** [comment]
maybe you can refer to https://stackoverflow.com/questions/38072616/permission-required-to-use-usagestatsmanager

**Comment by sils** [comment]
Yep, I recommend adding that to the readme for the next release to make that issue not appear for other users. I'm fine personally.

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
