### ISSUE TITLE
startAudioRecordingWithConfig throwing a  PlatformException error  "PlatformException(2, invalid argument, null, null)"

### ISSUE THREAD

**Issue by Emex4gman** [AgoraIO-Extensions/Agora-Flutter-SDK#373]
**Describe the bug**
When I tried to use the  startAudioRecordingWithConfig method on android to record the audio, I got a  PlatformException error
" PlatformException(2, invalid argument, null, null) "

![image](https://user-images.githubusercontent.com/23434595/125468831-7cc4a869-607d-479a-ac71-a9ce05501a81.png)

So, while trying to figure out what was going on, I found out  that 
startAudioRecordingWithConfig and  startAudioRecording  invoked the same channel methods but the arguments are different ;
![image](https://user-images.githubusercontent.com/23434595/125468181-091e7630-f714-45ab-9903-a8f3bf5d1785.png)

How do we resolve this. 

**To Reproduce**
1. call the engine .startAudioRecordingWithConfig method and pass the config "AudioRecordingConfiguration"

**Expected behavior**
No error should be thrown.

**Additional context**
Although the startAudioRecording still works fine, it has the deprecated flag.

**Comment by LichKing-2234** [comment]
Could you pls share your code about calling `startAudioRecordingWithConfig`?
