### ISSUE TITLE
Problem with animated surface view with Rtm Agora

### ISSUE THREAD

**Issue by erykkruk** [AgoraIO-Extensions/Agora-Flutter-SDK#375]
Hey,

I've got a problem with laggy animation in my app when I tried resizing video with animation (like on video). [LINK TO VIDEO](https://slack-files.com/TLJEDHY72-F028VA7RSKA-9390122389)

On the video you what I shared, at first, I opened the video with FlickerVideo player, and everything works fine.
At 17 seconds, you can see what happened when I clicked to open the "live" video with Agora surface view, it doesn't work as a normal player and it's a terrible experience.

To be sure is not my mistake, I also implemented animation in your example app and it worked the same.
I just replace the widget with AnimationContainer like this:

`AnimatedContainer(
      duration: const Duration(milliseconds: 500),
      height: toggle ? MediaQuery.of(context).size.height - 100 : 160,
      width: toggle ? MediaQuery.of(context).size.width : 100,
      curve: Curves.easeOutExpo,
      child: ClipRRect(
          borderRadius: toggle ? BorderRadius.zero : const BorderRadius.all(Radius.circular(8)),
          child: Expanded(
            child: Stack(
              children: [
                role == ClientRole.Broadcaster
                    ? RtcLocalView.SurfaceView()
                    : remoteUid != null
                        ? RtcRemoteView.SurfaceView(
                            uid: remoteUid!,
                          )
                        : Container()
              ],
            ),
          )),
    );`

```
✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-PL)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
[✓] VS Code (version 1.58.1)
[✓] Connected device (1 available)
```

I tested on Samsung S7 with Android 8, and Samsung A70 with Android 11

**Comment by LichKing-2234** [comment]
maybe you can try the TextureView on Android.

**Comment by erykkruk** [comment]
Thanks for the response - I tried, and I had the same problem :/

**Comment by LichKing-2234** [comment]
could you pls share the code about this? then we can test it.

**Comment by Virczek** [comment]
Hey, I shared in post. I have used example project, I just added my API there, and animation like:

`AnimatedContainer( duration: const Duration(milliseconds: 500), height: toggle ? MediaQuery.of(context).size.height - 100 : 160, width: toggle ? MediaQuery.of(context).size.width : 100, curve: Curves.easeOutExpo, child: ClipRRect( borderRadius: toggle ? BorderRadius.zero : const BorderRadius.all(Radius.circular(8)), child: Expanded( child: Stack( children: [ role == ClientRole.Broadcaster ? RtcLocalView.SurfaceView() : remoteUid != null ? RtcRemoteView.SurfaceView( uid: remoteUid!, ) : Container() ], ), )), );`

**Comment by erykkruk** [comment]
Could anyone help me? :) How optimized it with flutter?
