### ISSUE TITLE
Hide Access denied finding property "net.dns?" log

### ISSUE THREAD

**Issue by sandysultan** [AgoraIO-Extensions/Agora-Flutter-SDK#395]
Hi, is there any way I can remove or hide this kind of log? I know it's just a warning and I should be ignored it, but it's really hard to see my intended log, when 80% of log screen is full of this message.

Thanks

**Comment by LichKing-2234** [comment]
You can control it by calling the `setLogFilter` method.

**Comment by dgilperez** [comment]
Can you elaborate a bit on top of that @LichKing-2234?  Full command, maybe? Thanks !
