### ISSUE TITLE
enableLocalVideo method not working

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [AgoraIO-Extensions/Agora-Flutter-SDK#397]
Hi . Im got the problem when using enableLocalVideo . When i set enableLocalVideo(false) it work well . but then i enable it by set enableLocalVideo(true) , the other user cant receice my video stream anymore . 
agora version : agora_rtc_engine: ^4.0.6

**Comment by LichKing-2234** [comment]
have you tried our example?

**Comment by CaoGiaHieu-dev** [comment]
not yet . but i resolve it by using enableVideo to restart local view module . can you explain this ?

**Comment by LichKing-2234** [comment]
have you called `enableVideo` first?

**Comment by CaoGiaHieu-dev** [comment]
yes i did

**Comment by RuhaanSharma** [comment]
I am getting exactly same problem 

When I set enableLocalVideo(false) it works well . 
But then I enable it by set enableLocalVideo(true) , 
the other user cant receive my video stream anymore .
agora version : agora_rtc_engine: ^4.0.6

@CaoGiaHieu-dev  @LichKing-2234 Can you please share working code.

I have tried this

if (_isBlur) {
        await _engine.enableLocalVideo(false);
      } else {
        await _engine.enableVideo();
        await _engine.enableLocalVideo(true);
      }

**Comment by CaoGiaHieu-dev** [comment]
@RuhaanSharma  
I just restart video module by using enableVideo . not thinks else

**Comment by RuhaanSharma** [comment]
@CaoGiaHieu-dev I have tried using 
await _engine.enableVideo();
But this didn't worked.
Do you mean you have restarted whole screen ... this solution will not work for me.

@LichKing-2234 can you please provide some straight forward solution please.

**Comment by RuhaanSharma** [comment]
@LichKing-2234 
I have tried all permutation and combination in else case , none is working.
```
if (_isBlur) {
        await _engine.enableLocalVideo(false);
      } else {
        await _engine.enableLocalVideo(true);
        await _engine.enableVideo();
        await _engine.startPreview();
        await _engine.joinChannel(null, widget.callInfo.channelId, null, 0);
      }
```
    ```
  if (_isBlur) {
        await _engine.enableLocalVideo(false);
      } else {
        await _engine.enableLocalVideo(true);
        await _engine.enableVideo();
        await _engine.startPreview();
      }
```
    ```
    if (_isBlur) {
        await _engine.muteLocalVideoStream(false);
      } else {
       await _engine.enableVideo();
        await _engine.muteLocalVideoStream(true);
      }
```

It should simply work on calling same method in else case without the help of any other method needed.
Kindly fix this bug ASAP and let me know the solution.

**Comment by CaoGiaHieu-dev** [comment]
@RuhaanSharma 
did u try _engine.enableVideo(false) to close the local video when stop sending to sever ?? im closing local view and muteLocalVideoStream as the same time then restart it when open .
If its still not working i have no ideal about it

**Comment by RuhaanSharma** [comment]
@CaoGiaHieu-dev Can you please write your if-else code here.
It will be very helpful to see which methods you have used to close and then restart.
As the method you have mentioned doesn't exists 
_engine.enableVideo(false)
There is no method enableVideo with parameter boolean.
Kindly write your if-else complete code here, I will be highly thankful to you for the same.

**Comment by LichKing-2234** [comment]
@RuhaanSharma maybe you can debug and check the value of isbur

**Comment by CaoGiaHieu-dev** [comment]
This is my code to fix the problem . sorry about comment i reply . its not _engine.enableVideo(false) , its rtcEngine?.disableVideo()
```
void toggleVideo(bool enable) {
    rtcEngine?.muteLocalVideoStream(enable); // i only use this func .
  }
```
u can try to add this.
```
if(enable) { 
   rtcEngine?.enableVideo();
}
 else{
   rtcEngine?.disableVideo();
}
```

**Comment by RuhaanSharma** [comment]
> @RuhaanSharma maybe you can debug and check the value of _isBlur

@LichKing-2234  _isBlur is fine as when I toggle , video on local device start coming but video of remote device of same user doest not show.
if (_isBlur) {
Video stop at local device and remote device of the user who has pressed blur.
}
else{
Video starts at local device of that user but not on remote device to whom he was doing video calling 
}

When call starts my initEngine method is as follows:

 _engine = await RtcEngine.createWithContext(RtcEngineContext(APP_ID));
  this._addListeners();
  await _engine.enableVideo();
  await _engine.startPreview();
  await _engine.setChannelProfile(ChannelProfile.Communication);
  await _engine.joinChannel(null, widget.callInfo.channelId, null, 0);
  
  As this is one to one call only , my remote video widget code is as follows:
  Container(
            child: Row(
              children: <Widget>[
                Expanded(
                    child: RtcRemoteView.SurfaceView(
                  uid: remoteUid.first,
                )),
              ],
            ),
          );

**Comment by RuhaanSharma** [comment]
> This is my code to fix the problem . sorry about comment i reply . its not _engine.enableVideo(false) , its _engine?.disableVideo()
> 
> ```
> void toggleVideo(bool enable) {
>     rtcEngine?.muteLocalVideoStream(enable); // i only use this method .
>   }
> ```
> 
> u can try to add this.
> 
> ```
> if(enable) { 
>    rtcEngine?.enableVideo();
> }
>  else{
>    rtcEngine?.disableVideo();
> }
> ```

Thankyou so much @CaoGiaHieu-dev  for all your replies. 
Your solution didn't worked for me , I hope to get it resolved for me too soon
