### ISSUE TITLE
Unable to hear from broadcaster(when broadcaster end the call - incoming call from another real device).

### ISSUE THREAD

**Issue by sanjayvramani** [AgoraIO-Extensions/Agora-Flutter-SDK#401]
Normal user can not hear from brodcaster.

Seqeunce:-

1) Broadcaster speaking , we can hear him.
2) Broadcaster get incoming call on mobile number.
3) Broadcaster received incoming call and after 5 seconds disconnect it.
4) Broadcaster start speaking, we are unable to hear him. Broadcaster can hear other broadcaster.

Above things happen, when broadcaster using headphone/earphone.
Device: Vivo, Mi

**Comment by alenpmla** [comment]
Any update on this?

 I'm also facing this issue. When I get an incoming call from another device and disconnect it, The other people can't hear me even though my role is **BROADCASTER** and the microphone is **unmuted**. I can hear other broadcasters' voices. I had to leave the channel and join again in order to fix this issue.
 
Please look into this issue on higher priority as our customers facing this issue frequently.

**Comment by mehraj-numen** [comment]
Any update on this? @LichKing-2234 

My Users are facing this issue and every time this happens they have to re join..

**Comment by plutoless** [comment]
could you pls help provide some logs? does this only happen when there's incoming calls?

**Comment by mehraj-numen** [comment]
Observed this issue only when the user receives the incoming call or missed call (even ring happens only once).
will provide the logs in few mins.

**Comment by mehraj-numen** [comment]
While receiving the incoming call, below log generated in release mode.
`I/flutter ( 2107): state
I/flutter ( 2107): AudioLocalState.Failed
I/flutter ( 2107): state
I/flutter ( 2107): AudioLocalState.Stopped
I/flutter ( 2107): reason
I/flutter ( 2107): AudioRemoteStateReason.LocalMuted
I/flutter ( 2107): state
I/flutter ( 2107): AudioLocalState.Failed
I/flutter ( 2107): reason
I/flutter ( 2107): AudioRemoteStateReason.LocalUnmuted
I/flutter ( 2107): reason
I/flutter ( 2107): AudioRemoteStateReason.Internal
I/flutter ( 2107): reason
I/flutter ( 2107): AudioRemoteStateReason.Internal
I/flutter ( 2107): state
I/flutter ( 2107): AudioLocalState.Recording
I/flutter ( 2107): state
I/flutter ( 2107): AudioLocalState.Encoding

`

**Comment by fareesh** [comment]
Can you confirm if there is a known fix for this issue @LichKing-2234 ?

**Comment by LichKing-2234** [comment]
> Can you confirm if there is a known fix for this issue @LichKing-2234 ?

I think the latest version works.
