### ISSUE TITLE
 [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method muteLocalVideoStream on channel agora_rtc_channel)

### ISSUE THREAD

**Issue by Hwan-seok** [AgoraIO-Extensions/Agora-Flutter-SDK#404]
#### I did not hot restarted

**Describe the bug**
MissingPluginException occurs when using `muteLocalAudioStream` and `muteLocalVideoStream`.
>[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method muteLocalVideoStream on channel agora_rtc_channel)
>[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method muteLocalAudioStream on channel agora_rtc_channel)

It works as expected (muting) but exception occurs.

It only occurs on IOS DEVICES.

What I tried.
```
flutter clean
ios pod repo update
remove podfile.lock and pod install
detele and reinstall app
```
**To Reproduce**
get 4.0.6 rtc engine and try muteLocalVideoStream

**Desktop (please complete the following information):**
 - OS: Mac book m1 App(not mac os app)

**Smartphone (please complete the following information):**
 - Device: All IOS Devices => What I tested, Iphone 12 mini, Iphone 11, 
 - OS: 14.7.1
 - Version : 4.0.6 (latest)

**Additional context**

**Comment by LichKing-2234** [comment]
this is a bug, will be fixed next version. you can use publish and unpublish.

**Comment by Hwan-seok** [comment]
Are these two exactly the same to publish or unpublish?

**Comment by Hwan-seok** [comment]
But then, how can I unpublish audio or video only?

**Comment by Hwan-seok** [comment]
I feel it works properly but only throws platform exception right?
If above is correct then, could I just try and empty catch the method?

**Comment by LichKing-2234** [comment]
not work on iOS

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.

**Comment by Hwan-seok** [comment]
Closing the issue due to lost interest in it.
