### ISSUE TITLE
Local and remote videos feed on Safari are black screens 

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO-Extensions/Agora-Flutter-SDK#410]
**Describe the bug**
We have ported our app (Flutter iOS/Android) to web. Our agora implementation works perfectly fine on desktop on the latest versions of Chrome, Edge, and Firefox but has an issue in Safari (version 14.1.1 on Mac).

With Safari the local preview does not work and remains black. However, the remote user does actually receive the video feed. The local user on Safari also does not see the video feed of the remote user, the screen is black but the audio comes through. 

We have observed the exact same problem with mobile Chrome on Android. 

Is this a known issue?

**Comment by LichKing-2234** [comment]
I need to check it.

**Comment by rgb1380** [comment]
Any updates? Have you seen the issue?

**Comment by NSFriend** [comment]
Have the same issue

**Comment by LichKing-2234** [comment]
Sorry, guys, I am so busy these days, I will check it next week.

**Comment by rgb1380** [comment]
@LichKing-2234 And progress, please?

**Comment by LichKing-2234** [comment]
I have tested it. But I have no idea about it. I need more time.

**Comment by rgb1380** [comment]
Any update?

**Comment by reeteshranjan** [comment]
![Screenshot 2022-07-28 at 11 56 28 PM](https://user-images.githubusercontent.com/5516599/181615656-5e75de89-3111-4c51-99b9-7acc09755cff.png)

@LichKing-2234 I see this in console on Safari. No other browser shows this and everything works fine. I cannot see any other difference so thought will point this out.

Could not find anything concrete about the error; but hopefully the following will help:

1. I tried to see if there is anything specific to Safari developer options. Found the suggestion to enable `NSURLSession WebSocket` but it does not matter if this is enabled or disabled. I get the same error.
2. https://stackoverflow.com/a/66400537/3348386. It says should not have a port name. But why only Safari then?
3. Someone said TLS1.2 is required; but that's enabled on my system. It's an old story anyway.
4. The WebSocket subprotocols: is there anything around them here? Saw the list here https://www.iana.org/assignments/websocket/websocket.xml#subprotocol-name.

This is no longer a dev/flutter2 branch issue. I can see this with the latest flutter package.

**Comment by reeteshranjan** [comment]
@rgb1380 could you please edit the bug title to remove dev/flutter2? The bug is on main package now.

**Comment by reeteshranjan** [comment]
@LichKing-2234, any updates on this?

**Comment by mminhlequang** [comment]
xx

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.
