### ISSUE TITLE
Bringing up a 'calling' screen when the app is not running or running in the background.

### ISSUE THREAD

**Issue by lifehetu** [AgoraIO-Extensions/Agora-Flutter-SDK#412]
**Is your feature request related to a problem? Please describe.**
1. Users can join the same channel to join a video call.
2. In a running app, with push notifications and data messaging, a 'calling' screen can be brought up for a user to accept/reject a call.

But how do we notify a user that someone is calling when her app is not running or running in the background?

**Describe the solution you'd like**
With Agora flutter SDK, I would like to produce a 'calling' screen even when the app is not running or running in the background.

**Describe alternatives you've considered**
I am not sure about any alternative approach as of now. While I eagerly wait for this capability available to me out of the box from the Agora flutter SDK, I seek your help in helping me with some alternate approaches in achieving the same in Android and in iOS apps.

**Comment by LichKing-2234** [comment]
Use FCM+ConnectionService on Android and PushKit+CallKit on iOS.

**Comment by surveshoeb** [comment]
@lifehetu try [callkeep](https://pub.dev/packages/callkeep) it requires phone account permission to invoke the default calling screen of the device.
