### ISSUE TITLE
[dev/flutter2] Local view is broken on iOS (RtcLocalView.TextureView from example)

### ISSUE THREAD

**Issue by vlidholt** [AgoraIO-Extensions/Agora-Flutter-SDK#415]
**Describe the bug**
On iOS the local view doesn't work as expected. Testing the example from latest dev/flutter2 branch.
- On iPhone (running 14.7.1), the local view is unproportionally scaled and video remote streams do not show up.
- On iPad (running 13.5.1), the local view is incorrectly rotated. The transmitted video is correct though. Using the back camera causes the local view to disappear.

**Screenshots**
You get to see my happy face:

![IMG_3278](https://user-images.githubusercontent.com/1539812/132089932-2dea3f94-8327-4229-bc17-4e2c14e6641f.PNG)
![IMG_0022](https://user-images.githubusercontent.com/1539812/132089935-4410ec1c-51bb-44d2-91bc-ae7693bfed60.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 14.7.1
 - Version dev/flutter2

**Comment by LichKing-2234** [comment]
This is a known issue, you can keep using the `SurfaceView`.

**Comment by blopker** [comment]
FWIW, this seems to be fixed now.
