### ISSUE TITLE
cannot override 'release' which has been marked unavailable: not available in automatic reference counting mode

### ISSUE THREAD

**Issue by iBinbro** [AgoraIO-Extensions/Agora-Flutter-SDK#419]
**Describe the bug**
error: cannot override 'release' which has been marked unavailable: not available in automatic reference counting mode.

**To Reproduce**
1. agora_rtc_engine: ^4.1.0-alpha.2

**Screenshots**
![编译运行报错](https://user-images.githubusercontent.com/15324447/132439385-9e1fe696-5b03-4c97-816b-452a5013257b.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/15324447/132439578-5870c761-09c5-4a70-a376-8cb42d9bbe36.png)

我的flutter项目是默认的OC项目，在继承`agora_rtc_engine: ^4.1.0-alpha.2`后编译运行报错，release方法有问题，求解！
![如何解决](https://user-images.githubusercontent.com/15324447/132439690-327e3b70-056f-42ad-93d8-659910e56ed0.png)

**Comment by LichKing-2234** [comment]
您是需要macos么？4.1.0这个版本已经过时了，是为了支持desktop的，建议测试dev/flutter2分支
