### ISSUE TITLE
[dev/flutter2] RtcEngineEventHandler: rtcStats not Callback for flutter web

### ISSUE THREAD

**Issue by quangvinhvux** [AgoraIO-Extensions/Agora-Flutter-SDK#433]
**Describe the bug**
rtcStats not call back in every two seconds.
I already added event for rtcStats like this. 
_addListeners() {
    _engine.setEventHandler(RtcEngineEventHandler(
      rtcStats: (stats){
        log('rtcStats ${stats.duration}');
      },
      joinChannelSuccess: (channel, uid, elapsed) {
        log('joinChannelSuccess ${channel} ${uid} ${elapsed}');
        setState(() {
          isJoined = true;
        });
      }
 ));
  }
Thanks you for your help, I very appreciate your contribution

**Comment by LichKing-2234** [comment]
You can only get RtcStats in  the `LeaveChannel` event on Web.

**Comment by LichKing-2234** [comment]
Because the `RtcStats` event not support on Web.

**Comment by quangvinhvux** [comment]
> You can only get RtcStats in the `LeaveChannel` event on Web.

so do we have anyway to can get duration of the video call during the call ?

**Comment by LichKing-2234** [comment]
The best way is to use your server.

**Comment by quangvinhvux** [comment]
> The best way is to use your server.

I do not found any API to get statis of the call for server side. how can we do that ?
