### ISSUE TITLE
iOS App Audio after Agora VideoCall only on ear speaker

### ISSUE THREAD

**Issue by szuch** [AgoraIO-Extensions/Agora-Flutter-SDK#438]
**Bug Scenario**
1. My Flutter App on iOS is playing specific videos with audio over loud speaker. 
2. If an agora video call is made (incoming or outgoing) during that time, then this call is also on loud speaker
3. After ending the call the specific video is resumed. 
    **Problem: Now the Videos Audio is coming from the ear piece speaker and not the loud speak anymore, which is wrong.**
4. This is not happening on Android

**Expected behaviour**
After leaving the Agora call the in app audio should resume playing from the load speaker like before the call 

**Versions**
* Flutter 2.2.3
* latest agora_rtc_engine: ^4.0.7

**Smartphone**
 - Device: all iPhones
 - OS: 14.7

**Additional info**
* i already tried to call destroy or keep the agora engine after call but with both same behaviour
* i tried setDefaultAudioRoutetoSpeakerphone(true) and with false but error persists

**Comment by LichKing-2234** [comment]
you can refer to this doc
https://docs.agora.io/en/Video/set_audio_route_ios?platform=iOS

**Comment by szuch** [comment]
@LichKing-2234
Thanks. I know that part of the docs and im using 
_setDefaultAudioRouteToSpeakerphone_
and tried _setEnableSpeakerphone_
But the problem is **after finishing the call the other audio** of the app is still playing ducked. You can hear it but very silent.
After investigating the issue i found out that either the agora lib, but more likely the call kit lib are changing the AVAudioSession to their video call needs but after finishing the call these settings are not reset.
So i am doing this now manually with a MethodChannel call to iOS.

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
