### ISSUE TITLE
[Web][Screensharing] Stop sharing notification

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO-Extensions/Agora-Flutter-SDK#442]
After screen sharing the following window appears on the screen

<img width="464" alt="Screen Shot 2021-09-29 at 6 09 15 pm" src="https://user-images.githubusercontent.com/52327300/135229344-36f457c8-0692-4d2a-9ff2-677bc497001b.png">

Stopping screen sharing from this, does not result in graceful termination of screen sharing as the web app does not receive any notifications (the expected notification is leaveChannel) and therefore is unaware that screen sharing was stopped by the user.

**Comment by Muhammad-Ullah** [comment]
@rgb1380  if you have done the screensharing then please share the code

**Comment by rgb1380** [comment]
@Muhammad-Ullah see the examples folder in dev/flutter2. Look for screen_share.dart

**Comment by Muhammad-Ullah** [comment]
I am getting this error:
 PlatformException(ErrorCode.NotSuppported,null,null,null)

**Comment by Muhammad-Ullah** [comment]
@rgb1380 can you have a look at this issue?

**Comment by LichKing-2234** [comment]
@rgb1380 You can refer to the example to stop screen sharing.
