### ISSUE TITLE
Not publishing Media in flutter App

### ISSUE THREAD

**Issue by m4mehdi** [AgoraIO-Extensions/Agora-Flutter-SDK#447]
I've built the whole package with specific appId, channeId, token and all parameter which are required for running Basic videoCall. On the other hand I've run a web based video call. My web based video Call is running well and two participants can join the call. I've tried to join the meeting as a part of video call with flutter based app. The video of web part comes to App but the video of App does not go web part. The role is Broadcaster and there is no limitation for publishing video from App. I wonder how it is possible to receive the video from web part but not sending the video?

Flutter SDK:
Latest Version

OS:
Windows 10
Test on Samsung Note 5.0

**Comment by LichKing-2234** [comment]
have you tried our example?

**Comment by m4mehdi** [comment]
Hi Dear Arthas

Yes, I've used your example and I compiled that. Application runs and I can see other part video on App but my video on App does not go to other part which is on web. I used temporary token and Also, I've created token in server. Both time problem was the same.
I will appreciate your guidance.
BR
Mehdi
________________________________

**Comment by LichKing-2234** [comment]
does it solve your issue?
