### ISSUE TITLE
[Question] How do you properly use playEffect?

### ISSUE THREAD

**Issue by CodingAleCR** [AgoraIO-Extensions/Agora-Flutter-SDK#454]
I've been trying to make Agora play the sound effects that I've got but to no success. I've implemented in the same way as the Basic example on the repository and also following the suggestions at #181 but I have not been able to make it work. 

I'm trying to play sound effects while the user has the microphone on, I don't know if that is any issue or not.

The sounds seem to be getting the right path by using the `getAssetAbsolutePath` extension, I'm getting the event `audioEffectFinished` with the corresponding correct sound ids and there are no exceptions while calling `playEffect`.

Assets are all MP3 files, they work correctly with the `audioplayers` plugin. Here's how they are added to the `pubspec.yaml`:

First I tried: 
```
flutter:
  assets:
    - assets/audios/
```

Then I tried:

```
flutter:
  assets:
    - assets/audios/start.mp3
```

Devices used:

- iPhone 5S
- Simulator iPhone 12 Mini
- Simulator iPhone 12 Max

```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 months ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by LichKing-2234** [comment]
have you tried our example which named JoinChannelAudio?

**Comment by CodingAleCR** [comment]
Yes, that was the example I tried but to no luck.

**Comment by LichKing-2234** [comment]
Yes, it is expected behavior.

**Comment by CodingAleCR** [comment]
Just to clarify then, there is no way to use `playEffect` while the user is muted?

My use case is that I'm building a VoIP app that uses sound effects, but sometimes I need those sound effects to be played even when the user is muted. It'd be nice to have it all within agora and avoid different configuration settings for the audio session (which we have found does not play nice with `agora_rtc_engine` SDK.

**Comment by CodingAleCR** [comment]
Nevermind my misguided question. You *can* play audio while local audio is muted. My misconception came when I assumed that the example used the `muteLocalAudioStream`, but as it turns out, the example actually uses `enableLocalAudio` which is totally fine and makes complete sense to be required to use `playEffect`. Thank you for the quick replies!
