### ISSUE TITLE
AGORA ON FLUTTER 2 NOT WORKING

### ISSUE THREAD

**Issue by RalphLincoln** [AgoraIO-Extensions/Agora-Flutter-SDK#455]
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
W/System.err(21080): java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone1/temp: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
W/System.err(21080): java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
E/libc    (21080): Access denied finding property "net.dns1"
E/libc    (21080): Access denied finding property "net.dns2"
E/libc    (21080): Access denied finding property "net.dns3"
E/libc    (21080): Access denied finding property "net.dns4"
I/WifiManager(21080): WifiManager---->calculateSignalLevel---->rssi: -19  numLevels:5
W/GENP.0  (21080): type=1400 audit(0.0:6952): avc: denied { read } for name="temp" dev="sysfs" ino=7565 scontext=u:r:untrusted_app:s0:c155,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
W/System.err(21080): java.io.FileNotFoundException: /sys/class/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
W/System.err(21080): java.io.FileNotFoundException: /sys/class/thermal/thermal_zone1/temp: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
W/System.err(21080): java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone1/temp: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
W/System.err(21080): java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
E/libc    (21080): Access denied finding property "net.dns1"
E/libc    (21080): Access denied finding property "net.dns2"
E/libc    (21080): Access denied finding property "net.dns3"
E/libc    (21080): Access denied finding property "net.dns4"
I/WifiManager(21080): WifiManager---->calculateSignalLevel---->rssi: -19  numLevels:5
W/System.err(21080): java.io.FileNotFoundException: /sys/class/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/GENP.0  (21080): type=1400 audit(0.0:6956): avc: denied { read } for name="temp" dev="sysfs" ino=7565 scontext=u:r:untrusted_app:s0:c155,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
W/System.err(21080): java.io.FileNotFoundException: /sys/class/thermal/thermal_zone1/temp: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/GENP.0  (21080): type=1400 audit(0.0:6957): avc: denied { read } for name="temp" dev="sysfs" ino=7598 scontext=u:r:untrusted_app:s0:c155,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
W/GENP.0  (21080): type=1400 audit(0.0:6958): avc: denied { read } for name="temp" dev="sysfs" ino=7598 scontext=u:r:untrusted_app:s0:c155,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
W/GENP.0  (21080): type=1400 audit(0.0:6959): avc: denied { read } for name="temp" dev="sysfs" ino=7565 scontext=u:r:untrusted_app:s0:c155,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
W/System.err(21080): java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone1/temp: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
W/System.err(21080): java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(21080): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(21080): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(21080): 	at libcore.io.Linux.open(Native Method)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(21080): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(21080): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7500)
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(21080): 	... 3 more
E/libc    (21080): Access denied finding property "net.dns1"
E/libc    (21080): Access denied finding property "net.dns2"
E/libc    (21080): Access denied finding property "net.dns3"
E/libc    (21080): Access denied finding property "net.dns4"
I/WifiManager(21080): WifiManager---->calculateSignalLevel---->rssi: -19  numLevels:5
W/GENP.0  (21080): type=1400 audit(0.0:6960): avc: denied { read } for name="temp" dev="sysfs" ino=7565 scontext=u:r:untrusted_app:s0:c155,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
W/System.err(21080): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(21080): 	at java.io

**Comment by LichKing-2234** [comment]
the internal log, you can ignore it.

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
