### ISSUE TITLE
audioRouteChanged is not called on getting a call

### ISSUE THREAD

**Issue by shashikantdurge** [AgoraIO-Extensions/Agora-Flutter-SDK#456]
**Describe the bug**
Use-case:
User joins a Live broadcast channel with NO earphones connected, the audio route is SpeakerPhone
User gets a call in between, all audio streams are muted.
ISSUE => The audio route switches to earpiece, audioRouteChanged is not called.

**To Reproduce**
1. User A & B joins Live Broadcast channel as Broadcasters. No earphones connected.
2. Audio comes from SpeakerPhone for both users.
3. User A gets a phone call
4. User A disconnects the call
5. Now, The sound comes from earpiece rather than the SpeakerPhone for User A 

**Expected behavior**
Either switch back to the audio route what it was before getting call. (Recommended)
OR
Call the audioRouteChanged callback on changing it to earpiece. 

**Smartphone (please complete the following information):**
 - Device: [ OnePlus 3 Model: A3003]
 - OS: [ Android 9]
 - Version [ 22]

**Comment by LichKing-2234** [comment]
Have you tried the latest version?

**Comment by LichKing-2234** [comment]
https://pub.dev/packages/agora_rtc_engine/versions/4.2.0-rc.1

**Comment by littleGnAl** [comment]
If you still face this issue, please try upgrading to the latest version to see if it works or not.
