### ISSUE TITLE
 A problem occurred evaluating root project 'agora_rtc_engine'.

### ISSUE THREAD

**Issue by colarking** [AgoraIO-Extensions/Agora-Flutter-SDK#461]
**Describe the bug**
when i build apk for my app.
this plugin was error reported when building.
the log is follow this:
[ +403 ms] > Task :open_file:verifyReleaseResources
[        ] 1273 actionable tasks: 38 executed, 1235 up-to-date
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':keyboard_visibility:verifyReleaseResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > 1 exception was raised by workers:
[        ]      com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
[        ]      /Users/amaya/.gradle/caches/transforms-2/files-2.1/c3d2084802b5211df9c6a1255ff1a2c7/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.
[        ]      /Users/amaya/.gradle/caches/transforms-2/files-2.1/c3d2084802b5211df9c6a1255ff1a2c7/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 11m 0s
[ +422 ms] Running Gradle task 'assembleRelease'... (completed in 661.5s)
[   +1 ms] The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
[   +4 ms] Building plugin agora_rtc_engine...
[   +4 ms] Running Gradle task 'assembleAarRelease'...
[   +2 ms] Using gradle from /Users/amaya/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.0.7/android/gradlew.
[   +9 ms] executing: [/Users/amaya/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.0.7/android/] /Users/amaya/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.0.7/android/gradlew -I=/Users/amaya/fvm/versions/2.2.3/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/amaya/fvm/versions/2.2.3 -Poutput-dir=/Users/amaya/Workspace/yiren_client_1010/build/app -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true -Pdart-obfuscation=false -Ptrack-widget-creation=false -Ptree-shake-icons=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[ +744 ms] 
           FAILURE: Build failed with an exception.

           * Where:
           Build file '/Users/amaya/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.0.7/android/build.gradle' line: 29

           * What went wrong:
           A problem occurred evaluating root project 'agora_rtc_engine'.
           > Plugin with id 'com.android.library' not found.

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 585ms
[   +1 ms] Running Gradle task 'assembleAarRelease'... (completed in 757ms)

           * Where:
           Build file '/Users/amaya/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.0.7/android/build.gradle' line: 29

           * What went wrong:
           A problem occurred evaluating root project 'agora_rtc_engine'.
           > Plugin with id 'com.android.library' not found.

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 585ms

**Comment by colarking** [comment]
and i check the engne gradke file that apply plugin: 'com.android.library' 
is have exists in gradle file.
so what's wrong white this plugin,

**Comment by LichKing-2234** [comment]
pls make sure your gradle version and kotlin version is compatible

**Comment by muazharin** [comment]
@LichKing-2234 how can i make sure the gradle version and kotlin version are compatible?
what path i can find them?

**Comment by Jatin141** [comment]
Hello Team any update for this issue i am getting same issue

**Comment by Jatin141** [comment]
Hello Team when i am creating apk in andorid in flutter app getting this issue please check

ild file '/Users/jatinrana/Documents/Jatin Data/FlutterSDK/flutter_2_0_0/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-3.4.6/android/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating root project 'agora_rtc_engine'.
> Plugin with id 'com.android.library' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s


The plugin agora_rtc_engine could not be built due to the issue above.

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
