### ISSUE TITLE
Screen sharing on Firefox throws PlatformException

### ISSUE THREAD

**Issue by ratherNotB** [AgoraIO-Extensions/Agora-Flutter-SDK#462]
When attempting to screen share using Firefox with the example from:

https://github.com/AgoraIO/Agora-Flutter-SDK/blob/dev/flutter2/example/lib/examples/advanced/screen_sharing.dart

the following error is thrown:

Agora-SDK [ERROR]: [track-094e6182] 
AgoraRTCError DEVICE_NOT_FOUND: NotFoundError: 
The object can not be found here. AgoraRtcWrapper.bundle.js:2:174708

Uncaught Error: PlatformException(error, AgoraRTCError DEVICE_NOT_FOUND: NotFoundError: 
The object can not be found here., null, null)

**Comment by ratherNotB** [comment]
Yes, it is working perfectly on Chrome.

**Comment by LichKing-2234** [comment]
You can refer to this doc.
https://docs.agora.io/en/Video/web_sdk_compatibility?platform=Web
