### ISSUE TITLE
How to disable console log output from agora-iris

### ISSUE THREAD

**Issue by ratherNotB** [AgoraIO-Extensions/Agora-Flutter-SDK#463]
Is it possible to prevent agora-iris from writing to the browser console? For example to turn off the output of logging events such as the following? 

agora-iris network-quality 
Object { uplinkNetworkQuality: 1, downlinkNetworkQuality: 1 }
​
downlinkNetworkQuality: 1
​
uplinkNetworkQuality: 1
​
<prototype>: Object { … }

agora-iris _emitEvent NetworkQuality 
Object { uid: 0, txQuality: 1, rxQuality: 1 }
 
function s()

**Comment by LichKing-2234** [comment]
sure, I will optimize it next commit

**Comment by benyaminbeyzaie** [comment]
I have same issue with logs. They are too much and often useless

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.
