### ISSUE TITLE
Speaker doesn't work when 2 users are talking

### ISSUE THREAD

**Issue by sleith** [AgoraIO-Extensions/Agora-Flutter-SDK#466]
**Describe the bug**
I connect 2 users with both speakerphone is on. When i talk, i can't hear on the other side, sometimes can't hear at all, and sometimes the sound is very low. Until i disable the speakerphone then works normally.

**To Reproduce**
I test with https://github.com/AgoraIO/Agora-Flutter-SDK/tree/master/example
1. Join audio call by click 'JoinChannelAudio' and join button.
2. make sure speakerphone button is selected
3. do the same on the other device
4. Talk something, you can't hear the other one or volume is so low
5. Try disable one of the speakerphone, then it will work now

**Expected behaviour**
Speakerphone works on both sides 

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 9 and 11

**Comment by louisschprs** [comment]
I have also experienced something like this where switching the speakerphone to on or off could sometimes (Almost randomly) reduce the volume, I am not sure how to solve this though

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
