### ISSUE TITLE
stop call voice and video in forground

### ISSUE THREAD

**Issue by imanpr** [AgoraIO-Extensions/Agora-Flutter-SDK#467]
when app is open and is calling mode
evey thing is okay
but when i go to app forground mode  (app open but in cache mode) in call sound and video dont send to onother user

 is this case from flutter or agora?  and to fix that?
thanks

**Comment by LichKing-2234** [comment]
what do you mean about (app open but in cache mode)?

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
