### ISSUE TITLE
setBeautyEffectOptions not working

### ISSUE THREAD

**Issue by Benzt2h** [AgoraIO-Extensions/Agora-Flutter-SDK#469]
when use setBeautyEffectOptions true

flashing effect,It's like turning off, turning on the effect. 

this video my problem.
https://youtu.be/iPokqcKla4w

and ios not show effect on localview.

`
version agora_rtc_engine: ^4.0.7
`

```
await _engine.enableVideo();
    await _engine.setBeautyEffectOptions(
      true,
      BeautyOptions(
        lighteningContrastLevel: LighteningContrastLevel.Low,
        lighteningLevel: 1.0,
        rednessLevel: 0.0,
        smoothnessLevel: 1.0,
      ),
    );
```

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
