### ISSUE TITLE
Cant join channel

### ISSUE THREAD

**Issue by Samson11** [AgoraIO-Extensions/Agora-Flutter-SDK#479]
**Describe the bug**
When i join a channel with a temp token or token provided by my server

Despite having a valid token i get 
( 6350): Access denied finding property "net.dns1"

**Comment by DevKhalyd** [comment]
I had the same issue, sometimes is working fine but in other attempts just don't let join to the channels. It's a weird case. :(

**Comment by LichKing-2234** [comment]
you can get the error code from the Error event.

**Comment by DevKhalyd** [comment]
> you can get the error code from the Error event.

ErrorCode.JoinChannelRejected.
I've readed the docs about that enum. But is jut called one time. About the test I don't know what means. 😬

**Comment by LichKing-2234** [comment]
have you joined the channel already?

**Comment by LichKing-2234** [comment]
pls provide the sdk log.

**Comment by DevKhalyd** [comment]
Agora is working fine but sometimes that error occurs. Is weird. IDK. Let me do it again and if happens again I'll tell you. Thanks dude.

**Comment by devmfouad** [comment]
same issue with me
