### ISSUE TITLE
Flutter Agora - Is there any way to leave or end a broadcast stream when user kills the app from recent or discards app?

### ISSUE THREAD

**Issue by fldvlpr** [AgoraIO-Extensions/Agora-Flutter-SDK#486]
Hello @AgoraIO @ShengQiangLiu @yoreland @CLuCheng @LichKing-2234 ,

I was trying out agora flutter live streaming feature,

Everything seems to be working fine. But, there is now way to leave or end the stream or getting any callback to release the resources when a user removes or kills the app from recent apps.

Is there any way or agora team is able to manage this scenario anyway?

Thanks.

**Comment by LichKing-2234** [comment]
the resources will be released after app be killed.

**Comment by fldvlpr** [comment]
@LichKing-2234 still want to update some things from my side, then how can we manage it in flutter if possible?

**Comment by littleGnAl** [comment]
@fldvlpr 
On Android, there's no callback of "application be killed". 
On iOS, you can try implement the [applicationWillTerminate](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623111-applicationwillterminate) callback and notify to flutter side through [MethodChannel](https://api.flutter.dev/flutter/services/MethodChannel-class.html) to release the resources.

If you can determine the "application be killed" state according to the flutter [AppLifecycleState](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html), I think this answer is helpful for you.
https://stackoverflow.com/questions/52074265/flutter-detect-killing-off-the-app

**Comment by fldvlpr** [comment]
still not useful,

my usecase is there are multiple stream is ongoing and only admin will manage which stream will be viewed by viewers at any point.

So, let say at a time stream 1 and stream 2 are ongoing and admin has selected stream 2 as the live stream for viewers. In case if streamer 2 device user mistakenly kills the app then how we can notify other users about the change?

I want to call a socket event or api for that. Let me know for the possible solutions and approaches if you know any.

Thanks

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
