### ISSUE TITLE
Audio call dosent work from background service

### ISSUE THREAD

**Issue by Venkat19292** [AgoraIO-Extensions/Agora-Flutter-SDK#489]
I am using agora and ConnectionService of android to achieve VoIP calling app but when In the background I couldnt make voice call (even I join channel I cant listen any audio)

**Comment by LichKing-2234** [comment]
you should use foreground service if you want to keep calling in the background.

**Comment by nerdsarena** [comment]
we face the same issue in iOS
let me describe the current situation 
our app work as expected in all cases but we have this case when some one called from any android or iOS device 
to iOS device which not running the app in foreground mode both the caller device and the receiver not hear each other 
we are sure that microphone permission has given

any suggestions ?

**Comment by LichKing-2234** [comment]
try https://pub.dev/packages/callkeep?

**Comment by nerdsarena** [comment]
@LichKing-2234 thanks ... can you please refer any example who to use with agora SDK

**Comment by LichKing-2234** [comment]
just enable it, keep application alive in the background.
