### ISSUE TITLE
streamInjectedStatus api returns StartTimedout

### ISSUE THREAD

**Issue by silversquall** [AgoraIO-Extensions/Agora-Flutter-SDK#493]
I am trying to inject a stream into my channel using : https://docs.agora.io/en/Video/API%20Reference/flutter/v4.0.5/rtc_channel/RtcChannel/addInjectStreamUrl.html

Sometimes (not always), i get the callback called :  streamInjectedStatus: (String url, int uid, InjectStreamStatus status){},
with status = InjectStreamStatus.StartTimedout.

As i see in here the feature was planed to be descoped : https://docs.agora.io/en/Interactive%20Broadcast/inject_stream_apple?platform=iOS

Questions:
I'm wondering if i am doing something wrong or if the feature is just no more supported.
is this feature still supported ?
If yes then when do you plan to descope ?
if yes then will you replace it ?

thank you.

**Comment by LichKing-2234** [comment]
Could you pls provide the SDK log?

**Comment by silversquall** [comment]
[](url)

**Comment by silversquall** [comment]
@LichKing-2234 I made a mistake closing the issue, can you reopen it ?

**Comment by LichKing-2234** [comment]
@silversquall I mean the SDK log file, not log in the console.

**Comment by silversquall** [comment]
@LichKing-2234 do you mean to apply https://flutter.dev/docs/testing/code-debugging 
import 'dart:developer' as developer;
?

**Comment by LichKing-2234** [comment]
pls refer to the doc of `setLogFile` method.

**Comment by silversquall** [comment]
@LichKing-2234 you will find the file attached here
[agorasdk.log](https://github.com/AgoraIO/Agora-Flutter-SDK/files/7547413/agorasdk.log)
.

**Comment by LichKing-2234** [comment]
is this log about your issue? I can't get any useful info from it.

**Comment by silversquall** [comment]
@LichKing-2234 yes i called the streamInjectedStatus API and this is what i got.
At least can you tell if it is still supported or not ?

**Comment by LichKing-2234** [comment]
you can use resetful API.
https://docs.agora.io/en/Interactive%20Broadcast/inject_stream_restful_api?platform=RESTful

**Comment by silversquall** [comment]
@LichKing-2234 I do not see any API which helps inject a stream, can you clarify ?

**Comment by LichKing-2234** [comment]
Sorry, my mistake, the restful API is only for China now.

**Comment by silversquall** [comment]
So i will repeat the questions above 
As i see in here the feature was planed to be descoped : https://docs.agora.io/en/Interactive%20Broadcast/inject_stream_apple?platform=iOS

Questions:
I'm wondering if i am doing something wrong or if the feature is just no more supported.
is this feature still supported ?
If yes then when do you plan to descope ?
if yes then will you replace it with another API ?

Additionally, can you share a sample of usage of streamInjectedStatus API ?

**Comment by LichKing-2234** [comment]
You can refer to this doc.
https://docs-preprod.agora.io/en/Interactive%20Broadcast/inject_stream_restful_global?platform=All%20Platforms

**Comment by silversquall** [comment]
@LichKing-2234 that worked thanks.
Nevertheless i would recommand to clearly state in flutter doc that the API is no more supported.

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
