### ISSUE TITLE
Issue on Mobile Browser

### ISSUE THREAD

**Issue by ofmartinez** [AgoraIO-Extensions/Agora-Flutter-SDK#494]
**Describe the bug**

I am currently using flutter web. In the desktop browser, the streaming is working well. But In the mobile browser, the streaming is not showing.

**To Reproduce**
1. Start video streaming in the mobile browser
2. Start video streaming in the desktop browser
3. In the desktop browser, the video and audio coming from my mobile browser can be seen and heard in the desktop browser
4. But on the mobile side, the RtcLocalView and RtcRemoteView are displaying blank. no audio and video.

Thank you!

**Comment by LichKing-2234** [comment]
We do not test on mobile devices already. It is the next plan.

**Comment by ofmartinez** [comment]
> We do not test on mobile devices already. It is the next plan.

Hello @LichKing-2234 , when do you think you will make it work on a mobile browser? So we can assess if we will push thru on using agora or not. thank you so much!

**Comment by Ben-chedli** [comment]
Hi @LichKing-2234 , any updates about this issue ? We're facing the same problem with agora_rtc_engine: ^5.1.0, after deploying our web app video chat feature is working well with desktop web agora but not on mobile browser !

**Comment by Ben-chedli** [comment]
@LichKing-2234 , we're still waiting for a reply on this issue, agora still not working on a recent chrome mobile browser after deployment of the web app !

**Comment by fluttertests** [comment]
It works fine if  user uses the "desktop version" option in the mobile browsers. (I tried chrome safari). Fyi developer team.

**Comment by SittiphanSittisak** [comment]
Any update?
It is required for my app.
