### ISSUE TITLE
[FEATURE] change AudioOutputRoute

### ISSUE THREAD

**Issue by Faaatman** [AgoraIO-Extensions/Agora-Flutter-SDK#499]
**Is your feature request related to a problem? Please describe.**
Change AudioOutputRoute depending on what is available (ex. Bluetooth, EarPiece)

**Describe the solution you'd like**

- callback function that retrieves the available AudioOutput routes. (ex. `RtcEnginge.availableAudioOutputRoutes()`)

- function that chooses one of the available AudioOutput routes. 
(ex. `RtcEngine.setAudioOutputRoute(AudioOutputRouting.HeadsetBluetooth)`)

**Describe alternatives you've considered**
I can listen to `audioRouteChanged` but that doesn't solve the problem fully.

**Comment by LichKing-2234** [comment]
You can contact our developer support. It needs to be supported by the native layer first.

**Comment by Faaatman** [comment]
Oh ok!
Is there a way to get the **Current selected Audio Route** instead of waiting for the route to change?

**Comment by littleGnAl** [comment]
If you still face this issue, please try upgrading to the latest version to see if it works or not.
