### ISSUE TITLE
How to use  VirtualBackground when Live Streaming 

### ISSUE THREAD

**Issue by PongPloy2016** [AgoraIO-Extensions/Agora-Flutter-SDK#500]
How to use  set VirtualBackground when Live Streaming 

I use lean link : 

[](https://docs.agora.io/en/Video/API%20Reference/flutter/v4.0.7/agora_rtc_engine/RtcEngine/enableVirtualBackground.html)

and i custom in link becouse i want streaming to rtmp + key other 

[](https://tadaspetra.medium.com/live-streaming-to-multiple-platforms-with-multiple-users-ea59fef00ece)

@override
Future<void> enableVirtualBackground(
    bool enabled, VirtualBackgroundSource backgroundSource) {
  return _invokeMethod('enableVirtualBackground', {
    'enabled': enabled,
    'backgroundSource': backgroundSource.toJson(),
  });
}

i tryeing set method then  Call this method after enableVideo 

   VirtualBackgroundSource backgroundSource = VirtualBackgroundSource(
        color: Color.fromRGBO(38, 38, 38, 0.4),
        source: "/data/user/0/com.hollysoft.ar_live_ais/cache/file.jpg",
        backgroundSourceType: VirtualBackgroundSourceType.Img);

    await _engine.enableVirtualBackground(true, backgroundSource);

```


  Future<void> _initAgora() async {
    _engine = await RtcEngine.createWithConfig(RtcEngineConfig(appId));
    _client = await AgoraRtmClient.createInstance(appId);
    //AssetSetup
    await _engine.enableVideo();
    VirtualBackgroundSource backgroundSource = VirtualBackgroundSource(
        color: Color.fromRGBO(38, 38, 38, 0.4),
        source: "/data/user/0/com.hollysoft.ar_live_ais/cache/file.jpg",
        backgroundSourceType: VirtualBackgroundSourceType.Img);

    await _engine.enableVirtualBackground(true, backgroundSource);

    await _engine.startPreview();
    await _engine.muteLocalAudioStream(true);
    await _engine.muteLocalVideoStream(true);
    await _engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await _engine.setClientRole(ClientRole.Broadcaster);

    _joinChannel();
  }


  _joinChannel() async {
    if (defaultTargetPlatform == TargetPlatform.android) {
      await [Permission.microphone, Permission.camera].request();
    }
    await _engine.joinChannel(config.token, config.channelId, null, config.uid);
  }
```

<img width="1071" alt="Screen Shot 2564-11-23 at 01 47 57" src="https://user-images.githubusercontent.com/8625469/142918092-b7f03940-e373-4fb5-a511-16edef4d5b92.png">

and run bulid and the result turned out to be change color black background not show file set  , no color, no background, and wallpaper doesn't show.
but i not understant you write detail  because  you hot have example for  VirtualBackground in Live Streaming  
i not understant String? source How to use please example code 
Any advice please?

ask more

and more question if can try to get gif files and text, text or fonts can be dragged and drag files freely and if not, is there any one that can try to accept withCan Agora?

Please fully example for VirtualBackground when Live Streaming  

Thank you

**Comment by LichKing-2234** [comment]
it is working without VirtualBackgroundSource?

**Comment by PongPloy2016** [comment]
ok bro. thank you

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
