### ISSUE TITLE
Camera is upside down when on landscape on Iphone7 Plus

### ISSUE THREAD

**Issue by dganzella** [AgoraIO-Extensions/Agora-Flutter-SDK#517]
**Describe the bug**
Camera is upside down when on landscape on Iphone7 Plus

**To Reproduce**
Start  a session
Turn device into landscape

**Expected behavior**
Camera is not upside down

**Screenshots**
![image](https://user-images.githubusercontent.com/30127664/145087416-865d1925-3ee7-4f19-90ba-75afd19a399c.png)

**Smartphone (please complete the following information):**
iPhone7 Plus (iPhone9,2)

**Comment by dganzella** [comment]
![image](https://user-images.githubusercontent.com/30127664/145091058-86ebe544-87a3-4a7f-bbd0-f3d7faf9e8b9.png)

happens on example app too

**Comment by LichKing-2234** [comment]
is it working on other devices?

**Comment by mirrorlink** [comment]
@LichKing-2234 yes, its working on every device but this.

here is the log: https://pastebin.com/VvtuJYkk

I think something worth mentioning is that the REAR camera of this device is broken (completely broken, no image). But its the FRONT camera that is upside down.

INFO    (16: 6:43:480 |   28)  38507; RefreshCameraList: found 1 cameras
INFO    (16: 6:43:482 |    2)  38507; Camera 0: name Front Camera id com.apple.avfoundation.avcapturedevice.built-in_video:1
ERROR   (16: 6:43:482 |    0)  38507; captureIdFromIndex: failed to get device id for device 1
WARN    (16: 6:43:482 |    0)  38507; Camera index 1 is invalid! Use first camera com.apple.avfoundation.avcapturedevice.built-in_video:1 instead

Maybe this is confusing the code somehow?

We've testes it with other apps like google meets, but on google meets the orientation of the camera is fine. Its not upside down on google meets.

Some other details:

On the iphone 7 plus:

The camera is OK on portrait mode.
THe camera is NOT OK on any of the landscape modes. Its always perfectly inverted 180 degrees.

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
