### ISSUE TITLE
Range Exception for AudioVolumeIndication

### ISSUE THREAD

**Issue by tadaspetra** [AgoraIO-Extensions/Agora-Flutter-SDK#528]
**Describe the bug**
I get an exception for RangeError in the AudioVolumeIndication callback inside the agora SDK in `events.dart` because the List only has 2 things according to the docs (aka range 0-1) but in the SDK they look for List Element[2] which is the 3rd element.

**To Reproduce**
1. Running an app with Audio Indication enabled

**Expected behavior**
No exceptions should happen

**Screenshots**
![Screen Shot 2021-12-13 at 1 46 21 PM](https://user-images.githubusercontent.com/60107328/145877914-f851076f-8c9c-45c7-8af7-11052847d83a.png)

**Desktop (please complete the following information):**
 - Android and iOS

**Smartphone (please complete the following information):**
- Android Emulator and iOS15 iPhone 11 pro

**Additional context**
It is commented out in one of the branches within the repo, I wonder if that's related. https://github.com/AgoraIO/Agora-Flutter-SDK/blob/dev/flutter2-iris/lib/src/events.dart#L1314

**Comment by LichKing-2234** [comment]
which version of SDK you used?

**Comment by Akash-Manjhi** [comment]
@LichKing-2234  I am facing same issue when running for android, for web it working fine.
 I am using 
 agora_rtc_engine:
    git:
      url: https://github.com/AgoraIO/Agora-Flutter-SDK.git
      ref: dev/flutter2
      
What can be the reason? Do I need to add anything else, I have added     `await _engine.enableAudioVolumeIndication(200, 3, true);`
Please help its urgent.

**Comment by tadaspetra** [comment]
> which version of SDK you used?

This was on version 4.0.6. And that was the odd thing, is that I don't think this version supports flutter web, but there is a platform check for Web

**Comment by LichKing-2234** [comment]
if you just want android or ios, you should use the latest version on pub.dev

**Comment by Akash-Manjhi** [comment]
@LichKing-2234  Actually I wanted for android/ios and web as well. Can you please let me know which version is suitable as I have checked a lot there are only alpha versions which supports web but not working properly for web.
Thanks

**Comment by littleGnAl** [comment]
I think it's worth trying `agora_rtc_engine: 6.0.0`.
