### ISSUE TITLE
[Question] How do you use `playEffect` with downloaded audio files?

### ISSUE THREAD

**Issue by CodingAleCR** [AgoraIO-Extensions/Agora-Flutter-SDK#543]
Hi, I ran into an issue while trying to use `playEffect` with files downloaded to `path_provider`'s temporary directory. Is there a way to make it properly work? If so, where can I find an example?

This is the code I tried to make it work with:
```dart
    final tempDir = await getTemporaryDirectory();
    final soundFile = File('${tempDir.path}/sound-file.mp3');

    log('Is absolute ${soundFile.isAbsolute}');
    log(soundFile.absolute.path);
    log(soundFile.resolveSymbolicLinksSync());
    log(soundFile.path);

    await AgoraClient.instance.engine.playEffect(
      99,
      soundFile.path,
      0,
      1,
      1,
      100,
      false,
    );

```

**Comment by littleGnAl** [comment]
Hello @CodingAleCR, I think it's supported.

**Comment by littleGnAl** [comment]
I think you can make it work easily on `agora_rtc_engine: ^6.0.0` by using  MediaPlayer, please check https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/media_player/media_player.dart for reference.
