### ISSUE TITLE
[Question] Could we Live Streaming as Broadcaster from video/audio source files?

### ISSUE THREAD

**Issue by ThangD** [AgoraIO-Extensions/Agora-Flutter-SDK#545]
Hello, i have a feature live streaming from camera or other source from files. Could you please help how can i get this? Thanks so much.

**Comment by LichKing-2234** [comment]
Sorry for the late reply, You can refer to https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/example/android/app/src/main/kotlin/io/agora/agora_rtc_engine_example/custom_capture_audio/CustomCaptureAudioPlugin.kt and implement it on the native layer.

**Comment by babihutan** [comment]
I believe this is now possible with agora_rtc_engine 6.0.0-rc.2, is that right?

**Comment by babihutan** [comment]
Check this out:
https://docs.agora.io/en/interactive-live-streaming/develop/play-media/

**Comment by plutoless** [comment]
@babihutan yes play source media files is not possible directly with sdk apis.

**Comment by babihutan** [comment]
Thanks @plutoless, I've been eagerly watching and waiting for this feature for more than a year, going to hook up the new v6 api later this week.

**Comment by littleGnAl** [comment]
These features are available on `agora_rtc_engine: ^6.0.0`.
Push a camera stream, you can use `MediaEngine. pushVideoFrame `, check https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/push_video_frame/push_video_frame.dart for reference.

Push a video stream, you can use the MediaPlayer to handle this, check https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/media_player/media_player.dart for reference.
