### ISSUE TITLE
Don't know when user cancelled the browser screen sharing

### ISSUE THREAD

**Issue by tp** [AgoraIO-Extensions/Agora-Flutter-SDK#578]
**Describe the bug**
When we initiate a screen share in the browser, we can't detect when the user presses "Cancel".

Instead `startScreenCaptureByWindowId` stays in pending state forever and I also didn't see any event handler firing.

**To Reproduce**
Our application code is pretty much like the example here:

https://github.com/AgoraIO/Agora-Flutter-SDK/blob/dev/flutter2/example/lib/examples/advanced/screen_sharing.dart#L129

To reproduce, initiate the screensharing in the browser and then cancel (in the browser UI)

![image](https://user-images.githubusercontent.com/52437/152329060-0ddad7f9-f525-4e8a-baff-4dba12a89c33.png)

**Expected behavior**

Would be great to be able to find out when the user cancelled the screenshare in the browser (an exception from `startScreenCaptureByWindowId` would work just fine).

Our use-case is showing a loading spinner while the screen share is being set up, and I didn't see a way to make that disappear if the flow fails.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 97.0.4692.99 (Official Build) (arm64)

**Comment by LichKing-2234** [comment]
Sorry for the late reply, any error when you cancel the screen sharing?

**Comment by LichKing-2234** [comment]
Sorry for the late reply, any error when you cancel the screen sharing?

**Comment by Allamprabhu1058** [comment]
Hi, any luck with this issue? i am stuck with same issue

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.
