### ISSUE TITLE
Be able to know if user is speaking while muted.

### ISSUE THREAD

**Issue by mirrorlink** [AgoraIO-Extensions/Agora-Flutter-SDK#594]
**Is your feature request related to a problem? Please describe.**
I wanna provide a feedback if the user is speaking and doesnt notice he is muted.

![image](https://user-images.githubusercontent.com/58230638/154129120-50aa10a7-8332-4aaf-94d6-fabf0c3a36bb.png)

**Describe the solution you'd like**
An option to add to audioVolumeIndication to report local values even when muteLocalAudioStream is true. it makes sense, since the local audio is not disabled, only the sending of audio data.

**Describe alternatives you've considered**
I really do not want to capture the mic audio separately while in the middle of an agoraio call.

**Additional context**
pls

**Comment by LichKing-2234** [comment]
pls use enableLocalAudio instead of.

**Comment by mirrorlink** [comment]
> pls use enableLocalAudio instead of.

???

enableLocalAudio is already true.

**Comment by LichKing-2234** [comment]
is audioVolumeIndication working when muteLocalAudioStream is true?

**Comment by mirrorlink** [comment]
> audioVolumeIndication



> is audioVolumeIndication working when muteLocalAudioStream is true?

it isnt. thats exactly the issue.

I still wanna audioVolumeIndication to work when:

enableLocalAudio is already true and
muteLocalAudioStream is false

**Comment by littleGnAl** [comment]
If you still face this problem, please try upgrading the latest version of `agora_rtc_engine` to see if it works or not.
