### ISSUE TITLE
想咨询一个场景，多人视频通话，同时可以文字聊天、发图片，应该用Demo里的哪个场景来实现啊？

### ISSUE THREAD

**Issue by good-good-study** [AgoraIO-Extensions/Agora-Flutter-SDK#597]
想咨询一个场景，多人视频通话，同时可以文字聊天、发图片，应该用Demo里的哪个场景来实现啊？

**Comment by LichKing-2234** [comment]
Basic的Video demo即可，但是其他功能得单独开发

**Comment by good-good-study** [comment]
@LichKing-2234 
我在声网工单里提了问题，他们回复说，使用环信SDK来实现，声网SDK不可以吗？

**Comment by plutoless** [comment]
@good-good-study 可以考虑用RTM,但如果想要比较完整的IM功能建议还是考虑环信

**Comment by good-good-study** [comment]
想咨询下，声网flutter版本，单纯的发起和接听多人视频，app处于后台时，如何接听？
