### ISSUE TITLE
errorCode: 6 - The buffer size is insufficient to store the returned data

### ISSUE THREAD

**Issue by amandeepmunial** [AgoraIO-Extensions/Agora-Flutter-SDK#605]
Having intermittent video issues between iOS and Android on Flutter. Two users get connected in a room for video chat. One user is able to see the other, but not the other way around. The issue appears with one specific device but intermittently. Once it occurs, then it spreads like a bug...so many other users starts facing the issue when they move from one room to another.

Attached is the error log of one instance. Could someone help with - where to check the Buffer size, how to calculate the right size and how to increase it?

![89e47b1b-e670-4aca-8e18-ab6eba652a36](https://user-images.githubusercontent.com/66249050/155851104-a518f4ce-5479-4b96-8902-ffc2a95365f4.jpg)

**Comment by LichKing-2234** [comment]
is our example working?

**Comment by Faizulkarim** [comment]
I am facing the same issue for login to  Agora SDK

**Comment by ismayil1234** [comment]
does anybody found a  solution?
