### ISSUE TITLE
Current device(Android) is not emitting/ receiving onAudioVolumeIndicate and remoteAudioStateChanged events sent from it, but the second device is ?

### ISSUE THREAD

**Issue by Codesait** [AgoraIO-Extensions/Agora-Flutter-SDK#614]
**Describe the bug**

 Current Android device is not receiving onAudioVolumeIndicate and remoteAudioStateChanged events sent from it... probably other events too but i've not checked all, but other devices are getting the events ?
e.g
 -- when onAudioVolumeIndicate emits events, i never get my uid in the AudioVolumeInfo (speaker) from the device that is speaking.
 -- For remoteAudioStateChanged, current device which triggered mute doesn't get the event but it does for other devices in the channel.

i am currently using agora_rtc_engine: ^4.2.1

**Expected behavior**
I expect to receive event from RtcEngineEventHandler on every device/emulator even the device triggering the event.

**Smartphone:**
Device: Android
Version: version 11(real device) and android 12(emulator)

**Additional context**
Here are some snippets:

``` dart
Future<void> initializeAgora(
    RtcEngine engine, {
    bool? exists,
    bool? onStage,
    OngoingRoom? room,
    Function(ErrorCode code)? onError,
    Function(RtcStats stats)? onLeaveChannel,
    Function(List<AudioVolumeInfo> speakers, int totalVolume)?
        onAudioVolumeIndicate,
    Function(String channle, int uid, int elapsed)? joinChannelSuccess,
    Function(int uid, UserOfflineReason elapsed)? userOffline,
    Function(int uid, AudioRemoteState state, AudioRemoteStateReason reason,
            int elapse)?
        remoteAudioStateChanged,
  }) async {
    await _initAgoraRtcEngine(
      engine,
      exists: exists!,
      room: room,
      onStage: onStage!,
    );
    _addAgoraEventHandlers(engine,
        onError: onError,
        onAudionVolumeIndicate: onAudioVolumeIndicate,
        onLeaveChannel: onLeaveChannel,
        userOffline: userOffline,
        joinChannelSuccess: joinChannelSuccess,
        remoteAudioStateChanged: remoteAudioStateChanged);
  }

void _addAgoraEventHandlers(
    RtcEngine engine, {
    Function(ErrorCode code)? onError,
    Function(RtcStats stats)? onLeaveChannel,
    Function(List<AudioVolumeInfo> speakers, int totalVolume)?
        onAudionVolumeIndicate,
    Function(String channle, int uid, int elapsed)? joinChannelSuccess,
    Function(int uid, UserOfflineReason elapsed)? userOffline,
    Function(int uid, AudioRemoteState state, AudioRemoteStateReason reason,
            int elapse)?
        remoteAudioStateChanged,
  }) {
    engine.setEventHandler(RtcEngineEventHandler(
        error: onError,
        joinChannelSuccess: joinChannelSuccess,
        leaveChannel: onLeaveChannel,
        userOffline: userOffline,
        audioRouteChanged: (AudioOutputRouting audioOutputRouting) {
          log.i("audioOutputRouting " + audioOutputRouting.index.toString());
        },
        userJoined: (uid, elapsed) {
          log.i('userJoined: $uid');
        },
        audioVolumeIndication: onAudionVolumeIndicate,
        remoteAudioStateChanged: remoteAudioStateChanged,
        localAudioStateChanged: (AudioLocalState state, AudioLocalError e) {
          log.i('local audio state: $state');
        }));
  }
```

 Any work around for this ?

**Comment by LichKing-2234** [comment]
have you called enableAudioVolumeIndication?

**Comment by Codesait** [comment]
> have you called enableAudioVolumeIndication?

Yes i did

<img width="555" alt="Screenshot 2022-03-09 at 11 25 20 AM" src="https://user-images.githubusercontent.com/37216036/157423028-87c03c77-9fdc-4029-9ce2-9e35debff564.png">

**Comment by LichKing-2234** [comment]
could you pls double check your client role is broadcaster?

**Comment by Codesait** [comment]
> could you pls double check your client role is broadcaster?

Yes it is because i can be heard by room audience.

**Comment by EhisEA** [comment]
> could you pls double check your client role is broadcaster?

how does the audience know who is speaking?

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
