### ISSUE TITLE
Make custom_capture_audio as a standard flutter plugin 

### ISSUE THREAD

**Issue by littleGnAl** [AgoraIO-Extensions/Agora-Flutter-SDK#632]
Make custom_capture_audio standalone, to demonstrate how to implement `RtcEnginePlugin` as a standard flutter plugin

**Comment by littleGnAl** [comment]
see https://github.com/AgoraIO/Agora-Flutter-SDK/issues/615 also

**Comment by vakrolme** [comment]
@littleGnAl, the 6.0.0 branch doesn't support the old interface of `RtcEnginePluginRegistrant.register(customCaptureVideoPlugin)`. 

Could you please tell me how to port an existing plugin from 5.x.x to 6.x.x?

**Comment by littleGnAl** [comment]
@vakrolme Can you raise a new issue for your question?
