### ISSUE TITLE
Audio recording devices can't be changed on Web

### ISSUE THREAD

**Issue by rafaelortizzableh** [AgoraIO-Extensions/Agora-Flutter-SDK#637]
**The bug**
When using agora_rtc_engine on web, audio devices (input) are not being changed correctly. 

**To Reproduce**
Make sure you have an RTC engine initialized. The methods to be called in the following steps should be in RtcEngine.deviceManager. 

1. Call enumerateAudioRecordingDevices to get the list of available recording devices.
2. Call setAudioRecordingDevice with the id of the desired device.
3. Check that it has been changed calling getAudioRecordingDevice.
4. Error: Despite the right device id being shown as the current device, audio is being captured from the starting recording device.

**Expected behavior**
When the recording device is changed, audio should come from the selected recording device.

**Desktop**
 - MacOS 12.2.1 
 - Browser Chrome 99.0.4844.84 (Official Build) (arm64)
 - Version 5.0.1

**Additional context**
Issue happens on Web, using Chrome. Tested on agora_rtc_engine 5.01. 
-- Update 29/03/2022 - Tested the same behavior compiling for MacOS and was able to change devices without issues, so the scope of this issue seems to be for web only.

**Comment by tardisalbiazul** [comment]
@littleGnAl Hey, have you had a chance to look at this? 

Behavior seems inconsistent for audio playback devices too...

**Comment by littleGnAl** [comment]
Hello @tardisalbiazul, Sorry for so late response, it there any error log?

**Comment by tardisalbiazul** [comment]
No error log. After using setAudioRecordingDevice, once you call getAudioRecordingDevice, the current device corresponds with the one you just selected, but the actual result is inconsistent with this, basically the device is not updated. This is happening with Recording devices constantly, and with playback devices intermittently.

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.
