### ISSUE TITLE
Chrome "screensharing banner" stays active even after leaving the call

### ISSUE THREAD

**Issue by tp** [AgoraIO-Extensions/Agora-Flutter-SDK#643]
**Describe the bug**
While normal screensharing works great, there is a but in Agora and/or Chrome which keeps the screensharing banner alive after the user has switched the tab to share.

**To Reproduce**
1. Initiate screenshare
2. Share a specific tab
3. Switch to another tab in Chrome and click "Share this tab instead"
4. End call

**Expected behavior**

The screensharing banner should disappear.

**Screenshots**

What is shown before switching the screensharing tab:

![image](https://user-images.githubusercontent.com/52437/161517779-f6e83d97-7713-4808-9ae0-1d83b81c5692.png)

After the user has switched to that tab:

![image](https://user-images.githubusercontent.com/52437/161517840-1b82c4bc-b5f6-4e45-86b0-a9ad8fed6f3c.png)

Notification / banner still being shown for that "new tab", even after having left the call:

![image](https://user-images.githubusercontent.com/52437/161517884-4ece88b4-1895-4b3a-be31-cfe19e130a4d.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 99

**Comment by LichKing-2234** [comment]
have you call stopScreenSharing before leavechannel?

**Comment by tp** [comment]
@LichKing-2234 Yes, I tried to explicitly end the screenshare if active (via the helper) before ending the call, but that didn't change anything. This problem persisted.

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.
