### ISSUE TITLE
AddWaterMark png doesn't work

### ISSUE THREAD

**Issue by jmlarbaig** [AgoraIO-Extensions/Agora-Flutter-SDK#645]
Hi everyone, I tried until moment to add watermark on video. With assets, with the function "getAbsoluthPath("assets...")" and create image with screenshot widget package and implemente it into addWatermark() function but, nothing worked. 

Do you have some solutions please ? 

Also, in the futur, usually the watermark will be change in the same time of recording. Do you think that the new watermark will be take in account if I integrate function "addWatermark" inside periodic timer ?

**Comment by littleGnAl** [comment]
Sorry for the late response, do you set the `WatermarkOptions` for `addVideoWatermark` function?

**Comment by jmlarbaig** [comment]
Yes I set it, with positions and height / width

**Comment by littleGnAl** [comment]
Hello @jmlarbaig, can you show your code?

**Comment by jmlarbaig** [comment]
He @littleGnAl I'm sorry, I was buzy until now but I can answer,

So my code is that : 

  Future<void> handleTimeout() async {
    setState(() {
      _counter++;
    });
    print(_counter);
    print(directory);
    watermarkConfig.positionInLandscapeMode = Rectangle(
        x: (MediaQuery.of(context).size.width.toInt()) ~/ 2,
        y: (MediaQuery.of(context).size.height.toInt()) ~/ 2,
        width: MediaQuery.of(context).size.width.toInt(),
        height: MediaQuery.of(context).size.height.toInt());
    watermarkConfig.positionInPortraitMode = Rectangle(
        x: (MediaQuery.of(context).size.width.toInt()) ~/ 2,
        y: (MediaQuery.of(context).size.height.toInt()) ~/ 2,
        width: MediaQuery.of(context).size.width.toInt(),
        height: MediaQuery.of(context).size.height.toInt());
    try {
      setState(() {
        var path = _engine.getAssetAbsolutePath("images/test.png");
        print(path);
        _engine.addVideoWatermark(path, watermarkConfig);
      });
    } catch (event) {
      print("Error : $event");
    }

  }

**Comment by jmlarbaig** [comment]
This handleTimeOut function is called at the begging of the main code. My aim is to change the picture every second but for the moment, I just want to stream with only one

**Comment by littleGnAl** [comment]
Hello @jmlarbaig, can you try add `await` before `_engine.getAssetAbsolutePath("images/test.png")` and `_engine.addVideoWatermark(path, watermarkConfig)`

**Comment by jmlarbaig** [comment]
I alreeady try to add it but nothing change, the path is ok, png also, visibleInpreview is turn on on True and startPreview too

**Comment by fabio-o0** [comment]
@jmlarbaig hey, running into the same issue. Did you ever get the watermark to show up?

**Comment by jmlarbaig** [comment]
Hey Fabio,

I have search a lot and I didn't find solution. I went to other solution

**Comment by fabio-o0** [comment]
@jmlarbaig what solution did you end up going with?

**Comment by jmlarbaig** [comment]
I used this package : 

https://pub.dev/packages/haishin_kit

**Comment by fabio-o0** [comment]
@jmlarbaig got you, I will look into it. Thanks for the quick responses btw. Did you still use agora for the videocall, just connected to the stream using haishin?

**Comment by jmlarbaig** [comment]
It depend of what you want, just streming something or if you want to do B2B

**Comment by littleGnAl** [comment]
If you still face this issue, please try upgrading to the latest version to see if it works or not.
