### ISSUE TITLE
Bluetooth and Samsung Audio issues on Packages > v4.0.7

### ISSUE THREAD

**Issue by fareesh** [AgoraIO-Extensions/Agora-Flutter-SDK#653]
We seem to be stuck with the 4.0.7 version and and unable to upgrade because of two issues.

One is a known issue i.e. https://github.com/AgoraIO/Agora-Flutter-SDK/issues/434

The other appears to reliably occur in newer Samsung phones, particularly the S21 and S22 Ultra - where the speaker's volume is incredibly low and inaudible to others. Even if we boost the recording volume to 400, this does not seem to have much of an effect.

Both the aforementioned issues appear to be fine on the 4.0.7 SDK because our core functionality - i.e. audio works well on this version.

Since the newer versions of the Flutter SDK address features unrelated to voice calls, we are sticking with 4.0.7 but  I am concerned that at some point we will lose compatibility and critical bug fixes as OS versions are updated.

Is the team aware of the Samsung issue, and is there any ETA or known fix that we can undertake to resolve either of them?

Is there anything that we can do to contribute fixes to either of these issues?

**Comment by littleGnAl** [comment]
Thanks for reporting, I have reported this issue internally, but still waiting to investigate, I will feedback here if there's any update.

**Comment by littleGnAl** [comment]
> Even if we boost the recording volume to 400, this does not seem to have much of an effect.

Hello @fareesh, can you share what API or the code you call for this implementation?

**Comment by fareesh** [comment]
adjustRecordingSignalVolume(400)

**Comment by OmarHamed553** [comment]
Hello is there any solution for this issue so far i've been getting a lot of reports from users on samsung phones they're all using 6.2.0 agora_rtc_engine version and experiencing low volume issues and if the user switched off the bluetooth on the phone then it's finr otherwise they'll experience the issue ...

**Comment by littleGnAl** [comment]
@OmarHamed553 
I think it's better to raise a ticket to Agora support for further investigation.
