### ISSUE TITLE
热重启或热加载 RtcEngineEventHandler 无效

### ISSUE THREAD

**Issue by kids-return** [AgoraIO-Extensions/Agora-Flutter-SDK#657]
必须停止再重启启动才能生效，修改代码后就不再生效，不知道是哪里的问题，是不是不支持呀。
开发起来好难受

使用的事例代码 https://docs.agora.io/cn/Interactive%20Broadcast/start_live_flutter?platform=Flutter

**Comment by littleGnAl** [comment]
Hello @kids-return , which version of `agora_rtc_engine` do you use?

**Comment by littleGnAl** [comment]
If you still face issues, please try upgrading to the new version to see if it works for you.
