### ISSUE TITLE
Macos - video is flicker during joining channel

### ISSUE THREAD

**Issue by ThangD** [AgoraIO-Extensions/Agora-Flutter-SDK#665]
**Describe the bug**
Run the example on macos, video is flickering as the attachement

**To Reproduce**
1. Run example on MACOS
2. Run JoinChannelVideo
3. Other user join the channel
4. Watch the video

**Expected behavior**
Video is NOT flicker

**Desktop (please complete the following information):**
 - OS: Macos

**Additional context**

https://user-images.githubusercontent.com/7744981/165435531-174aaf56-dc97-41b0-82bd-bcbf1a37c69b.mp4

This is not happens with Window.

**Comment by littleGnAl** [comment]
@ThangD Thanks for reporting, this issue is related to flutter sdk macos support, we are still investigating how to fix it.

**Comment by rennylangat** [comment]
I had the same issue. When joining from the emulator on a Mac both android and iphone Emulators sort of flicker for a few seconds then there is a noticeable lag in the response from the android emulator even though both broadcaster and audience are on the same network

**Comment by steveseow** [comment]
Have the described issue here on a 2017 MBP, but not on a 2021 MBP. Both with Intel.

**Comment by ThangD** [comment]
@littleGnAl Could you please hep to look into this issue? It's raised for a long time, it is effected for us to release the MACOS build. Thank you.

**Comment by littleGnAl** [comment]
This should be fixed in https://pub.dev/packages/agora_rtc_engine/versions/6.0.0-rc.1, maybe it's worth to try.
