### ISSUE TITLE
getSdkVersion is not set as a static method

### ISSUE THREAD

**Issue by maxxfrazer** [AgoraIO-Extensions/Agora-Flutter-SDK#671]
**Describe the bug**
Getting engine version is not a static method. 
Cannot call `RtcEngine.getSdkVersion()` for example, because the method is not set as static.

> Version: 5.1.0

**To Reproduce**
Attempt to call `RtcEngine.getSdkVersion()`, it can only be called on an instance of the engine.

**Expected behavior**
I would expect to be able to call RtcEngine.getSdkVersion(), in the same way as I can call `AgoraRtmClient.getSdkVersion()`

**Screenshots**

<img width="532" alt="Screenshot 2022-04-29 at 17 07 48" src="https://user-images.githubusercontent.com/5754073/165982375-38c21481-7d02-4ad1-badb-cb802dd702e2.png">

**Comment by littleGnAl** [comment]
Hello @maxxfrazer , this is a breaking change since 5.0.0
https://docs.agora.io/en/Video/release_flutter_video?platform=Flutter#v500-native-352

**Comment by maxxfrazer** [comment]
@littleGnAl thanks for the link!
Could you help me understand why this change was made? As it's different from the native platform and Flutter RTM behaviour.

**Comment by littleGnAl** [comment]
@maxxfrazer This is caused by the limitation of the current implementation.
