### ISSUE TITLE
Flutter / Bluetooth microphone not working (Android only)

### ISSUE THREAD

**Issue by sebklose** [AgoraIO-Extensions/Agora-Flutter-SDK#672]
**Describe the bug**
We have 1:many event with video and audio - one person can have video and speak, the participants can see and hear the person.
If the trainer is having a bluetooth headset on - the sound is not transmitted (seems microphone of BT device not used)

**Expected behavior**
Any bluetooth headset connected can be used for audio microphone

**Screenshots**
no

**Smartphone (please complete the following information):**
- using version 5.0.0
- permissions are granted to use BT
- Android

**Additional context**
```
<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
<uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>

```

**Comment by littleGnAl** [comment]
Related https://github.com/AgoraIO/Agora-Flutter-SDK/issues/434

**Comment by littleGnAl** [comment]
Can you check if the audio option is on or off in the configuration or not?
There's maybe something configuration on your connected BT device page like below.
<img width="314" alt="image" src="https://user-images.githubusercontent.com/8847263/183241457-b2c02d37-ee4b-4723-b378-6419e7c51d53.png">
