### ISSUE TITLE
Firefox can show video from mobile app rotated 90 degrees

### ISSUE THREAD

**Issue by blopker** [AgoraIO-Extensions/Agora-Flutter-SDK#675]
**Describe the bug**
The issue is when Firefox is rendering video captured from a mobile app. The video may be in the incorrect orientation. When the same video is viewed on Chrome, however, the orientation is correct. 

The page at https://docs.agora.io/en/Video/web_sdk_known_issues?platform=Web says this is potentially a known issue with the web SDK, but maybe it's a different issue with Flutter? "When the Web SDK on Firefox communicates with the SDK on some devices, the video on Firefox is rotated."

Is there a workaround at least? This seems like a major issue that makes the browser experience unusable, at least with Firefox?

**To Reproduce**
1. Use the demo app to connect clients using a mobile app (I used Android, but I think iPhone has the same issue) and Firefox on desktop.
2. See that Firefox will not change the mobile app's video orientation when the phone switches from portrait to landscape.

**Expected behavior**
I'd expect Firefox to rotate the video so that the person's face is in the correct orientation. 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 99.0.1

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android
 - Browser: N/A
 - Version: 12

Thank you!

**Comment by littleGnAl** [comment]
I had reported this issue internally, still waiting for the response.

**Comment by blopker** [comment]
Thank you @littleGnAl, I appreciate the update.

**Comment by blopker** [comment]
Bump. Any update on this?

**Comment by littleGnAl** [comment]
@blopker 
Sorry for the late response, you can set the `VideoOutputOrientationMode` to `VideoOutputOrientationMode.FixedPortrait` for a workaround at this time.
```dart
    VideoEncoderConfiguration config = VideoEncoderConfiguration(
      ...
      orientationMode: VideoOutputOrientationMode.FixedPortrait,
    );
    await _engine.setVideoEncoderConfiguration(config);
```

**Comment by blopker** [comment]
Thanks, we'll give it a try. Is this something the Agora SDK will do automatically in the future?

**Comment by bsabhi** [comment]
using the WEB SDK, I don't see any workaround to this issue/limitation expect from manually rotating the container.
In my case the web SDK communicates with IOS, does this mean IOS SDK should specify orientationMode?
@blopker could you update us with your findings? thanks!

**Comment by littleGnAl** [comment]
@bsabhi 
This should be set on the native side, say that set it on iOS in your case.

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.
