### ISSUE TITLE
Various Video Call web bugs

### ISSUE THREAD

**Issue by mikemilla** [AgoraIO-Extensions/Agora-Flutter-SDK#689]
**Describe the bug**
1. Safari, iOS 15.4.1 (iPhone 13 Pro) — Local and Remote videos do not render (Video does broadcast and can be seen by other participants)
2. Chrome 101.0.4952.61, Android 12 (Pixel 3A) — Same issue as 1
3. Safari 14.0.2, MacOS 11.1 (Macbook Pro 2014) — Video freezes after a few seconds (Could be related to old browser version)

**To Reproduce**
Join a video call via the mobile browser with the targets above

**Expected behavior**
Video rendering smoothly on the local device(s)

**Screenshots**
Chrome Mac Screenshot - Works properly with no issues <img width="213" alt="Screen Shot 2022-05-25 at 12 00 19 AM" src="https://user-images.githubusercontent.com/6370613/170177482-586e6b20-a355-4d56-9171-32836269e4ec.png">

Safari iOS Screenshot - No rendered previews <img width="213" alt="Screen Shot 2022-05-25 at 12 00 19 AM" src="https://user-images.githubusercontent.com/6370613/170177614-3908f8da-92cf-483c-8e37-d2f58408d23c.jpg">

**Additional context**
Current sdk being used is `agora_rtc_engine: ^5.2.0`

**Comment by fluttertests** [comment]
same here.

**Comment by blopker** [comment]
I'm having the same issue as well. No mobile devices see to be able to show video on Flutter web. The same code running in Chrome and Safari on desktop work fine. Mobile devices are transmitting video to desktop, just the mobile devices do not show any local or remote video.

**Comment by blopker** [comment]
I can replicate this with the example app in this repo:

1. In the example app folder, run `flutter run -d chrome`
2. Note the port in which the app launches
3. Run `export PORT=60878 && adb reverse tcp:$PORT tcp:$PORT` with the noted port for PORT
4. Follow the instructions here: https://developer.chrome.com/docs/devtools/remote-debugging/ to debug Chrome on android
5. On the Android device, go to localhost:$PORT. This should load the app and allow the computer to get log data.

**Comment by blopker** [comment]
Any dev thoughts on this? Mobile web seems so close to working.

**Comment by hmbenhaim** [comment]
also for me working on chrome on mac, not working on chrome and firefox on android

**Comment by mikemilla** [comment]
Here is an update on what I've tried (cc: @blopker)

- My hunch is that the AgoraRtcWrapper.bundle.js may not be configured correctly. Old examples of the flutter web library include a script tag in the index.html file. I cloned the repo, built the new file, installed it manually, and experienced the same issue. I also tried to find and older bundle js, and found the same problem. I created an issue in Iris repo (https://github.com/AgoraIO-Community/Iris-Rtc-Web/issues/1)

- I downloaded a web sdk example and tried it in safari mac and it worked well. Maybe the pipeline from the web SDK to the wrapper SDK isn't up to date?

- I currently have a ticket open with support about this issue. Will update here when I get a response. I would imagine Agora would like this to work as I am very confident Agora is the most popular p2p video library for Flutter in the world.

**Comment by mminhlequang** [comment]
any update?

**Comment by NamHofstadter** [comment]
any update?

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.

**Comment by oexza** [comment]
There is no documentation on how to use it @littleGnAl 

> The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.

**Comment by littleGnAl** [comment]
@oexza 
Add the main branch as git package:
```
agora_rtc_engine:
  git:
    url: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK.git
    ref: main
```

Then follow the integration guide https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK?tab=readme-ov-file#web-alpha
