### ISSUE TITLE
Mobile heat so much due to agora and switchh off

### ISSUE THREAD

**Issue by user97116** [AgoraIO-Extensions/Agora-Flutter-SDK#705]
I am using latest version of agora and flutter but still same overheating issues

**Comment by plutoless** [comment]
which device you are using? media encoding/decoding naturally cost more than normal mobile activities. the heat could be affected by various reasons: e.g. video resolution, device capabilities etc.

**Comment by user97116** [comment]
my device is decent I playend decent games with no heat issues. in agora I am facing heat issues sometimes when I am streaming 480p video resolution...inject stream to youtube or facebook with in build agora recording. this heat so much I see device warning temp. is too high and sometimes device off.

**Comment by littleGnAl** [comment]
I think it's better to submit a ticket to agora support to investigate this issue.
