### ISSUE TITLE
[iOS] Event handlers are not called after hot restart

### ISSUE THREAD

**Issue by AndriiVivcharenko** [AgoraIO-Extensions/Agora-Flutter-SDK#715]
**Describe the bug**
Whenever I do a hot restart and then join any channel it stops handling events (joinChannelSuccess, userJoined etc). I Didn't pay much attention to this before until I got the same behavior in the release build uploaded to testflight. I don't know when exactly it happens in the release build, but it didn't work for hours and then started working again in the same build.
I created an isolated example in [a separate repo](https://github.com/AndriiVivcharenko/agora_test). Tried it with both temp token / generated access token.

**To Reproduce**
1. Start the example and click the "join channel" button on two phones
2. Leave the channel on the second phone
3. Do a hot restart
4. Join the channel again and see that the first one sees joined user, but on the second phone doesn't handle events, and _joined is not true because joinChannelSuccess wasn't called. 

**Smartphone:**
 - Device: iPhone 8 Plus, iPhohe X
 - OS: 15.5, 15.3.1
 - Version 5.2.0

**Additional context**
Logs from the phone where events were not called. I removed my appid and token from the iris log file
[agora-iris.log](https://github.com/AgoraIO/Agora-Flutter-SDK/files/9083221/agora-iris.log)
[agorasdk.log](https://github.com/AgoraIO/Agora-Flutter-SDK/files/9083224/agorasdk.log)

**Comment by littleGnAl** [comment]
Thanks for the report, we will investigate and fix it.

**Comment by Aanu1995** [comment]
I experiencing the same issue

**Comment by yuki384** [comment]
I am getting the same issue.

**Comment by mdusaama0** [comment]
> Thanks for the report, we will investigate and fix it.

did you fix it?

**Comment by littleGnAl** [comment]
This fix has landed the `main` branch.
