### ISSUE TITLE
Web - Local preview not show if NOT joined channel

### ISSUE THREAD

**Issue by ThangD** [AgoraIO-Extensions/Agora-Flutter-SDK#724]
Describe the bug
Run the example on web, run "JoinChannelVideo", preview of local is NOT show if not joined channel

To Reproduce

1.Run example on Web
2.Run JoinChannelVideo
3. Local video preview not show
4. Click Join channel
5. Local video preview is working

Additional context: Working on the desktop

**Comment by passsionforprogramming** [comment]
I have also seen this issue as well for Flutter Web. bump

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.
