### ISSUE TITLE
Window build - agora-iris.log error with permission denied

### ISSUE THREAD

**Issue by ThangD** [AgoraIO-Extensions/Agora-Flutter-SDK#725]
**Describe the bug**
Permission denied of logging when build the installer of window

**To Reproduce**
1. Create window build with: flutter pub run msix:create
2. Installing the build on window
3. The error of permission denied as image attached
![image](https://user-images.githubusercontent.com/7744981/180915140-a9655d6b-e26c-46ca-8e6b-1ef91d79669b.png)

**Comment by littleGnAl** [comment]
Thanks for reporting, may I ask is it causing crashes?

**Comment by ThangD** [comment]
Yes, it it crashing with the logs above.

**Comment by ThangD** [comment]
@littleGnAl Could you please help to look into this issue soon, i am still waiting for releasing the window app. Thank you so much.

**Comment by littleGnAl** [comment]
I am so sorry that I have no experience publishing the Windows app, but I just wonder why the `AgoraRtcScreenSharing.exe` has been executed directly.

**Comment by ThangD** [comment]
@littleGnAl The error occurs because we do NOT have permission for iris-logger on the WorkSpace folder when installing. Could we change this logs to others path? Thank you.

**Comment by ThangD** [comment]
@littleGnAl Could you pls help on this one?

**Comment by littleGnAl** [comment]
Sorry for the late response, we are working on this fix.

**Comment by littleGnAl** [comment]
After a little dig into the `msix` package, the `AppxManifest.xml` file will be created by default, and the `Executable` value will be set the first `.exe` file name https://github.com/YehudaKremer/msix/blob/f003af4ead7f536259a44985232412d45ce37714/lib/src/configuration.dart#L250, it will be set to `AgoraRtcScreenSharing.exe` in this case. 

So if you are not using the screen sharing feature, you can chagne the `Executable` value to the actual `.exe` file name should be worked for this case.
<img width="787" alt="image" src="https://user-images.githubusercontent.com/8847263/188124672-a7d2827b-6faf-4aa3-9114-dc1f19d5c2ba.png">

and maybe this link is helpful
https://github.com/YehudaKremer/msix/issues/120

**Comment by ThangD** [comment]
@littleGnAl Thank so much for your information, the app is using the Share Screen feature.

**Comment by littleGnAl** [comment]
This should be fixed on `agora_rtc_engine: ^6.0.0`.
