### ISSUE TITLE
App sandbox issue when trying to upload the app build to app store connect

### ISSUE THREAD

**Issue by Saikrishnamasetti** [AgoraIO-Extensions/Agora-Flutter-SDK#726]
![Screenshot 2022-07-26 at 11 33 46 AM](https://user-images.githubusercontent.com/64223594/180934768-61e8a392-ea2f-4c60-b933-39053c1ac74b.png)

I am using [agora_rtc_engine](https://pub.dev/packages/agora_rtc_engine) flutter package and trying to upload my app to app store connect and facing this issue.

**Comment by littleGnAl** [comment]
You should enable the App Sandbox in your project if you need to distribute your APP to Mac App Store
https://developer.apple.com/documentation/security/app_sandbox?language=objc

**Comment by Saikrishnamasetti** [comment]
Yes, I have done that in both DebugProfile.entitlements and Release.entitlements files.

**Comment by littleGnAl** [comment]
Is it works or not?

**Comment by Saikrishnamasetti** [comment]
No, If I remove the package it is working but not with the package. How can I fix this?

**Comment by imariman** [comment]
Same issue, any solutions for this?

**Comment by imariman** [comment]
Still waiting for this to publish my macos app. :/

**Comment by ThangD** [comment]
Same issue here, also waiting for publishing to macos app.

**Comment by littleGnAl** [comment]
By following the guide https://developer.apple.com/documentation/xcode/embedding-a-helper-tool-in-a-sandboxed-app?language=objc, maybe you can try the steps below but without testing:
1. Go to `AgoraRtcWrapper.framework/Resources` path
```
cd /The/path/to/your/flutter/project/macos/Pods/AgoraIrisRTC_macOS/AgoraRtcWrapper.framework/Resources
```

2. Create an entitlements file
```
/usr/libexec/PlistBuddy -c "Add :com.apple.security.app-sandbox bool true" "AgoraRtcScreenSharing.entitlements"
/usr/libexec/PlistBuddy -c "Add :com.apple.security.inherit bool true" AgoraRtcScreenSharing.entitlements
```
3. Sign the `AgoraRtcScreenSharing`
```
codesign -s - -i io.agora.iris.rtc.screensharing -o runtime --entitlements AgoraRtcScreenSharing.entitlements -f AgoraRtcScreenSharing
```
4. Then try to rebuild your APP see if works or not.

But for the disclaimer, I didn't test these steps cause my personal development account can't publish the APP to the APP store, so I can't verify twhether he steps work or not. And this is just a temporary solution.

**Comment by littleGnAl** [comment]
I try to build our example and upload it to the Mac App Store, it failed with the `AgoraRtcScreenSharing` not signed error, run the following command to sign the `AgoraRtcScreenSharing`:
```
codesign -o runtime -f -v --timestamp --deep -s "YOUR CODE_SIGN_IDENTITY" /Users/workspace/Agora-Flutter-SDK/example/macos/Pods/AgoraIrisRTC_macOS/AgoraRtcWrapper.framework/Resources/AgoraRtcScreenSharing
```
Then process the archive follow, it works fine for the example.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/8847263/188827544-98b874b0-dc38-48c8-b9ec-d5b067341edf.png">

I'm not very sure if there are any configs missing in your's project.

**Comment by ThangD** [comment]
@littleGnAl Confirm it working, i can push the macos app to Testflight now. Thank you.
