### ISSUE TITLE
Incorrect Audio Info Duration

### ISSUE THREAD

**Issue by nizwar** [AgoraIO-Extensions/Agora-Flutter-SDK#728]
**Describe the bug**
Once user load music more than 1 hours, requestAudioFileInfo return incorrect durationMS, for example on this image i load 3 hours music, but once i parse it, it only produce 18:23 (18 minutes 23 sec) output of duration MS : 1103818, the correct one was 3:52:55 (3 hours, 52 minutes, 55 sec)

**Expected behavior**
Correct duration of file info

**Screenshots**
Info loaded on File
![IMG_3004](https://user-images.githubusercontent.com/33113137/181230100-c080c5e5-8e4c-4773-a2c8-2fee30f1362b.jpeg)

Info loaded with Agora
![IMG_3003](https://user-images.githubusercontent.com/33113137/181230136-db6a7b91-b372-43b2-b21c-4327f7513226.jpeg)

Note : Those screenshots was same file

**Comment by littleGnAl** [comment]
Thanks for reporting.

**Comment by littleGnAl** [comment]
It's worth trying `agora_rtc_engine: ^6.1.0`
