### ISSUE TITLE
Flutter mobile web video issues

### ISSUE THREAD

**Issue by mikemilla** [AgoraIO-Extensions/Agora-Flutter-SDK#735]
Still experiencing video issues on Flutter Web.

Video issues on:
- Mobile Safari
- Mobile Android
- Mac Safari

Chrome Mac does work.

**Comment by mikemilla** [comment]
I'm trying to debug this as well and can't seem to find a solid way to test this. What is your development flow for testing flutter web?

**Comment by mikemilla** [comment]
Is something going on with this library? https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/assets/AgoraRtcWrapper.bundle.js

Mac Safari is likely the easiest to test this one for dev cycles and I am unable to get this bundle working.

**Comment by mikemilla** [comment]
Original post: https://github.com/AgoraIO/Agora-Flutter-SDK/issues/689

Please remove this if this issue is no longer needed.

**Comment by ThangD** [comment]
Same issue here.

**Comment by fisforfaheem** [comment]
same issue but no one is replying

**Comment by littleGnAl** [comment]
The web version is still in alpha and does not support mobile web at this time.

**Comment by spicylola** [comment]
I have same issue as well

**Comment by chukovskid** [comment]
I also have the same issue, how can we help you to improve this?

**Comment by fisforfaheem** [comment]
Update the flutter package and improve performance of video and audio

**Comment by Tpow99** [comment]
> The web version is still in alpha and does not support mobile web at this time.

Is there an active timeline on the mobile web support?

**Comment by fisforfaheem** [comment]
Please AGORA team reply...  Also update version 4/5 of agora for flutter
cant shift to version 6



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/12/22,
00:40:48

**Comment by mminhlequang** [comment]
any update?

**Comment by Statyk7** [comment]
I'm looking at a video call option for Flutter and Agora seems promising, but I need web support, is there a way around the limitation of this package not supporting web anymore? Use the Agora Web SDK in a Flutter WebView control?

**Comment by mminhlequang** [comment]
hzz

**Comment by fisforfaheem** [comment]
Already moved to ZEEGO, Agora needs more reworking



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
04/27/23,
01:50:01 AM

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.
