### ISSUE TITLE
RtcChannelEventHandler receives not allowed VideoRemoteStateReason enum

### ISSUE THREAD

**Issue by Hwan-seok** [AgoraIO-Extensions/Agora-Flutter-SDK#738]
**Describe the bug**
See the crash report screenshot below.

**Screenshots**
![스크린샷 2022-08-11 오전 1 48 08](https://user-images.githubusercontent.com/38072762/183968744-e4061c84-01ff-4b89-8ac7-5ec6f38768da.png)

**Smartphone (please complete the following information):**
 - Device: Android & IOS regardless of version

**Comment by littleGnAl** [comment]
Thanks for reporting.

**Comment by littleGnAl** [comment]
This fix has been merged to https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/master, you can depend on the `agora_rtc_engine` as the git package at this time.

**Comment by littleGnAl** [comment]
This fix has been released `agora_rtc_engine: ^5.3.1`.
https://pub.dev/packages/agora_rtc_engine
