### ISSUE TITLE
Stopping Share Screen Does not switch back to camera

### ISSUE THREAD

**Issue by 1AhmedYasser** [AgoraIO-Extensions/Agora-Flutter-SDK#739]
**Describe the bug**
When I am in a video call , I start screen sharing so my camera feed gets replaced with my screen feed, but when I stop sharing my screen using (await agoraEngine?.stopScreenCapture()), it stops the screen share feed, but does not switch back to the camera feed

**Expected behavior**
Upon Stopping screen sharing , the video feed should be replaced with the camera feed

**Comment by ahmedessid** [comment]
same problem here..

**Comment by littleGnAl** [comment]
Which platform are you running into issues with?

**Comment by 1AhmedYasser** [comment]
Both Android & iOS

**Comment by 1AhmedYasser** [comment]
Can You Expose this method to be used in the flutter SDK: setVideoSource (newAgoraDefaultSource ())

https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html?platform=Android#aa240e991d12b5240fc5fd362cbc0d521

**Comment by iaohtdev** [comment]
same issuse

**Comment by littleGnAl** [comment]
It's a known issue, we will expose a new API to achieve this on the next release.

**Comment by shaikmohammed8** [comment]
does any one have solution for screen sharing in android and ios

**Comment by littleGnAl** [comment]
This fix has been merged to https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/master, you can depend on the `agora_rtc_engine` as the git package at this time.

**Comment by littleGnAl** [comment]
This fix has been released `agora_rtc_engine: ^5.3.1`.
https://pub.dev/packages/agora_rtc_engine

**Comment by 1AhmedYasser** [comment]
Thank you so much
