### ISSUE TITLE
[LiveStream] Can I display 2 SurfaceView/TextureView of a Host User like picture below?

### ISSUE THREAD

**Issue by dqcuong2** [AgoraIO-Extensions/Agora-Flutter-SDK#740]
![Screen Shot 2022-08-23 at 16 26 43](https://user-images.githubusercontent.com/108870525/186123580-7b9c6fed-6d16-442b-8777-9eb9319411a8.png)

**Comment by littleGnAl** [comment]
Which platform you are using?

**Comment by dqcuong2** [comment]
iOS and Android sir

**Comment by littleGnAl** [comment]
The `agora_rtc_engine` plugin does not support this feature, maybe you can try https://pub.dev/packages/agora_rtc_ng if you really need this feature, but it is still in beta.

**Comment by dqcuong2** [comment]
@littleGnAl After try this https://pub.dev/packages/agora_rtc_ng. I still can not display a small screen on other of a remote user. Can you help me?

**Comment by tunytuan90** [comment]
> @littleGnAl After try this https://pub.dev/packages/agora_rtc_ng. I still can not display a small screen on other of a remote user. Can you help me?
Did you get the same error?

**Comment by littleGnAl** [comment]
You can try the code snippet below to render multiple local streams:
```
Stack(
  children: [
    AgoraVideoView(
      controller: VideoViewController(
        rtcEngine: _engine,
        canvas: const VideoCanvas(
            uid: 0, setupMode: VideoViewSetupMode.videoViewSetupAdd),
        useFlutterTexture: _isUseFlutterTexture,
        useAndroidSurfaceView: _isUseAndroidSurfaceView,
      ),
    ),
    Align(
      child: SizedBox(
        width: 300,
        height: 150,
        child: AgoraVideoView(
          controller: VideoViewController(
            rtcEngine: _engine,
            canvas: const VideoCanvas(
                uid: 0,
                setupMode: VideoViewSetupMode.videoViewSetupAdd),
            useFlutterTexture: _isUseFlutterTexture,
            useAndroidSurfaceView: _isUseAndroidSurfaceView,
          ),
        ),
      ),
    ),
  ],
);
```
If you have a problem with how to render the remote users, maybe you can learn how it works in our example
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/20b0b18d9f9f6b772feedd076463168d72fcfb30/example/lib/examples/basic/join_channel_video/join_channel_video.dart#L145

**Comment by bigboss5696** [comment]
Hi @littleGnAl,
I am trying to use agora screen sharing to share between AgoraVideoViews. But I found that, agora only allows full screen sharing. But I only want to share part of the screen, I only want to share what is displayed on the AgoraVideoView. Any solution help me in this case? I am using agora's example:
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/20b0b18d9f9f6b772feedd076463168d72fcfb30/example/lib/examples/advanced/screen_sharing/screen_sharing.dart

**Comment by littleGnAl** [comment]
Sharing part of the screen is not supported on mobile.

**Comment by ldquancmcglobal** [comment]
Hi @littleGnAl 
If I use the web, is it possible to do this?

**Comment by bigboss5696** [comment]
Hi @littleGnAl 
If I use the web, is it possible to do this?

**Comment by littleGnAl** [comment]
@bigboss5696 
It's so sorry that `6.0.0-rc.2` does not support the web yet, please raise another issue for your cause it's off-topic of this issue, thanks.
