### ISSUE TITLE
Getting this issue

### ISSUE THREAD

**Issue by sawproduction** [AgoraIO-Extensions/Agora-Flutter-SDK#743]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:generateDebugRFile'.
> Could not resolve all files for configuration ':agora_rtc_engine:debugCompileClasspath'.
   > Failed to transform annotation-experimental-1.1.0.aar (androidx.annotation:annotation-experimental:1.1.0) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for ExtractAarTransform: /home/sirwaleed/.gradle/caches/transforms-3/7f587b29568a4f8e237b611e0650f5e3/transformed/jetified-annotation-experimental-1.1.0.aar.
         > /home/sirwaleed/.gradle/caches/transforms-3/7f587b29568a4f8e237b611e0650f5e3/transformed/jetified-annotation-experimental-1.1.0.aar (No such file or directory)
   > Failed to transform tracing-1.0.0.aar (androidx.tracing:tracing:1.0.0) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for ExtractAarTransform: /home/sirwaleed/.gradle/caches/transforms-3/0140d387151ae272d8e07965c9802b02/transformed/jetified-tracing-1.0.0.aar.
         > /home/sirwaleed/.gradle/caches/transforms-3/0140d387151ae272d8e07965c9802b02/transformed/jetified-tracing-1.0.0.aar (No such file or directory)
   > Failed to transform window-java-1.0.0-beta04.aar (androidx.window:window-java:1.0.0-beta04) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for ExtractAarTransform: /home/sirwaleed/.gradle/caches/transforms-3/4f9109c3f811837e3ff21356db532795/transformed/jetified-window-java-1.0.0-beta04.aar.
         > /home/sirwaleed/.gradle/caches/transforms-3/4f9109c3f811837e3ff21356db532795/transformed/jetified-window-java-1.0.0-beta04.aar (No such file or directory)
   > Failed to transform window-1.0.0-beta04.aar (androidx.window:window:1.0.0-beta04) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for ExtractAarTransform: /home/sirwaleed/.gradle/caches/transforms-3/bfc2aa6059b1d5c609cbf9b2eee0b7a3/transformed/jetified-window-1.0.0-beta04.aar.
         > /home/sirwaleed/.gradle/caches/transforms-3/bfc2aa6059b1d5c609cbf9b2eee0b7a3/transformed/jetified-window-1.0.0-beta04.aar (No such file or directory)

**Comment by littleGnAl** [comment]
The issue is most likely not relative to the `agora_rtc_engine` plugin. Maybe you can try clean and rebuild it.
