### ISSUE TITLE
How do I know if I am receiving Video Sctream?

### ISSUE THREAD

**Issue by meet7sagar** [AgoraIO-Extensions/Agora-Flutter-SDK#746]
**Is your feature request related to a problem? Please describe.**
I want to know whether rtc_remote_view.SurfaceView is receiving a video stream or not?

**Additional context**
I want to show another widget if the remote video stream is not received.

**Comment by littleGnAl** [comment]
Maybe you can try `remoteVideoStateChanged` callback.
