### ISSUE TITLE
Video quality is so terrible in Pakistan and south asian region, that i am frstrated also no updates for months now

### ISSUE THREAD

**Issue by fisforfaheem** [AgoraIO-Extensions/Agora-Flutter-SDK#748]
Please could you update the voice quality and video quality

**Comment by littleGnAl** [comment]
It's better to submit a new ticket to agora support for this issue.

**Comment by fisforfaheem** [comment]
i wish i could send, but having weird build errors in xcode 13 :( due to agora pods

**Comment by littleGnAl** [comment]
Can you raise another issue of the build errors cause it's off-topic of this issue?
