### ISSUE TITLE
在readme中看到了Flutter应用得安卓/IOS不支持自采集这些功能，请问windows macos有这个限制嘛？

### ISSUE THREAD

**Issue by 390057892** [AgoraIO-Extensions/Agora-Flutter-SDK#754]
由于性能原因，agora_rtc_engine暂时没有实现agora native(Android/iOS) sdk的所有功能，如自定义音频采集和渲染 ，[自定义视频采集和渲染](https://docs.agora.io/cn/Video/custom_video_android?platform=Android)，[原始音频数据](https://docs.agora.io/cn/Video/raw_data_audio_android?platform=Android)等功能，agora_rtc_engine提供[RtcEnginePlugin](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/android/src/main/java/io/agora/rtc/base/RtcEnginePlugin.kt)/[RtcEnginePlugin](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/ios/Classes/Base/RtcEnginePlugin.h)，允许你在Android/iOS代码中与Flutter端创建的[RtcEngine](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/lib/src/rtc_engine.dart)交互，你可以继承[RtcEnginePlugin](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/android/src/main/java/io/agora/rtc/base/RtcEnginePlugin.kt)/[RtcEnginePlugin](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/ios/Classes/Base/RtcEnginePlugin.h)实现自己的插件，在onRtcEngineCreated回调中获取[RtcEngine](https://docs.agora.io/cn/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html)/[AgoraRtcEngineKit](https://docs.agora.io/cn/Video/API%20Reference/oc/Classes/AgoraRtcEngineKit.html)，请注意不要在Android/iOS中调用[RtcEngine.destroy](https://docs.agora.io/cn/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#afb808cdc9025a77af7dd2bce98311bfe)/[AgoraRtcEngineKit.destroy](https://docs.agora.io/cn/Video/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/destroy)方法，因为这会影响Flutter端的[RtcEngine](https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/lib/src/rtc_engine.dart)功能。如何使用RtcEnginePlugin

**Comment by littleGnAl** [comment]
You can check our `custom_capture_audio` example for reference https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/master/example/lib/examples/advanced/custom_capture_audio.

The desktop(macOS/Windows) is not supporting this feature yet.
