### ISSUE TITLE
Unable to display flutter web shared screen to flutter android

### ISSUE THREAD

**Issue by panjikrisnayasabfi** [AgoraIO-Extensions/Agora-Flutter-SDK#757]
**Describe the bug**
Unable to display flutter web shared screen to flutter android, but the video call feature working fine

**To Reproduce**
1. Share screen in flutter web
2. Choose a screen to share
3. Click share

**Expected behavior**
The flutter android user able to see my flutter web shared screen

**Screenshots**
![image](https://user-images.githubusercontent.com/110375310/189847814-ee94fea9-6345-4448-a099-3bf09a0e4cb8.png)
(Android user keep seeing my camera video instead of my shared screen)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Samsung
 - OS: Android

**Comment by littleGnAl** [comment]
Duplicated https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/735
