### ISSUE TITLE
Attach File with Agora RTM 

### ISSUE THREAD

**Issue by rezanandika10** [AgoraIO-Extensions/Agora-Flutter-SDK#760]
**Is your feature request related to a problem? Please describe.**
I need an Attach file (ex: .jpg, .pdf) for Agora Flutter SDK

**Describe the solution you'd like**
Create attach file feature for Agora Flutter SDK

**Describe alternatives you've considered**
Attach any extension file like .jpg, .pdf, .mp3, and all file extensions

**Comment by maxxfrazer** [comment]
RTM isn't supporting files since the native version `1.5.0`, so I don't expect this will be added here.
Also the flutter RTM repo is [here](https://github.com/AgoraIO/Agora-Flutter-RTM-SDK)

**Comment by rezanandika10** [comment]
Thank your for your answer @maxxfrazer
