### ISSUE TITLE
Release 6.0.0-rc.1 - Old import is not working anymore, should update example adapt to new version

### ISSUE THREAD

**Issue by ThangD** [AgoraIO-Extensions/Agora-Flutter-SDK#761]
**Describe the bug**
The old import of V5xx is not working with release 6.0.0-rc.1

**To Reproduce**
1. From Agora version 5.1.0
2. Upgrade to 6.0.0-rc.1
3. The code with old import occurs errors as image
<img width="874" alt="image" src="https://user-images.githubusercontent.com/7744981/190390042-c5738a86-0c04-4244-9748-4235e40d12c8.png">
4. A lot of old params and api name changed. Example, old version which i was using "getScreenShareHelper", don't know what is using with new version.

**Expected behavior**
Have docs to update the change from V5xx to V6xx

**Desktop (please complete the following information):**
 - OS: macos

Update: Should update by manual, API params change alot.

**Comment by littleGnAl** [comment]
The version 6.x is the major update and introduce some break changes,  you can check the release note for more detail https://docs.agora.io/en/video-call-4.x/migration_guide_flutter_ng?platform=Flutter.

The import should be `import 'package:agora_rtc_engine/agora_rtc_engine.dart'`, the `getScreenShareHelper` is no longer needed cause the version > 6.0.0 support multiple streams by default, you can check our example for reference
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/example/lib/examples/advanced

**Comment by ThangD** [comment]
@littleGnAl 

Try example build, error when targeting is web
../../flutter/.pub-cache/hosted/pub.dartlang.org/iris_event-1.2.0/lib/iris_event.dart:1:8: Error: Not found: 'dart:ffi'
import 'dart:ffi' as ffi;
       ^
../lib/src/impl/api_caller.dart:3:8: Error: Not found: 'dart:ffi'
import 'dart:ffi' as ffi;
       ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/iris_event-1.2.0/lib/src/native_iris_event_bindings.dart:4:8: Error: Not found: 'dart:ffi'
import 'dart:ffi' as ffi;

**Comment by littleGnAl** [comment]
@ThangD Can you try 6.0.0-rc.2?

**Comment by ThangD** [comment]
@littleGnAl 
I tried with 6.0.0-rc.2
Error still occurs with web build.
Btw, i also get this exception, could you pls help to know how to ovewcome?
flutter: #0      _ApiCallExecutor.requestPort (package:agora_rtc_engine/src/impl/api_caller.dart)
#1      _ApiCallExecutor.callIrisApiWithUin8ListAsync (package:agora_rtc_engine/src/impl/api_caller.dart:280:5)
#2      ApiCaller.callIrisApiWithUin8ListAsync (package:agora_rtc_engine/src/impl/api_caller.dart:99:10)
#3      ApiCaller.callIrisApi (package:agora_rtc_engine/src/impl/api_caller.dart:107:12)
#4      RtcEngineImpl.initialize (package:agora_rtc_engine/src/impl/agora_rtc_engine_impl.dart:275:21)
<asynchronous suspension>
flutter: LateInitializationError: Field 'requestPort' has not been initialized.

**Comment by littleGnAl** [comment]
I'm so sorry that the web support on 6.x is still WIP.

**Comment by ThangD** [comment]
@littleGnAl Thank you for your information.
How about this one? i sometime got this exception.

Btw, i also get this exception, could you pls help to know how to ovewcome?
flutter: #0 _ApiCallExecutor.requestPort (package:agora_rtc_engine/src/impl/api_caller.dart)
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/1 _ApiCallExecutor.callIrisApiWithUin8ListAsync (package:agora_rtc_engine/src/impl/api_caller.dart:280:5)
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/2 ApiCaller.callIrisApiWithUin8ListAsync (package:agora_rtc_engine/src/impl/api_caller.dart:99:10)
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/3 ApiCaller.callIrisApi (package:agora_rtc_engine/src/impl/api_caller.dart:107:12)
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/4 RtcEngineImpl.initialize (package:agora_rtc_engine/src/impl/agora_rtc_engine_impl.dart:275:21)

flutter: LateInitializationError: Field 'requestPort' has not been initialized.

**Comment by littleGnAl** [comment]
Do you know how to reproduce this error? It seems that you call any API before the `RtcEngine.initialize` so cause this error.

**Comment by ThangD** [comment]
@littleGnAl with sharing screen, how the remote user view the screen? I tried with uid but not success
AgoraVideoView(
                      controller: VideoViewController(
                      rtcEngine: _engine,
                      canvas: const VideoCanvas(
                        uid: 'uid',
                        sourceType: VideoSourceType.videoSourceScreen,
                      ),
                    ))

**Comment by littleGnAl** [comment]
Please check the example for reference https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/screen_sharing/screen_sharing.dart

**Comment by littleGnAl** [comment]
You should call `joinChannelEx ` to push the screen share stream to the remote users.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/e4a76ff35809703b5094d5e26f380924d11684c0/example/lib/examples/advanced/screen_sharing/screen_sharing.dart#L104

**Comment by ThangD** [comment]
Yes, i was. I also tried with example.

**Comment by littleGnAl** [comment]
The join channel button will push the camera/screen sharing stream to the remote.

**Comment by ThangD** [comment]
What is the uid will we using?

**Comment by littleGnAl** [comment]
The `uid` 0 means local stream (camera or screen sharing), not 0 means remote user stream, maybe you can check the basic example to see how it works first 
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/basic/join_channel_video/join_channel_video.dart

**Comment by ThangD** [comment]
yes, i understand it. I tried with uid (not use 0) which is not working with example.

**Comment by littleGnAl** [comment]
Can you try start screen sharing then join channel in the example, and view the stream on the web demo see if works or not
https://webdemo.agora.io/basicVideoCall/index.html

**Comment by ThangD** [comment]
@littleGnAl Do we have any events for others know the screen share is STOP? In the old release, when STOPING screen, the uid of screen sharing is OFFLINE. Thank you.
