### ISSUE TITLE
运行web端报错

### ISSUE THREAD

**Issue by ZClee128** [AgoraIO-Extensions/Agora-Flutter-SDK#768]
../../../flutter/.pub-cache/hosted/http%2558%2547%2547mirrors.cnnic.cn%2547dart-pub%2547/iris_event-1.2.0/lib/iris_event.dart:1:8: Error: Not found: 'dart:ffi'
import 'dart:ffi' as ffi;
       ^

: Error: Not found: 'dart:ffi'
../…/impl/api_caller.dart:3
import 'dart:ffi' as ffi;
       ^

**Comment by ZClee128** [comment]
oving the 'external' keyword or adding a JS interop annotation.
  external int bytes_per_sample;
               ^
../flutter/.pub-cache/hosted/http%2558%2547%2547mirrors.cnnic.cn%2547dart-pub%2547/agora_rtc_engine-6.0.0-rc.2/lib/src/impl/native_iris_api_engine_bindings.dart:1723:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int num_channels_;
               ^
../flutter/.pub-cache/hosted/http%2558%2547%2547mirrors.cnnic.cn%2547dart-pub%2547/agora_rtc_engine-6.0.0-rc.2/lib/src/impl/native_iris_api_engine_bindings.dart:1726:33: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Array<ffi.Int16> data_;
                                ^
../flutter/.pub-cache/hosted/http%2558%2547%2547mirrors.cnnic.cn%2547dart-pub%2547/agora_rtc_engine-6.0.0-rc.2/lib/src/impl/native_iris_api_engine_bindings.dart:1737:36: Error: Only JS interop members may be 'external'.

**Comment by ZClee128** [comment]
以下是demo报的错
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/18162711/191728302-1c8a5571-6dc0-432c-8651-c98fe4c606c0.png">

**Comment by littleGnAl** [comment]
It's so sorry that flutter web is not supported yet on 6.0.0-rc.2

**Comment by blopker** [comment]
It looks like 6.0.0 stable just landed (nice), but also doesn't have web support? Is there a rough timeline for that?

**Comment by followthemoney1** [comment]
the same, any updates?

**Comment by kaushikgodhani** [comment]
same issue please help
