### ISSUE TITLE
Sharing part of the screen is not supported on mobile.

### ISSUE THREAD

**Issue by bigboss5696** [AgoraIO-Extensions/Agora-Flutter-SDK#769]
I am trying to use agora screen sharing to share between AgoraVideoViews in the same channel. But I found that, agora only allows full screen sharing. But I only want to share part of the screen, I don't want to share things other than AgoraVideoView. Any solution help me in this case? I am using agora's example:
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/20b0b18d9f9f6b772feedd076463168d72fcfb30/example/lib/examples/advanced/screen_sharing/screen_sharing.dart

**Comment by littleGnAl** [comment]
Sharing part of the screen is not supported on mobile.
