### ISSUE TITLE
Issue with agora engine web

### ISSUE THREAD

**Issue by sjtsh** [AgoraIO-Extensions/Agora-Flutter-SDK#770]
I was trying to create a simple video broadcasting mechanism on the web with flutter and agora and came upon an issue by which a new uid is being realised. Still, the broadcast is not displayed on the remote surface view.
**this is the viewer screen**
import 'dart:async';

import 'package:agora_rtc_engine/rtc_engine.dart';
import 'package:agora_rtc_engine/rtc_local_view.dart' as RtcLocalView;
import 'package:agora_rtc_engine/rtc_remote_view.dart' as RtcRemoteView;
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:provider/provider.dart';
import 'package:streamon/Providers/UserManagement.dart';

import 'StartStreamScreen.dart';

class LiveStreamViewer extends StatefulWidget {
  @override
  _LiveStreamViewerState createState() => _LiveStreamViewerState();
}

class _LiveStreamViewerState extends State<LiveStreamViewer> {
  int? _remoteUid;
  bool _localUserJoined = false;
  late RtcEngine _engine;

  @override
  void initState() {
    super.initState();
    initAgora();
  }

  @override
  void dispose() {
    _engine.destroy();
    super.dispose();
  }

  Future<void> initAgora() async {
    // retrieve permissions
    //create the engine
    _engine = await RtcEngine.create(appId);
    _engine.setEventHandler(
      RtcEngineEventHandler(
          joinChannelSuccess: (String channel, int uid, int elapsed) {
        print("local user $uid joined");
        setState(() {
          _localUserJoined = true;
        });
      }, userJoined: (int uid, int elapsed) {
        print("remote user $uid joined");
        setState(() {
          _remoteUid = uid;
        });
      }, userOffline: (int uid, UserOfflineReason reason) {
        print("remote user $uid left channel");
        setState(() {
          _remoteUid = null;
        });
      }, leaveChannel: (stats) {
        setState(() {
          _remoteUid = null;
        });
      }),
    );
    await _engine.joinChannel(token, "test", null, 0);
  }

  Widget build(BuildContext context) {
    return Scaffold(
      body: _remoteUid == null
          ? Center(
              child: CircularProgressIndicator(),
            )
          : RtcRemoteView.SurfaceView(
              uid: _remoteUid!,
              channelId: 'test',
            ),
    );
  }
}

**this is the broadcast screen**

class StartStreamScreen extends StatefulWidget {
  @override
  _StartStreamScreenState createState() => _StartStreamScreenState();
}

class _StartStreamScreenState extends State<StartStreamScreen> {
  List<int> _remoteUid = [];
  bool _localUserJoined = false;
  late RtcEngine _engine;

  @override
  void initState() {
    super.initState();
    initAgora();
  }

  @override
  void dispose() {
    _engine.destroy();
    super.dispose();
  }

  Future<void> initAgora() async {
    // retrieve permissions
    //create the engine
    _engine = await RtcEngine.createWithContext(RtcEngineContext(appId));
    _engine.setEventHandler(
      RtcEngineEventHandler(
          joinChannelSuccess: (String channel, int uid, int elapsed) {
        print(uid);
        print("local user $uid joined");
        setState(() {
          _localUserJoined = true;
        });
      }, userJoined: (int uid, int elapsed) {
        print("remote user $uid joined");
        setState(() {
          _remoteUid.add(uid);
        });
      }, userOffline: (int uid, UserOfflineReason reason) {
        print("remote user $uid left channel");
        setState(() {
          _remoteUid.removeWhere((element) => element == uid);
        });
      }, leaveChannel: (stats) {
        setState(() {
          _remoteUid.clear();
        });
      }),
    );
    await _engine.enableVideo();
    await _engine.startPreview();
    await _engine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await _engine.setClientRole(ClientRole.Broadcaster);
    await _engine.joinChannel(token, 'test', null, 0);
  }

  // Create UI with local view and remote view
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: Stack(
              children: [
                RtcLocalView.SurfaceView(),
                Positioned(
                    top: 20,
                    right: 20,
                    height: 40,
                    width: 40,
                    child: Container(
                      height: 40,
                      width: 40,
                      decoration: BoxDecoration(
                          color: Colors.red, shape: BoxShape.circle),
                    ))
              ],
            ),
          ),
          SizedBox(
            height: 60,
            child: Text(
              "dsfsdsdf",
              style:
                  TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );
    // body: Stack(
    //   children: [
    //     _remoteVideo(),
    //     _localUserJoined
    //         ?
    //         : CircularProgressIndicator(),
    //   ],
    // ),
    // );
  }
}

I am testing it on chrome rn

**Comment by littleGnAl** [comment]
Can you share a reproducible demo and steps for your case? I don't think your code snippet is clear for me to reproduce the problem.

**Comment by hmbenhaim** [comment]
Hi get tons of ffi errors which is of course not supporting web.
i use version 6.0.0

**Comment by littleGnAl** [comment]
Please raise a new issue for your case @hmbenhaim .
