### ISSUE TITLE
Android Build is not working

### ISSUE THREAD

**Issue by Juanixou** [AgoraIO-Extensions/Agora-Flutter-SDK#772]
When I try to build my flutter application on Android, it returns a connection error related with jitpack.io. I'm working with agora rtc 5.0.1, and it is working with ios.

`* What went wrong:
Execution failed for task ':agora_rtc_engine:generateDebugRFile'.
> Could not resolve all files for configuration ':agora_rtc_engine:debugCompileClasspath'.
   > Could not resolve com.github.agorabuilder:iris-rtc:3.5.2.
     Required by:
         project :agora_rtc_engine
      > Skipped due to earlier error
      > Could not resolve com.github.agorabuilder:iris-rtc:3.5.2.
         > Could not get resource 'https://www.jitpack.io/com/github/agorabuilder/iris-rtc/3.5.2/iris-rtc-3.5.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/agorabuilder/iris-rtc/3.5.2/iris-rtc-3.5.2.pom'.
               > Connect to www.jitpack.io:443 [www.jitpack.io/149.56.28.39] failed: Connection refused (Connection refused)
      > Could not resolve com.github.agorabuilder:iris-rtc:3.5.2.
         > Could not get resource 'https://www.jitpack.io/com/github/agorabuilder/iris-rtc/3.5.2/iris-rtc-3.5.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/agorabuilder/iris-rtc/3.5.2/iris-rtc-3.5.2.pom'.
               > Connect to www.jitpack.io:443 [www.jitpack.io/149.56.28.39] failed: Connection refused (Connection refused)
      > Skipped due to earlier error`

**Comment by littleGnAl** [comment]
Can you try `agora_rtc_engine: ^5.3.0`?

**Comment by Juanixou** [comment]
> Can you try `agora_rtc_engine: ^5.3.0`?

It works! Thank you so much!!
