### ISSUE TITLE
Version 6.0.0 not working on web 

### ISSUE THREAD

**Issue by hmbenhaim** [AgoraIO-Extensions/Agora-Flutter-SDK#774]
Version 6.0.0 failed to run on web 

**To Reproduce**
Update to version 6.0.0 
Migrate the code to fit with the breaking changes in version 6.0.0
Run the app on web
Get a lot of ffi errors and the failed to run 

**Expected behaviour**
To run nice and smoothly

**Desktop (please complete the following information):**
 - OS:  Mac os 13
 - Browser chrome
 - Version 103

**Comment by littleGnAl** [comment]
It's sorry that 6.0.0 is not supported web yet.

**Comment by littleGnAl** [comment]
See https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/775

**Comment by hmbenhaim** [comment]
Ok I'll close this one because you have opened a new one for iOS and web
