### ISSUE TITLE
Known issue on agora_rtc_engine: ^6.0.0

### ISSUE THREAD

**Issue by littleGnAl** [AgoraIO-Extensions/Agora-Flutter-SDK#775]
There are some known issues on `agora_rtc_engine: ^6.0.0` which will be supported in the future
* Flutter web is not supported yet
* iOS simulator not supported yet

**Comment by jsaulsberry-cvet** [comment]
Errors returned by flutter web                                                 ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1587:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int captureTimeMs;
               ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1604:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int speech;
               ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1607:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int sendEvenIfEmpty;
               ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1621:33: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external Func_MaxMetadataSize getMaxMetadataSize;
                                ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1623:37: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external Func_ReadyToSendMetadata onReadyToSendMetadata;
                                    ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1625:34: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external Func_MetadataReceived onMetadataReceived;
                                 ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1636:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int uid;
               ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1639:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int size;
               ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1641:35: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external ffi.Pointer<ffi.Uint8> buffer;
                                  ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1644:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int timeStampMs;
               ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1702:30: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external Func_AudioOnFrame onFrame;
                             ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1711:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int capture_timestamp;
               ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1714:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int samples_per_channel_;
               ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1717:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int sample_rate_hz_;
               ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-6.0.0/lib/src/impl/native_iris_api_engine_bindings.dart:1720:16: Error: Only JS interop members may be 'external'.
Try removing the 'external' keyword or adding a JS interop annotation.
  external int bytes_per_sample;

**Comment by seanharding** [comment]
Is there any estimate on when the issue with iOS Simulator will be fixed?

**Comment by vmwsree** [comment]
Why isnt the old sample apps not working anymore?

**Comment by md186** [comment]
Can also confirm, im not able to launche the app on ios simulator. It's cruel developing on ios atm without a working simulator.

**Comment by nholmvio** [comment]
Any updates on the simulator fix?  It's prohibitively impactful that we cannot leverage ios simulator!
Thank you for prompt attention to this.

**Comment by rasitayaz** [comment]
Using pods configuration in [Podfile of example project](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/ios/Podfile) worked for me.

**Comment by papmodern** [comment]
@littleGnAl  Any estimation for web support on agora 6?

**Comment by papmodern** [comment]
I can't understand if its not supporting web, why the pub page shows another thing?

**Comment by alizaeri** [comment]
> it works fine for me. Hope it helps you guys **Podfile**
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>         config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
>         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
>     end
>   end
> end
> ```

It Works for me too. Thank you

**Comment by ali-alizadeh** [comment]
Is there any plan on adding support for web on version 6.0.0?

**Comment by spAds2** [comment]
Excluding simulators from build configs is not really a solution for many use cases.
I'm currently testing some solutions for a big education institute (40+ companies) and thanks to such bugs, being unaddressed for 6+ months, Agora makes my decision fast and easy to scrap them off my list. Thanks!

**Comment by littleGnAl** [comment]
iOS simulator is supported on `agora_rtc_engine: ^6.1.0`
https://pub.dev/packages/agora_rtc_engine

**Comment by littleGnAl** [comment]
Flutter web support is planned but there's no timeline guaranteed at this time, you can vote on this issue, which may increase the priority internally.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/844

**Comment by rkalra247** [comment]
Are there plans to add support rtm for flutter web?

**Comment by rkalra247** [comment]
Plans to add rtm support for flutter web?

**Comment by github4f** [comment]
Any update on the flutter web?

**Comment by aytunch** [comment]
Hi, is web support currently being worked on?

**Comment by mujjuTrootech** [comment]
Hi, is web support currently being worked on? Because in web do not worked this. So can you please provide alternative solution if any available.

**Comment by virendracarpenter** [comment]
It's also not working working on downgrading

**Comment by nholmvio** [comment]
Agora product managers..

Please It's a business impact on not having web support for your flutter packages ( RTM as well).

If I could go back i would have NOT leveraged agora in the solution with flutter.  I suspect everyone assumed web would be getting addressed concurrently when we selected flutter and agora's flutter integration into our solutions.  

It's  business and technology limiting to not be able to deploy web with common code base.  Can you please prioritize this for RTM/RTC. 

thank you.

**Comment by papmodern** [comment]
@nholmvio Unfortunately their support on flutter plugin is unacceptable. We had a product with a custom implementation on their old implementation and it was so stable and promising. Then they introduced their new version of plugin with objective-c and java which ruined everything. 
We already moved to LiveKit to overcome the limitations. It's not reliable on network connectivity as Agora has, but their developers are much more responsive and active. 

I hope someday Agora understands flutter is growing and they are losing many customers in this area!

**Comment by github4f** [comment]
@papmodern: it seems LiveKit is more expensive compared to Agora (i.e., $0.02/minute vs. 0.004/minute). Did you install the open source version on-premise?

**Comment by papmodern** [comment]
@github4f Nope. We are using their expensive server

**Comment by ysc1995** [comment]
> @nholmvio Unfortunately their support on flutter plugin is unacceptable. We had a product with a custom implementation on their old implementation and it was so stable and promising. Then they introduced their new version of plugin with objective-c and java which ruined everything. We already moved to LiveKit to overcome the limitations. It's not reliable on network connectivity as Agora has, but their developers are much more responsive and active.
> 
> I hope someday Agora understands flutter is growing and they are losing many customers in this area!

Hi @papmodern ! I work at Agora. I'm so sorry to hear that you had a bad experience on our Flutter SDK. Would you mind share with us what are the issues you have with our new version of plugin? Your experience is important to us. We would like to learn and improve! Thank you in advanced!

**Comment by faustodc** [comment]
> It's also not working working on downgrading

@virendracarpenter If you downgrade to 5.3.1 it is working on web https://pub.dev/packages/agora_rtc_engine/versions/5.3.1
