### ISSUE TITLE
Error while running pod install

### ISSUE THREAD

**Issue by hamzasidd3634** [AgoraIO-Extensions/Agora-Flutter-SDK#776]
CocoaPods could not find compatible versions for pod "AgoraIrisRTC_iOS":
  In Podfile:
    agora_rtc_engine (from `.symlinks/plugins/agora_rtc_engine/ios`) was resolved to 6.0.0, which depends on
      AgoraIrisRTC_iOS (= 4.0.0-rc.2)

**Comment by littleGnAl** [comment]
Maybe relative https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/773
