### ISSUE TITLE
Some imports are not working after updating to latest version "6.0.0".

### ISSUE THREAD

**Issue by mahboobahmed6577** [AgoraIO-Extensions/Agora-Flutter-SDK#779]
Hi, I'm developing an audio video calling web app with agora.  I Just updated agora to "6.0.0". Previously I was using "5.3.0" and it was working fine. Now these two imports are not working. 
```
import 'package:agora_rtc_engine/rtc_local_view.dart' as RtcLocalView;
import 'package:agora_rtc_engine/rtc_remote_view.dart' as RtcRemoteView;
```

**Comment by littleGnAl** [comment]
Flutter web is not supported on 6.0.0, see https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/775

**Comment by virendracarpenter** [comment]
Same issue with me
