### ISSUE TITLE
JoinAudio is Not working

### ISSUE THREAD

**Issue by vmwsree** [AgoraIO-Extensions/Agora-Flutter-SDK#780]
From yesterday in my app Audio only room is not been working, I tried the example app joinchannelaudio also it's not working, but I can hear audio if I joinwithvideo.

1. Run the sample app in examples folder
2. Click on JoinChannelAudio
3. Use a second device to connect to JoinChannelAudio
4. No Audio can be heard
5. If I use JoinChannelVideo u can hear audio

**Comment by vmwsree** [comment]
I'm getting this log these calls are not made by me 

`I/agora.io(15219): local audio publish timeout 5005
I/agora.io(15219): [RS]: **report stats: seq: 26, report list size 1, tx/rx: 3926/1200, cache size: 0
I/agora.io(15219): [ATW]: Audio statistics - play count: playout count = 1800 signal level: far_in = 0
I/agora.io(15219): [ATW]: Audio statistics - rec count: record count = 1800 signal level: near_in = 102, near_out = 102
I/agora.io(15219): **CALL STATS: duration 31s cpu app/total 17.62/0.0 battery 255 tx/rx: 2/1 kbps 31.810K/25.960K bytes
I/agora.io(15219): [ATW]: Audio statistics - play count: playout count = 3600 signal level: far_in = 0
I/agora.io(15219): [ATW]: Audio statistics - rec count: record count = 3600 signal level: near_in = 108, near_out = 108
I/agora.io(15219): [RS]: **report stats: seq: 58, report list size 1, tx/rx: 12089/2736, cache size: 0
`

**Comment by littleGnAl** [comment]
I think it's better to submit a ticket to agora support, you may need to share some sensitive data for further investigation.
