### ISSUE TITLE
Too much console messages version 6.0.0

### ISSUE THREAD

**Issue by utkudenis** [AgoraIO-Extensions/Agora-Flutter-SDK#783]
Hi Guys, 

how can ı stop these console messages ? 

rtc version 6.0.0 

![image](https://user-images.githubusercontent.com/68633376/194722044-468252b8-7376-4796-9588-a8fc29807b9c.png)

**Comment by littleGnAl** [comment]
I think you can try set the `RtcEngineContext.logConfig` when initialize.
https://docs.agora.io/cn/All/API%20Reference/flutter_ng/API/class_irtcengine.html#api_irtcengine_initialize

**Comment by utkudenis** [comment]
![image](https://user-images.githubusercontent.com/68633376/194756595-631eaf1e-a03c-4a45-ad82-f211ad22b4be.png)

Both LoglevelNone and LogLevelError Does not change anything. 

And your link is routing to cn language. When ı switch to english it directs to english general website 

Platfrom android

**Comment by littleGnAl** [comment]
This config can only filter the log printed by agora, I think the tag with `agora.io` should be filtered.
