### ISSUE TITLE
Flutter Web: emits leave channel event before actually joining a channel

### ISSUE THREAD

**Issue by spideythewebhead** [AgoraIO-Extensions/Agora-Flutter-SDK#784]
**Describe the bug**

When initializing the plugin on web it has some weird behaviour, and a leave channel event is emitted before actually joining a channel. Android/iOS is working.

here's a list of calls/events

1. agora-iris callApi 0 {..app information}
1. agora-iris callApi 162 {"appType":4}
1. agora-iris callApi 25 {}
1. agora-iris callApi 2 {"profile":1}

Now it's the leave event with additional logs from JS SDK

00:51:22:596 Agora-SDK [INFO]: [client-1ae56] Leaving channel
AgoraRtcWrapper.bundle.js:2 00:51:22:596 Agora-SDK [DEBUG]: [client-1ae56] reset client
AgoraRtcWrapper.bundle.js:2 00:51:22:597 Agora-SDK [DEBUG]: P2PChannel.reset
AgoraRtcWrapper.bundle.js:2 00:51:22:597 Agora-SDK [DEBUG]: [lock-P2PChannel-mutex-9] is created.
AgoraRtcWrapper.bundle.js:2 00:51:22:598 Agora-SDK [DEBUG]: [lock-client-publish-10] is created.
AgoraRtcWrapper.bundle.js:2 00:51:22:598 Agora-SDK [DEBUG]: [lock-client-subscribe-11] is created.
AgoraRtcWrapper.bundle.js:2 00:51:22:598 Agora-SDK [DEBUG]: [lock-client-leave-2] is locked, current queue 1. 
AgoraRtcWrapper.bundle.js:2 00:51:22:599 Agora-SDK [INFO]: [client-1ae56] Leaving channel repeated, success
AgoraRtcWrapper.bundle.js:2 00:51:22:600 Agora-SDK [DEBUG]: [lock-client-leave-2] is not locked, current queue 0. 
AgoraRtcWrapper.bundle.js:2 agora-iris _emitEvent LeaveChannel 

00:51:22:604 Agora-SDK [DEBUG]: [lock-client-leave-12] is created.
AgoraRtcWrapper.bundle.js:2 00:51:22:604 Agora-SDK [DEBUG]: [lock-client-publish-13] is created.
AgoraRtcWrapper.bundle.js:2 00:51:22:604 Agora-SDK [DEBUG]: [lock-client-renewtoken-14] is created.
AgoraRtcWrapper.bundle.js:2 00:51:22:604 Agora-SDK [DEBUG]: [lock-client-subscribe-15] is created.
AgoraRtcWrapper.bundle.js:2 00:51:22:604 Agora-SDK [INFO]: [client-a17cc] Initializing AgoraRTC client v4.11.0 build: v4.11.0-0-g961abf54(3/31/2022, 5:02:17 PM), mode: live, codec: h264
AgoraRtcWrapper.bundle.js:2 00:51:22:605 Agora-SDK [DEBUG]: [lock-websocket-16] is created.
AgoraRtcWrapper.bundle.js:2 00:51:22:608 Agora-SDK [DEBUG]: [lock-config-distribute-17] is created.
AgoraRtcWrapper.bundle.js:2 00:51:22:608 Agora-SDK [DEBUG]: [lock-P2PChannel-mutex-18] is created.

agora-iris callApi 3 {"role":1,"options":null}

agora-iris callApi 4 {"token":"<token here>","channelId":"0XcKvB5gcuRT3MJjTmo6","info":null,"uid":0,"options":null} // this is join channel

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome 106.0.5249.61
 - Plugin version: 5.3.1

**Additional context**

If you know why this might be happening let me know, so i can have a look. Because this is blocking for releasing on web

**Comment by littleGnAl** [comment]
`leaveChannel` will be called when the RtcEngine be released
https://github.com/AgoraIO-Community/Iris-Rtc-Web/blob/c0fa7a67146cd5a117dc27a4dfc4fde9728ee15a/src/IrisRtcEngine.ts#L649

I think this log may not affect the `joinChannel` function.

**Comment by spideythewebhead** [comment]
Hi, the thing is that I only call release function only when the widget is disposed.

This seems to be happening while doing the initialisation of the engine.

Do you want me to attach the code?

**Comment by littleGnAl** [comment]
I think it's good to have a reproducible demo for the case.

**Comment by spideythewebhead** [comment]
I have found what causes the issue, having the channel profile to Live Broadcasting causes an issue on web (i am not sure why it does tho). Removing the 2 lines fixes the issue with receiving the channel event.

```dart
await rtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
await rtcEngine.setClientRole(ClientRole.Broadcaster);
```

I have attached the reproducable code, in case you want to have a further look.
[agora_issue784.zip](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/files/9741625/agora_issue784.zip)

**Comment by littleGnAl** [comment]
I think you can add a `isJoinedChannel` flag to track the join channel status, and only handle the leaveChannel logic if the `isJoinedChannel` is true at this time. e.g.,
```dart
    rtcEngine.setEventHandler(
      RtcEngineEventHandler(
        leaveChannel: (RtcStats stats) {
          if (isJoinedChannel) {
            // do somthing
            isJoinedChannel = false;
          }
        },
        joinChannelSuccess: (String channel, int uid, int elapsed) {
          isJoinedChannel = true;
          // do somthing
        },
      ),
    );
```

**Comment by spideythewebhead** [comment]
Yes this could be a solution too, thanks.
