### ISSUE TITLE
Agora Cloud Recording Video Call Unable to Record Local Video and Audio

### ISSUE THREAD

**Issue by panjikrisnayasabfi** [AgoraIO-Extensions/Agora-Flutter-SDK#785]
**Describe the bug**
The agora video call recording result is not showing the local video and audio (only showing the other user)
![Screenshot 2022-10-10 152801](https://user-images.githubusercontent.com/110375310/194825790-e82419da-8852-45cf-b731-da84aabfebcc.png)

This is the video call from flutter web looks like
![Screenshot 2022-10-10 145642](https://user-images.githubusercontent.com/110375310/194827567-45e42983-178f-49e0-887f-9d8a461d52d8.png)

**To Reproduce**
1. Video call from flutter web to flutter android app
2. Request permissions
3. Start the cloud recording
4. End the video call
5. End the cloud recording

**Expected behavior**
The recording result shows both users

So, I use composite cloud recording with this payload to start the recording
`{ 'cname': channel, 'uid': uid, 'clientRequest': { 'token': token, 'recordingConfig': { 'channelType': 0, // communication profile 'streamTypes': 2, // subscribe to both video and audio streams 'audioProfile': 1, // mono, bitrate up to 128 kbps 'videoStreamType': 0, // high quality stream 'maxIdleTime': 3600, 'transcodingConfig': { 'width': 1920, 'height': 1080, 'fps': 30, 'bitrate': 3150, 'mixedVideoLayout': 3, // 1 for best fit layout (grid view), 3 for custom layout (need to set the layoutConfig) 'backgroundColor': '#000000', 'layoutConfig': [ { 'uid': subscribedUids[0], 'x_axis': 0.0, 'y_axis': 0.0, 'width': 1.0, 'height': 0.5, 'alpha': 1.0, 'render_mode': 1 }, { 'uid': subscribedUids[1], 'x_axis': 0.0, 'y_axis': 0.5, 'width': 0.5, 'height': 0.5, 'alpha': 1.0, 'render_mode': 1 }, { 'x_axis': 0.5, 'y_axis': 0.5, 'width': 0.5, 'height': 0.5, 'alpha': 1.0, 'render_mode': 1 } ] }, 'subscribeVideoUids': subscribedUids, 'subscribeAudioUids': subscribedUids, 'subscribeUidGroup': 0 }, 'recordingFileConfig': { 'avFileType': ['hls', 'mp4'] }, 'storageConfig': { 'vendor': 6, 'region': 0, 'bucket': agoraBucket, 'accessKey': agoraStorageAccessKey, 'secretKey': agoraStorageSecretKey, } } }`

**Comment by littleGnAl** [comment]
I think this feature is not relative to the `agora_rtc_engine` plugin, it's better to submit a new ticket to agora support for further investigation.
