### ISSUE TITLE
audio volume indication still working when muteLoacalAudio(true) 

### ISSUE THREAD

**Issue by ebrahim2222** [AgoraIO-Extensions/Agora-Flutter-SDK#786]
I/flutter ( 5353): true
D/spdlog  ( 5353): [2022-10-11 15:27:17.108] [5353] [debug] [iris_rtc_engine.cc:74] api name RtcEngine_muteLocalAudioStream params {"mute":true}
I/agora.io( 5353): (00001430): RtcEngine::muteLocalAudioStream(this:0xb40000744244cc00, mute:1)
I/agora.io( 5353): (00001431):   RtcConnectionImpl::muteLocalAudio(this:0xb4000072d8224c00, mute:1)
I/agora.io( 5353): [CALLCTX] void agora::rtc::CallContext::onAudioMuteMe(bool): mute: 1, videoHasPublishedStream: 0
I/agora.io( 5353): [LUR] onMuteLocalAudio mute:1
I/agora.io( 5353): PublishStateManager::onAudioMuted 1
I/agora.io( 5353): PublishStateManager::doAudioAction action kUnpublish, audio_current_state_: PUB_STATE_PUBLISHED
I/agora.io( 5353): PublishStateManager::doAudioAction PUB_STATE_PUBLISHED => PUB_STATE_NO_PUBLISHED
I/agora.io( 5353): [LUR] onAudioPublishStateChanged oldState:3, newState:1, elapseSinceLastState:366
I/agora.io( 5353): (00001432): ChannelProxy::onAudioPublishStateChanged->onAudioPublishStateChanged(this:0xb400007429bf6800, channel:63456efa9a79f798c6cb0dc5, oldState:3, newState:1, elapseSinceLastState:366)

**Comment by littleGnAl** [comment]
It's expected behavior, please check our doc for reference.
https://api-ref.agora.io/en/voice-sdk/flutter/6.x/API/class_irtcengineeventhandler.html#callback_irtcengineeventhandler_onaudiovolumeindication

**Comment by ebrahim2222** [comment]
but i need to stop it after calling mute local user to remove the user from list !!

**Comment by littleGnAl** [comment]
I think you can call `enableAudioVolumeIndication ` to control whether receive the callback or not.
https://api-ref.agora.io/en/voice-sdk/flutter/6.x/API/class_irtcengine.html#api_irtcengine_enableaudiovolumeindication

**Comment by ebrahim2222** [comment]
man i do it in need to prevent audioAudioVolumeIndication from working after mute local user .. it's working in previous version !!

**Comment by littleGnAl** [comment]
It's a break-change behavior from 6.x.
see https://docs.agora.io/en/video-calling/develop/migration-guide#volume-indication for more detail.
