### ISSUE TITLE
Audio and Video device manager errors

### ISSUE THREAD

**Issue by federico-amura-phononx** [AgoraIO-Extensions/Agora-Flutter-SDK#787]
**Describe the bug**
every time I call a method from the video device manager or audio device manager I get an exception. 

**To Reproduce**
1. obtain a video audio reference or a video audio reference
2. Call (for example) "getDevice" from "VideoDeviceManager"

**Expected behavior**
The device

**Screenshots**
![Captura de Pantalla 2022-10-11 a la(s) 12 46 34](https://user-images.githubusercontent.com/112664991/195138746-c04f7064-861e-4fc7-bb4f-45aa15d61197.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: IOS 16

**Comment by littleGnAl** [comment]
The AudioDeviceManager/VideoDeviceManager only supports desktops.
