### ISSUE TITLE
Can you support channel switching?

### ISSUE THREAD

**Issue by seemelala** [AgoraIO-Extensions/Agora-Flutter-SDK#788]
//to delete
//#define FUNC_RTCENGINE_SETCONTENTINSPECT "RtcEngine_SetContentInspect"
//#define FUNC_RTCENGINE_SWITCHCHANNEL "RtcEngine_switchChannel"
Can you support channel switching?

**Comment by littleGnAl** [comment]
Please follow our migration guide for the switch channel feature.
https://docs.agora.io/en/video-calling/develop/migration-guide#fast-channel-switching
