### ISSUE TITLE
Microphone mode support in iOS

### ISSUE THREAD

**Issue by nizwar** [AgoraIO-Extensions/Agora-Flutter-SDK#792]
I wonder, Is there any functions to make user able to change microphone modes in iOS?

![IMG_3654](https://user-images.githubusercontent.com/33113137/196032415-d14ea5af-2bf3-4c55-b9f1-a243275c0402.PNG)
![IMG_3653](https://user-images.githubusercontent.com/33113137/196032424-97ceb5cc-8b83-4962-b3e6-a95a6447ca0d.PNG)

**Comment by littleGnAl** [comment]
It's sorry that there's no API to change the Mic Mode from `agora_rtc_engine`.
