### ISSUE TITLE
Unable to run iOS device after updating to agora 6.0.0. Getting "framework not found -framework" error. 

### ISSUE THREAD

**Issue by clement89** [AgoraIO-Extensions/Agora-Flutter-SDK#793]
Ld /Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/Runner.app/Runner normal (in target 'Runner' from project 'Runner')
    cd /Users/clementjoseph/Work/PlusApp/plusapp-mobile/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios15.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -L/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/usr/lib/swift -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/AppAuth -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/BoringSSL-GRPC -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/CryptoSwift -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FMDB -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseAppCheckInterop -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseAuth -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseAuthInterop -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseCore -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseCoreDiagnostics -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseCoreExtension -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseCoreInternal -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseFirestore -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseInstallations -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseMessaging -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseStorage -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/FirebaseStorageInternal -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/GTMAppAuth -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/GTMSessionFetcher -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/GoogleDataTransport -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/GoogleSignIn -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/GoogleUtilities -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/Libuv-gRPC -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/MTBBarcodeScanner -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/PromisesObjC -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/ReachabilitySwift -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/abseil -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/agora_rtc_engine -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/audio_session -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/audioplayers -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/cloud_firestore -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/connectivity_plus -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/device_info -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/dolbyio_comms_sdk_flutter -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/firebase_auth -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/firebase_auth_oauth -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/firebase_core -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/firebase_messaging -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/firebase_storage -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/flutter_callkit_incoming -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/flutter_contacts -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/flutter_local_notifications -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/flutter_ringtone_player -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/flutter_share -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/flutter_sound -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/flutter_sound_core -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/gRPC-C++ -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/gRPC-Core -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/google_sign_in_ios -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/image_picker_ios -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/iris_event -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/just_audio -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/leveldb-library -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/nanopb -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/open_file -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/path_provider_ios -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/permission_handler_apple -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/photo_manager -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/platform_device_id -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/qr_code_scanner -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/sign_in_with_apple -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/sqflite -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/url_launcher_ios -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/webview_flutter_wkwebview -F/Users/clementjoseph/Work/PlusApp/plusapp-mobile/ios/Pods/AgoraIrisEventFlutter_iOS -F/Users/clementjoseph/Work/PlusApp/plusapp-mobile/ios/Pods/AgoraIrisRTC_iOS -F/Users/clementjoseph/Work/PlusApp/plusapp-mobile/ios/Pods/AgoraRtcEngine_Special_iOS -F/Users/clementjoseph/Work/PlusApp/plusapp-mobile/ios/Pods/VoxeetSDK -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/XCFrameworkIntermediates/AgoraIrisEventFlutter_iOS -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/XCFrameworkIntermediates/AgoraIrisRTC_iOS -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/XCFrameworkIntermediates/AgoraRtcEngine_Special_iOS -F/Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/XCFrameworkIntermediates/VoxeetSDK -filelist /Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner_lto.o -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner.swiftmodule -ObjC -lc++ -lsqlite3 -lstdc++ -lz -framework AVFoundation -framework AgoraAiNoiseSuppressionExtension -framework AgoraAudioBeautyExtension -framework AgoraClearVisionExtension -framework AgoraContentInspectExtension -framework AgoraDav1d -framework AgoraDrmLoaderExtension -framework AgoraPvcExtension -framework AgoraReplayKitExtension -framework AgoraRtcKit -framework AgoraRtcWrapper -framework AgoraSoundTouch -framework AgoraSpatialAudioExtension -framework AgoraSuperResolutionExtension -framework AgoraVideoSegmentationExtension -framework Agorafdkaac -framework Agoraffmpeg -framework AppAuth -framework CoreGraphics -framework CoreTelephony -framework CoreText -framework CryptoKit -framework CryptoSwift -framework FBLPromises -framework FMDB -framework FirebaseAppCheckInterop -framework FirebaseAuth -framework FirebaseAuthInterop -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseCoreExtension -framework FirebaseCoreInternal -framework FirebaseFirestore -framework FirebaseInstallations -framework FirebaseMessaging -framework FirebaseStorage -framework FirebaseStorageInternal -framework Foundation -framework GTMAppAuth -framework GTMSessionFetcher -framework GoogleDataTransport -framework GoogleSignIn -framework GoogleUtilities -framework LocalAuthentication -framework MTBBarcodeScanner -framework MediaPlayer -framework PhotosUI -framework QuartzCore -framework Reachability -framework SafariServices -framework Security -framework SystemConfiguration -framework UIKit -framework VoxeetSDK -framework WebRTC -framework absl -framework agora_rtc_engine -framework audio_session -framework audioplayers -framework cloud_firestore -framework connectivity_plus -framework device_info -framework dolbyio_comms_sdk_flutter -framework dvclient -framework firebase_auth -framework firebase_auth_oauth -framework firebase_core -framework firebase_messaging -framework firebase_storage -framework flutter_callkit_incoming -framework flutter_contacts -framework flutter_local_notifications -framework flutter_ringtone_player -framework flutter_share -framework flutter_sound -framework flutter_sound_core -framework google_sign_in_ios -framework grpc -framework grpcpp -framework image_picker_ios -framework iris_event -framework iris_event_handler -framework just_audio -framework leveldb -framework nanopb -framework open_file -framework openssl_grpc -framework path_provider_ios -framework permission_handler_apple -framework photo_manager -framework platform_device_id -framework qr_code_scanner -framework sign_in_with_apple -framework sqflite -framework url_launcher_ios -framework uv -framework webview_flutter_wkwebview -weak_framework AuthenticationServices -weak_framework UserNotifications -ObjC -lc++ -lsqlite3 -lstdc++ -lz -framework AVFoundation -framework -framework -framework AgoraCore -framework AgoraDav1dExtension -framework AgoraFDExtension -framework AgoraFullAudioFormatExtension -framework AgoraReplayKitExtension -framework AgoraRtcKit -framework AgoraRtcWrapper -framework AgoraSoundTouch -framework AgoraSpatialAudioExtension -framework AgoraSuperResolutionExtension -framework AgoraVideoProcessExtension -framework AgoraVideoSegmentationExtension -framework Agorafdkaac -framework Agoraffmpeg -framework AppAuth -framework CoreGraphics -framework CoreTelephony -framework CoreText -framework CryptoSwift -framework FBLPromises -framework FMDB -framework FirebaseAppCheckInterop -framework FirebaseAuth -framework FirebaseAuthInterop -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseCoreExtension -framework FirebaseCoreInternal -framework FirebaseFirestore -framework FirebaseInstallations -framework FirebaseMessaging -framework FirebaseStorage -framework FirebaseStorageInternal -framework Foundation -framework GTMAppAuth -framework GTMSessionFetcher -framework GoogleDataTransport -framework GoogleSignIn -framework GoogleUtilities -framework LocalAuthentication -framework MTBBarcodeScanner -framework MediaPlayer -framework PhotosUI -framework QuartzCore -framework Reachability -framework SafariServices -framework Security -framework SystemConfiguration -framework UIKit -framework VoxeetSDK -framework WebRTC -framework absl -framework agora_rtc_engine -framework audio_session -framework audioplayers -framework cloud_firestore -framework connectivity_plus -framework device_info -framework dolbyio_comms_sdk_flutter -framework dvclient -framework firebase_auth -framework firebase_core -framework firebase_messaging -framework firebase_storage -framework flutter_callkit_incoming -framework flutter_contacts -framework flutter_local_notifications -framework flutter_ringtone_player -framework flutter_share -framework flutter_sound -framework flutter_sound_core -framework google_sign_in_ios -framework grpc -framework grpcpp -framework image_picker_ios -framework just_audio -framework leveldb -framework nanopb -framework open_file -framework openssl_grpc -framework path_provider_ios -framework permission_handler_apple -framework photo_manager -framework platform_device_id -framework qr_code_scanner -framework sqflite -framework url_launcher_ios -framework uv -framework webview_flutter_wkwebview -weak_framework AuthenticationServices -weak_framework UserNotifications -framework Pods_Runner -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat -o /Users/clementjoseph/Library/Developer/Xcode/DerivedData/Runner-bmxglfrsvnmmvdfxktpnspxpjplq/Build/Products/Release-iphoneos/Runner.app/Runner

ld: framework not found -framework
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by littleGnAl** [comment]
Is there more detail on the logs?
