### ISSUE TITLE
[5.3.1] Web - enumerateVideoDevices not working

### ISSUE THREAD

**Issue by ThangD** [AgoraIO-Extensions/Agora-Flutter-SDK#798]
**Describe the bug**
Call _engine.deviceManager.enumerateVideoDevices() on web return different values on desktop

**To Reproduce**
1. Go to example
2. Run device manager view
3. Try on desktop is run success.
4. Try on Web, can get the enum values of video devices but different with desktop one, caused run SetVideoDevice not working

**Comment by littleGnAl** [comment]
I think you can sort the devices list by the device id to ensure the order that you want.

**Comment by ThangD** [comment]
@littleGnAl The device id on the web is different value caused the Set is not working, not the wrong order of list.

**Comment by littleGnAl** [comment]
The API behavior is a little different on web.
https://github.com/AgoraIO-Community/Iris-Rtc-Web/blob/c0fa7a67146cd5a117dc27a4dfc4fde9728ee15a/src/IrisRtcEngine.ts#L901

https://github.com/AgoraIO-Community/Iris-Rtc-Web/blob/c0fa7a67146cd5a117dc27a4dfc4fde9728ee15a/src/IrisRtcEngine.ts#L728

I think you should call the `setDevice` before `joinChannel `/ `startPreview `.

**Comment by ThangD** [comment]
@littleGnAl 
The list of MediaDeviceInfo is different btw desktop and web:
1. Desktop: 
`[[{deviceId: 0x112000046d0825, deviceName: USB Camera VID:1133 PID:2085}
flutter: {deviceId: EAB7A68FEC2B4487AADFD8A91C1CB782, deviceName: FaceTime HD Camera}]]`
2. Web: 
`[{deviceId: 54bf03901f28b3187b99db64624707e610ffc3a4f3d07d0cf01c71773e0219cc, deviceName: USB Camera VID:1133 PID:2085 (046d:0825)}
{deviceId: 90a35781bd401ea7ce1bb6d7f965087cfe29a15e1bed37aa73d066de9b80f70e, deviceName: FaceTime HD Camera}]
`

I tried with the Agora Web demo, it is using the value like the deskop: https://webdemo.agora.io/recordingDeviceControl/index.html#

**Comment by littleGnAl** [comment]
@ThangD 
I think it's not the issue with the `deviceId` value, after a little dig into the web implementation, 
https://github.com/AgoraIO-Community/Iris-Rtc-Web/blob/c0fa7a67146cd5a117dc27a4dfc4fde9728ee15a/src/IrisRtcDeviceManager.ts#L594, the `setVideoDeviceId ` only set a new value but not reload the video track.

So I think you should call `setVideoDeviceId ` before `joinChannel`/`startPreview` functions.
