### ISSUE TITLE
flutter  5.3.1 切换远程用户，远程视频不切换

### ISSUE THREAD

**Issue by shichunlei** [AgoraIO-Extensions/Agora-Flutter-SDK#801]
flutter 5.3.1 版本集成之后切换远程用户不发生变化

例如：当前远程用户A uid:111
还有个远程用户B uid：222
把当前用户切换至远程用户B，这时候远程的视频并没有跟着切换

remote.SurfaceView(uid: 111, channelId: _channelId);

将111切换至222，远程视频并没有变化

**Comment by littleGnAl** [comment]
I think you can add the `key` property to ensure that each `remote.SurfaceView` is unique. e.g.,
```dart
remote.SurfaceView(key: UniqueKey(), uid: 111, channelId: _channelId);
```

**Comment by shichunlei** [comment]
添加KEY之后接收远程视频的用户端视频频闪，见附件视频

https://user-images.githubusercontent.com/7146745/198188689-2335a108-f446-4f1c-8b4a-616fc3057cf1.mp4

**Comment by littleGnAl** [comment]
I think it's better to provide a reproducible demo for this case.

**Comment by shichunlei** [comment]
使用ValueKey 没问题了，谢谢你的回答
