### ISSUE TITLE
Add support for blutooth headset buttons

### ISSUE THREAD

**Issue by DemeoStep** [AgoraIO-Extensions/Agora-Flutter-SDK#802]
As agora blocking system MediaKeysEvents - provide support for listen to this events.

Now it's not possible to operate bluetooth headset buttons with agora. No way to answer to call, mute session or other operation. Double tap disconnects headset from session (stop call), long press simply operates with system volume...

With MediaKeysEvents support it will be possible to answer a call riding a car, use other bluetooth devices such as bluetooth buttons, bluetooth speakers and so.

**Comment by littleGnAl** [comment]
I think it's better to submit a new ticket to agora support to follow this issue.

**Comment by DemeoStep** [comment]
Ticket submitted
