### ISSUE TITLE
Could not determine artifacts for io.agora.rtc:full-sdk:3.7.0.3 in Agora 5.3.1

### ISSUE THREAD

**Issue by stevanusw28** [AgoraIO-Extensions/Agora-Flutter-SDK#804]
**Describe the bug**
There is an error timeout when getting dependencies from Agora SDK from jcenter, so the Flutter application cannot be built.

```
FAILURE: Build failed with an exception.

             * What went wrong:
             Could not determine the dependencies of task ':agora_rtc_engine:compileReleaseAidl'.
             > Could not resolve all dependencies for configuration ':agora_rtc_engine:releaseRuntimeClasspath'.
                > Could not determine artifacts for io.agora.rtc:full-sdk:3.7.0.3
                   > Could not get resource 'https://jcenter.bintray.com/io/agora/rtc/full-sdk/3.7.0.3/full-sdk-3.7.0.3.aar'.
                      > Could not HEAD 'https://jcenter.bintray.com/io/agora/rtc/full-sdk/3.7.0.3/full-sdk-3.7.0.3.aar'.
                         > Read timed out

             * Try:
             Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

             * Get more help at https://help.gradle.org

             BUILD FAILED in 4m 37s
```

**To Reproduce**
Run the Flutter app and build AAR using agora version 5.3.1 

**Expected behavior**
The Flutter application can be reproduced

**Additional context**

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.10.5, on macOS 13.0 22A380 darwin-x64, locale en-ID)
> [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.2)
> [✓] IntelliJ IDEA Community Edition (version 2022.2)
> [✓] VS Code (version 1.72.2)
> [✓] Connected device (2 available)
>     ! Error: Stevanus Wijaya’s iPhone is not connected. Xcode will continue when Stevanus Wijaya’s iPhone is connected. (code -13)
> [✓] HTTP Host Availability

**Comment by littleGnAl** [comment]
I think you should check your network to see if it can connect to jcenter.

**Comment by stevanusw28** [comment]
We already double checking our network connection, and our connection is fine @littleGnAl

**Comment by duhanbalci** [comment]
same

**Comment by littleGnAl** [comment]
As I know the jcenter will be end of service, I think you can remove usages of `jcenter()`  from your build scripts and try again.
