### ISSUE TITLE
Local Video Not Working (6.0.0)

### ISSUE THREAD

**Issue by kwameopareasiedu** [AgoraIO-Extensions/Agora-Flutter-SDK#805]
**Describe the bug**
After following the [guide on video calling](https://docs.agora.io/en/video-calling/get-started/get-started-sdk), which implements both local and remote views, the local video on the Flutter app does not render

**To Reproduce**
1. Create a new Flutter app
2. Install `agora_rtc_engine: 6.0.0`
3. Follow the [video calling guide](https://docs.agora.io/en/video-calling/get-started/get-started-sdk)
4. Run the app

**Expected behavior**
Both local and remote video should be playing when the channel is joined and the video module is enabled

**Smartphone (please complete the following information):**
 - Device: Samsung A33
 - OS: Android 12
 - Agora SDK Version: 6.0.0

**Addional Information:**
I downgraded to `5.3.1` which worked perfectly

**Comment by littleGnAl** [comment]
We will check the guide later, I think you can check our example for reference at this time.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/example/lib/examples/basic/join_channel_video

**Comment by kwameopareasiedu** [comment]
> We will check the guide later, I think you can check our example for reference at this time. https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/example/lib/examples/basic/join_channel_video

I'll check it out and provide feedback here...

**Comment by alpcanm** [comment]
When i enter  uid 0 local video working but another numbers not working.

**Comment by kwameopareasiedu** [comment]
@alpcanm I just tried it. It works perfectly now. Thanks so much.

@littleGnAl You may need to update the docs to indicate this. Using a uid of 0 for the local `AgoraVideoView` allows the video to render. 

I also noticed that the `onJoinChannelSuccess` also returns connection with uid of 0, but only when the `engine.joinChannelWithUserAccount` is used. Putting this here for future reference.

I'll close the issue now...
