### ISSUE TITLE
Setting COMMUNICATION profile on join channel is not consistent with API results

### ISSUE THREAD

**Issue by GrupoDO** [AgoraIO-Extensions/Agora-Flutter-SDK#806]
**Describe the bug**
When I join on a channel with channelType = COMMUNICATION and then I get the users list from the API, the API returns that channel type is LIVE_BROADCASTING and the expected key "users" is replaced by "broadcasters".

From the docs in https://docs.agora.io/en/voice-calling/reference/channel-management-rest-api#gets-the-user-status

```
mode: Number. The channel profile:

    1：The COMMUNICATION profile.
    2: The LIVE_BROADCASTING profile.

total: Number. The total number of the users in the channel. This field is returned only when mode is 1.
users: Array. User IDs of all users in the channel. This field is returned only when mode is 1.
broadcasters：Array. User IDs of all hosts in the channel. This field is returned only when mode is 2.
```

**To Reproduce**
1. Join on a channel using type COMMUNICATION 
2. Get the users list from API
3. See error

**Expected behavior**
In the API response the "mode" key must be 1
Current response is: 

```
{"success":true,"data":{"channel_exist":true,"mode":2,"broadcasters":[966496378],"audience":[],"audience_total":0}}
```

The correct response must be:
```
{"success":true,"data":{"channel_exist":true,"mode":1,"users":[966496378],"audience":[],"audience_total":0}}
```

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android 12
 - Version 12

**Additional context**
[Full log](https://pastebin.com/pNDsdzdy)

**Comment by plutoless** [comment]
so what do you get when you join with live-broadcasting mode?

**Comment by GrupoDO** [comment]
When I join using LIVE_BROADCASTING mode the API returns the correct data:

```
{
	"success": true,
	"data": {
		"channel_exist": true,
		"mode": 2,
		"broadcasters": [
			2640238546
		],
		"audience": [],
		"audience_total": 0
	}
}
```

**Comment by littleGnAl** [comment]
This issue is not relative to the `agora_rtc_engine`, I think it's better to raise a ticket to the agora support to keep track it.
