### ISSUE TITLE
Keyboard and resizing the view

### ISSUE THREAD

**Issue by alpcanm** [AgoraIO-Extensions/Agora-Flutter-SDK#808]
When i open the keyboard with TextField, the AgoraVideoView resize. İ'm using those on Stack widget, textfield is on bottom of stack. İ don't want it to resize when i open the device keyboard. Can you help me?

**Comment by littleGnAl** [comment]
https://stackoverflow.com/questions/46551268/when-the-keyboard-appears-the-flutter-widgets-resize-how-to-prevent-this

**Comment by alpcanm** [comment]
Thanks for answer
