### ISSUE TITLE
RenderMode not working for flutter texture rendering

### ISSUE THREAD

**Issue by trevorwang** [AgoraIO-Extensions/Agora-Flutter-SDK#813]
**Describe the bug**

**To Reproduce**
1. Run macOS example
2. Open join_channel_video
3. search and wrap AgoraVideoView in a SizedBox
 ```
 SizedBox(
                      width: 50,
                      height: 200,
                      child: AgoraVideoView(
....
```
4. UI will be reloaded automatically

**Expected behavior**
Video should be displayed and not be stretched

**Screenshots**
![Screenshot 2022-11-11 at 11 11 58](https://user-images.githubusercontent.com/121966/201254892-c7945c84-8f97-48f3-a4a5-1686f66831a5.png)

**Desktop (please complete the following information):**
macOS : 13.0 (22A380)
flutter 3.3.8

**Additional context**
it works well on iOS platform

**Comment by littleGnAl** [comment]
Thanks for reporting, this is a known issue, which will be faced on macOS/Windows.

**Comment by trevorwang** [comment]
Is there a target milestone to fix this? Or any workaround solutions here?

When I try to preview local videos from the camera or screen captured,  the video ratio is not known before joining the channel

I have tried the below callbacks
-  `onLocalVideoStats` :   
the local video size is notified after joining the channel
- `onFirstLocalVideoFrame` 
**_this method is not called at all_**
- `onVideoSizeChanged`
It seems only to be called when the remote video changes.  There's no UID which equals 0

**Comment by littleGnAl** [comment]
This fix is planned, but there's no timeline guarantee yet.

I think there's a theoretical solution but without verification. I think you can try to register the `VideoFrameObserver` (see `MediaEngine.registerVideoFrameObserver`) to get the local video size from `onCaptureVideoFrame` and remote video size from `onRenderVideoFrame`.

**Comment by trevorwang** [comment]
Hi @littleGnAl 

I have done some tests by the following code. And the camera video size is captured by the callback method.

The weird thing is that `onCaptureVideoFrame` is called when I start to share the screen. `onScreenCaptureVideoFrame` is **_NOT_** invoked as the docment mentioned

```
    _engine.getMediaEngine().registerVideoFrameObserver(
          VideoFrameObserver(
            onCaptureVideoFrame: (videoFrame) {
              logger.i(
                  "onCaptureVideoFrame ${videoFrame.width} ${videoFrame.height}");
            },
            onSecondaryScreenCaptureVideoFrame: (videoFrame) {
              logger.i(
                  "onSecondaryScreenCaptureVideoFrame ${videoFrame.width} ${videoFrame.height}");
            },
            onScreenCaptureVideoFrame: (videoFrame) {   // not invoked while sharing screen
              logger.i(
                  "onScreenCaptureVideoFrame ${videoFrame.width} ${videoFrame.height}");
            },
          ),
        );
```

**Comment by littleGnAl** [comment]
@trevorwang 
> The weird thing is that onCaptureVideoFrame is called when I start to share the screen. onScreenCaptureVideoFrame is NOT invoked as the docment mentioned

I think it had been fixed on `main` branch.

**Comment by trevorwang** [comment]
It works on the latest code.

Any idea why `onFirstLocalVideoFrame ` was not called?

**Comment by littleGnAl** [comment]
The `onFirstLocalVideoFrame ` is not fired if rendered by raw data. Since the `AgoraVideoView` is rendered by raw data on macOS/Windows underlying, so the callback is not called.

**Comment by trevorwang** [comment]
@littleGnAl 

Thanks for your explanation. Clear now.

**Comment by littleGnAl** [comment]
Render mode is supported on macOS/Windows/iOS flutter texture rendering in the `main` branch.

**Comment by littleGnAl** [comment]
This should be supported in version > 6.1.1
