### ISSUE TITLE
Event callbacks don't work after navigation

### ISSUE THREAD

**Issue by MaxTenco** [AgoraIO-Extensions/Agora-Flutter-SDK#814]
**Describe the bug**
I have two pages:
- Home: there is a button to go to the "Agora page"
- Agora: where can I enter and leave a channel

The first time I enter a channel, everything works.
Then I try to go back to the home page, I click on the button to go to the Agora page.
When I try to click the "Join" button, the callback event on JoinChannelSuccess doesn't fire.
So I notice that after browsing the event callbacks no longer fire.

I used the example of [docs](https://docs.agora.io/en/voice-calling/get-started/get-started-sdk?platform=flutter).

**To Reproduce**
1. Launch the app
2. Click on the button 'Go to Agora Call'
3. Click on the button 'Join'
4. The text change from "Join a channel" to "Waiting for a remote user to join..."
5. Click on the button 'Leave'
6.  The text change from "Waiting for a remote user to join..." to "Join a channel"
7. Click on back arrow
8. Click on the button 'Go to Agora Call'
9.  Click on the button 'Join'
10. The text doesn't change, the event JoinChannelSuccess was not fired

**Expected behavior**
I expect that the event callbacks work always also with navigation

**Additional context**
[Here](https://github.com/MaxTenco/agora-test) there is the project
Please fix the bug

**Comment by devangktailor** [comment]
Hello,

I am also facing this same issue in my application.


In my application there is a home page and I move into the details of user page and click on the video button and request for the call It works well at the first time. Also, I entered into the channel. At the first time I get the callback into the into the event, but at the second time I can not get the callback into the event.

But In my case audio is working fine, but I can not get the video stream in the event.

**To Reproduce**

Steps to reproduce the behavior:

1. Launch the app
2. Get the list of user the home page
3. Navigate to the user detail page
4. Open one dialog for the video request when I clicked on the request I joined the agora channel.
5. Disconnect the call and leave to the channel.
6. Agian folow the process from step 4.
7. Audio is working but video stream not work.

Please look into this and help me for same.

**Comment by devhardikbeladiya** [comment]
I have found a fix and it's working fine for me.

try adding following line while you are disposing the widget.

@override
  void dispose() {
    _engine.release();
    super.dispose();
  }

**Comment by littleGnAl** [comment]
As @devhardikbeladiya stated, the `RtcEngine` needs to be released on `dispose` callback.

**Comment by littleGnAl** [comment]
This is the doc issue, I have submitted an issue to the doc repo.
https://github.com/AgoraIO/Docs-Source/issues/876

**Comment by MaxTenco** [comment]
Now, everything works.
Thanks
