### ISSUE TITLE
6.0 muteLocalVideoStream, muteLocalAudioStream is NOT working

### ISSUE THREAD

**Issue by ThangD** [AgoraIO-Extensions/Agora-Flutter-SDK#815]
**Describe the bug**
muteLocalVideoStream, muteLocalAudioStream is NOT working on version 6.0

**To Reproduce**
1. Go to example
2. Click on 'join_channel_video'
3. Add option 'muteLocalVideoStream', 'muteLocalAudioStream'

**Expected behavior**
Others in the channel updated base on muteLocalVideoStream/ muteLocalAudioStream.

**Desktop (please complete the following information):**
 - OS: MACOS

**Additional context**
It is working on the 5.x version

**Comment by ThangD** [comment]
@littleGnAl Could you pls help to take a look on this one?

**Comment by littleGnAl** [comment]
I think you can try [onUserMuteAudio](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/1bdb923668e1be27541cb5c331e2daa30d4079ec/lib/src/agora_rtc_engine.dart#L1820) or [onUserMuteVideo](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/1bdb923668e1be27541cb5c331e2daa30d4079ec/lib/src/agora_rtc_engine.dart#L1829) callback.

**Comment by Qimeron** [comment]
interface/cpp/rtc_engine/IAgoraRtcEngine.h

`  /** Occurs when a remote user's audio stream playback pauses/resumes.

     The SDK triggers this callback when the remote user stops or resumes sending the audio stream by
     calling the `muteLocalAudioStream` method.

     @note This callback can be inaccurate when the number of users (in the `COMMUNICATION` profile) or hosts (in the `LIVE_BROADCASTING` profile) in the channel exceeds 17.

     @param uid The user ID.
     @param muted Whether the remote user's audio stream is muted/unmuted:
     - true: Muted.
     - false: Unmuted.
     */
  virtual void onUserMuteAudio(uid_t uid, bool muted) {
    (void)uid;
    (void)muted;
  }

  /** Occurs when a remote user pauses or resumes sending the video stream.
   *
   * When a remote user calls `muteLocalVideoStream` to stop or resume publishing the video stream, the
   * SDK triggers this callback to report the state of the remote user's publishing stream to the local
   * user.

   @note This callback is invalid when the number of users or broadacasters in a
   channel exceeds 20.

   @param userId ID of the remote user.
   @param muted Whether the remote user stops publishing the video stream:
   - true: The remote user has paused sending the video stream.
   - false: The remote user has resumed sending the video stream.
   */
  virtual void onUserMuteVideo(uid_t userId, bool muted) {
    (void)userId;
    (void)muted;
  }`

**Comment by ThangD** [comment]
@littleGnAl When HOST muteLocalAudioStream/ muteLocalVideoStream, it is not effect. Audience still heard and see the HOST.

**Comment by Qimeron** [comment]
> @littleGnAl When HOST muteLocalAudioStream/ muteLocalVideoStream, it is not effect. Audience still heard and see the HOST.

may I get your help to get the logs?

**Comment by Qimeron** [comment]
> @littleGnAl When HOST muteLocalAudioStream/ muteLocalVideoStream, it is not effect. Audience still heard and see the HOST.

may I get your help to get the logs?

**Comment by ThangD** [comment]
@Qimeron Thank you so much. Seem we can use the new function: enableAudio(),   enableVideo() for replacing in the new version. Just need to confirm.

**Comment by ThangD** [comment]
@littleGnAl @Qimeron Could you pls help to confirm? i used enableAudio(), enableVideo(), it can stop PULISH video/ audio but can not received video/audio as well.

**Comment by littleGnAl** [comment]
This work on my side, can you share a reproducible demo of this issue?
