### ISSUE TITLE
e: /Users/wumingshi/Downloads/flutter3.3.4/.pub-cache/hosted/pub.flutter-io.cn/agora_rtc_engine-5.1.0/android/src/main/kotlin/io/agora/agora_rtc_engine/AgoraRtcEnginePlugin.kt: (251, 18): Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by wumingshicong** [AgoraIO-Extensions/Agora-Flutter-SDK#816]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by littleGnAl** [comment]
Please try `agora_rtc_engine: ^6.0.0`.
