### ISSUE TITLE
[6.0.0] Mobile - RtcEngineEx.joinChannelEx is FAILED with clientRoleAudience

### ISSUE THREAD

**Issue by ThangD** [AgoraIO-Extensions/Agora-Flutter-SDK#818]
**Describe the bug**
Mobile - RtcEngineEx.joinChannelEx is FAILED with clientRoleAudience

**To Reproduce**
1. Go to 'example'
2. Click on 'ScreenSharing'
3. Change joinChannel with clientRoleAudience role
4. Error with exception :
`E/flutter (16566): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: AgoraRtcException(-17, null)
E/flutter (16566): #0      RtcEngineExImpl.joinChannelEx (package:agora_rtc_engine/src/binding/agora_rtc_engine_ex_impl.dart:43:7)
E/flutter (16566): <asynchronous suspension>
E/flutter (16566): #1      _State._joinChannel (package:agora_rtc_engine_example/examples/advanced/screen_sharing/screen_sharing.dart:113:7)
E/flutter (16566): <asynchronous suspension>`

**Expected behavior**
No error occurs, can join channel successfully.

**Desktop (please complete the following information):**
 - 
**Smartphone (please complete the following information):**
 - Device: SamSung A50

**Additional context**
Work wells on desktop (MACOS)

**Comment by ThangD** [comment]
@littleGnAl Could you pls help to take a look on this one? Thank you.

**Comment by littleGnAl** [comment]
Error code `-17` means the user has joined the channel, you need to leave the channel first.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/1bdb923668e1be27541cb5c331e2daa30d4079ec/lib/src/agora_base.dart#L249

**Comment by ThangD** [comment]
@littleGnAl No user joined the channel yet, you can reproduce like the step i described above. No problem with desktop, only happen with mobile.

**Comment by littleGnAl** [comment]
Do you use the same uid?

**Comment by littleGnAl** [comment]
This change works fine.
<img width="703" alt="image" src="https://user-images.githubusercontent.com/8847263/202357409-d46e4b5e-bcd6-4b45-b368-a4be5d5cc2d1.png">
