### ISSUE TITLE
Invalid argument(s): Failed to load dynamic library 'libiris_event_handler.so': dlopen failed: library "libiris_event_handler.so" not found

### ISSUE THREAD

**Issue by sauravdpl** [AgoraIO-Extensions/Agora-Flutter-SDK#819]
**Describe the bug**
Added all the example code from the agora website  [https://docs.agora.io/en/interactive-live-streaming/get-started/get-started-sdk?platform=flutter](official agora website). When testing the live stream from the android app live stream was not working. On the Console, it throw the error : 
Invalid argument(s): Failed to load dynamic library 'libiris_event_handler.so': dlopen failed: library "libiris_event_handler.so" not found

**To Reproduce**
1. Go to [https://docs.agora.io/en/interactive-live-streaming/get-started/get-started-sdk?platform=flutter](offical agora website)
2. Add all the code from site to the flutter app.
3. Run app 
4. Select host option 
5.  Click on the join   

**Expected behavior**
Using example code from the official site of agora live stream example should be working.

**Screenshots**
![Capturesssss](https://user-images.githubusercontent.com/109728647/201958966-e85cf798-7b34-4eaa-9a9e-91f3d54bc6cb.PNG)

**Smartphone :**
 - Device: Pixel 5 android emulator
 - OS: Android 11 (API 30)

**Comment by littleGnAl** [comment]
I think a reproducible demo for this issue if helpful.

**Comment by sauravdpl** [comment]
I have listed steps in "To Reproduce" section

**Comment by maerlynflagg** [comment]
i had this issue yesterday after upgrade to 6.0.0, too. like you, i had the issue on emulator, not on a real device.

**Smartphone**

- Device: Google Pixel 3 Android Emulator
- OS: API 29 Android

**Comment by littleGnAl** [comment]
Only support `x86_64 ` arch for the emulator.

**Comment by roman-stakhovskyi** [comment]
Same issue after upgrade to 6.0.0, on real device Xiaomi Redmi 4 Pro

**Comment by huzaifansari54** [comment]
same issue

**Comment by huzaifansari54** [comment]
here it what i get as error
![Capturez](https://user-images.githubusercontent.com/78638431/208623415-8fe58b14-7e27-4789-b621-59c7aa4652e4.JPG)
  
can any one help please

**Comment by Tinsae-Ayana** [comment]
I'm facing same issue. have anyone got the solution?

**Comment by amsyary** [comment]
any sollution about this error.?

**Comment by vangtry** [comment]
Any solution about this error ??

**Comment by umarfarooqweb** [comment]
Any solution about this error ??

**Comment by ElshiatyTube** [comment]
Any solution??

**Comment by littleGnAl** [comment]
If you meet this error, please check the steps below:
1. If you run on an android emulator, the `libiris_event_handler.so` only support `x86_64`  arch
2. Please check `pubspec.lock` if there's `iris_event` package, if not run `flutter packages get` first
3. Please run `flutter clean` first before building
