### ISSUE TITLE
[6.0] setVideoEncoderConfiguration not effect on the "onRemoteVideoStats" event

### ISSUE THREAD

**Issue by ThangD** [AgoraIO-Extensions/Agora-Flutter-SDK#821]
**Describe the bug**
setVideoEncoderConfiguration not effect on the "onRemoteVideoStats" event

**To Reproduce**
1. Go to 'example'
2. Click on 'join_channel_video', 
3. Change setVideoEncoderConfiguration t0
 ` await _engine.setVideoEncoderConfiguration(
      const VideoEncoderConfiguration(
        dimensions: VideoDimensions(width: 480, height: 480),
        frameRate: 15,
        bitrate: 0,
      ),
    );`
5. Others user in channel listen event: onRemoteVideoStats
6. Result is 
`flutter: [Agora] onRemoteVideoStats , state: {uid: 40, delay: 34, width: 360, height: 640, receivedBitrate: 777, decoderOutputFrameRate: 14, rendererOutputFrameRate: 14, frameLossRate: 0, packetLossRate: 0, rxStreamType: 0, totalFrozenTime: 0, frozenRate: 0, avSyncTimeMs: 0, totalActiveTime: 0, publishDuration: 0, superResolutionType: 0}`

**Expected behavior**
onRemoteVideoStats should be the same with user configured is: 480x480

**Additional context**
Works on 5.3 version.

**Comment by littleGnAl** [comment]
I think you should ensure whether uid 40 calls the `_engine.setVideoEncoderConfiguration` function.
BTW, I think you can fork and change the demo if this can be reproducibly by our example, so I can find the issue more easily.
