### ISSUE TITLE
ArgumentError (Invalid argument(s): Failed to load dynamic library 'libiris_event_handler.so': dlopen failed: library "libiris_event_handler.so" not found)

### ISSUE THREAD

**Issue by navidanchitrali** [AgoraIO-Extensions/Agora-Flutter-SDK#824]
i am facing two errors  please help!

1.  when i press te join channel button :  ArgumentError (Invalid argument(s): Failed to load dynamic library 'libiris_event_handler.so': dlopen failed: library "libiris_event_handler.so" not found)

2.  . when i press the camera front button :  LateError (LateInitializationError: Field 'requestPort' has not been initialized.)
  
the code i am trying : 

      import 'package:agora_rtc_engine/agora_rtc_engine.dart';
      import 'package:chat_in_english/ui/screens/dashboard/video%20broadcoast/example_actions_widget.dart';
      import 'package:chat_in_english/ui/screens/dashboard/video%20broadcoast/log_sink.dart';
   
      import 'package:flutter/foundation.dart';
      import 'package:flutter/material.dart';
      import 'package:permission_handler/permission_handler.dart';
      
      /// MultiChannel Example
      class JoinChannelVideo extends StatefulWidget {
        /// Construct the [JoinChannelVideo]
        const JoinChannelVideo({Key? key}) : super(key: key);
      
        @override
        State<StatefulWidget> createState() => _State();
      }
      
      class _State extends State<JoinChannelVideo> {
        late final RtcEngine _engine;
        bool _isReadyPreview = false;
      
        bool isJoined = false, switchCamera = true, switchRender = true;
        Set<int> remoteUid = {};
        late TextEditingController _controller;
        bool _isUseFlutterTexture = false;
        bool _isUseAndroidSurfaceView = false;
        ChannelProfileType _channelProfileType =
            ChannelProfileType.channelProfileLiveBroadcasting;
      
        @override
        void initState() {
          super.initState();
          _requestPermissionIfNeed();
          _controller = TextEditingController(text: 'testchannel');
      
          _initEngine();
        }
      
        @override
        void dispose() {
          super.dispose();
          _dispose();
        }
      
        Future<void> _dispose() async {
          await _engine.leaveChannel();
          await _engine.release();
        }
      
        Future<void> _requestPermissionIfNeed() async {
          if (defaultTargetPlatform == TargetPlatform.android) {
            await [Permission.microphone, Permission.camera].request();
          }
        }
      
        Future<void> _initEngine() async {
          _engine = createAgoraRtcEngine();
          await _engine.initialize(RtcEngineContext(
            appId: 'b3bee66900fd4bc9af9622016796c74b',
          ));
      
          _engine.registerEventHandler(RtcEngineEventHandler(
            onError: (ErrorCodeType err, String msg) {
              logSink.log('[onError] err: $err, msg: $msg');
            },
            onJoinChannelSuccess: (RtcConnection connection, int elapsed) {
              logSink.log(
                  '[onJoinChannelSuccess] connection: ${connection.toJson()} elapsed: $elapsed');
              setState(() {
                isJoined = true;
              });
            },
            onUserJoined: (RtcConnection connection, int rUid, int elapsed) {
              logSink.log(
                  '[onUserJoined] connection: ${connection.toJson()} remoteUid: $rUid elapsed: $elapsed');
              setState(() {
                remoteUid.add(rUid);
              });
            },
            onUserOffline:
                (RtcConnection connection, int rUid, UserOfflineReasonType reason) {
              logSink.log(
                  '[onUserOffline] connection: ${connection.toJson()}  rUid: $rUid reason: $reason');
              setState(() {
                remoteUid.removeWhere((element) => element == rUid);
              });
            },
            onLeaveChannel: (RtcConnection connection, RtcStats stats) {
              logSink.log(
                  '[onLeaveChannel] connection: ${connection.toJson()} stats: ${stats.toJson()}');
              setState(() {
                isJoined = false;
                remoteUid.clear();
              });
            },
          ));
      
          await _engine.enableVideo();
      
          await _engine.setVideoEncoderConfiguration(
            const VideoEncoderConfiguration(
              dimensions: VideoDimensions(width: 640, height: 360),
              frameRate: 15,
              bitrate: 0,
            ),
          );
      
          await _engine.startPreview();
      
          setState(() {
            _isReadyPreview = true;
          });
        }
      
        Future<void> _joinChannel() async {
          await _engine.joinChannel(
            token:
                '007eJxTYBBpmDv9g1ZRxRyhyx3sW6tP298zM77yQ+8Xh3f01nfa10MUGJKMk1JTzcwsDQzSUkySki0T0yzNjIwMDM3MLc2SzU2SLkpUJDcEMjI884hjZWSAQBCfm6EktbgkOSMxLy81h4EBAFglIqM=',
            channelId: _controller.text,
            uid: config.uid,
            options: ChannelMediaOptions(
              channelProfile: _channelProfileType,
              clientRoleType: ClientRoleType.clientRoleBroadcaster,
            ),
          );
        }
      
        Future<void> _leaveChannel() async {
          await _engine.leaveChannel();
        }
      
        Future<void> _switchCamera() async {
          await _engine.switchCamera();
          setState(() {
            switchCamera = !switchCamera;
          });
        }
      
        @override
        Widget build(BuildContext context) {
          return Scaffold(
            body: ExampleActionsWidget(
              displayContentBuilder: (context, isLayoutHorizontal) {
                if (!_isReadyPreview) return Container();
                return Stack(
                  children: [
                    AgoraVideoView(
                      controller: VideoViewController(
                        rtcEngine: _engine,
                        canvas: const VideoCanvas(uid: 0),
                        useFlutterTexture: _isUseFlutterTexture,
                        useAndroidSurfaceView: _isUseAndroidSurfaceView,
                      ),
                    ),
                    Align(
                      alignment: Alignment.topLeft,
                      child: SingleChildScrollView(
                        scrollDirection: Axis.horizontal,
                        child: Row(
                          children: List.of(remoteUid.map(
                            (e) => SizedBox(
                              width: 120,
                              height: 120,
                              child: AgoraVideoView(
                                controller: VideoViewController.remote(
                                  rtcEngine: _engine,
                                  canvas: VideoCanvas(uid: e),
                                  connection:
                                      RtcConnection(channelId: _controller.text),
                                  useFlutterTexture: _isUseFlutterTexture,
                                  useAndroidSurfaceView: _isUseAndroidSurfaceView,
                                ),
                              ),
                            ),
                          )),
                        ),
                      ),
                    )
                  ],
                );
              },
              actionsBuilder: (context, isLayoutHorizontal) {
                final channelProfileType = [
                  ChannelProfileType.channelProfileLiveBroadcasting,
                  ChannelProfileType.channelProfileCommunication,
                ];
                final items = channelProfileType
                    .map((e) => DropdownMenuItem(
                          child: Text(
                            e.toString().split('.')[1],
                          ),
                          value: e,
                        ))
                    .toList();
      
                return Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    TextField(
                      controller: _controller,
                      decoration: const InputDecoration(hintText: 'Channel ID'),
                    ),
                    if (!kIsWeb &&
                        (defaultTargetPlatform == TargetPlatform.android ||
                            defaultTargetPlatform == TargetPlatform.iOS))
                      Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        children: [
                          if (defaultTargetPlatform == TargetPlatform.iOS)
                            Column(
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  const Text('Rendered by Flutter texture: '),
                                  Switch(
                                    value: _isUseFlutterTexture,
                                    onChanged: isJoined
                                        ? null
                                        : (changed) {
                                            setState(() {
                                              _isUseFlutterTexture = changed;
                                            });
                                          },
                                  )
                                ]),
                          if (defaultTargetPlatform == TargetPlatform.android)
                            Column(
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.start,
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  const Text('Rendered by Android SurfaceView: '),
                                  Switch(
                                    value: _isUseAndroidSurfaceView,
                                    onChanged: isJoined
                                        ? null
                                        : (changed) {
                                            setState(() {
                                              _isUseAndroidSurfaceView = changed;
                                            });
                                          },
                                  ),
                                ]),
                        ],
                      ),
                    const SizedBox(
                      height: 20,
                    ),
                    const Text('Channel Profile: '),
                    DropdownButton<ChannelProfileType>(
                      items: items,
                      value: _channelProfileType,
                      onChanged: isJoined
                          ? null
                          : (v) {
                              setState(() {
                                _channelProfileType = v!;
                              });
                            },
                    ),
                    const SizedBox(
                      height: 20,
                    ),
                    Row(
                      children: [
                        Expanded(
                          flex: 1,
                          child: ElevatedButton(
                            onPressed: isJoined ? _leaveChannel : _joinChannel,
                            child: Text('${isJoined ? 'Leave' : 'Join'} channel'),
                          ),
                        )
                      ],
                    ),
                    if (defaultTargetPlatform == TargetPlatform.android ||
                        defaultTargetPlatform == TargetPlatform.iOS) ...[
                      const SizedBox(
                        height: 20,
                      ),
                      ElevatedButton(
                        onPressed: _switchCamera,
                        child: Text('Camera ${switchCamera ? 'front' : 'rear'}'),
                      ),
                    ],
                  ],
                );
              },
            ),
          );
           
        }
      }

**Comment by uktamjon-komilov** [comment]
Same issue!

`

import 'package:agora_rtc_engine/agora_rtc_engine.dart';
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';

String appId = "67703ad3fdd7459eb1d9703c9789f7b3";

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  String channelName = "test";
  String token =
      "007eJxTYGipVDl99/+s6Vm9O+Zd2noqpP50RJ7P1wni1pZPTxxcOCdGgcHM3NzAODHFOC0lxdzE1DI1yTDFEiiSbGluYZlmnmRSvbwiuSGQkWGDpxorIwMEgvgsDCWpxSUMDAAtFCHY3";

  int uid = 0; // uid of the local user

  int? _remoteUid; // uid of the remote user
  bool _isJoined = false; // Indicates if the local user has joined the channel
  late RtcEngine agoraEngine; // Agora engine instance

  // Global key to access the scaffold
  final GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey =
      GlobalKey<ScaffoldMessengerState>();

  showMessage(String message) {
    scaffoldMessengerKey.currentState?.showSnackBar(
      SnackBar(content: Text(message)),
    );
  }

  @override
  void initState() {
    super.initState();
    setupVoiceSDKEngine();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      scaffoldMessengerKey: scaffoldMessengerKey,
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Get started with Voice Calling'),
        ),
        body: ListView(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
          children: [
            // Status text
            SizedBox(
              height: 40,
              child: Center(
                child: _status(),
              ),
            ),
            // Button Row
            Row(
              children: <Widget>[
                Expanded(
                  child: ElevatedButton(
                    child: const Text("Join"),
                    onPressed: () => {join()},
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: ElevatedButton(
                    child: const Text("Leave"),
                    onPressed: () => {leave()},
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _status() {
    String statusText;

    if (!_isJoined) {
      statusText = 'Join a channel';
    } else if (_remoteUid == null) {
      statusText = 'Waiting for a remote user to join...';
    } else {
      statusText = 'Connected to remote user, uid:$_remoteUid';
    }

    return Text(
      statusText,
    );
  }

  void join() async {
    // Set channel options including the client role and channel profile
    ChannelMediaOptions options = const ChannelMediaOptions(
      clientRoleType: ClientRoleType.clientRoleBroadcaster,
      channelProfile: ChannelProfileType.channelProfileCommunication,
    );

    await agoraEngine.joinChannel(
      token: token,
      channelId: channelName,
      options: options,
      uid: uid,
    );
  }

  void leave() {
    setState(() {
      _isJoined = false;
      _remoteUid = null;
    });
    agoraEngine.leaveChannel();
  }

  Future<void> setupVoiceSDKEngine() async {
    // retrieve or request microphone permission
    await [Permission.microphone].request();

    //create an instance of the Agora engine
    agoraEngine = createAgoraRtcEngine();
    await agoraEngine.initialize(RtcEngineContext(appId: appId));

    // Register the event handler
    agoraEngine.registerEventHandler(
      RtcEngineEventHandler(
        onJoinChannelSuccess: (RtcConnection connection, int elapsed) {
          showMessage(
              "Local user uid:${connection.localUid} joined the channel");
          setState(() {
            _isJoined = true;
          });
        },
        onUserJoined: (RtcConnection connection, int remoteUid, int elapsed) {
          showMessage("Remote user uid:$remoteUid joined the channel");
          setState(() {
            _remoteUid = remoteUid;
          });
        },
        onUserOffline: (RtcConnection connection, int remoteUid,
            UserOfflineReasonType reason) {
          showMessage("Remote user uid:$remoteUid left the channel");
          setState(() {
            _remoteUid = null;
          });
        },
      ),
    );
  }

  // Clean up the resources when you leave
  @override
  void dispose() async {
    await agoraEngine.leaveChannel();
    super.dispose();
  }
}


`

**Comment by uktamjon-komilov** [comment]
Same issue!

```

import 'package:agora_rtc_engine/agora_rtc_engine.dart';
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';

String appId = "67703ad3fdd7459eb1d9703c9789f7b3";

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  String channelName = "test";
  String token =
      "007eJxTYGipVDl99/+s6Vm9O+Zd2noqpP50RJ7P1wni1pZPTxxcOCdGgcHM3NzAODHFOC0lxdzE1DI1yTDFEiiSbGluYZlmnmRSvbwiuSGQkWGDpxorIwMEgvgsDCWpxSUMDAAtFCHY3";

  int uid = 0; // uid of the local user

  int? _remoteUid; // uid of the remote user
  bool _isJoined = false; // Indicates if the local user has joined the channel
  late RtcEngine agoraEngine; // Agora engine instance

  // Global key to access the scaffold
  final GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey =
      GlobalKey<ScaffoldMessengerState>();

  showMessage(String message) {
    scaffoldMessengerKey.currentState?.showSnackBar(
      SnackBar(content: Text(message)),
    );
  }

  @override
  void initState() {
    super.initState();
    setupVoiceSDKEngine();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      scaffoldMessengerKey: scaffoldMessengerKey,
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Get started with Voice Calling'),
        ),
        body: ListView(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
          children: [
            // Status text
            SizedBox(
              height: 40,
              child: Center(
                child: _status(),
              ),
            ),
            // Button Row
            Row(
              children: <Widget>[
                Expanded(
                  child: ElevatedButton(
                    child: const Text("Join"),
                    onPressed: () => {join()},
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: ElevatedButton(
                    child: const Text("Leave"),
                    onPressed: () => {leave()},
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _status() {
    String statusText;

    if (!_isJoined) {
      statusText = 'Join a channel';
    } else if (_remoteUid == null) {
      statusText = 'Waiting for a remote user to join...';
    } else {
      statusText = 'Connected to remote user, uid:$_remoteUid';
    }

    return Text(
      statusText,
    );
  }

  void join() async {
    // Set channel options including the client role and channel profile
    ChannelMediaOptions options = const ChannelMediaOptions(
      clientRoleType: ClientRoleType.clientRoleBroadcaster,
      channelProfile: ChannelProfileType.channelProfileCommunication,
    );

    await agoraEngine.joinChannel(
      token: token,
      channelId: channelName,
      options: options,
      uid: uid,
    );
  }

  void leave() {
    setState(() {
      _isJoined = false;
      _remoteUid = null;
    });
    agoraEngine.leaveChannel();
  }

  Future<void> setupVoiceSDKEngine() async {
    // retrieve or request microphone permission
    await [Permission.microphone].request();

    //create an instance of the Agora engine
    agoraEngine = createAgoraRtcEngine();
    await agoraEngine.initialize(RtcEngineContext(appId: appId));

    // Register the event handler
    agoraEngine.registerEventHandler(
      RtcEngineEventHandler(
        onJoinChannelSuccess: (RtcConnection connection, int elapsed) {
          showMessage(
              "Local user uid:${connection.localUid} joined the channel");
          setState(() {
            _isJoined = true;
          });
        },
        onUserJoined: (RtcConnection connection, int remoteUid, int elapsed) {
          showMessage("Remote user uid:$remoteUid joined the channel");
          setState(() {
            _remoteUid = remoteUid;
          });
        },
        onUserOffline: (RtcConnection connection, int remoteUid,
            UserOfflineReasonType reason) {
          showMessage("Remote user uid:$remoteUid left the channel");
          setState(() {
            _remoteUid = null;
          });
        },
      ),
    );
  }

  // Clean up the resources when you leave
  @override
  void dispose() async {
    await agoraEngine.leaveChannel();
    super.dispose();
  }
}


```

**Comment by littleGnAl** [comment]
Duplicated https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/819

**Comment by Tinsae-Ayana** [comment]
I am facing the same issue. Anybody got the solution?

**Comment by umarfarooqweb** [comment]
anybody got the solution
