### ISSUE TITLE
Black Screen local iOS/Android

### ISSUE THREAD

**Issue by maerlynflagg** [AgoraIO-Extensions/Agora-Flutter-SDK#825]
hello,

we work with a flutter app (sender) and WebPage (receiver). encryption is enabled.  this worked fine for some month. now i upgraded to Agora 6.0.0 on app and i get black screen.

```
FireFox 107.0
agora_rtc_engine: ^6.0.0
```

the receiver has video and audio. all is fine.  but now, the app's have only audio and black screen.

some code snippets:

```
    await _initAgoraRtcEngine();
    _addAgoraEventHandlers();

    await _engine.joinChannel(token: widget.token, channelId: widget.channelId, uid: 999, options: const ChannelMediaOptions());
```

```
  /// Create agora sdk instance and initialize
  Future<void> _initAgoraRtcEngine() async {
    _engine = createAgoraRtcEngine();

    await _engine.initialize(const RtcEngineContext(
      appId: NtagConstants.AGORA_APP_ID,
      channelProfile: ChannelProfileType.channelProfileCommunication,
    ));

    await _engine.enableVideo();
    await _engine.switchCamera();
    await _engine.enableEncryption(enabled: true, config: EncryptionConfig(encryptionMode: EncryptionMode.aes256Xts, encryptionKey: widget.secret));

    await _engine.startPreview();
  }
```

```
  /// Event Handler setzen
  void _addAgoraEventHandlers() {
    _engine.registerEventHandler(RtcEngineEventHandler(
      onLeaveChannel: (RtcConnection con, RtcStats stats) {
        setState(() {
          _users.clear();
        });
      },
      onUserJoined: (RtcConnection con, int uid, int elapsed) {
        setState(() {
          _users.add(uid);
          _localUserJoined = true;
        });
      },
      onUserOffline: (RtcConnection con, int uid, UserOfflineReasonType reason) {
        setState(() {
          _users.remove(uid);
        });
      },
    ));
  }
```

```
                Container(
                  child: _localUserJoined
                      ? AgoraVideoView(
                          controller: VideoViewController(
                            rtcEngine: _engine,
                            canvas: const VideoCanvas(uid: 999),
                          ),
                        )
                      : Container(
                        child: const Center(
                          child: CircularProgressIndicator()
                        ),
                      ),
                ),
```

the CircularProgressIndicator is every time gone and the AgoraVideoView is black.

by the way, in Chrome is only audio on receiver.

I'm not sure if it's a bug or if I forgot something to upgrade to 6.0.0. Any ideas?

**Comment by littleGnAl** [comment]
You should render a valid user id which saves in the `_users`, please check our example for how to implement the video rendering.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/1bdb923668e1be27541cb5c331e2daa30d4079ec/example/lib/examples/basic/join_channel_video/join_channel_video.dart#L135

**Comment by Tpow99** [comment]
Steps in the provided do not work, local preview still blank

**Comment by maerlynflagg** [comment]
> You should render a valid user id which saves in the `_users`, please check our example for how to implement the video rendering.
> 
> https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/1bdb923668e1be27541cb5c331e2daa30d4079ec/example/lib/examples/basic/join_channel_video/join_channel_video.dart#L135

Thank you for response. one problem is solved. after the update to 6.0.0 the constellation firefox and flutter app works again. audio and video are now available for both.

I forgot the second AgoraVideoView. 

```
AgoraVideoView(
              controller: VideoViewController(
                rtcEngine: _engine,
                canvas: const VideoCanvas(uid: 0),
           
              ),
            ),
```
now, this case ist fine.


for information:

in the Chrome and flutter app constellation, the app has video and audio, but the browser only receives audio. in the video it looks like nothing is happening.

**Comment by moneer-muntazah** [comment]
@littleGnAl  what is a valid user id, and does the value passed to `VideoCanvas` has to match the rtc user id encoded in the token?

**Comment by littleGnAl** [comment]
@moneer-muntazah 
Can you please raise a new issue for your problem, thanks?
