### ISSUE TITLE
Mobile - is it possible to share video and screen at the same time?

### ISSUE THREAD

**Issue by bhavinb98** [AgoraIO-Extensions/Agora-Flutter-SDK#834]
This is more of a help question than a bug/feature report.

Flutter Agora version - 6.0.0

I tried going through the Agora docs but there isn't anything explicitly stated anywhere that video publishing should be turned off while sharing the screen.

These are the docs I referred:-
    SDK 4 docs - https://docs.agora.io/en/video-calling/develop/product-workflow?platform=flutter

Is it possible to share video and screen at the same time?

Also, is it possible for multiple users to share their screen at the same time?

What are the restrictions for screen sharing?

**Comment by bhavinb98** [comment]
So here you are setting `false` for `publishCameraTrack` and `publishMicrophoneTrack`, so you are muting the video and audio of the user who is sharing the screen, correct? 
Is this mandatory?
Also, why do you need to stop publishing microphone track as well?

```
await _engine.updateChannelMediaOptionsEx(
      options: const ChannelMediaOptions(
        publishScreenTrack: true,
        publishSecondaryScreenTrack: true,
        publishCameraTrack: false,
        publishMicrophoneTrack: false,
        publishScreenCaptureAudio: true,
        publishScreenCaptureVideo: true,
        clientRoleType: ClientRoleType.clientRoleBroadcaster,
      ),
      connection:
          RtcConnection(channelId: _controller.text, localUid: shareShareUid),
    );
```

**Comment by littleGnAl** [comment]
`publishMicrophoneTrack ` is not mandatory, but `publishCameraTrack ` is mandatory since you can only publish screen sharing or video in one stream.

**Comment by bhavinb98** [comment]
I see. Thanks!
