### ISSUE TITLE
flutter 5.3.1 版本 屏幕共享功能在ios设备上不能正常工作

### ISSUE THREAD

**Issue by shichunlei** [AgoraIO-Extensions/Agora-Flutter-SDK#836]

**Comment by littleGnAl** [comment]
Can you provide reproducible steps or a reproducible demo for this issue?

**Comment by littleGnAl** [comment]
In our demo, please follow this step to test the screen sharing
https://docs.agora.io/cn/video-legacy/screen_sharing_flutter?platform=Flutter
<img width="797" alt="image" src="https://user-images.githubusercontent.com/8847263/206617061-ef4ee5b4-2792-4559-b896-7d93a214a62c.png">
