### ISSUE TITLE
White screen issue while switching between full and split screen during video call.

### ISSUE THREAD

**Issue by BzCod3r** [AgoraIO-Extensions/Agora-Flutter-SDK#840]
we've tested it with android 12 and android 13, what we have found is, white screen comes more frequently in android 13 as compare to android 12. need your kind support. Thanks in advance.

**Comment by littleGnAl** [comment]
Can you provide reproducible steps or a reproducible demo?

**Comment by Ghazanfarrajpoot** [comment]
![WhatsApp Image 2022-12-23 at 9 50 23 PM](https://user-images.githubusercontent.com/85117969/209429573-defce3e3-b1df-46c3-b8db-878770d4405b.jpeg)


something like this?
