### ISSUE TITLE
Live Streaming Media Push Sdk with flutter 

### ISSUE THREAD

**Issue by amityamsi** [AgoraIO-Extensions/Agora-Flutter-SDK#845]
**Is your feature request related to a problem? Please describe.**
I want to publish my live streams to other social media like Youtube,Facebook,Twitter etc But Agora not providing Sdk for that yet

**Describe the solution you'd like**
Publish Media Push Sdk for Flutter pp

**Describe alternatives you've considered**
Agora provided RestFul Api for that but there is no proper documentation or example for how to correctly use that in our Flutter code

**Comment by littleGnAl** [comment]
I think it is just the HTTP/HTTPS request for the RESTful API. You can easy to use the [http](https://pub.dev/packages/http) package or whatever you like to make a request to it.

**Comment by amityamsi** [comment]
@littleGnAl 
I done media push with the RestFul api but after so many discussion and help from agora team, because there is no proper example to do that in Flutter so it will be great to add example in Documentation

**Comment by amityamsi** [comment]
If anyone facing the same problem regarding Media Push with RESTful API then below is the blog to solve your problem
https://www.codemicros.com/2022/12/agora-media-push-with-flutter-using.html
