### ISSUE TITLE
getting void function error, please help needed

### ISSUE THREAD

**Issue by Ghazanfarrajpoot** [AgoraIO-Extensions/Agora-Flutter-SDK#850]
<img width="933" alt="Screenshot 2022-12-24 at 2 18 17 PM" src="https://user-images.githubusercontent.com/85117969/209429391-f0705e25-1af4-4e14-b09b-e1b57bb17278.png">
<img width="1211" alt="Screenshot 2022-12-24 at 2 20 35 PM" src="https://user-images.githubusercontent.com/85117969/209429415-9cb9442e-f825-4f17-a6ab-90450a7ece82.png">

**Comment by littleGnAl** [comment]
It is most likely the issue from agora_ui_kit, you should raise an issue in the agora_ui_kit repo.

**Comment by Ghazanfarrajpoot** [comment]
Ok, Moving to ZEEgocloud any way, agora's services is very Bad in Pakistan
