### ISSUE TITLE
Getting Whitish/Grey screen on calls why?? please see it's been weeks, why agora is not fixing?

### ISSUE THREAD

**Issue by Ghazanfarrajpoot** [AgoraIO-Extensions/Agora-Flutter-SDK#851]
![WhatsApp Image 2022-12-23 at 9 50 23 PM](https://user-images.githubusercontent.com/85117969/209429539-4439f86f-36cd-4690-b5bc-8e4698553829.jpeg)

**Comment by Ghazanfarrajpoot** [comment]
we are paying for agora but still issues

**Comment by littleGnAl** [comment]
Can you please provide reproducible steps or a reproducible demo? I don't think I can fix anything based on a screenshot.

**Comment by Ghazanfarrajpoot** [comment]
Worst api, Moving to Zeeogo cloud, much better and UI us modern and 4k Calls. Tired of wasting last 6 months on this garbage and error filled servies
