### ISSUE TITLE
Bug when building ... 

### ISSUE THREAD

**Issue by spkinguy1** [AgoraIO-Extensions/Agora-Flutter-SDK#853]
it shows me some Error about not compatible Data type ... 
in some Kotlin files inside library. 
the Error after using `flutter run`
e: /home/mahdi/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.2.2/android/src/main/kotlin/io/agora/agora_rtc_engine/AgoraRtcEnginePlugin.kt: (146, 18): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by littleGnAl** [comment]
Please upgrade the latest version of `agora_rtc_engine`.
