### ISSUE TITLE
Camera is being used by app after disconnecting the call

### ISSUE THREAD

**Issue by NavasKoya** [AgoraIO-Extensions/Agora-Flutter-SDK#859]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by littleGnAl** [comment]
Can you please share which platform you faced this problem with, and the reproducible steps or reproducible demo?

**Comment by NavasKoya** [comment]
Hi,
M facing the issue in agora package: agora_rtc_engine: ^6.1.0. 
Logic is: We are creating video room between 2 users. Once the video is completed by same or other user, we are forced to go to home page. by killing the process.

To kill we are using:

Future<void> _dispose() async {
    await _engine.disableAudio();
    await _engine.disableVideo();
    await _engine.stopPreview();
    await _engine.stopLocalVideoTranscoder();
    await _engine.stopAudioRecording();
    await _engine.stopAllEffects();
    await _engine.stopAudioMixing();
    await _engine.stopPrimaryCustomAudioTrack();
    await _engine.stopSecondaryCustomAudioTrack();
    await _engine.stopScreenCapture();
    await _engine.stopPrimaryCameraCapture();
    await _engine.stopSecondaryCameraCapture();
    await _engine.stopPrimaryScreenCapture();
    await _engine.stopSecondaryScreenCapture();
    await _engine.stopSecondaryCustomAudioTrack();
    await _engine.disableAudioSpectrumMonitor();
    await _engine.leaveChannel();
    await _engine.release();
  }

Once it comes to home page, caqmera won't be displayed. But we user switches app and come back again, from that point camera will be in use.

**Comment by littleGnAl** [comment]
If you call `startPreview` immediately when the APP is opened, it should be the expected behavior.
