### ISSUE TITLE
Channel Profile is Broadcasting even if it is set to Communication

### ISSUE THREAD

**Issue by moneer-muntazah** [AgoraIO-Extensions/Agora-Flutter-SDK#865]
To try this out run the example app. Use basic join channel set it to `channelProfileCommunication`

Make a call to the REST API https://docs.agora.io/en/video-calling/reference/channel-management-rest-api?platform=android#gets-the-user-list 
to query the channel and you will always get mode 2 LIVE_BROADCASTING ! 

This issue did not exist in version 5

**Comment by littleGnAl** [comment]
Thanks for reporting, it's a known issue, I will update here if any updates.

**Comment by abdallah-gaber-hoods** [comment]
any update about this?

**Comment by littleGnAl** [comment]
This issue should be fixed in the latest version, please try upgrading it to see if it works or not.
