### ISSUE TITLE
How to start recording audio call using Agora, flutter?

### ISSUE THREAD

**Issue by FaizanAhmad127** [AgoraIO-Extensions/Agora-Flutter-SDK#866]
I am successful in implementing audio and video call and tried to implement recording feature but the documentation doesn't have any option in which you can record the call and store it locally on the phone. My question is if local storing/saving of call is not possible then why there is a method for starting and stopping recording?

```
_engine.startAudioRecording(AudioRecordingConfiguration(
       fileRecordingType: AudioFileRecordingType.audioFileRecordingMixed,
       quality: AudioRecordingQualityType.audioRecordingQualityMedium,
       encode: false,
       sampleRate: 32000,
       filePath: 'yourTempPath.mp3', //don't know what to put here
       
     ));
```

**Comment by littleGnAl** [comment]
I think you may need to get an absolute path for the `filePath`, e.g.,
```dart
    Directory appDocDir = await getApplicationDocumentsDirectory();
    String p = path.join(appDocDir.path, 'example.wav');
```
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/e078d6634a3c7c5f5b1bcf0d1eeb81e37f40e7bb/example/lib/examples/advanced/media_recorder/media_recorder.dart#L134

The supported format of file please check the API doc for reference.
https://api-ref.agora.io/en/voice-sdk/flutter/6.x/API/class_irtcengine.html#ariaid-title188
