### ISSUE TITLE
agora_rtc_engine 6.1.0 startAudioMixing method is missing the replace parameter.

### ISSUE THREAD

**Issue by ChrisMICDUP** [AgoraIO-Extensions/Agora-Flutter-SDK#874]
In the latest version of Agora, the replace parameter has gone missing from from the startAudioMixing method.

The documentation implies that the functionality provided by replace=true is still available but there is no indication of how to go about this.

_[Future]<void> startAudioMixing(
{required [String] filePath,
required [bool] loopback,
required [int] cycle,
[int]startPos = 0}
)

Starts playing the music file. This method mixes the specified local or online audio file with the audio from the microphone, or replaces the microphone's audio with the specified local or remote audio file._

**Comment by ChrisMICDUP** [comment]
Found this in the migration guide: "The replace parameter in startAudioMixing: Use publishMicrophoneTrack in the ChannelMediaOptions instead."

https://docs.agora.io/en/video-calling/develop/migration-guide?platform=flutter

**Comment by littleGnAl** [comment]
Yes, it's a break change of this API.
