### ISSUE TITLE
A QUICK QUESTION: On desktop can agora detect external cameras 

### ISSUE THREAD

**Issue by Princewil** [AgoraIO-Extensions/Agora-Flutter-SDK#882]
HI, just a quick question:

Can I detect external cameras connected to my desktop using agora, if yes then how do I do that?

Can I do that for external audios too?

A quick response will be highly appreciated. Thank you

**Comment by littleGnAl** [comment]
Please check our device manager example.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/device_manager/device_manager.dart

**Comment by Princewil** [comment]
I will check it right away, but I believe this is a yes right?

**Comment by littleGnAl** [comment]
Yes, it's supported.

**Comment by Princewil** [comment]
Alright!
I have gone through the example too. 
I will implement it on my on going project, if I have any further questions I let you know. 

Thank you so much for the quick response, really appreciate it.
