### ISSUE TITLE
Unhandled Exception: LateInitializationError: Field 'requestPort' has not been initialized.

### ISSUE THREAD

**Issue by bhavykoshti** [AgoraIO-Extensions/Agora-Flutter-SDK#885]
**Describe the bug**
When you start the call after ending one call that call is not starting, even the local video view is not starting

**To Reproduce**
1. Start one call wait for both person to come live
2. End that call
3. Start Another call

**Expected behavior**
When i start another call i should be able to start it normally just like the previous one

**Smartphone (please complete the following information):**
 - Device: Redmi note 8 Pro, Pixel 6
 - OS: Android
 - Version Android 11 and 13

**Additional context**
```[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'requestPort' has not been initialized.
#0      _ApiCallExecutor.requestPort (package:agora_rtc_engine/src/impl/api_caller.dart)
#1      _ApiCallExecutor.callIrisApiWithUin8ListAsync (package:agora_rtc_engine/src/impl/api_caller.dart:280:5)
#2      ApiCaller.callIrisApiWithUin8ListAsync (package:agora_rtc_engine/src/impl/api_caller.dart:99:10)
#3      ApiCaller.callIrisApi (package:agora_rtc_engine/src/impl/api_caller.dart:107:12)
#4      RtcEngineImpl.leaveChannel (package:agora_rtc_engine/src/impl/agora_rtc_engine_impl.dart:759:25)
#5      ChatVideoCallModel.dispose (package:agreed/feature/chat/video_call/video_call_model.dart:152:18)
#6      _runGuarded (package:riverpod/src/framework/container.dart:5:7)
#7      Iterable.forEach (dart:core/iterable.dart:325:35)
#8      ProviderElementBase._runOnDispose (package:riverpod/src/framework/provider_base.dart:909:26)
#9      ProviderElementBase.dispose (package:riverpod/src/framework/provider_base.dart:860:5)
#10     ProviderContainer._disposeProvider (package:riverpod/src/framework/container.dart:354:13)
#11     _ProviderScheduler._performDispose (package:riverpod/src/framework/scheduler.dart:81:26)
#12     _ProviderScheduler._task (package:riverpod/src/framework/scheduler.dart:42:5)
#13     _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:303:12)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#17     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)

E/flutter ( 3742): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: IsolateSpawnException: Unable to spawn isolate: Could not prepare the child

E/flutter ( 3742): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'requestPort' has not been initialized.
#0      _ApiCallExecutor.requestPort (package:agora_rtc_engine/src/impl/api_caller.dart)
#1      _ApiCallExecutor.callIrisApiWithUin8ListAsync (package:agora_rtc_engine/src/impl/api_caller.dart:280:5)
#2      ApiCaller.callIrisApiWithUin8ListAsync (package:agora_rtc_engine/src/impl/api_caller.dart:99:10)
#3      ApiCaller.callIrisApi (package:agora_rtc_engine/src/impl/api_caller.dart:107:12)
#4      RtcEngineImpl.leaveChannel (package:agora_rtc_engine/src/impl/agora_rtc_engine_impl.dart:759:25)
#5      ChatVideoCallModel.dispose (package:agreed/feature/chat/video_call/video_call_model.dart:152:18)
#6      _runGuarded (package:riverpod/src/framework/container.dart:5:7)
#7      Iterable.forEach (dart:core/iterable.dart:325:35)
#8      ProviderElementBase._runOnDispose (package:riverpod/src/framework/provider_base.dart:909:26)
#9      ProviderElementBase.dispose (package:riverpod/src/framework/provider_base.dart:860:5)
#10     ProviderContainer._disposeProvider (package:riverpod/src/framework/container.dart:354:13)
#11     _ProviderScheduler._performDispose (package:riverpod/src/framework/scheduler.dart:81:26)
#12     _ProviderScheduler._task (package:riverpod/src/framework/scheduler.dart:42:5)
#13     _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:303:12)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#17     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)```

**Comment by littleGnAl** [comment]
Can you share API call logs? There should be something like the below log to the console.
```
[2023-02-06 15:07:57.542] [84585] [debug] [iris_rtc_engine_impl.cc:112] api name RtcEngine_initialize params {"context":{"appId":"******"}}
[2023-02-06 15:07:57.621] [84585] [debug] [iris_rtc_device_manager_impl.cc:29] IrisRtcDeviceManagerImpl Initialize
```

**Comment by adiShinwari** [comment]
@bhavykoshti 
 Hey did you solve it?
I am also getting the same error.

**Comment by adiShinwari** [comment]
@littleGnAl hello, 
I am also getting the same error on the same steps. I am pasting my logs below. 
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'requestPort' has not been initialized.
#0      _ApiCallExecutor.requestPort (package:agora_rtc_engine/src/impl/api_caller.dart)
api_caller.dart:1
#1      _ApiCallExecutor.callIrisApiWithUin8ListAsync
api_caller.dart:273
#2      ApiCaller.callIrisApiWithUin8ListAsync
api_caller.dart:110
#3      ApiCaller.callIrisApi
api_caller.dart:118
#4      RtcEngineImpl.setupRemoteVideo
agora_rtc_engine_impl.dart:687
#5      VideoViewControllerBaseMixin.disposeRender
video_view_controller_impl.dart:72
#6      _AgoraRtcRenderPlatformViewState._disposeRender
agora_video_view_impl.dart:115
#7      _AgoraRtcRenderPlatformViewState.dispose

**Comment by BakhtawarHabib** [comment]
did you resolve it 
?

**Comment by littleGnAl** [comment]
Please check this comment 
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/860#issuecomment-1370420470

**Comment by bhavykoshti** [comment]
This occurs when your initialization is not properly done, Will check in few days if it occurs again, if not then will close this issue

**Comment by adiShinwari** [comment]
Resolved from my side

**Comment by bhavykoshti** [comment]
What changes have you made? @adiShinwari

**Comment by adiShinwari** [comment]
I am creating a single instance of agora rtc at the start of the app using getit package. And I am using it.

**Comment by littleGnAl** [comment]
I'm addressing a fix here, but I still need more tests before it can be merged.
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/905

**Comment by hadi7khan** [comment]
I am getting the same error? Video or audio call is not connecting, throwing this error.

**Comment by littleGnAl** [comment]
This fix https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/905 has landed `main` branch

**Comment by abdulkash** [comment]
Am getting the same error here is my implementation

_engine = createAgoraRtcEngine();
    await _engine.initialize(RtcEngineContext(
      appId: APP_ID,
    ));
    await _engine.enableVideo();

    _engine.registerEventHandler(
      RtcEngineEventHandler(
        onJoinChannelSuccess: (RtcConnection connection, int elapsed) async {
          dev.log("Joined live uid => ${connection.localUid}");

          await Wakelock.enable();
        },
        onUserJoined: (RtcConnection connection, int uid, int elapsed) {
          dev.log("Joined live");
          setState(
            () {
              _users.add(LiveUser(id: uid, videoMuted: false, audioMuted: false));
            },
          );
        },
        onUserMuteVideo: (connection, id, mute) {
          setState(() {
            _users[_users.indexWhere((element) => element.id == id)].videoMuted = mute;
          });
        },
        onUserMuteAudio: (connection, uid, mute) {
          setState(() {
            _users[_users.indexWhere((element) => element.id == uid)].audioMuted = mute;
          });
        },
        onUserOffline: (connection, uid, reasonType) {
          // if (uid == guestID) {
          //   setState(() {
          //     accepted = false;
          //   });
          // }
          setState(() {
            _users.removeWhere((element) => element.id == uid);
          });
        },
        onError: (typr, e) {
          dev.log(e.toString());
        },
        onLeaveChannel: (connection, stats) {
          setState(
            () {
              _users.clear();
            },
          );
        },
      ),
    );

    final viewModel = context.read<LiveViewModel>();
    final parsedInviteId = viewModel.parseInviteId(
      widget.inviteId,
    );

    ChannelMediaOptions options = ChannelMediaOptions(
      clientRoleType: ClientRoleType.clientRoleBroadcaster,
      channelProfile: ChannelProfileType.channelProfileLiveBroadcasting,
    );


    await _engine.joinChannel(
      token: parsedInviteId['token'],
      channelId: parsedInviteId['channelName'],
      uid: context.read<UserViewModel>().user_id,
      options: options,
    );

**Comment by bhavykoshti** [comment]
```
  agora_rtc_engine:
    git:
      url: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK.git
      ref: main
```

instead your library in yaml

**Comment by abdulkash** [comment]
@bhavykoshti 
am not getting any camera preview from when i initialize the engine, i have enabled video and also start preview when video view is created. and also when i release the engine the spawned isolate still remains
