### ISSUE TITLE
Lock device with proximity sensor in voice call

### ISSUE THREAD

**Issue by cnkygmr** [AgoraIO-Extensions/Agora-Flutter-SDK#889]
How do we lock the device like whatsapp during voice call in flutter?
During a voice call, the screen stays on and while the device is on the ear, taps and opens other applications.

**Comment by littleGnAl** [comment]
It's a business logic of the application, and I'm sorry that I'm not a user of whatsapp, I think you asking this question in StackOverflow may be more helpful.
