### ISSUE TITLE
IOS external sound decreasing until muted after joining a channel

### ISSUE THREAD

**Issue by silversquall** [AgoraIO-Extensions/Agora-Flutter-SDK#899]
**Describe the bug**
I am playing a .mp3 sound using an external library. The moment i am joining any agora channel, the .mp3 sound goes down until it is muted.
I can see the following logs:

```
[warning] /tmp/jenkins/IRIS-SDK/rtc/cxx/src/internal/rtc_engine_event_handler.cc:43 onWarning warn 1029 msg nullptr
[avas]     AVAudioSession_iOS.mm:1243  Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.
```

**additional infos**
  agora_rtc_engine:  5.3.1
  agora_rtm: 1.1.0 
  The device is an iphone 7 running under ios 15.3.1

**Comment by littleGnAl** [comment]
Related https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/709

**Comment by littleGnAl** [comment]
see https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/709#issuecomment-1172263499
