### ISSUE TITLE
onUserJoined event not triggering when same user ID joins the call on different device.

### ISSUE THREAD

**Issue by pedroenrre** [AgoraIO-Extensions/Agora-Flutter-SDK#902]
**Describe the bug**
If you use the method joinChannelWithUserAccount from two different devices with the same userAccount, the onUserJoined event is not triggering. So, each device does not see the other.

**To Reproduce**
1. Create a channel with two different users.
2. Join this channel with one repeated userAccount.
3. The first two user wont be able to know there is a third person on the call. It remains "invisible"to them but can hear all the call.

**Expected behavior**
Triggers the onUserJoined event every time, including repeated users.
Create a method to retrieve a list of users on the call.

**Comment by littleGnAl** [comment]
I think you should make sure the `userAccount` is unique。
https://api-ref.agora.io/en/voice-sdk/flutter/6.x/API/class_irtcengine.html#api_irtcengine_joinchannelwithuseraccount2__userAccount
