### ISSUE TITLE
is there any way I can get a video frame of a remote user?

### ISSUE THREAD

**Issue by adiShinwari** [AgoraIO-Extensions/Agora-Flutter-SDK#906]
I am developing video application with random guys. I want to check if the remote or local user is showing something unethical like naked , nudity or something violent. I will be using the TensorFlow model for checking but how can I get the frame/image of each user after every 3 seconds to send it to my trained model.

**Comment by littleGnAl** [comment]
I think you can try [registerVideoFrameObserver](https://api-ref.agora.io/en/voice-sdk/flutter/6.x/API/class_imediaengine.html#api_imediaengine_registervideoframeobserver)
https://api-ref.agora.io/en/voice-sdk/flutter/6.x/API/class_imediaengine.html#ariaid-title7
