### ISSUE TITLE
App size is too big Version. -- 6.1.0

### ISSUE THREAD

**Issue by bhavykoshti** [AgoraIO-Extensions/Agora-Flutter-SDK#907]
version latest, 
My app size for android is now 144MB after implementing the agora sdk
I only want to implement live video calls via agora.

**Comment by littleGnAl** [comment]
What error did you face?

**Comment by bhavykoshti** [comment]
No errors just the app size is too big, and i have tried other solutions but those works for the old version of agora sdk which is 5.3.0
```
 if (isDev(project)) {
        implementation fileTree(dir: "libs", include: ["*.jar"])
    } else {
        api 'io.agora.rtc:iris-rtc:4.1.0-rc.2'
//        api 'io.agora.rtc:full-sdk:4.1.0-1'
//        implementation 'io.agora.rtc:full-screen-sharing:4.1.0-1'
    }
    implementation 'io.agora.rtc:full-rtc-basic:3.7.0.3'
    implementation 'io.agora.rtc:full-ains:3.6.2'
    implementation 'io.agora.rtc:full-jnd:3.7.0.3'
    implementation 'io.agora.rtc:full-full-audio-format:3.6.2'
    implementation "io.agora.rtc:full-super-resolution:3.7.0.3"

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${safeExtGet('kotlin_version', "1.7.21")}"
```

Error --

iris error i was getting erlier i will take more time to analyse this weekend and will share logs 
But for now can you provide me the latest version of these dependencies ?

**Comment by littleGnAl** [comment]
You can find the full maven dependencies list here:
https://docs.agora.io/cn/video-call-4.x/reduce_size_ng?platform=Android#maven-central-%E9%9B%86%E6%88%90%E6%97%B6%E5%88%A0%E9%99%A4%E6%8F%92%E4%BB%B6

**Comment by littleGnAl** [comment]
>E/AndroidRuntime(28489): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "getMediaPlayerCacheManager" referenced by "/data/app/~~1ucsc1y5L3cWfUYf3aycwQ==/com.agreedonline-YYXVVEKBlohd3s7udvdw5A==/base.apk!/lib/arm64-v8a/libAgoraRtcWrapper.so"...
E/AndroidRuntime(28489): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/AndroidRuntime(28489): 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/AndroidRuntime(28489): 	at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime(28489): 	at io.agora.agora_rtc_ng.AgoraRtcNgPlugin.onMethodCall(AgoraRtcNgPlugin.java:62)
E/AndroidRuntime(28489): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(28489): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(28489): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319)
E/AndroidRuntime(28489): 	at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$TsixYUB5E6FpKhMtCSQVHKE89gQ(Unknown Source:0)
E/AndroidRuntime(28489): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(28489): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(28489): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28489): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(28489): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(28489): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(28489): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28489): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(28489): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process (28489): Sending signal. PID: 28489 SIG: 9

For this error, you can try the latest code in `main` branch.

**Comment by bhavykoshti** [comment]
```
dependencies {
    if (isDev(project)) {
        implementation fileTree(dir: "libs", include: ["*.jar"])
    } else {
        api 'io.agora.rtc:iris-rtc:4.1.0-rc.2'
//        api 'io.agora.rtc:full-sdk:4.1.0-1'
//        implementation 'io.agora.rtc:full-screen-sharing:4.1.0-1'
    }
    def agora_sdk_version = "4.0.1"

    implementation "io.agora.rtc:full-rtc-basic:${agora_sdk_version}"
    implementation "io.agora.rtc:full-ains:${agora_sdk_version}"
    implementation "io.agora.rtc:full-jnd:${agora_sdk_version}"
    implementation "io.agora.rtc:full-full-audio-format:${agora_sdk_version}"
    implementation "io.agora.rtc:full-super-resolution:${agora_sdk_version}"

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${safeExtGet('kotlin_version', "1.7.21")}"

}
```


Error -- 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:generateDebugRFile'.
> Could not resolve all files for configuration ':agora_rtc_engine:debugCompileClasspath'.
   > Could not find io.agora.rtc:full-ains:4.0.1.
     Required by:
         project :agora_rtc_engine
   > Could not find io.agora.rtc:full-jnd:4.0.1.
     Required by:
         project :agora_rtc_engine
   > Could not find io.agora.rtc:full-full-audio-format:4.0.1.
     Required by:
         project :agora_rtc_engine

```

**Comment by littleGnAl** [comment]
I think the version should be `4.1.0-1`

**Comment by bhavykoshti** [comment]
nope, even that version is not working!

**Comment by littleGnAl** [comment]
I believe the name had been changed, you may check this for reference
https://docs.agora.io/cn/video-call-4.x/reduce_size_ng?platform=Android#implementation-字段

**Comment by X-SLAYER** [comment]
yes the names has been changed and you have typo in the audio implementation
copy this instead it works for me 
```gradle
dependencies {
  def agora_sdk_version = "4.1.0-1"

  if (isDev(project)) {
    implementation fileTree(dir: "libs", include: ["*.jar"])
  } else {
     api 'io.agora.rtc:iris-rtc:4.1.0-rc.2'
     // api 'io.agora.rtc:full-sdk:4.1.0-1'
     // implementation 'io.agora.rtc:full-screen-sharing:4.1.0-1'
  }
  
    implementation "io.agora.rtc:full-rtc-basic:${agora_sdk_version}"
    implementation "io.agora.rtc:ains:${agora_sdk_version}"
    implementation 'io.agora.rtc:full-audio-format:3.7.2.1'
    implementation "io.agora.rtc:full-super-resolution:${agora_sdk_version}"

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${safeExtGet('kotlin_version', "1.7.21")}"
  
}
```
or use the forked and edited version from my repo

```yaml
  agora_rtc_engine:
    git:
      url: https://github.com/X-SLAYER/Agora-Flutter-SDK.git
      ref: main
```

**Comment by bhavykoshti** [comment]
@X-SLAYER that's not a typo you can actually check those dependencies on the maven website, and i already had my own fork

```
dependencies {
    if (isDev(project)) {
        implementation fileTree(dir: "libs", include: ["*.jar"])
    } else {
        api 'io.agora.rtc:iris-rtc:4.1.0-rc.2'
//        api 'io.agora.rtc:full-sdk:4.1.0-1'
//        implementation 'io.agora.rtc:full-screen-sharing:4.1.0-1'
    }
    def agora_sdk_version = "4.1.0"

    implementation "io.agora.rtc:full-rtc-basic:${agora_sdk_version}"
    implementation "io.agora.rtc:full-ains:3.7.0"
    implementation "io.agora.rtc:full-jnd:3.7.2.1"
    implementation "io.agora.rtc:full-full-audio-format:3.7.0"
    implementation "io.agora.rtc:full-super-resolution:${agora_sdk_version}"

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${safeExtGet('kotlin_version', "1.7.21")}"

}
```

This one works for me 
and last apk release size for android is 29mb and my previous apk size was 12mb so its great,

@littleGnAl 
I still need solution for ios

**Comment by afzl-wtu** [comment]
@littleGnAl and without AGora RTC ENGINE app size is 8 MB.

**Comment by dragojsguru** [comment]
Please guys resolve this! Does anyone have some solution for ios and Android.

**Comment by mminhlequang** [comment]
any update?

**Comment by vivekmzkl** [comment]
agora_rtc_engine: ^6.2.0
Application size before using Agora: 16 MB
Application size after using Agora: 126 MB
No updates...

**Comment by MuhammadIbrahim001** [comment]
I any solution for reducing size??

**Comment by littleGnAl** [comment]
Please check https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/907 for reference.
