### ISSUE TITLE
How to play music while my mic is muted?

### ISSUE THREAD

**Issue by melshenawyarabapps** [AgoraIO-Extensions/Agora-Flutter-SDK#930]

**Comment by littleGnAl** [comment]
I think you can use `MediaPlayer` to play the music.
https://api-ref.agora.io/en/voice-sdk/flutter/6.x/API/class_imediaplayer.html#class_imediaplayer

**Comment by amityamsi** [comment]
I used Media Player in my project to play music So you can do the same i.e. play music when mic is off and vice versa
