### ISSUE TITLE
A QUICK QUESTION: How to get VideoCanvas uid for liveStream as a Broadcaster

### ISSUE THREAD

**Issue by Princewil** [AgoraIO-Extensions/Agora-Flutter-SDK#958]
I published an issue recently complaining of a crash on windows while about to start a livestream broadcast.
Fortunately this issue was fixed after I used this repo:
```
agora_rtc_engine:
    git:
      url: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK.git
      ref: main 
```
Currently the windows does not crash and my desktop camera light is on meaning video feeds is ongoing

However, I can seem to preview my local video feed: 
![Screenshot (17)](https://user-images.githubusercontent.com/40724883/225709034-a9b29189-fa13-48d3-bbfe-eb4f5d417592.png)
An error popped up as follows

Now my question is: **How do I get this VideoCanvas uid as a Broadcaster (i.e clientRoleBroadcaster)??** since we can't pass int value of 0 as shown on this picture:
![Screenshot (16)](https://user-images.githubusercontent.com/40724883/225709643-164a8e87-93d3-444a-9d79-487553980b90.png)

Note: calling getCallId() funct returns a string with both alphabets and numbers as shown below:
![Screenshot (18)](https://user-images.githubusercontent.com/40724883/225710412-f683bb23-d64c-4c0b-9e65-e113691096f6.png)

A quick response will be highly appreciated. 
Thanks you

**Comment by littleGnAl** [comment]
The uid 0 means the local user, you should not use the `VideoViewController.remote` to render the local user, please check our example for reference
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/b3da6fc8e116cbbc6bf852b5276692405be9d4b1/example/lib/examples/basic/join_channel_video/join_channel_video.dart#L129

For how to render the remote user, please also check our example for reference
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/b3da6fc8e116cbbc6bf852b5276692405be9d4b1/example/lib/examples/basic/join_channel_video/join_channel_video.dart#L149

**Comment by Princewil** [comment]
Got it, Working as expected now!
Thank you so much
