### ISSUE TITLE
模拟器崩溃

### ISSUE THREAD

**Issue by FuXiaoZhang** [AgoraIO-Extensions/Agora-Flutter-SDK#968]
使用的版本是4.0.7，在模拟器上使用会报如下错误，如果解决或者如何能够catch到错误，不让app崩溃？
![1679392061(1)](https://user-images.githubusercontent.com/17977186/226570626-7453c7c3-6942-4619-a52b-549d4006946b.jpg)

**Comment by littleGnAl** [comment]
What arch of your simulator?

**Comment by FuXiaoZhang** [comment]
> 

使用的雷电模拟器崩溃，夜神是ok的

**Comment by littleGnAl** [comment]
Can you show the arch of the simulator by using the following command:
```
adb shell cat /proc/cpuinfo
```
https://stackoverflow.com/questions/6630386/how-to-find-arm-processor-version-on-android-device

**Comment by FuXiaoZhang** [comment]
雷电：
![image](https://user-images.githubusercontent.com/17977186/226581533-06f43e02-c06e-4e3a-8ab9-c32e000cc592.png)
夜神：adb.exe: no devices/emulators found

**Comment by littleGnAl** [comment]
I think it's the problem with the 雷电 simulator.
It's better to submit a ticket to agora support for further investigation, thanks.
