### ISSUE TITLE
onMusicChartsResult after getMusicCharts() is not callback

### ISSUE THREAD

**Issue by YaoboY** [AgoraIO-Extensions/Agora-Flutter-SDK#975]
flutter 6.1.0 demo，使用MusicPlayer功能，调用getMusicCharts()方法后，返回："由于10秒内没有数据传输，连接关闭"，监听里的onMusicChartsResult没有回调。

使用getMusicCharts后控制台打印：
[+14404 ms] V/AudioManager(25636): querySoundEffectsEnabled...
[        ] D/spdlog  (25636): [2023-03-23 14:04:56.067] [25636] [debug] [iris_rtc_music_center_impl.cc:52] api name MusicContentCenter_getMusicCharts params {}
[   +1 ms] I/agora.io(25636): (00002239): MusicContentCenterImpl::getMusicCharts(this:0x78681e3a00, requestId: 61B93D9A9DE8442A9BABBBC9F3322B03)
[        ] D/spdlog  (25636): [2023-03-23 14:04:56.068] [25636] [debug] [iris_rtc_music_center_impl.cc:68] ret 0 result {"requestId":"61B93D9A9DE8442A9BABBBC9F3322B03","result":0}
[ +594 ms] I/agora.io(25636): Connection Closed due to no data transport in 10 s    由于10秒内没有数据传输，连接关闭
[        ] I/agora.io(25636): [5136783802879328595|remote:115.******.206:8130] destroy session 0x7872894300
[   +1 ms] I/agora.io(25636): [5136783802879328595|remote:115.******.206:8130] start last ack, duration: 2000 ms
[        ] I/agora.io(25636): destroy session builder 0x786beb1b00
[        ] I/agora.io(25636): [5136783802879328595|remote:115.******.206:8130] destroy connection 0x7873bcc200
[        ] I/agora.io(25636): [5136783802879328595|remote:115.******.206:8130] destroy path 0x7873c16000

**Comment by littleGnAl** [comment]
It's better to raise a new ticket to Agora Support for further investigation of this issue.
