### ISSUE TITLE
Screen share not scale full screen when push to RTMP (it's cropped)

### ISSUE THREAD

**Issue by phucdth12a** [AgoraIO-Extensions/Agora-Flutter-SDK#978]
I use future share screen window:
await rtcEngine.startScreenCaptureByWindowId(
        windowId: sourceId!,
        regionRect: const Rectangle(x: 0, y: 0, width: 0, height: 0),
        captureParams: const ScreenCaptureParameters(
          captureMouseCursor: true,
          dimensions:
              VideoDimensions(width: 1200, height: 720),
          frameRate: 30,
          bitrate: 1800,
        ),
      );

and display it by AgoraView like image below
![Screenshot 2023-03-24 at 11 39 05](https://user-images.githubusercontent.com/18467891/227426846-66c3af3d-26c1-4156-85e7-b5a9bb45ade2.png)

and update media channel like this: 
const ChannelMediaOptions(
                  autoSubscribeAudio: false,
                  autoSubscribeVideo: false,
                  publishCameraTrack: false,
                  publishMicrophoneTrack: false,
                  publishScreenTrack: true,
                  publishSecondaryScreenTrack: true,
                  publishScreenCaptureAudio: true,
                  publishScreenCaptureVideo: true,
                  publishCustomAudioTrack: false,
                  publishCustomVideoTrack: false,
                  publishMediaPlayerAudioTrack: false,
                  publishMediaPlayerVideoTrack: false,
                  clientRoleType: ClientRoleType.clientRoleBroadcaster,
                )

After update LiveTranscoding
LiveTranscoding(
          transcodingUsers: listTranscodingUsers,
          userCount: 17,
          width: 1200,
          height: 720,
          videoBitrate: 1800,
          videoCodecProfile: VideoCodecProfileType.videoCodecProfileHigh,
          videoFramerate: 30,
          lowLatency: true,
          audioSampleRate: AudioSampleRateType.audioSampleRate44100,
          audioBitrate: 48,
          audioChannels: 1,
          backgroundImage: listImages,
          backgroundImageCount: 10,
          audioCodecProfile: AudioCodecProfileType.audioCodecProfileLcAac,
        )

with users share screen
TranscodingUser(
          uid: screenId,
          x: 0,
          y: 0,
          width: 1200,
          height: 720,
          audioChannel: 2,
          alpha: 1,
          zOrder: 0,
        )

But user receive image cropped:
<img width="1121" alt="Screenshot 2023-03-24 at 11 39 14" src="https://user-images.githubusercontent.com/18467891/227427267-9b692203-caa7-4e85-ad3f-ca6a86981134.png">

So can setting image in RTMP scale like that display in AgoraView. Tks.

**Comment by littleGnAl** [comment]
I think you can try adjusting the `TranscodingUser.width/height` and the `LiveTranscoding.width/height`.

**Comment by phucdth12a** [comment]
> I think you can try adjusting the `TranscodingUser.width/height` and the `LiveTranscoding.width/height`.

Not work for me. Because user can change size of screen window.
In user local or user remote that screen is scaled.
but when push to rtmp that screen cropped.

i don't know data push to rtmp not like user see.

**Comment by littleGnAl** [comment]
I think it's better to raise a ticket to agora support for further investigation.
