### ISSUE TITLE
Does the previous versions (5.3.1/5.1.0) still work? (Flutter WEB)

### ISSUE THREAD

**Issue by Sypzer** [AgoraIO-Extensions/Agora-Flutter-SDK#984]
Does the previous versions (5.3.1/5.1.0) still work? I tried implementing them for Flutter Web and I get this error. Instead of trying to find something wrong in my code I am asking whether there is no point in searching further because of the version. 

*The code is the one provided in the example for 5.1.0

Here is the error:
Error: PlatformException(error, data: {"retry":false,"csIp":"15.237.134.178"}
assets/packages/agora_rtc_engine/assets/AgoraRtcWrapper.bundle.js 2:562937                                                 _W
assets/packages/agora_rtc_engine/assets/AgoraRtcWrapper.bundle.js 2:560320                                                 lts
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
packages/flutter/src/services/message_codecs.dart 653:7                                                                    decodeEnvelope
packages/flutter/src/services/platform_channel.dart 315:18                                                                 _invokeMethod
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1660:54                                          runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 767:44                                    handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 796:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 567:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 640:7                                     callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

**Comment by littleGnAl** [comment]
All the bugs relative to the Web should be addressed on 6.x.

**Comment by luvishq** [comment]
@littleGnAl : because of this issue we might have to end up using some other solution , can you confirm if there is an ETA for fixing this one ?

**Comment by ips-jm** [comment]
Just tried it and for me version 5.3.1 is still working.

**Comment by luvishq** [comment]
It is intermittently failing for me with that error

**Comment by littleGnAl** [comment]
@luvishq I'm so sorry that there's no timeline guarantee yet.

**Comment by Sypzer** [comment]
It does work indeed! Thank you, I just forgot to add this script in index.html!

<script src="AgoraRtcWrapper.bundle.js" type="application/javascript"></script>
